(function (root) {
  "use strict";
  const V16 = root.STCTV16 || {};
  const Integrity = root.STCTV15?.integrityHash;
  const Fixture = V16.roadFixture;
  const Providers = V16.routingProviders;
  const Twin = V16.executionTwin;
  const Stores = V16.executionStore;
  const Alerts = V16.operationsAlerts;
  const Queue = V16.offlineQueue;
  const Driver = V16.driverSimulator;
  const Analytics = V16.planVsActual;
  const Layers = V16.mapLayers;
  if (!Integrity || !Fixture || !Providers || !Twin || !Stores || !Alerts || !Queue || !Driver || !Analytics || !Layers) return;

  const VERSION = "stct-experience-ui-v1.6";
  const COPY = {
    zh: {
      nav: "动态运营", title: "道路感知动态运营", subtitle: "Synthetic Fixture 支撑的本地模拟，不代表实时运营。", boundary: "本地模拟 / 非实时运营", paused: "已暂停", restored: "已恢复为暂停状态",
      tabs: { road: "道路路由", operations: "运营指挥", actual: "计划与模拟实际", rolling: "滚动重排", driver: "司机模拟器" },
      roadTitle: "道路感知实验室", operationsTitle: "运营指挥中心", actualTitle: "计划与模拟实际", rollingTitle: "滚动重优化", driverTitle: "本地司机模拟器",
      routingProvider: "路由提供方", roadProfile: "道路车型", snap: "吸附置信度", restrictions: "转向与车辆限制", toll: "收费道路", closure: "道路封闭", reset: "重置视图", follow: "跟随车辆", exitFollow: "退出跟随", previous: "上一个配送点", next: "下一个配送点", routeSummary: "文本路线摘要", distance: "道路距离", duration: "预计用时", roadNetwork: "道路网络", estimated: "估算路线", noWebgl: "地图渲染不可用，完整运营表格仍可使用。",
      executionStatus: "执行状态", stale: "陈旧", offline: "离线", liveSimulation: "本地模拟流", alerts: "运营告警", routeHealth: "路线健康度", all: "全部", acknowledge: "确认", handling: "开始处理", resolve: "解决", alertSummary: "屏幕阅读器告警摘要", noAlerts: "当前筛选无告警", simulateStale: "模拟陈旧", clearStale: "恢复本地流",
      planned: "计划", simulatedActual: "模拟实际", routeAdherence: "路线遵循率", etaError: "ETA 误差", dwellVariance: "停留偏差", completion: "完成率", stop: "配送点", arrival: "到达", delta: "偏差", status: "状态", eventSeek: "定位事件", tableEquivalent: "地图和图表的表格等价视图",
      rollingNote: "固定已完成前缀与已装载订单；只比较已观察候选，不声称全局最优。", transferPolicy: "转运策略", virtualCrossdock: "虚拟越库模拟", candidate: "候选方案", localRepair: "本地修复", fullOrtools: "Full OR-Tools", preview: "预览", applySimulation: "应用到模拟", confirmApply: "确认应用模拟恢复", cancel: "取消", handover: "交接", counterRecovery: "反向恢复", pendingSelection: "尚未选择候选", appliedSimulation: "已应用模拟计划修订",
      assignedRoute: "分配路线", nextStop: "下一配送点", queue: "离线队列", acceptRoute: "接受路线", depart: "出发", arrive: "到达", startService: "开始服务", complete: "完成", fail: "失败", skip: "跳过", goOffline: "转为离线", reconnect: "重新连接", mapFocus: "聚焦地图", driverBoundary: "仅本地司机工作流模拟，不申请 GPS 权限，不提供导航。",
      capsule: "导出 Capsule", readOnly: "默认只读回放", close: "关闭", providerConfigured: "已配置本地提供方", fixture: "合成道路数据", partial: "事件不完整", open: "待处理", acknowledged: "已确认", inProgress: "处理中", resolved: "已解决", high: "高", critical: "严重", medium: "中", focusPreserved: "主视图与焦点保持", mapDescription: "合成道路图：仓库经三个配送点形成道路路线，红线为计划路线，蓝色圆点为配送点。",
    },
    en: {
      nav: "Operations", title: "Road-Aware Dynamic Operations", subtitle: "Local simulation backed by Synthetic Fixture data; not live operations.", boundary: "Local Simulation / Not Live Operations", paused: "Paused", restored: "Restored in paused state",
      tabs: { road: "Road-Aware Lab", operations: "Operations", actual: "Plan vs Actual", rolling: "Rolling Reoptimization", driver: "Driver Simulator" },
      roadTitle: "Road-Aware Lab", operationsTitle: "Operations Command Center", actualTitle: "Plan vs Simulated Actual", rollingTitle: "Rolling Reoptimization", driverTitle: "Local Driver Simulator",
      routingProvider: "Routing Provider", roadProfile: "Road Profile", snap: "Snap Confidence", restrictions: "Turn and vehicle restrictions", toll: "Toll", closure: "Closure", reset: "Reset view", follow: "Follow vehicle", exitFollow: "Exit follow", previous: "Previous stop", next: "Next stop", routeSummary: "Text route summary", distance: "Road distance", duration: "Estimated duration", roadNetwork: "Road network", estimated: "Estimated Route", noWebgl: "Map rendering is unavailable; the complete operational tables remain available.",
      executionStatus: "Execution status", stale: "Stale", offline: "Offline", liveSimulation: "Local simulation stream", alerts: "Operational Alerts", routeHealth: "Route Health", all: "All", acknowledge: "Acknowledge", handling: "Start handling", resolve: "Resolve", alertSummary: "Screen-reader alert summary", noAlerts: "No alerts match this filter", simulateStale: "Simulate stale", clearStale: "Restore local stream",
      planned: "Planned", simulatedActual: "Simulated Actual", routeAdherence: "Route Adherence", etaError: "ETA Error", dwellVariance: "Dwell Variance", completion: "Completion", stop: "Stop", arrival: "Arrival", delta: "Delta", status: "Status", eventSeek: "Seek event", tableEquivalent: "Table equivalent for map and chart content",
      rollingNote: "Completed prefixes and loaded orders stay pinned. The observed candidates do not imply global optimality.", transferPolicy: "Transfer Policy", virtualCrossdock: "Virtual Cross-dock Simulation", candidate: "Candidate", localRepair: "Local repair", fullOrtools: "Full OR-Tools", preview: "Preview", applySimulation: "Apply to simulation", confirmApply: "Confirm simulated recovery", cancel: "Cancel", handover: "Handover", counterRecovery: "Counter-Recovery", pendingSelection: "No candidate selected", appliedSimulation: "Simulated plan revision applied",
      assignedRoute: "Assigned route", nextStop: "Next stop", queue: "Offline Queue", acceptRoute: "Accept route", depart: "Depart", arrive: "Arrive", startService: "Start service", complete: "Complete", fail: "Fail", skip: "Skip", goOffline: "Go offline", reconnect: "Reconnect", mapFocus: "Focus map", driverBoundary: "Local driver workflow simulation only; no GPS permission and no navigation.",
      capsule: "Export Capsule", readOnly: "Read-only replay by default", close: "Close", providerConfigured: "Configured Local Provider", fixture: "Synthetic road data", partial: "Partial Events", open: "Open", acknowledged: "Acknowledged", inProgress: "In Progress", resolved: "Resolved", high: "High", critical: "Critical", medium: "Medium", focusPreserved: "Primary view and focus preserved", mapDescription: "Synthetic road map: a depot connects to three stops. Red marks the planned route and blue circles mark stops.",
    },
    ja: {
      nav: "動的運用", title: "道路対応の動的運用", subtitle: "Synthetic Fixture によるローカルシミュレーションです。ライブ運用ではありません。", boundary: "ローカルシミュレーション / ライブ運用ではありません", paused: "一時停止", restored: "一時停止状態で復元済み",
      tabs: { road: "道路対応ラボ", operations: "運用指令", actual: "計画対シミュレーション実績", rolling: "ローリング再最適化", driver: "ドライバーシミュレーター" },
      roadTitle: "道路対応ラボ", operationsTitle: "運用指令センター", actualTitle: "計画対シミュレーション実績", rollingTitle: "ローリング再最適化", driverTitle: "ローカルドライバーシミュレーター",
      routingProvider: "ルーティングプロバイダー", roadProfile: "道路プロファイル", snap: "スナップ信頼度", restrictions: "右左折・車両制限", toll: "有料道路", closure: "通行止め", reset: "表示をリセット", follow: "車両を追跡", exitFollow: "追跡を終了", previous: "前の配送先", next: "次の配送先", routeSummary: "テキスト経路概要", distance: "道路距離", duration: "推定所要時間", roadNetwork: "道路ネットワーク", estimated: "推定ルート", noWebgl: "地図を描画できません。完全な運用表は引き続き利用できます。",
      executionStatus: "実行状態", stale: "更新停止", offline: "オフライン", liveSimulation: "ローカルシミュレーションストリーム", alerts: "運用アラート", routeHealth: "ルート健全性", all: "すべて", acknowledge: "確認", handling: "対応開始", resolve: "解決", alertSummary: "スクリーンリーダー用アラート概要", noAlerts: "該当するアラートはありません", simulateStale: "更新停止をシミュレート", clearStale: "ローカルストリームを復元",
      planned: "計画", simulatedActual: "シミュレーション実績", routeAdherence: "ルート遵守率", etaError: "ETA 誤差", dwellVariance: "滞在時間差", completion: "完了率", stop: "配送先", arrival: "到着", delta: "差分", status: "状態", eventSeek: "イベントへ移動", tableEquivalent: "地図とチャートの表形式代替", rollingNote: "完了済みプレフィックスと積載済み注文を固定します。観測候補は大域最適を意味しません。", transferPolicy: "転送ポリシー", virtualCrossdock: "仮想クロスドックシミュレーション", candidate: "候補", localRepair: "ローカル修復", fullOrtools: "Full OR-Tools", preview: "プレビュー", applySimulation: "シミュレーションに適用", confirmApply: "シミュレーション復旧を確認", cancel: "キャンセル", handover: "引き継ぎ", counterRecovery: "カウンター復旧", pendingSelection: "候補が未選択です", appliedSimulation: "シミュレーション計画改訂を適用済み",
      assignedRoute: "割当ルート", nextStop: "次の配送先", queue: "オフラインキュー", acceptRoute: "ルート承認", depart: "出発", arrive: "到着", startService: "サービス開始", complete: "完了", fail: "失敗", skip: "スキップ", goOffline: "オフラインへ", reconnect: "再接続", mapFocus: "地図にフォーカス", driverBoundary: "ローカルドライバーワークフローのシミュレーションのみ。GPS 権限とナビゲーションはありません。", capsule: "Capsule をエクスポート", readOnly: "既定は読み取り専用リプレイ", close: "閉じる", providerConfigured: "設定済みローカルプロバイダー", fixture: "合成道路データ", partial: "イベント不完全", open: "未対応", acknowledged: "確認済み", inProgress: "対応中", resolved: "解決済み", high: "高", critical: "重大", medium: "中", focusPreserved: "メインビューとフォーカスを保持", mapDescription: "合成道路地図：倉庫から三つの配送先へ接続します。赤線は計画ルート、青い円は配送先です。",
    },
  };
  const state = { installed: false, opened: false, previousView: "mapView", tab: "road", noWebGL: false, reducedMotion: false, restored: false, selectedStop: 0, follow: false, alertFilter: "ALL", stale: false, recoveryCandidate: "", recoveryConfirm: false, recoveryApplied: false, liveMessage: "", listener: null, interval: null, activeRafs: 0, model: null, driver: null, layers: Layers.createRegistry(), measurements: { commandCenterOpenMs: null, alertFilterMs: null, eventSeekMs: null, metricRecomputeMs: null, timelineRenderMs: null, routeSwitchMs: null }, counters: { applicationUpdates: 0, mapAdapterUpdates: 0, mapSourceUpdates: 0, browserRafCallbacks: 0 } };
  const text = (value) => String(value ?? "");
  const esc = (value) => text(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));
  const fmt = (value, digits = 1) => Number(value || 0).toLocaleString(language() === "zh" ? "zh-CN" : language() === "ja" ? "ja-JP" : "en-US", { maximumFractionDigits: digits, minimumFractionDigits: digits });
  function language() { const value = root.STCTCore?.getLanguage?.() || document.documentElement.lang || "en"; return value.startsWith("zh") ? "zh" : value.startsWith("ja") ? "ja" : "en"; }
  function copy() { return COPY[language()]; }
  function host() { return document.getElementById("experienceRoot"); }
  function activeView() { return document.querySelector(".view.active")?.id || "mapView"; }
  function point(graph, id, pointId) { const value = graph.nodes.find((node) => node.nodeId === id); return { pointId, lon: value.lon, lat: value.lat }; }

  async function createModel() {
    const graph = Fixture.createFixture(); const provider = Providers.createRegistry().get("SYNTHETIC_ROAD_FIXTURE");
    const points = [point(graph, "DEPOT", "DEPOT"), point(graph, "B", "STOP-01"), point(graph, "C", "STOP-02"), point(graph, "ZONE_B", "STOP-03")];
    const request = { schemaVersion: "stct-routing-request-v1.6", providerId: provider.id, profile: "light-truck", points, distanceUnit: "km", durationUnit: "minutes", snapToleranceMeters: 120 };
    const route = await provider.route(request); const matrix = await provider.matrix(request);
    const plan = { schemaVersion: "stct-plan-v1.6-ui", planId: "V16-ROAD-AWARE-DEMO", planHash: Integrity.hashValue({ plan: "V16-ROAD-AWARE-DEMO", routeHash: route.routeHash }), revision: 1, logicalStartMinute: 480, verification: { status: "PASS" }, vehicles: [{ id: "VEH-16", maxVolume: 12 }], routes: [{ routeId: "ROAD-16", vehicleId: "VEH-16", orderIds: ["STOP-01", "STOP-02", "STOP-03"], etaByOrder: { "STOP-01": 497, "STOP-02": 514, "STOP-03": 536 }, serviceMinutesByOrder: { "STOP-01": 5, "STOP-02": 8, "STOP-03": 5 }, volumeByOrder: { "STOP-01": 2, "STOP-02": 4, "STOP-03": 3 }, geometry: route.geometry, edgeIds: route.edgeIds, totalDistance: route.totalDistance, maxVolume: 12 }] };
    const run = Twin.createRun({ scenarioId: "V16-UI-SYNTHETIC", inputHash: Integrity.hashValue({ scenario: "V16-UI-SYNTHETIC" }), planHash: plan.planHash, routeGeometryHash: route.routeHash, matrixHash: matrix.matrixHash, providerProvenance: route.providerProvenance, simulationSeed: "1600", executionProfile: "URBAN_CONGESTION", logicalStartMinute: 480, revision: 1 });
    const store = Stores.createStore({ run, plan, clock: () => "2026-08-31T00:00:00.000Z" });
    const makeEvent = (sequence, eventType, fields = {}) => Twin.createEvent(run, { eventId: `UI-${sequence}-${eventType}`, sequence, eventType, logicalTime: fields.logicalTime ?? 480 + sequence, routeId: fields.routeId ?? (eventType === "RUN_RELEASED" ? "" : "ROAD-16"), vehicleId: fields.vehicleId ?? (eventType === "RUN_RELEASED" ? "" : "VEH-16"), orderId: fields.orderId || "", coordinate: fields.coordinate, roadEdgeId: fields.roadEdgeId, ackId: fields.ackId, payload: { planRevision: 1, ...(fields.payload || {}) } });
    const events = [makeEvent(1, "RUN_RELEASED", { logicalTime: 480 }), makeEvent(2, "ROUTE_ACCEPTED", { logicalTime: 481 }), makeEvent(3, "VEHICLE_DEPARTED", { logicalTime: 482 }), makeEvent(4, "POSITION_RECORDED", { logicalTime: 488, coordinate: route.geometry[Math.min(1, route.geometry.length - 1)], roadEdgeId: route.edgeIds[0], payload: { segmentDistanceKm: .7, roadMatched: true } }), makeEvent(5, "STOP_ARRIVED", { logicalTime: 500, orderId: "STOP-01" }), makeEvent(6, "SERVICE_STARTED", { logicalTime: 500, orderId: "STOP-01" }), makeEvent(7, "SERVICE_COMPLETED", { logicalTime: 506, orderId: "STOP-01", ackId: "ACK-STOP-01" }), makeEvent(8, "POSITION_RECORDED", { logicalTime: 510, coordinate: route.geometry[Math.min(3, route.geometry.length - 1)], roadEdgeId: route.edgeIds[Math.min(1, route.edgeIds.length - 1)], payload: { segmentDistanceKm: .9, roadMatched: true } })];
    events.forEach((event) => store.append(event)); const executionState = store.snapshot(); const report = Analytics.compute({ plan, executionState, matrixProfile: "light-truck", tolerances: { earlyMinutes: 5, lateMinutes: 5 } });
    const inbox = Alerts.createInbox();
    [
      Alerts.alertFromRule("ETA_RISK", { executionRunHash: run.executionRunHash, routeId: "ROAD-16", vehicleId: "VEH-16", orderId: "STOP-02", logicalTime: 510, etaRiskMinutes: 14, relatedEventIds: [events.at(-1).eventId], source: "ACCEPTED_EXECUTION_EVENTS" }),
      Alerts.alertFromRule("OFF_ROUTE", { executionRunHash: run.executionRunHash, routeId: "ROAD-16", vehicleId: "VEH-16", orderId: "STOP-03", logicalTime: 511, offRouteDistanceKm: .8, relatedEventIds: [events.at(-1).eventId], source: "LOCAL_SIMULATION" }),
      Alerts.alertFromRule("EXCESS_DWELL", { executionRunHash: run.executionRunHash, routeId: "ROAD-16", vehicleId: "VEH-16", orderId: "STOP-01", logicalTime: 506, dwellMinutes: 18, relatedEventIds: [events[6].eventId], source: "ACCEPTED_EXECUTION_EVENTS" }),
    ].filter(Boolean).forEach((alert) => inbox.add(alert));
    const driverStore = Stores.createStore({ run, plan, clock: () => "2026-08-31T00:00:00.000Z" }); driverStore.append(makeEvent(1, "RUN_RELEASED", { logicalTime: 480 })); const queue = Queue.createQueue(); const driver = Driver.create({ run, plan, store: driverStore, queue, inbox: Alerts.createInbox(), vehicleId: "VEH-16" });
    const routeHealth = Alerts.routeHealth({ timeWindowRiskPercent: 22, executionProgressPercent: 34, dwellRiskPercent: 15, routeAdherencePercent: 94, minutesSinceEvent: 2, openAlertCount: 3 });
    return { graph, provider, route, matrix, plan, run, store, executionState, report, inbox, routeHealth, events, points, candidates: [{ id: "LOCAL", label: "localRepair", type: "LOCAL_REGRET_INSERTION", distance: route.totalDistance * .96, changePenalty: 3, status: "PASS", planHash: Integrity.hashValue({ candidate: "LOCAL" }) }, { id: "FULL", label: "fullOrtools", type: "FULL_REOPTIMIZATION_OR_TOOLS", distance: route.totalDistance * .91, changePenalty: 7, status: "VERIFIED_HTTP_INTEGRATION", planHash: Integrity.hashValue({ candidate: "FULL" }) }], driver };
  }

  function project(graph, coordinate) {
    const focusCoordinates = state.model?.route?.geometry || graph.nodes.map((node) => [node.lon, node.lat]); const lons = focusCoordinates.map((pointValue) => pointValue[0]); const lats = focusCoordinates.map((pointValue) => pointValue[1]); const lonMargin = Math.max(.005, (Math.max(...lons) - Math.min(...lons)) * .1); const latMargin = Math.max(.005, (Math.max(...lats) - Math.min(...lats)) * .3); const minLon = Math.min(...lons) - lonMargin; const maxLon = Math.max(...lons) + lonMargin; const minLat = Math.min(...lats) - latMargin; const maxLat = Math.max(...lats) + latMargin;
    return [40 + (coordinate[0] - minLon) / Math.max(.00001, maxLon - minLon) * 720, 365 - (coordinate[1] - minLat) / Math.max(.00001, maxLat - minLat) * 330];
  }
  function roadSvg() {
    const { graph, route, points } = state.model; const roads = graph.edges.map((edge) => { const xy = edge.geometry.map((coordinate) => project(graph, coordinate).map((value) => value.toFixed(1)).join(",")).join(" "); return `<polyline class="v16-road-edge" points="${xy}"/>`; }).join("");
    const routePoints = route.geometry.map((coordinate) => project(graph, coordinate).map((value) => value.toFixed(1)).join(",")).join(" ");
    const stops = points.map((pointValue, index) => { const [x, y] = project(graph, [pointValue.lon, pointValue.lat]); const active = index === state.selectedStop ? " active" : ""; return `<g class="v16-map-stop${active}" data-stop-index="${index}" tabindex="0" role="button" aria-label="${esc(pointValue.pointId)}"><circle cx="${x}" cy="${y}" r="${index ? 9 : 12}"/><text x="${x + 13}" y="${y - 10}">${esc(pointValue.pointId)}</text></g>`; }).join("");
    return `<svg class="v16-road-map" viewBox="0 0 800 400" role="img" aria-labelledby="v16MapTitle v16MapDesc" data-map-renderer="SYNTHETIC_FIXTURE_SVG"><title id="v16MapTitle">${esc(copy().roadNetwork)}</title><desc id="v16MapDesc">${esc(copy().mapDescription)}</desc><g class="v16-road-grid">${roads}</g><polyline class="v16-planned-route" points="${routePoints}"/><polyline class="v16-actual-route" points="${routePoints.split(" ").slice(0, Math.max(2, Math.ceil(route.geometry.length * .42))).join(" ")}"/>${stops}</svg>`;
  }
  function metric(label, value, suffix = "") { return `<div class="v16-metric"><span>${esc(label)}</span><strong>${esc(value)}${esc(suffix)}</strong></div>`; }
  function sectionHead(title, note = "") { return `<div class="v16-section-head"><div><h3>${esc(title)}</h3>${note ? `<p>${esc(note)}</p>` : ""}</div></div>`; }
  function stateLabel(value) { const c = copy(); return ({ OPEN: c.open, ACKNOWLEDGED: c.acknowledged, IN_PROGRESS: c.inProgress, RESOLVED: c.resolved })[value] || value; }

  function renderRoad() {
    const c = copy(); const model = state.model; const selected = model.points[state.selectedStop]; const noMap = state.noWebGL ? `<div class="v16-no-webgl" role="status"><strong>${esc(c.noWebgl)}</strong><p>${esc(c.routeSummary)}: DEPOT → STOP-01 → STOP-02 → STOP-03</p></div>` : roadSvg();
    return `<section id="v16Panel-road" class="v16-panel" data-v16-panel="road" aria-labelledby="v16RoadTitle">${sectionHead(c.roadTitle, `${c.providerConfigured} · ${c.fixture}`)}<div class="v16-toolbar"><label>${esc(c.routingProvider)}<select id="v16Provider"><option>SYNTHETIC_ROAD_FIXTURE</option></select></label><label>${esc(c.roadProfile)}<select id="v16Profile"><option>LIGHT_TRUCK</option></select></label><span class="v16-fact"><small>${esc(c.snap)}</small><b>HIGH · 100%</b></span><span class="v16-fact"><small>${esc(c.restrictions)}</small><b>${model.route.restrictionsApplied.length}</b></span><span class="v16-fact"><small>${esc(c.toll)}</small><b>${model.route.tollSummary.tollEdgeCount}</b></span></div><div class="v16-map-layout"><div class="v16-map-surface" tabindex="0" aria-describedby="v16RouteLongDescription">${noMap}<div class="v16-map-actions"><button type="button" data-v16-action="reset-map">↺ <span>${esc(c.reset)}</span></button><button type="button" data-v16-action="toggle-follow">◎ <span>${esc(state.follow ? c.exitFollow : c.follow)}</span></button></div></div><div class="v16-route-inspector" role="region" aria-label="${esc(c.routeSummary)}">${sectionHead(selected.pointId)}${metric(c.distance, fmt(model.route.totalDistance), " km")}${metric(c.duration, fmt(model.route.totalDuration, 0), " min")}<div class="v16-step-actions"><button type="button" data-v16-action="previous-stop">← ${esc(c.previous)}</button><button type="button" data-v16-action="next-stop">${esc(c.next)} →</button></div><div id="v16RouteLongDescription" class="v16-long-description"><strong>${esc(c.routeSummary)}</strong><p>DEPOT → STOP-01 → STOP-02 → STOP-03</p><p>${esc(c.closure)}: 0 · ${esc(c.estimated)}: false</p></div></div></div>${routeTable()}</section>`;
  }
  function routeTable() { const c = copy(); return `<div class="v16-table-wrap"><table><caption>${esc(c.tableEquivalent)}</caption><thead><tr><th>${esc(c.stop)}</th><th>${esc(c.distance)}</th><th>${esc(c.duration)}</th><th>${esc(c.status)}</th></tr></thead><tbody>${state.model.route.legs.map((leg) => `<tr><td>${esc(leg.toPointId)}</td><td>${fmt(leg.distance)} km</td><td>${fmt(leg.duration, 0)} min</td><td><span class="v16-status shape-pass">PASS ✓</span></td></tr>`).join("")}</tbody></table></div>`; }

  function filteredAlerts() { const rows = state.model.inbox.list({ sort: "severity" }); return state.alertFilter === "ALL" ? rows : rows.filter((alert) => alert.state === state.alertFilter || alert.severity === state.alertFilter); }
  function alertButtons(alert) { const c = copy(); if (alert.state === "OPEN") return `<button type="button" data-alert-action="ack" data-alert-id="${esc(alert.alertId)}">✓ ${esc(c.acknowledge)}</button>`; if (alert.state === "ACKNOWLEDGED") return `<button type="button" data-alert-action="handling" data-alert-id="${esc(alert.alertId)}">▶ ${esc(c.handling)}</button>`; if (alert.state === "IN_PROGRESS") return `<button type="button" data-alert-action="resolve" data-alert-id="${esc(alert.alertId)}">✓ ${esc(c.resolve)}</button>`; return ""; }
  function alertsList() { const c = copy(); const rows = filteredAlerts(); if (!rows.length) return `<p class="v16-empty">${esc(c.noAlerts)}</p>`; return rows.map((alert) => `<article class="v16-alert" data-alert-state="${alert.state}" data-severity="${alert.severity}" tabindex="-1"><div class="v16-alert-marker" aria-hidden="true">${alert.severity === "CRITICAL" ? "!" : "▲"}</div><div><strong>${esc(alert.ruleId.replaceAll("_", " "))}</strong><p>${esc(alert.routeId)} · ${esc(alert.orderId)} · ${esc(stateLabel(alert.state))}</p><small>${esc(alert.evidence[0]?.metric)} ${esc(alert.evidence[0]?.actualValue)}</small></div><div class="v16-alert-action">${alertButtons(alert)}</div></article>`).join(""); }
  function renderOperations() {
    const c = copy(); const rows = state.model.inbox.list(); const status = state.stale ? c.stale : c.liveSimulation;
    return `<section id="v16Panel-operations" class="v16-panel" data-v16-panel="operations" aria-labelledby="v16OperationsTitle">${sectionHead(c.operationsTitle, c.boundary)}<div class="v16-command-strip">${metric(c.executionStatus, status)}${metric(c.routeHealth, fmt(state.model.routeHealth.score, 0), "/100")}${metric(c.alerts, String(rows.filter((row) => !["RESOLVED", "DISMISSED"].includes(row.state)).length))}<div class="v16-command-actions"><button type="button" data-v16-action="toggle-stale">${esc(state.stale ? c.clearStale : c.simulateStale)}</button></div></div><div class="v16-operations-grid"><div class="v16-alert-inbox"><div class="v16-filter-row"><label>${esc(c.alerts)}<select id="v16AlertFilter"><option value="ALL">${esc(c.all)}</option><option value="OPEN">${esc(c.open)}</option><option value="ACKNOWLEDGED">${esc(c.acknowledged)}</option><option value="IN_PROGRESS">${esc(c.inProgress)}</option><option value="HIGH">${esc(c.high)}</option></select></label></div><div id="v16AlertList">${alertsList()}</div></div><div class="v16-operations-summary"><strong>${esc(c.alertSummary)}</strong><p>${rows.length} ${esc(c.alerts)} · ${esc(c.partial)} · ${esc(c.focusPreserved)}</p><ul>${rows.map((alert) => `<li>${esc(alert.ruleId)}: ${esc(stateLabel(alert.state))}, ${esc(alert.routeId)}, ${esc(alert.orderId)}</li>`).join("")}</ul></div></div></section>`;
  }
  function renderActual() {
    const c = copy(); const report = state.model.report;
    const rows = report.stops.map((stop) => `<tr><td>${esc(stop.orderId)}</td><td>${fmt(stop.plannedArrival, 0)}</td><td>${stop.simulatedActualArrival === null ? "—" : fmt(stop.simulatedActualArrival, 0)}</td><td>${stop.etaErrorMinutes === null ? "—" : `${stop.etaErrorMinutes > 0 ? "+" : ""}${fmt(stop.etaErrorMinutes, 0)} min`}</td><td><span class="v16-status ${stop.completed ? "shape-pass" : "shape-pending"}">${stop.completed ? "✓ COMPLETED" : "○ PENDING"}</span></td><td><button type="button" data-event-seek="${esc(stop.orderId)}">⌖ ${esc(c.eventSeek)}</button></td></tr>`).join("");
    return `<section id="v16Panel-actual" class="v16-panel" data-v16-panel="actual" aria-labelledby="v16ActualTitle">${sectionHead(c.actualTitle, `${c.planned} / ${c.simulatedActual}`)}<div class="v16-metrics">${metric(c.completion, fmt(report.metrics.completionRate), "%")}${metric(c.routeAdherence, fmt(report.metrics.routeAdherencePercent), "%")}${metric(c.etaError, report.metrics.etaMaeMinutes === null ? "—" : fmt(report.metrics.etaMaeMinutes), " min")}${metric(c.dwellVariance, report.metrics.dwellVarianceMinutes === null ? "—" : fmt(report.metrics.dwellVarianceMinutes), " min")}</div><div class="v16-actual-layout"><div class="v16-timeline" aria-label="${esc(c.actualTitle)}"><div class="v16-timeline-axis"><span>480</span><span>500</span><span>520</span><span>540</span></div><div class="v16-timeline-lane planned"><b>${esc(c.planned)}</b><i style="width:86%"></i></div><div class="v16-timeline-lane actual"><b>${esc(c.simulatedActual)}</b><i style="width:42%"></i></div></div><div class="v16-table-wrap"><table><caption>${esc(c.tableEquivalent)}</caption><thead><tr><th>${esc(c.stop)}</th><th>${esc(c.planned)}</th><th>${esc(c.simulatedActual)}</th><th>${esc(c.delta)}</th><th>${esc(c.status)}</th><th>${esc(c.eventSeek)}</th></tr></thead><tbody>${rows}</tbody></table></div></div></section>`;
  }
  function renderRolling() {
    const c = copy(); const cards = state.model.candidates.map((candidate) => `<label class="v16-candidate ${state.recoveryCandidate === candidate.id ? "selected" : ""}"><input type="radio" name="v16RecoveryCandidate" value="${candidate.id}" ${state.recoveryCandidate === candidate.id ? "checked" : ""}><span><strong>${esc(c[candidate.label])}</strong><small>${esc(candidate.type)}</small></span><b>${fmt(candidate.distance)} km</b><em>${candidate.status === "PASS" ? "✓ PASS" : "✓ HTTP"}</em></label>`).join("");
    const action = state.recoveryConfirm ? `<div class="v16-confirm" role="alert"><strong>${esc(c.confirmApply)}</strong><button type="button" data-v16-action="confirm-recovery">✓ ${esc(c.confirmApply)}</button><button type="button" data-v16-action="cancel-recovery">× ${esc(c.cancel)}</button></div>` : `<div class="v16-recovery-actions"><button type="button" data-v16-action="preview-recovery" ${state.recoveryCandidate ? "" : "disabled"}>▣ ${esc(c.preview)}</button><button type="button" data-v16-action="apply-recovery" ${state.recoveryCandidate ? "" : "disabled"}>✓ ${esc(c.applySimulation)}</button></div>`;
    return `<section id="v16Panel-rolling" class="v16-panel" data-v16-panel="rolling" aria-labelledby="v16RollingTitle">${sectionHead(c.rollingTitle, c.rollingNote)}<div class="v16-rolling-meta">${metric(c.transferPolicy, "LOCK_LOADED_ORDERS")}${metric(c.handover, "510 min")}${metric(c.counterRecovery, "AVAILABLE AFTER ACK")}</div><div class="v16-candidates" role="radiogroup" aria-label="${esc(c.candidate)}">${cards}</div>${action}<div class="v16-recovery-summary" role="status">${esc(state.recoveryApplied ? c.appliedSimulation : state.recoveryCandidate ? `${c.preview}: ${state.recoveryCandidate}` : c.pendingSelection)}</div><div class="v16-route-morph"><div><span>${esc(c.simulatedActual)}</span><b>ROAD-16 · prefix fixed</b></div><div aria-hidden="true">→</div><div><span>${esc(c.planned)}</span><b>${esc(state.recoveryCandidate || "CANDIDATE")}</b></div></div></section>`;
  }
  function driverAction(name, label, enabled) { return `<button type="button" data-driver-action="${name}" ${enabled ? "" : "disabled"}>${esc(label)}</button>`; }
  function renderDriver() {
    const c = copy(); const view = state.model.driver.viewModel(); const legal = view.legalActions;
    return `<section id="v16Panel-driver" class="v16-panel" data-v16-panel="driver" aria-labelledby="v16DriverTitle">${sectionHead(c.driverTitle, c.driverBoundary)}<div class="v16-driver-layout"><div class="v16-driver-route"><span>${esc(c.assignedRoute)}</span><strong>${esc(view.assignedRoute.routeId)} · VEH-16</strong><p>${esc(c.nextStop)}: ${esc(view.currentStop?.orderId || "—")} · ${esc(view.currentStop?.state || "COMPLETED")}</p><button type="button" data-v16-action="driver-map-focus">⌖ ${esc(c.mapFocus)}</button></div><div class="v16-driver-actions">${driverAction("acceptRoute", c.acceptRoute, legal.acceptRoute)}${driverAction("depart", c.depart, legal.depart)}${driverAction("arrive", c.arrive, legal.arrive)}${driverAction("startService", c.startService, legal.startService)}${driverAction("complete", c.complete, legal.complete)}${driverAction("fail", c.fail, legal.fail)}${driverAction("skip", c.skip, legal.skip)}${driverAction("goOffline", c.goOffline, legal.goOffline)}${driverAction("reconnect", c.reconnect, legal.reconnect)}</div><div class="v16-queue"><strong>${esc(c.queue)}</strong><span class="v16-status ${view.offline ? "shape-alert" : "shape-pass"}">${view.offline ? `! ${esc(c.offline)}` : `✓ ${esc(c.liveSimulation)}`}</span><p>${view.queue.length ? view.queue.map((item) => `${esc(item.localEventId)} · ${esc(item.statusText)}`).join("<br>") : "0 LOCAL_PENDING"}</p></div></div></section>`;
  }
  function panel() { return ({ road: renderRoad, operations: renderOperations, actual: renderActual, rolling: renderRolling, driver: renderDriver })[state.tab](); }
  function shell() {
    const c = copy(); return `<section id="v16Experience" class="v16-experience ${state.noWebGL ? "is-no-webgl" : ""} ${state.reducedMotion ? "is-reduced-motion" : ""}" data-version="1.6" data-boundary="LOCAL_SIMULATION_NOT_LIVE"><header class="v16-header"><div><p class="v16-eyebrow">STCT v1.6 · ${esc(c.boundary)}</p><h2>${esc(c.title)}</h2><p>${esc(c.subtitle)}</p></div><div class="v16-header-actions"><span class="v16-status shape-pending">Ⅱ ${esc(c.paused)}</span>${state.restored ? `<span class="v16-status shape-pass">✓ ${esc(c.restored)}</span>` : ""}<button type="button" data-v16-action="export-capsule">⇩ ${esc(c.capsule)}</button><button type="button" data-v16-action="close" aria-label="${esc(c.close)}">×</button></div></header><nav class="v16-tabs" role="tablist">${Object.entries(c.tabs).map(([id, label]) => `<button type="button" role="tab" data-v16-tab="${id}" aria-selected="${state.tab === id}" tabindex="${state.tab === id ? "0" : "-1"}">${esc(label)}</button>`).join("")}</nav><main id="v16PanelHost">${panel()}</main><footer class="v16-footer"><span>${esc(c.readOnly)}</span><span>SHA-256 · ${esc(state.model.provider.id)} · ${esc(state.model.matrix.matrixHash.slice(-12))}</span></footer><div id="v16Live" class="v16-sr-only" aria-live="polite" aria-atomic="true">${esc(state.liveMessage)}</div></section>`; }
  function render() { if (!host() || !state.model) return; host().innerHTML = shell(); saveView(); }
  function renderPanel(restoreSelector) { const panelHost = document.getElementById("v16PanelHost"); if (!panelHost) return; panelHost.innerHTML = panel(); const target = restoreSelector ? panelHost.querySelector(restoreSelector) : null; target?.focus?.(); saveView(); }
  function saveView() { try { sessionStorage.setItem("stct-v16-view", JSON.stringify({ tab: state.tab, selectedStop: state.selectedStop, alertFilter: state.alertFilter, follow: state.follow, executionCursor: state.model?.executionState?.latestLogicalTime || 0, paused: true })); } catch (_) {} }
  function restoreView() { try { const value = JSON.parse(sessionStorage.getItem("stct-v16-view") || "null"); if (!value) return; if (["road", "operations", "actual", "rolling", "driver"].includes(value.tab)) state.tab = value.tab; state.selectedStop = Math.max(0, Math.min(3, Number(value.selectedStop || 0))); state.alertFilter = text(value.alertFilter || "ALL"); state.follow = value.follow === true; state.restored = true; } catch (_) {} }

  function switchTab(tab) { if (!["road", "operations", "actual", "rolling", "driver"].includes(tab)) return; const started = performance.now(); state.tab = tab; render(); if (tab === "operations") state.measurements.commandCenterOpenMs = performance.now() - started; if (tab === "actual") state.measurements.timelineRenderMs = performance.now() - started; }
  function announce(message) { state.liveMessage = message; const live = document.getElementById("v16Live"); if (live) live.textContent = message; }
  async function handleDriver(action, button) { const driver = state.model.driver; const functions = { acceptRoute: () => driver.acceptRoute(), depart: () => driver.depart(), arrive: () => driver.arrive(), startService: () => driver.startService(), complete: () => driver.complete(), fail: () => driver.failStop({ reason: "SYNTHETIC_DRIVER_FAILURE" }), skip: () => driver.skip(), goOffline: () => driver.goOffline(), reconnect: () => driver.reconnect() }; if (!functions[action]) return; const selector = `[data-driver-action="${action}"]`; try { const result = await functions[action](); announce(`${action}: ${result.status}`); renderPanel(selector); } catch (error) { announce(`${action}: ${error.code || error.message}`); button?.focus?.(); } }
  function handleAlert(action, id, button) { const inbox = state.model.inbox; const logicalTime = state.model.executionState.latestLogicalTime + 1; try { if (action === "ack") inbox.acknowledge(id, { logicalTime, owner: "LOCAL_DISPATCHER" }); else if (action === "handling") inbox.startHandling(id, { logicalTime, owner: "LOCAL_DISPATCHER" }); else if (action === "resolve") inbox.resolve(id, { logicalTime, reason: "Synthetic evidence reviewed", evidence: [{ source: "LOCAL_SIMULATION", status: "CLEARED" }] }); announce(`${id}: ${action}`); renderPanel(`[data-alert-id="${id}"]`); } catch (error) { announce(error.code || error.message); button?.focus?.(); } }
  function handleClick(event) {
    const tab = event.target.closest("[data-v16-tab]")?.dataset.v16Tab; if (tab) { switchTab(tab); return; }
    const driverButton = event.target.closest("[data-driver-action]"); if (driverButton) { handleDriver(driverButton.dataset.driverAction, driverButton); return; }
    const alertButton = event.target.closest("[data-alert-action]"); if (alertButton) { handleAlert(alertButton.dataset.alertAction, alertButton.dataset.alertId, alertButton); return; }
    const candidate = event.target.closest('input[name="v16RecoveryCandidate"]'); if (candidate) { state.recoveryCandidate = candidate.value; state.recoveryConfirm = false; renderPanel(`input[value="${candidate.value}"]`); return; }
    const seek = event.target.closest("[data-event-seek]"); if (seek) { const started = performance.now(); state.selectedStop = Math.max(0, state.model.points.findIndex((pointValue) => pointValue.pointId === seek.dataset.eventSeek)); state.measurements.eventSeekMs = performance.now() - started; announce(`${copy().eventSeek}: ${seek.dataset.eventSeek}`); seek.focus(); return; }
    const stop = event.target.closest("[data-stop-index]"); if (stop) { state.selectedStop = Number(stop.dataset.stopIndex); renderPanel(`[data-stop-index="${state.selectedStop}"]`); return; }
    const action = event.target.closest("[data-v16-action]")?.dataset.v16Action; if (!action) return;
    if (action === "close") close(); else if (action === "reset-map") { state.selectedStop = 0; state.follow = false; renderPanel('[data-v16-action="reset-map"]'); }
    else if (action === "toggle-follow") { state.follow = !state.follow; renderPanel('[data-v16-action="toggle-follow"]'); }
    else if (action === "previous-stop" || action === "next-stop") { const started = performance.now(); const direction = action === "previous-stop" ? -1 : 1; state.selectedStop = (state.selectedStop + direction + state.model.points.length) % state.model.points.length; state.measurements.routeSwitchMs = performance.now() - started; renderPanel(`[data-v16-action="${action}"]`); }
    else if (action === "toggle-stale") { state.stale = !state.stale; announce(state.stale ? copy().stale : copy().liveSimulation); renderPanel('[data-v16-action="toggle-stale"]'); }
    else if (action === "preview-recovery") { announce(`${copy().preview}: ${state.recoveryCandidate}`); }
    else if (action === "apply-recovery") { state.recoveryConfirm = true; renderPanel('[data-v16-action="confirm-recovery"]'); }
    else if (action === "confirm-recovery") { state.recoveryConfirm = false; state.recoveryApplied = true; announce(copy().appliedSimulation); renderPanel(); }
    else if (action === "cancel-recovery") { state.recoveryConfirm = false; renderPanel('[data-v16-action="apply-recovery"]'); }
    else if (action === "driver-map-focus") announce("FOCUS_MAP_ONLY · navigationClaim=false");
    else if (action === "export-capsule") announce(`${copy().capsule}: READ_ONLY_REPLAY`);
  }
  function handleChange(event) { if (event.target.id === "v16AlertFilter") { const started = performance.now(); state.alertFilter = event.target.value; const list = document.getElementById("v16AlertList"); if (list) list.innerHTML = alertsList(); state.measurements.alertFilterMs = performance.now() - started; announce(`${copy().alerts}: ${state.alertFilter}`); } }
  function handleKeydown(event) { const tab = event.target.closest("[data-v16-tab]"); if (!tab || !["ArrowLeft", "ArrowRight"].includes(event.key)) return; event.preventDefault(); const tabs = [...document.querySelectorAll("[data-v16-tab]")]; const index = tabs.indexOf(tab); const next = tabs[(index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length]; switchTab(next.dataset.v16Tab); document.querySelector(`[data-v16-tab="${next.dataset.v16Tab}"]`)?.focus(); }
  function attach() { const target = host(); if (!target || state.listener) return; state.listener = { click: handleClick, change: handleChange, keydown: handleKeydown }; target.addEventListener("click", handleClick); target.addEventListener("change", handleChange); target.addEventListener("keydown", handleKeydown); }
  function detach() { const target = host(); if (!target || !state.listener) return; target.removeEventListener("click", state.listener.click); target.removeEventListener("change", state.listener.change); target.removeEventListener("keydown", state.listener.keydown); state.listener = null; }

  async function open(options = {}) {
    const started = performance.now(); if (state.opened) close({ restore: false }); state.previousView = activeView() === "experienceView" ? state.previousView : activeView(); root.STCTCore?.switchView?.("experienceView"); const c = copy(); const v16Nav = document.querySelector("[data-v16-open] span:last-child"); const replayNav = document.querySelector("[data-experience-open] span:last-child"); if (v16Nav) v16Nav.textContent = c.nav; if (replayNav) replayNav.textContent = language() === "zh" ? "演练" : language() === "ja" ? "演習" : "Replay"; document.querySelectorAll(".navbtn").forEach((button) => button.classList.toggle("active", button.hasAttribute("data-v16-open")));
    state.noWebGL = options.noWebGL === true || new URLSearchParams(location.search).get("no-webgl") === "1"; state.reducedMotion = options.reducedMotion === true || new URLSearchParams(location.search).get("reduced-motion") === "1" || Boolean(matchMedia?.("(prefers-reduced-motion: reduce)")?.matches); state.restored = false; restoreView(); state.model = await createModel(); state.driver = state.model.driver; state.layers.registerAll("EXPERIENCE_V16"); state.opened = true; render(); attach(); state.measurements.commandCenterOpenMs = performance.now() - started; return snapshot();
  }
  function close(options = {}) { if (state.interval) { clearInterval(state.interval); state.interval = null; } detach(); state.layers.cleanupOwner("EXPERIENCE_V16"); if (host()) host().replaceChildren(); state.opened = false; state.activeRafs = 0; document.querySelector("[data-v16-open]")?.classList.remove("active"); if (options.restore !== false) root.STCTCore?.switchView?.(state.previousView && state.previousView !== "experienceView" ? state.previousView : "mapView"); return diagnostics(); }
  function setNoWebGL(value) { state.noWebGL = value === true; if (state.opened) render(); return state.noWebGL; }
  function snapshot() { return { version: VERSION, opened: state.opened, tab: state.tab, noWebGL: state.noWebGL, reducedMotion: state.reducedMotion, paused: true, autoRelease: false, autoPlay: false, autoApplyRecovery: false, externalRequests: false, measurements: { ...state.measurements } }; }
  function diagnostics() { return { opened: state.opened, activeListeners: state.listener ? 3 : 0, activeRafs: state.activeRafs, activeLayers: state.layers.count(), intervalActive: Boolean(state.interval), counters: { ...state.counters } }; }

  function performancePlan(stopCount = 240) {
    const orderIds = Array.from({ length: stopCount }, (_, index) => `PERF-${String(index + 1).padStart(3, "0")}`); const etaByOrder = {}; const serviceMinutesByOrder = {}; const volumeByOrder = {}; orderIds.forEach((id, index) => { etaByOrder[id] = 480 + index * 2; serviceMinutesByOrder[id] = 1; volumeByOrder[id] = 1; });
    const plan = { planHash: Integrity.hashValue({ perf: stopCount }), verification: { status: "PASS" }, logicalStartMinute: 480, vehicles: [{ id: "PV", maxVolume: stopCount }], routes: [{ routeId: "PR", vehicleId: "PV", orderIds, etaByOrder, serviceMinutesByOrder, volumeByOrder, totalDistance: stopCount * .8, maxVolume: stopCount }] };
    const run = { executionRunHash: Integrity.hashValue({ perfRun: stopCount }), logicalStartMinute: 480, status: "RUNNING" }; const acceptedEvents = []; orderIds.forEach((id, index) => { acceptedEvents.push({ eventId: `PA-${index}`, eventHash: Integrity.hashValue({ id, type: "A" }), sequence: index * 3 + 1, eventType: "STOP_ARRIVED", logicalTime: etaByOrder[id] + index % 7, orderId: id, routeId: "PR", vehicleId: "PV", payload: {} }, { eventId: `PS-${index}`, eventHash: Integrity.hashValue({ id, type: "S" }), sequence: index * 3 + 2, eventType: "SERVICE_STARTED", logicalTime: etaByOrder[id] + index % 7, orderId: id, routeId: "PR", vehicleId: "PV", payload: {} }, { eventId: `PC-${index}`, eventHash: Integrity.hashValue({ id, type: "C" }), sequence: index * 3 + 3, eventType: "SERVICE_COMPLETED", logicalTime: etaByOrder[id] + index % 7 + 1, orderId: id, routeId: "PR", vehicleId: "PV", payload: {} }); });
    const executionState = { authority: "EXECUTION_STORE_V16", run, acceptedEvents, executionStateHash: Integrity.hashValue({ perfState: stopCount }) }; return { plan, executionState };
  }
  function measureMetrics240() { const input = performancePlan(240); const started = performance.now(); const report = Analytics.compute(input); state.measurements.metricRecomputeMs = performance.now() - started; return { milliseconds: state.measurements.metricRecomputeMs, stopCount: report.stops.length, metricReportHash: report.metricReportHash }; }
  async function performanceProbe(options = {}) {
    const durationMs = Math.max(800, Number(options.durationMs || 1200)); const tickMs = Math.max(20, Number(options.tickMs || 40)); state.counters = { applicationUpdates: 0, mapAdapterUpdates: 0, mapSourceUpdates: 0, browserRafCallbacks: 0 }; let longTaskCount = 0; let observer = null;
    if (typeof PerformanceObserver !== "undefined" && PerformanceObserver.supportedEntryTypes?.includes("longtask")) { observer = new PerformanceObserver((list) => { longTaskCount += list.getEntries().length; }); observer.observe({ entryTypes: ["longtask"] }); }
    const started = performance.now(); await new Promise((resolve) => { state.interval = setInterval(() => { state.counters.applicationUpdates += 1; state.counters.mapAdapterUpdates += 1; state.counters.mapSourceUpdates += 1; const marker = document.querySelector(".v16-map-stop.active circle"); if (marker) marker.dataset.tick = String(state.counters.applicationUpdates); if (performance.now() - started >= durationMs) { clearInterval(state.interval); state.interval = null; resolve(); } }, tickMs); }); observer?.disconnect(); const elapsed = performance.now() - started; const metrics = measureMetrics240(); return { stopCount: 240, elapsedMs: elapsed, longTaskCount, applicationUpdateHz: state.counters.applicationUpdates / elapsed * 1000, mapAdapterUpdateHz: state.counters.mapAdapterUpdates / elapsed * 1000, mapSourceUpdateHz: state.counters.mapSourceUpdates / elapsed * 1000, browserRafHz: 0, rawCounts: { ...state.counters }, metricRecomputeMs: metrics.milliseconds };
  }
  function install() { if (state.installed) return; state.installed = true; document.querySelector("[data-v16-open]")?.addEventListener("click", () => open()); root.STCTV16.experienceUI = { VERSION, COPY, open, close, switchTab, setNoWebGL, snapshot, diagnostics, performanceProbe, measureMetrics240, state }; }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", install, { once: true }); else install();
})(typeof globalThis !== "undefined" ? globalThis : window);
