(function (root, factory) {
  "use strict";
  const contract = typeof module !== "undefined" && module.exports ? require("./network-contract-v18.js") : root.STCTV18?.networkContract;
  const solver = typeof module !== "undefined" && module.exports ? require("./network-solver-v18.js") : root.STCTV18?.networkSolver;
  const accounting = typeof module !== "undefined" && module.exports ? require("./network-accounting-v18.js") : root.STCTV18?.networkAccounting;
  const api = factory(contract, solver, accounting);
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) { root.STCTV18 = root.STCTV18 || { version: "1.8.0" }; root.STCTV18.scenarioLab = api; }
})(typeof globalThis !== "undefined" ? globalThis : this, function (Contract, Network, Accounting) {
  "use strict";

  if (!Contract?.normalizeScenario || !Network?.solveNetwork || !Accounting?.computeAccounting) throw new Error("STCT v1.8 scenario dependencies are required.");
  const VERSION = "stct-scenario-lab-v1.8";
  const TYPES = Object.freeze(["BASELINE", "ADD_DEPOT", "REMOVE_DEPOT", "DEPOT_CAPACITY_CHANGE", "ADD_VEHICLE_TYPE", "FLEET_MIX_CHANGE", "VEHICLE_TYPE_SHORTAGE", "DRIVER_UNAVAILABLE", "SHIFT_EXTENSION", "DEMAND_PEAK", "RELEASE_TIME_SHIFT", "ZONE_CHANGE", "DOCK_CAPACITY_CHANGE", "WAVE_POLICY_CHANGE", "ROAD_CLOSURE", "CROSS_DOCK_ENABLE", "CROSS_DOCK_INTERRUPTION"]);
  const TERMS = Object.freeze({ BASELINE: { zh: "基准场景", en: "Baseline scenario", ja: "ベースラインシナリオ" }, FLEET_MIX: { zh: "车队组合", en: "Fleet mix", ja: "車両構成" }, DEMAND_SHOCK: { zh: "需求冲击", en: "Demand shock", ja: "需要ショック" }, SCENARIO_CHANGED: { zh: "场景已变化", en: "Scenario changed", ja: "シナリオ変更" }, TESTED_CONFIGURATION: { zh: "测试配置中的最佳结果", en: "Best found in tested configurations", ja: "テスト構成内の最良結果" } });
  const clone = (value) => typeof structuredClone === "function" ? structuredClone(value) : JSON.parse(JSON.stringify(value)); const text = (value) => String(value ?? ""); const number = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback; const round = (value) => Math.round(Number(value) * 1000) / 1000;
  function shiftTime(value, minutes) { const parts = text(value).split(":").map(Number); const total = ((number(parts[0]) * 60 + number(parts[1]) + number(minutes)) % 1440 + 1440) % 1440; return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`; }
  function term(code, locale = "en") { const language = text(locale).startsWith("zh") ? "zh" : text(locale).startsWith("ja") ? "ja" : "en"; return TERMS[code]?.[language] || code; }
  function baseline(source) { const scenario = Contract.normalizeScenario(source); const identity = Contract.identityBundle(scenario); return { scenarioId: "SCENARIO-BASELINE", type: "BASELINE", revision: 1, parentScenarioId: "", parentInputHash: "", inputHash: identity.networkInputHash, changeHash: Contract.hashArtifact({ type: "BASELINE", inputHash: identity.networkInputHash }), scenario, label: "Baseline", audit: [{ action: "CAPTURE_BASELINE", inputHash: identity.networkInputHash }] }; }
  function nextId(type, payload) { return `SCENARIO-${type}-${Contract.hashArtifact(payload).slice(-10).toUpperCase()}`; }
  function applyScenario(parent, type, payload = {}) {
    if (!TYPES.includes(type) || type === "BASELINE") throw Object.assign(new Error("Unsupported scenario type"), { code: "SCENARIO_TYPE_UNSUPPORTED" }); const parentRecord = parent.scenario ? parent : baseline(parent); const scenario = clone(parentRecord.scenario); const beforeHash = Contract.identityBundle(scenario).networkInputHash; const firstDepot = scenario.depots[0];
    if (type === "ADD_DEPOT") { const suffix = payload.suffix || scenario.depots.length + 1; const depotId = payload.depotId || `D-ADDED-${suffix}`; const zoneId = `Z-${depotId}`; const loadDock = `DOCK-${depotId}-LOAD`; const mixedDock = `DOCK-${depotId}-MIXED`; scenario.zones.push({ zoneId, mode: "DIAGNOSTIC_ONLY", depotIds: [depotId], geometry: { type: "FixtureCircle", center: payload.coordinate || [117.35, 39.2], radiusKm: 20 } }); scenario.docks.push({ dockId: loadDock, depotId, type: "LOAD", compatibleVehicleTypes: scenario.vehicleTypes.map((row) => row.vehicleTypeId), operatingWindows: [{ start: "06:00", end: "23:59" }], simultaneousCapacity: 1, loadRate: 3, unloadRate: 3, fixedSetupMinutes: 5, queuePolicy: "FCFS" }, { dockId: mixedDock, depotId, type: "MIXED", compatibleVehicleTypes: scenario.vehicleTypes.map((row) => row.vehicleTypeId), operatingWindows: [{ start: "06:00", end: "23:59" }], simultaneousCapacity: 1, loadRate: 3, unloadRate: 3, fixedSetupMinutes: 5, queuePolicy: "FCFS" }); scenario.depots.push({ depotId, name: payload.name || `Synthetic Added Depot ${suffix}`, coordinate: payload.coordinate || [117.35, 39.2], timezone: scenario.planningHorizon.timezone, role: "SATELLITE", capabilities: ["DELIVERY", "PICKUP", "RELOAD"], operatingWindows: [{ start: "06:00", end: "23:59" }], serviceZoneIds: [zoneId], dockIds: [loadDock, mixedDock], reloadSupported: true, transferSupported: false, startVehicleIds: [], allowedVehicleTypes: scenario.vehicleTypes.map((row) => row.vehicleTypeId), fixedOperatingCost: 250, variableHandlingCost: 1.2, carbonFactor: 0.012, capacity: { dailyOrders: 100, volume: 500, weight: 5000, handlingMinutes: 1200, parkingSlots: 20 } }); }
    if (type === "REMOVE_DEPOT") { const depotId = payload.depotId; const depot = scenario.depots.find((row) => row.depotId === depotId); const referenced = scenario.orders.some((row) => row.allowedDepotIds.includes(depotId) || row.fixedDepotId === depotId) || scenario.vehicles.some((row) => row.homeDepotId === depotId || row.allowedStartDepotIds.includes(depotId) || row.allowedEndDepotIds.includes(depotId)); if (!depot || referenced) throw Object.assign(new Error("Only an unused depot can be removed"), { code: "SCENARIO_DEPOT_IN_USE" }); const dockIds = new Set(depot.dockIds); const zoneIds = new Set(depot.serviceZoneIds); scenario.depots = scenario.depots.filter((row) => row.depotId !== depotId); scenario.docks = scenario.docks.filter((row) => !dockIds.has(row.dockId)); scenario.zones = scenario.zones.filter((row) => !zoneIds.has(row.zoneId)); }
    if (type === "DEPOT_CAPACITY_CHANGE") { const depot = scenario.depots.find((row) => row.depotId === (payload.depotId || firstDepot.depotId)); depot.capacity[payload.field || "dailyOrders"] = number(payload.value, depot.capacity[payload.field || "dailyOrders"]); }
    if (type === "ADD_VEHICLE_TYPE") { const vehicleTypeId = payload.vehicleTypeId || `VT-ADDED-${scenario.vehicleTypes.length + 1}`; scenario.vehicleTypes.push({ vehicleTypeId, capacity: payload.capacity || { volume: 24, weight: 1200 }, cost: payload.cost || { fixed: 160, trip: 16, perKm: 0.9, perMinute: 0.2 }, emission: payload.emission || { loadedKgPerKm: 0.2, emptyKgPerKm: 0.15 }, energy: payload.energy || {} }); scenario.depots.forEach((depot) => { if (!depot.allowedVehicleTypes.includes(vehicleTypeId)) depot.allowedVehicleTypes.push(vehicleTypeId); }); scenario.docks.forEach((dock) => { if (!dock.compatibleVehicleTypes.includes(vehicleTypeId)) dock.compatibleVehicleTypes.push(vehicleTypeId); }); }
    if (type === "FLEET_MIX_CHANGE") { const vehicleTypeId = payload.vehicleTypeId || scenario.vehicleTypes[0].vehicleTypeId; const depotId = payload.depotId || firstDepot.depotId; const count = Math.max(1, number(payload.count, 1)); for (let index = 0; index < count; index += 1) { const vehicleId = `V-MIX-${scenario.vehicles.length + 1}`; const driverId = `DR-MIX-${scenario.drivers.length + 1}`; scenario.vehicles.push({ vehicleId, vehicleTypeId, homeDepotId: depotId, allowedStartDepotIds: [depotId], allowedEndDepotIds: [depotId], capacity: clone(payload.capacity || scenario.vehicleTypes.find((row) => row.vehicleTypeId === vehicleTypeId).capacity), cost: clone(payload.cost || {}), emission: clone(payload.emission || {}), energy: {}, routingProfile: payload.routingProfile || "CAR", maxTrips: number(payload.maxTrips, 3), availabilityWindows: [{ start: "06:00", end: "23:59" }], reloadCompatibility: [depotId] }); scenario.drivers.push({ driverId, homeDepotId: depotId, allowedEndDepotIds: [depotId], skills: ["DELIVERY", "PICKUP"], shiftWindows: [{ start: "06:00", end: "23:59" }], maxDrivingMinutes: 540, maxDutyMinutes: 720, requiredBreaks: [], compatibleVehicleTypes: [vehicleTypeId] }); scenario.depots.find((row) => row.depotId === depotId).startVehicleIds.push(vehicleId); } }
    if (type === "VEHICLE_TYPE_SHORTAGE") { const vehicleTypeId = payload.vehicleTypeId || scenario.vehicleTypes[0].vehicleTypeId; const count = Math.max(1, number(payload.count, 1)); scenario.vehicles.filter((vehicle) => vehicle.vehicleTypeId === vehicleTypeId).slice(0, count).forEach((vehicle) => { vehicle.availabilityWindows = []; }); }
    if (type === "DRIVER_UNAVAILABLE") { const driverId = payload.driverId || scenario.drivers[0].driverId; const driver = scenario.drivers.find((row) => row.driverId === driverId); if (driver) driver.shiftWindows = []; }
    if (type === "SHIFT_EXTENSION") { const minutes = Math.max(1, number(payload.minutes, 120)); scenario.drivers.filter((driver) => !payload.depotId || driver.homeDepotId === payload.depotId).forEach((driver) => { driver.maxDutyMinutes += minutes; driver.shiftWindows = driver.shiftWindows.map((window) => ({ ...window, end: shiftTime(window.end, minutes) })); }); }
    if (type === "DEMAND_PEAK") { const factor = number(payload.factor, 1.1); const dimension=payload.dimension||"both"; if(!["both","volume","weight"].includes(dimension)||factor<0)throw Object.assign(new Error("Invalid demand dimension or factor"),{code:"SCENARIO_DEMAND_DIMENSION_INVALID"}); scenario.orders.forEach((order) => { if (!payload.zoneId || order.zoneId === payload.zoneId) { if(dimension!=="weight")order.demand.volume = round(number(order.demand.volume) * factor); if(dimension!=="volume")order.demand.weight = round(number(order.demand.weight) * factor); } }); }
    if (type === "RELEASE_TIME_SHIFT") { const minutes = number(payload.minutes, 60); scenario.orders.forEach((order) => { if (!payload.zoneId || order.zoneId === payload.zoneId) order.releaseTime = shiftTime(order.releaseTime, minutes); }); }
    if (type === "ZONE_CHANGE") { const zone = scenario.zones.find((row) => row.zoneId === (payload.zoneId || scenario.zones[0].zoneId)); zone.mode = payload.mode || "PREFERRED"; if (payload.depotIds) zone.depotIds = [...payload.depotIds]; }
    if (type === "DOCK_CAPACITY_CHANGE") { const dock = scenario.docks.find((row) => row.dockId === (payload.dockId || scenario.docks[0].dockId)); dock.simultaneousCapacity = Math.max(1, number(payload.value, dock.simultaneousCapacity)); }
    if (type === "WAVE_POLICY_CHANGE") scenario.policies.wavePolicy = payload.wavePolicy || "PRIORITY";
    if (type === "ROAD_CLOSURE") { const closures = scenario.routingContext.closures || []; let index = closures.length + 1; while (closures.some(row => row.closureId === `CLOSURE-${index}`)) index++; scenario.routingContext.closures = [...closures, { closureId: payload.closureId || `CLOSURE-${index}`, from: payload.from || "FIXTURE-A", to: payload.to || "FIXTURE-B", status: "CLOSED" }]; }
    if (type === "CROSS_DOCK_ENABLE") { const depot = scenario.depots.find((row) => row.depotId === (payload.depotId || scenario.depots[scenario.depots.length - 1].depotId)); depot.transferSupported = true; if (!depot.capabilities.includes("CROSS_DOCK")) depot.capabilities.push("CROSS_DOCK"); scenario.policies.crossDockEnabled = true; }
    if (type === "CROSS_DOCK_INTERRUPTION") { const depot = scenario.depots.find((row) => row.depotId === (payload.depotId || scenario.depots.find((item) => item.transferSupported)?.depotId || scenario.depots[0].depotId)); depot.transferSupported = false; depot.capabilities = depot.capabilities.filter((capability) => capability !== "CROSS_DOCK"); scenario.policies.crossDockEnabled = false; }
    const normalized = Contract.normalizeScenario(scenario); const inputHash = Contract.identityBundle(normalized).networkInputHash; const change = { type, payload: clone(payload), parentInputHash: beforeHash, inputHash }; return { scenarioId: nextId(type, change), type, revision: parentRecord.revision + 1, parentScenarioId: parentRecord.scenarioId, parentInputHash: beforeHash, inputHash, changeHash: Contract.hashArtifact(change), scenario: normalized, label: type.replaceAll("_", " "), audit: [...parentRecord.audit, { action: "APPLY_SCENARIO", type, payload: clone(payload), parentInputHash: beforeHash, inputHash }] };
  }
  function restoreBaseline(value) {
    const record = value?.baseline || value?.baselineRecord || value;
    if (!record || record.type !== "BASELINE") throw Object.assign(new Error("Baseline record is required"), { code: "SCENARIO_BASELINE_UNAVAILABLE" });
    return clone(record);
  }
  function history(source) { const base = baseline(source); return { baseline: base, records: [base], cursor: 0 }; }
  function pushHistory(state, type, payload) { const parent = state.records[state.cursor]; const record = applyScenario(parent, type, payload); return { baseline: state.baseline, records: [...state.records.slice(0, state.cursor + 1), record], cursor: state.cursor + 1 }; }
  function undo(state) { return { ...state, cursor: Math.max(0, state.cursor - 1) }; }
  function active(state) { return state.records[state.cursor]; }
  function resultStaleness(record, result) { return { status: record.inputHash === result.networkInputHash ? "CURRENT" : "STALE_REJECTED", scenarioInputHash: record.inputHash, resultInputHash: result.networkInputHash }; }
  function evaluateFleetMix(parent, payload = {}, solveOptions = {}) { const record = applyScenario(parent, "FLEET_MIX_CHANGE", payload); const plan = Network.solveNetwork(record.scenario, solveOptions); const ledger = Accounting.computeAccounting(record.scenario, plan); return { schemaVersion: "stct-fleet-mix-result-v1.8", scenarioId: record.scenarioId, networkInputHash: record.inputHash, label: "Best found in tested configurations", optimalityWording: "Not a global fleet optimum.", configuration: clone(payload), metrics: { service: ledger.metrics.serviceLevel, cost: ledger.cost.total, carbonKg: ledger.carbon.totalKg, vehicles: record.scenario.vehicles.length, trips: plan.trip.trips.length, dockCongestion: ledger.metrics.dockCongestion, emptyDistanceKm: ledger.metrics.emptyDistanceKm, peakRequirement: Math.max(...plan.trip.tripChains.map((row) => row.tripIds.length), 0) }, planHash: plan.networkPlanHash, accountingHash: ledger.accountingHash, typeCompatibility: record.scenario.vehicles.every((vehicle) => record.scenario.vehicleTypes.some((type) => type.vehicleTypeId === vehicle.vehicleTypeId)), depotAllocation: record.scenario.vehicles.reduce((rows, vehicle) => { rows[vehicle.homeDepotId] = (rows[vehicle.homeDepotId] || 0) + 1; return rows; }, {}), audit: record.audit };
  }
  function applyShock(parent, shock, payload = {}) { if (["DEMAND_10", "DEMAND_25", "DEMAND_50", "REGIONAL_PEAK"].includes(shock)) return applyScenario(parent, "DEMAND_PEAK", { factor: shock === "DEMAND_10" ? 1.1 : shock === "DEMAND_25" ? 1.25 : shock === "DEMAND_50" ? 1.5 : number(payload.factor, 1.5), zoneId: shock === "REGIONAL_PEAK" ? payload.zoneId : "" }); const parentRecord = parent.scenario ? parent : baseline(parent); const scenario = clone(parentRecord.scenario); if (shock === "TIME_WINDOW_TIGHTEN") scenario.orders.forEach((order) => { order.timeWindows = [{ start: payload.start || "10:00", end: payload.end || "12:00" }]; }); if (shock === "DEPOT_OUTAGE") { const depotId = payload.depotId || scenario.depots[0].depotId; scenario.vehicles.filter((vehicle) => vehicle.homeDepotId === depotId).forEach((vehicle) => { vehicle.availabilityWindows = []; }); } if (shock === "DOCK_FAILURE") { const depotId = payload.depotId || scenario.depots[0].depotId; scenario.docks.filter((dock) => dock.depotId === depotId).forEach((dock) => { dock.type = "UNLOAD"; }); } const normalized = Contract.normalizeScenario(scenario); const inputHash = Contract.identityBundle(normalized).networkInputHash; const change = { shock, payload, parentInputHash: parentRecord.inputHash, inputHash }; return { scenarioId: nextId(shock, change), type: shock, revision: parentRecord.revision + 1, parentScenarioId: parentRecord.scenarioId, parentInputHash: parentRecord.inputHash, inputHash, changeHash: Contract.hashArtifact(change), scenario: normalized, label: shock.replaceAll("_", " "), audit: [...parentRecord.audit, { action: "APPLY_SHOCK", shock, payload: clone(payload), inputHash }] };
  }
  function evaluateShock(parent, shock, payload = {}, solveOptions = {}) { const record = applyShock(parent, shock, payload); const plan = Network.solveNetwork(record.scenario, solveOptions); const ledger = Accounting.computeAccounting(record.scenario, plan); const alerts = [...plan.dock.alerts, ...plan.custody.alerts, ...(plan.trip.unassigned.length ? [{ reasonCode: "SERVICE_IMPACT", count: plan.trip.unassigned.length }] : [])]; return { schemaVersion: "stct-demand-shock-result-v1.8", shock, scenarioId: record.scenarioId, networkInputHash: record.inputHash, propagation: { assignment: { assigned: plan.assignment.assignments.length, unassigned: plan.assignment.unassigned.length }, dock: clone(plan.dock.metrics), wave: clone(plan.waves.metrics), trip: clone(plan.trip.metrics), route: { distanceKm: plan.trip.metrics.routeDistanceKm }, service: ledger.metrics.serviceLevel, cost: ledger.cost.total, carbonKg: ledger.carbon.totalKg, alerts }, planHash: plan.networkPlanHash, accountingHash: ledger.accountingHash, audit: record.audit };
  }
  function compareResults(left, right) { const sameInput = left.networkInputHash === right.networkInputHash; return { comparable: sameInput, wording: sameInput ? "SAME_INPUT_OPTIMIZATION" : "SCENARIO_CHANGED", claimAllowed: sameInput ? "OPTIMIZATION_DIFFERENCE" : "SCENARIO_CHANGE_ONLY" }; }
  function candidateMetrics(candidate) {
    if (!candidate?.metrics && !candidate?.propagation) return {};
    const metrics = candidate.metrics || {}; const propagation = candidate.propagation || {}; const trip = propagation.trip || {}; const dock = propagation.dock || {};
    return { service: metrics.service ?? propagation.service, cost: metrics.cost ?? propagation.cost, carbonKg: metrics.carbonKg ?? propagation.carbonKg, vehicles: metrics.vehicles ?? 0, trips: metrics.trips ?? trip.tripCount, dockCongestion: metrics.dockCongestion ?? dock.congestionReservations, emptyDistanceKm: metrics.emptyDistanceKm ?? trip.repositionDistanceKm, transferCount: metrics.transferCount ?? 0, latestCompletion: metrics.latestCompletion ?? 0, blockedCount: metrics.blockedCount ?? 0, serviceLayer: metrics.serviceLayer || "SERVICE_FIRST" };
  }
  function observedFrontier(candidates) { const required = ["service", "cost", "carbonKg", "vehicles", "trips", "dockCongestion", "emptyDistanceKm", "transferCount", "latestCompletion", "blockedCount", "serviceLayer"]; const normalized = candidates.map((candidate) => ({ ...candidate, metrics: candidateMetrics(candidate) })).filter((candidate) => required.every((key) => candidate.metrics[key] !== undefined && Number.isFinite(candidate.metrics[key]) || key === "serviceLayer" && candidate.metrics[key])); if (!normalized.length) return { status: "EMPTY", excluded: candidates.length, frontier: [] }; const key = `${normalized[0].networkInputHash}|${normalized[0].metrics.serviceLayer}|${normalized[0].metrics.blockedCount}`; const eligible = normalized.filter((candidate) => `${candidate.networkInputHash}|${candidate.metrics.serviceLayer}|${candidate.metrics.blockedCount}` === key); const excluded = candidates.length - eligible.length; const frontier = eligible.filter((candidate, index) => !eligible.some((other, otherIndex) => otherIndex !== index && other.metrics.service >= candidate.metrics.service && other.metrics.cost <= candidate.metrics.cost && other.metrics.carbonKg <= candidate.metrics.carbonKg && other.metrics.vehicles <= candidate.metrics.vehicles && other.metrics.trips <= candidate.metrics.trips && other.metrics.dockCongestion <= candidate.metrics.dockCongestion && other.metrics.emptyDistanceKm <= candidate.metrics.emptyDistanceKm && other.metrics.transferCount <= candidate.metrics.transferCount && other.metrics.latestCompletion <= candidate.metrics.latestCompletion && (other.metrics.service > candidate.metrics.service || other.metrics.cost < candidate.metrics.cost || other.metrics.carbonKg < candidate.metrics.carbonKg))); return { status: "PASS", title: "Observed Network Candidate Frontier", sameInputHash: normalized[0].networkInputHash, serviceLayer: normalized[0].metrics.serviceLayer, blockedCount: normalized[0].metrics.blockedCount, frontier, excluded };
  }
  function validateNarrative(value) { const lower = text(value).toLowerCase(); return { status: lower.includes("global optimum") || lower.includes("globally optimal") || lower.includes("全局最优") ? "REJECTED" : "PASS", reasonCode: lower.includes("global optimum") || lower.includes("globally optimal") || lower.includes("全局最优") ? "GLOBAL_OPTIMUM_CLAIM_FORBIDDEN" : "" }; }
  function arenaSync(record, result) { return { scenarioId: record.scenarioId, networkInputHash: record.inputHash, map: { depotCount: record.scenario.depots.length, closureCount: record.scenario.routingContext.closures.length }, trips: { count: result.metrics?.trips ?? result.propagation?.trip.tripCount ?? 0 }, docks: { count: record.scenario.docks.length, congestion: result.metrics?.dockCongestion ?? result.propagation?.dock.congestionReservations ?? 0 }, heatmap: { points: record.scenario.orders.length, source: "CANONICAL_SCENARIO_DEMAND" } }; }
  function mobileCompare(left, right) { return { layout: "STACKED_SCENARIO_SHEETS", rows: [left, right].map((row) => ({ scenarioId: row.scenarioId, networkInputHash: row.networkInputHash, metrics: candidateMetrics(row) })), closeAction: "RETURN_TO_SCENARIO_LIST" }; }
  function scenarioTable(results) { return results.map((row) => ({ scenarioId: row.scenarioId, networkInputHash: row.networkInputHash, wording: row.label || row.shock, ...candidateMetrics(row) })); }
  function animationPolicy(reducedMotion) { return { reducedMotion: Boolean(reducedMotion), animatePropagation: !reducedMotion, staticRelationsVisible: true }; }
  function networkStory(result) { return { status: "PREVIEW", autoApply: false, applyRequiresConfirmation: true, scenarioId: result.scenarioId }; }
  function costDrilldown(source, plan) { const ledger = Accounting.computeAccounting(source, plan); return { accountingHash: ledger.accountingHash, allocationMethod: ledger.cost.allocationMethod, order: ledger.allocations.order, zone: ledger.allocations.zone, depot: ledger.allocations.depot, trip: ledger.allocations.trip, wave: ledger.allocations.wave, vehicleType: ledger.allocations.vehicleType }; }
  function exportResult(kind, result) { const payload = { schemaVersion: `stct-${kind.toLowerCase()}-export-v1.8`, networkInputHash: result.networkInputHash, result: clone(result) }; payload.exportHash = Contract.hashArtifact(payload); return JSON.stringify(payload, null, 2) + "\n"; }
  function createCapsule(record, result) { const capsule = { schemaVersion: "stct-scenario-capsule-v1.8", scenarioId: record.scenarioId, type: record.type, parentInputHash: record.parentInputHash, networkInputHash: record.inputHash, changeHash: record.changeHash, scenario: clone(record.scenario), result: clone(result) }; capsule.capsuleHash = Contract.hashArtifact(capsule); return capsule; }
  function replay(capsule) { const { capsuleHash, ...payload } = capsule; return { status: Contract.hashArtifact(payload) === capsuleHash && Contract.identityBundle(capsule.scenario).networkInputHash === capsule.networkInputHash ? "EQUIVALENT" : "MISMATCH" }; }

  return { VERSION, TYPES, TERMS, term, baseline, applyScenario, history, pushHistory, undo, active, restoreBaseline, resultStaleness, evaluateFleetMix, applyShock, evaluateShock, compareResults, observedFrontier, validateNarrative, arenaSync, mobileCompare, scenarioTable, animationPolicy, networkStory, costDrilldown, exportResult, createCapsule, replay, candidateMetrics };
});
