'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{chromium}=require('playwright'),X=require('../vendor/xlsx/xlsx.full.min.js');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_EXCEL_EVIDENCE,packages=process.env.STCT_MAP_PACKAGES,nonUC=process.env.STCT_NON_UC_PACKAGE;
assert.ok(out&&packages&&nonUC);fs.mkdirSync(out,{recursive:true});
const hash=v=>crypto.createHash('sha256').update(v).digest('hex'),sources=()=>Object.fromEntries(['supply-chain-report-workspace-v01.js','supply-chain-controller-v19.js','supply-chain-view-v19.js','platform-services-v19.js'].map(f=>[f,hash(fs.readFileSync(path.join(root,f)))]));
const report={status:'RUNNING',tier:'MACOS_CHROME_BUSINESS_DOWNLOAD_NOT_WINDOWS_EXCEL',sourceBefore:sources(),checks:[],pageErrors:[]};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>err?res.writeHead(404).end():res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(file)]||'application/octet-stream'}).end(data));});
let browser,context,page;
async function expose(locator){for(const d of (await locator.locator('xpath=ancestor::details').all()).reverse())if(!await d.evaluate(e=>e.open))await d.locator(':scope > summary').click();}
async function download(action,name){const button=page.locator('[data-supply-action="'+action+'"]');await expose(button);const event=page.waitForEvent('download');await button.click();const d=await event;await d.saveAs(path.join(out,name));return {suggestedFilename:d.suggestedFilename(),bytes:fs.readFileSync(path.join(out,name))};}
(async()=>{try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));report.port=server.address().port;browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 for(const scope of ['OUTBOUND_ONLY','UPSTREAM_ONLY','FULL_CHAIN','NON_UC']){
  context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>report.pageErrors.push(e.message));await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
  await page.goto(`http://127.0.0.1:${report.port}/index.html?forceHeuristic=1&noWebGL=1#/`);if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.getByRole('button',{name:/测算供应链方案/}).click();const input=page.locator('[data-supply-file="study"]');await expose(input);const file=scope==='NON_UC'?nonUC:path.join(packages,scope+'.package.json');await input.setInputFiles(file);await page.locator('[data-supply-action="export-xlsx"]').waitFor();
  const state=await page.evaluate(()=>STCTPlatformV19.instance.designAdapter.supplySnapshot()),before=hash(JSON.stringify(state.snapshot));
  const {bytes,suggestedFilename}=await download('export-xlsx',scope+'.xlsx');assert.match(suggestedFilename,/\.xlsx$/);assert.equal(bytes.subarray(0,2).toString(),'PK');const book=X.read(bytes,{type:'buffer'});assert.deepEqual(book.SheetNames,['说明','方案比较','新方案匹配明细','参照匹配明细']);const rows=X.utils.sheet_to_json(book.Sheets['新方案匹配明细'],{header:1,defval:null}),column=label=>rows[0].findIndex(v=>v.includes(label));
  const snapshot=state.snapshot,groups=snapshot.rows.map(r=>r.result||r),expected=groups.flatMap(g=>['inbound','outbound','transfer'].flatMap(k=>g[k]||[]));assert.equal(rows.length-1,expected.length);const byId=new Map(rows.slice(1).map(r=>[[r[column('Scenario ID')],r[column('Leg')],r[column('Period')],r[column('Demand ID')],r[column('From ID')],r[column('To ID')]].join('\0'),r]));
  for(const g of groups)for(const k of ['inbound','outbound','transfer'])for(const leg of g[k]||[]){const key=[g.scenarioId,leg.kind||k.toUpperCase(),leg.period,leg.demandId??null,leg.fromNodeId,leg.toNodeId].join('\0'),row=byId.get(key);assert.ok(row,key);assert.equal(row[column('Quantity')],leg.quantity);assert.equal(row[column('Distance km')],leg.distanceKm);assert.equal(row[column('Volume km')],leg.volumeKm);assert.equal(row[column(' Cost')],leg.cost??null);assert.equal(row[column('Snapshot hash')],snapshot.snapshotHash);assert.equal(row[column('From name')],state.study.nodes.find(n=>n.nodeId===leg.fromNodeId).name||leg.fromNodeId);}
  const comparison=X.utils.sheet_to_json(book.Sheets['方案比较'],{header:1,defval:null}),actualIds=comparison.slice(1).filter(r=>r[0]!=='REFERENCE').map(r=>r[2]);assert.deepEqual(actualIds,await page.evaluate(()=>STCTPlatformV19.trustedReport.project(STCTPlatformV19.instance.designAdapter.supplySnapshot()).candidates.map(c=>c.id)));
  for(const action of ['export-csv','export-comparison-csv']){const d=await download(action,scope+'-'+action+'.csv');assert.deepEqual([...d.bytes.subarray(0,3)],[239,187,191]);assert.ok(!d.bytes.subarray(3).includes(Buffer.from([239,187,191])),'Exactly one BOM');const text=new TextDecoder('utf-8',{fatal:true}).decode(d.bytes);assert.ok(!text.includes('\uFFFD'));}
  assert.equal(hash(JSON.stringify((await page.evaluate(()=>STCTPlatformV19.instance.designAdapter.supplySnapshot())).snapshot)),before);await page.screenshot({path:path.join(out,scope+'-controls.png')});report.checks.push({scope,status:'PASS',nativePackageSHA256:hash(fs.readFileSync(file)),assignmentRows:expected.length,xlsxSHA256:hash(bytes),bytes:bytes.length,allLedgerValuesMatched:true,csvBom:true,snapshotUnchanged:true});
  if(scope==='NON_UC')for(const [locale,names]of [['en',['Notes','Scenario comparison','Candidate assignments','Reference assignments']],['ja',['説明','計画比較','候補割当明細','参照割当明細']]]){await page.locator('[data-platform-locale]').selectOption(locale);const d=await download('export-xlsx','NON_UC-'+locale+'.xlsx');assert.deepEqual(X.read(d.bytes,{type:'buffer'}).SheetNames,names);report.checks.push({scope,locale,status:'PASS',xlsxSHA256:hash(d.bytes)});}
  await context.close();
 }
 assert.equal(report.pageErrors.length,0);report.status='PASS';
}catch(error){report.status='FAIL';report.error=error.stack;if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}
finally{if(browser)await browser.close();await new Promise(r=>server.close(r));report.serviceClosed=true;report.sourceAfter=sources();report.sourceStable=JSON.stringify(report.sourceBefore)===JSON.stringify(report.sourceAfter);if(!report.sourceStable){report.status='FAIL';process.exitCode=1;}fs.writeFileSync(path.join(out,'BROWSER_RESULTS.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}})();
