'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const projection=require('../platform-supply-map-v8.js');
const node=(nodeId,role,coordinate)=>({nodeId,name:nodeId,role,coordinate,coordinateSystem:'WGS84'});
const leg=(fromNodeId,toNodeId,quantity,distanceKm,cost=null,period='P1')=>({fromNodeId,toNodeId,quantity,distanceKm,cost,period});
const study={studyId:'FLOW-SYNTHETIC',inputHash:'I',periods:['P1','P2'],unit:'t',nodes:[node('West depot','DC',[112,32]),node('East depot','DC',[120,32]),node('Longer','CUSTOMER',[113,34]),node('Shorter','CUSTOMER',[119,34]),node('Unknown','CUSTOMER',null),node('Zero','CUSTOMER',[120,31]),node('Changed','CUSTOMER',[114,30]),node('Seasonal','CUSTOMER',[118,30])]};
const before=[leg('West depot','Longer',10,10),leg('West depot','Shorter',20,40),leg('West depot','Unknown',5,null),leg('East depot','Zero',2,0,0),leg('West depot','Changed',2,30),leg('East depot','Seasonal',1,30,null,'P1'),leg('East depot','Seasonal',2,30,null,'P2')];
const after=[leg('East depot','Longer',10,20),leg('East depot','Shorter',20,10),leg('East depot','Unknown',5,20),leg('East depot','Zero',2,0,0),leg('West depot','Changed',3,20),leg('East depot','Seasonal',2,20,null,'P1'),leg('East depot','Seasonal',1,20,null,'P2')];
const snapshot={schemaVersion:'stct-supply-chain-v5-snapshot-v1',studyHash:'I',snapshotHash:'SNAP',analysisScope:'OUTBOUND_ONLY',baseline:{outbound:before},rows:[{scenarioId:'PLAN',selectedSiteIds:['East depot','West depot'],outbound:after}],decision:{focusScenarioId:'PLAN'}};
const original=JSON.stringify({study,snapshot}),model=projection.projectComparison(study,snapshot), frozen=JSON.stringify(model);
const all=projection.exploreRelations(model);assert.equal(all.groups.length,6);assert.equal(all.unknownCount,3);
const longer=projection.exploreRelations(model,{direction:'LONGER'});assert.equal(longer.groups.length,1);assert.equal(longer.groups[0].deltaKm,10);assert.equal(longer.relations.length,2,'old and new links retained');assert.equal(longer.groups[0].before.cost,null);
assert.equal(projection.exploreRelations(model,{direction:'LONGER',minKm:11}).groups.length,0);
assert.equal(projection.exploreRelations(model,{direction:'SHORTER',minKm:30}).groups[0].nodeId,'Shorter');
assert.equal(all.groups.find(g=>g.nodeId==='Zero').deltaKm,0);assert.equal(all.groups.find(g=>g.nodeId==='Zero').before.cost,0);
assert.equal(all.groups.find(g=>g.nodeId==='Changed').reason,'QUANTITY_CHANGED');assert.equal(all.groups.find(g=>g.nodeId==='Seasonal').reason,'QUANTITY_CHANGED');
assert.equal(projection.exploreRelations(model,{direction:'UNKNOWN',minKm:100}).groups.length,3);
assert.equal(projection.exploreRelations(model,{nodeIds:[]}).groups.length,0);
assert.equal(projection.exploreRelations(model,{nodeIds:['Longer']}).relations.length,2);
assert.equal(projection.exploreRelations(model,{nodeIds:['West depot'],direction:'LONGER'}).relations.length,2,'counterpart retained even outside spotlight');
assert.equal(projection.exploreRelations(projection.projectComparison(study,snapshot,{change:'NEW'})).groups[0].reason,'PARTIAL_SCOPE');
assert.equal(projection.exploreRelations(projection.projectComparison(study,{...snapshot,studyHash:'STALE'})).groups.length,0);
assert.equal(JSON.stringify({study,snapshot}),original);assert.equal(JSON.stringify(model),frozen);
const inboundStudy={...study,nodes:[...study.nodes,node('Source A','SUPPLIER',[111,32]),node('Source B','SUPPLIER',[121,32])]};
const inboundSnapshot={...snapshot,analysisScope:'UPSTREAM_ONLY',baseline:{inbound:[leg('Source A','West depot',10,10),leg('Source B','West depot',30,30)]},rows:[{scenarioId:'PLAN',inbound:[leg('Source A','West depot',20,10),leg('Source B','West depot',20,30)]}]};
const upstream=projection.exploreRelations(projection.projectComparison(inboundStudy,inboundSnapshot));assert.equal(upstream.groups.length,1);assert.equal(upstream.groups[0].before.weightedKm,25);assert.equal(upstream.groups[0].after.weightedKm,20);assert.equal(upstream.groups[0].deltaKm,-5);
const source=fs.readFileSync(require.resolve('../platform-map-runtime-v19.js'),'utf8');
const seam=`root.__flow={setup(m,locale){model=m;owner='SUPPLY';config={locale};views.clear();resetFlow();},state:()=>view(),computeFlow,flowPanel,activeFeatures,resetFlow};`;
const sandbox={STCTPlatformV19:{supplyMap:projection,businessNumber:{number:(n,l,d=1)=>Number.isFinite(n)?n.toLocaleString(l,{maximumFractionDigits:d}):'—'}},cancelAnimationFrame(){}};
vm.runInNewContext(source.replace(/\}\)\(globalThis\);\s*$/,seam+'})(globalThis);'),sandbox);const api=sandbox.__flow;
for(const locale of ['zh','en','ja']){api.setup(model,locale);Object.assign(api.state(),{flowOpen:true,flowDirection:'LONGER',flowIds:['West depot']});api.computeFlow();const html=api.flowPanel();assert.ok(html.includes('Longer'));assert.ok(!html.includes('data-p7-flow-receiver="outbound\u0000Shorter"'));assert.ok(html.includes('—'));const lines=api.activeFeatures().filter(f=>f.geometry.type==='LineString');assert.equal(lines.length,2);assert.ok(lines.every(f=>f.properties.focused));api.resetFlow();assert.equal(api.state().flowOpen,false);assert.equal(api.activeFeatures(true).length,model.features.length);}
assert.equal(JSON.stringify(model),frozen);
if(process.argv.includes('--fixture'))fs.writeFileSync(process.argv[process.argv.indexOf('--fixture')+1],JSON.stringify({study,snapshot}));
console.log('PASS flow explorer: receiver reassignment, thresholds, null/zero, per-period comparability, incomplete scopes, stale identity, endpoint spotlight, three-language rendering, feature filtering and immutability. Synthetic projection/VM only.');
