#!/usr/bin/env node
'use strict';
// Real business controls: existing validated study packages, no state injection or new solve.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_MAP_EVIDENCE,packages=process.env.STCT_MAP_PACKAGES,nonUC=process.env.STCT_NON_UC_PACKAGE;
assert.ok(out&&packages&&nonUC,'Set evidence and native study package paths');fs.mkdirSync(out,{recursive:true});
const live=process.env.STCT_MAP_LIVE==='1',log={status:'RUNNING',method:'Home, native package file input, real map buttons/keyboard; read-only diagnostics. Saved native results, not a new solver acceptance.',liveBasemap:live,checks:[],pageErrors:[],consoleErrors:[]};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(f,(e,b)=>e?res.writeHead(404).end():res.writeHead(200,{'content-type':({'.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'}).end(b));});
async function mapTool(container,selector){const button=container.locator(selector),group=button.locator('xpath=ancestor::details[contains(@class,"p7-tool-group")][1]');if(await group.count()&&!await group.evaluate(e=>e.open))await group.locator(':scope > summary').click();await button.click();}
(async()=>{let browser,page;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce'});
 await context.route('**/*',route=>{const u=new URL(route.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)||live&&u.hostname==='tiles.openfreemap.org'?route.continue():route.abort();});
 page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>log.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')log.consoleErrors.push(m.text());});
 const base=`http://127.0.0.1:${server.address().port}/index.html?forceHeuristic=1`;
 async function home(suffix=''){await page.goto(base+suffix+'#/');if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.locator('.platform-home').waitFor();await page.locator('.platform-home-action[data-platform-route="/design/supply-chain-study"]').click();}
 const host=()=>page.locator('.p7-map-workspace:visible'),diag=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());
 const model=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.snapshot());
 const snapshot=()=>page.evaluate(()=>JSON.stringify(window.STCTPlatformV19.instance.designAdapter.supplySnapshot().snapshot));
 async function upload(file,noGL=false){await page.locator('[data-supply-action="step"][data-supply-id="0"]').click();const input=page.locator('[data-supply-file="study"]'),details=input.locator('xpath=ancestor::details[1]');if(!await details.evaluate(e=>e.open))await details.locator('summary').click();await input.setInputFiles(file);await page.locator('[data-supply-map-panel]').waitFor();await host().locator('[data-p7-period]').waitFor();if(!noGL)await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-clustered-groups'));}
 async function display(){const group=host().locator('[data-p7-toolgroup=layers]');if(!await group.evaluate(e=>e.open))await group.locator(':scope > summary').click();const details=host().locator('.p7-exploration-settings');if(!await details.evaluate(e=>e.open))await details.locator('summary').click();}
 async function full(){await host().locator('[data-p7-expand]').click();await page.locator('dialog.p7-map-fullscreen[open]').waitFor();}
 async function close(){await page.locator('[data-p7-fullscreen-close]').click();assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),0);}
 await home();await upload(path.join(packages,'uc-full.package.json'));
 const initial=await snapshot(),initialModel=await model(),firstPeriod=initialModel.relationContext.periods[0];
 await full();await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();
 await host().locator('[data-p7-cluster]').first().waitFor();
 const d=await diag();assert.ok(d.density.total>200);assert.equal(d.density.shown,d.density.total);assert.equal(d.density.limited,false);assert.equal(d.exploration.clusteredPointCount,d.density.total);
 assert.ok(d.exploration.renderedWidths.every(r=>r.width>=1.5&&r.width<=7));assert.ok(d.exploration.linePaint.flat(8).includes('displayWidth'));
 const zoom=d.viewStates.SUPPLY.zoom;await host().locator('[data-p7-cluster]').first().press('Enter');await page.waitForFunction(z=>window.STCTPlatformV19.mapRuntime.diagnostics().viewStates.SUPPLY.zoom>z,zoom);assert.equal(await snapshot(),initial);
 await host().locator('[data-p7-fit]').click();
 log.checks.push({name:'UC full-chain: all customer points reach actual native clustered source; real DOM cluster keyboard zoom; quantity widths applied to real layers; no result mutation',status:'PASS',points:d.density.total});
 await display();await host().locator('[data-p7-width]').selectOption('uniform');assert.ok((await diag()).exploration.renderedWidths.every(r=>r.width===null));await host().locator('[data-p7-width]').selectOption('quantity');await host().locator('[data-p7-clusters]').uncheck();assert.equal((await diag()).exploration.clusteredPointCount,0);await host().locator('[data-p7-clusters]').check();await host().locator('.p7-exploration-settings summary').click();
 await host().locator('[data-p7-period]').press('ArrowRight');assert.equal((await diag()).provenance.period,firstPeriod);assert.equal(await page.locator('[data-supply-compare="period"]').inputValue(),firstPeriod);assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),1);assert.deepEqual((await model()).flowScale,initialModel.flowScale);assert.ok((await model()).relations.every(r=>r.periods.every(p=>p===firstPeriod)));assert.equal((await diag()).provenance.selectedScenarioId,d.provenance.selectedScenarioId);
 await host().locator('[data-p7-period-step="1"]').click();assert.equal((await diag()).provenance.period,initialModel.relationContext.periods[1]);await host().locator('[data-p7-period-all]').click();assert.equal((await diag()).provenance.period,'ALL');assert.equal(await snapshot(),initial);
 await mapTool(host(),'[data-p7-compare]');await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().comparison.candidateLayers.includes('p7-supply-clustered-groups'));assert.equal((await diag()).mapInstances,2);await host().locator('[data-p7-period]').press('ArrowRight');assert.equal((await diag()).provenance.period,firstPeriod);assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),1);await host().locator('[data-p7-period-all]').click();await mapTool(host(),'[data-p7-compare]');
 log.checks.push({name:'Visible width/cluster toggles, keyboard and button period selection, adapter dropdown sync, same candidate and common scale; dual-map sources recreate after period update; fullscreen preserved',status:'PASS'});
 // Curtain and guided interpretation operate on the same immutable native snapshot.
 await mapTool(host(),'[data-p7-swipe]');await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().comparison.candidateLayers.includes('p7-supply-relations-candidate'));
 assert.equal((await diag()).comparison.layout,'swipe');
 const panes=await host().locator('.p7-map-pane').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return{x:b.x,y:b.y,w:b.width,h:b.height,clip:getComputedStyle(e).clipPath};}));assert.equal(panes[0].x,panes[1].x);assert.equal(panes[0].w,panes[1].w);assert.equal(panes[0].h,panes[1].h);assert.match(panes[1].clip,/50%/);
 await host().locator('[data-p7-swipe-position]').press('ArrowRight');assert.equal((await diag()).comparison.swipePosition,51);await host().locator('[data-p7-swipe-position]').press('Home');assert.equal((await diag()).comparison.swipePosition,5);await host().locator('[data-p7-swipe-position]').press('End');assert.equal((await diag()).comparison.swipePosition,95);
 for(let i=0;i<45;i++)await host().locator('[data-p7-swipe-position]').press('ArrowLeft');
 await mapTool(host(),'[data-p7-guide]');assert.equal(await host().locator('[data-p7-guide-leg]').count(),2);
 for(const kind of ['inbound','outbound']){await host().locator('nav [data-p7-guide-step="'+kind+'"]').click();assert.equal(await host().locator('[data-p7-guide-leg]').count(),1);const sum=initialModel.relations.filter(r=>r.kind===kind).reduce((a,r)=>a+r.afterMetrics.quantity,0);const exact=Number(await host().locator('[data-p7-guide-leg] tbody tr').first().locator('td').nth(1).getAttribute('title'));assert.ok(Math.abs(exact-sum)<1e-7);const sources=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics().exploration.renderedWidths);const ids=new Set(initialModel.relations.filter(r=>r.kind===kind).map(r=>r.relationId));assert.ok(sources.every(f=>ids.has(f.relationId)));}
 await host().locator('nav [data-p7-guide-step="CHANGED"]').click();assert.ok((await diag()).exploration.renderedWidths.every(f=>initialModel.relations.some(r=>r.relationId===f.relationId&&r.change!=='UNCHANGED')));await page.keyboard.press('Escape');assert.equal(await host().locator('.p7-map-guide').isVisible(),false);assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),1);
 await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'curtain-desktop.png')});
 await page.setViewportSize({width:390,height:844});const mobilePanes=await host().locator('.p7-map-pane').evaluateAll(es=>es.map(e=>({w:e.clientWidth,h:e.clientHeight,x:e.getBoundingClientRect().x})));assert.deepEqual(mobilePanes[0],mobilePanes[1]);await mapTool(host(),'[data-p7-guide]');await host().locator('.p7-map-guide').scrollIntoViewIfNeeded();assert.ok(await page.locator('.p7-fullscreen-body').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:path.join(out,'walkthrough-mobile.png')});await page.keyboard.press('Escape');await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'curtain-mobile.png')});await page.setViewportSize({width:1440,height:1080});
 await mapTool(host(),'[data-p7-bookmarks]');await host().locator('[data-p7-bookmark-name]').fill('Curtain 50');await host().locator('[data-p7-bookmark-save]').click();await host().locator('[data-p7-swipe-position]').press('End');await host().locator('[data-p7-bookmark-restore]').last().click();assert.equal((await diag()).comparison.layout,'swipe');assert.equal((await diag()).comparison.swipePosition,50);await mapTool(host(),'[data-p7-bookmarks]');
 await mapTool(host(),'[data-p7-compare]');assert.equal((await diag()).comparison.layout,'split');assert.equal((await diag()).comparison.split,true);await mapTool(host(),'[data-p7-compare]');assert.equal((await diag()).mapInstances,1);assert.equal(await snapshot(),initial);
 log.checks.push({name:'Curtain equal-sized live canvases desktop/390px; keyboard divider and view restore; scenario walkthrough exact ledger and change-only geometry; Escape keeps fullscreen; immutable result',status:'PASS'});
 await mapTool(host(),'[data-p7-analysis]');await host().locator('[data-p7-multi]').click();assert.equal((await diag()).exploration.clusteredPointCount,0);await host().locator('[data-p7-multi]').click();await mapTool(host(),'[data-p7-analysis]');
 await mapTool(host(),'[data-p7-bookmarks]');await host().locator('[data-p7-bookmark-name]').fill('Map exploration test');await host().locator('[data-p7-bookmark-save]').click();const restore=host().locator('[data-p7-bookmark-restore]').last();await display();await host().locator('[data-p7-width]').selectOption('uniform');await host().locator('[data-p7-clusters]').uncheck();await restore.click();assert.equal((await diag()).exploration.widthMode,'quantity');assert.equal((await diag()).exploration.clusterEnabled,true);await mapTool(host(),'[data-p7-bookmarks]');if(await host().locator('.p7-exploration-settings summary').isVisible()&&await host().locator('.p7-exploration-settings').evaluate(e=>e.open))await host().locator('.p7-exploration-settings summary').click();
 await host().locator('.p7-map-exploration').scrollIntoViewIfNeeded();await host().locator('[data-p7-cluster]').first().waitFor();await page.screenshot({path:path.join(out,'desktop-fullscreen.png')});await close();
 for(const locale of ['en','ja','zh']){await page.locator('.platform-locale-control select').selectOption(locale);await mapTool(host(),'[data-p7-guide]');assert.match(await host().locator('.p7-map-guide').innerText(),{en:/Network overview/,ja:/ネットワーク概要/,zh:/全网概览/}[locale]);await host().locator('[data-p7-guide-close]').click();assert.match(await host().locator('.p7-period-timeline').innerText(),{en:/Explore periods/,ja:/期間別に確認/,zh:/按期间查看/}[locale]);await host().locator('[data-p7-period]').press('ArrowRight');await host().locator('[data-p7-period-all]').click();}
 await page.setViewportSize({width:390,height:844});await full();await host().locator('.p7-map-exploration').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await page.locator('.p7-fullscreen-body').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:path.join(out,'mobile-fullscreen.png')});await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();await host().locator('[data-p7-cluster]').first().waitFor();await page.screenshot({path:path.join(out,'mobile-map.png')});await host().locator('[data-p7-period-step="1"]').click();assert.equal((await diag()).provenance.period,firstPeriod);await close();await page.setViewportSize({width:1440,height:1080});
 await page.emulateMedia({media:'print'});await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().mode==='SCHEMATIC');assert.ok(await host().locator('.p7-map-schematic polyline').count()>0);assert.equal(await host().locator('[data-p7-period-step="1"]').isVisible(),false);await page.emulateMedia({media:'screen'});
 assert.equal(await snapshot(),initial);log.checks.push({name:'Multi-selection expands points; saved view restores display preferences; zh/en/ja; 390px fullscreen no overflow; print keeps weighted relation schematic; snapshot invariant',status:'PASS'});
 for(const [file,scope] of [[path.join(packages,'uc-outbound.package.json'),'OUTBOUND_ONLY'],[path.join(packages,'uc-upstream.package.json'),'UPSTREAM_ONLY'],[nonUC,'NON_UC']]){await upload(file);const before=await snapshot(),m=await model();await host().locator('[data-p7-period]').press('ArrowRight');const filtered=await model();assert.equal(filtered.relationContext.period,m.relationContext.periods[0]);assert.ok(filtered.relations.every(r=>r.periods.every(p=>p===m.relationContext.periods[0])));assert.equal(await snapshot(),before);if(scope!=='NON_UC')assert.equal((await diag()).provenance.analysisScope,scope);await host().locator('[data-p7-period-all]').click();log.checks.push({name:scope+' native package readback and map timeline by business controls',status:'PASS'});}
 // Same saved study reopened through a fresh browser origin; no app-state injection.
 const noGLContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await noGLContext.route('**/*',route=>{const u=new URL(route.request().url());return u.hostname==='127.0.0.1'||['blob:','data:'].includes(u.protocol)?route.continue():route.abort();});page=await noGLContext.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>log.pageErrors.push(e.message));await home('&noWebGL=1');await upload(nonUC,true);assert.equal((await diag()).mode,'SCHEMATIC');await full();await display();assert.equal(await host().locator('[data-p7-clusters]').isDisabled(),true);await host().locator('[data-p7-width]').selectOption('uniform');const uniform=await host().locator('.p7-map-schematic polyline').evaluateAll(es=>es.map(e=>e.getAttribute('stroke-width')));await host().locator('[data-p7-width]').selectOption('quantity');const weighted=await host().locator('.p7-map-schematic polyline').evaluateAll(es=>es.map(e=>e.getAttribute('stroke-width')));assert.notDeepEqual(uniform,weighted);await host().locator('.p7-exploration-settings summary').click();await host().locator('[data-p7-period]').press('ArrowRight');assert.equal((await diag()).provenance.period,(await model()).relationContext.periods[0]);await mapTool(host(),'[data-p7-swipe]');assert.equal(await host().locator('.p7-map-pane:visible').count(),2);await host().locator('[data-p7-swipe-position]').press('ArrowRight');assert.equal((await diag()).comparison.swipePosition,51);await mapTool(host(),'[data-p7-guide]');assert.equal(await host().locator('.p7-map-guide').isVisible(),true);await page.emulateMedia({media:'print'});assert.equal(await host().locator('.is-candidate').evaluate(e=>getComputedStyle(e).clipPath),'none');await page.pdf({path:path.join(out,'no-webgl-print.pdf'),format:'A4'});await page.emulateMedia({media:'screen'});await host().locator('[data-p7-guide-close]').click();await page.screenshot({path:path.join(out,'no-webgl.png')});await page.keyboard.press('Escape');assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),0);log.checks.push({name:'No-WebGL: business-controls native import, weighted/uniform SVG, keyboard timeline, disabled clustering explanation and Escape fullscreen',status:'PASS'});
 assert.deepEqual(log.pageErrors,[]);log.status='PASS';
 }catch(e){log.status='FAIL';log.error=e.stack;if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(log,null,2));console.log(JSON.stringify(log));}
})();
