'use strict';
// Real business controls; faults are injected only at the isolated HTTP request layer.
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),output=process.env.STCT_ROAD_EVIDENCE;
if(!output||!process.env.STCT_UC_WORKBOOK)throw Error('STCT_ROAD_EVIDENCE and STCT_UC_WORKBOOK required');
fs.mkdirSync(output,{recursive:true});
const log={kind:'BROWSER_BUSINESS_CONTROLS_WITH_ISOLATED_HTTP_FAULTS',status:'RUNNING',stages:[],pageErrors:[],requests:0};let mode='negative',held=[];
const read=page=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
const wait=async(page,fn)=>{await page.waitForFunction(()=>!document.querySelector('[data-supply-action="matrix-generate"]')?.disabled,{timeout:30000});return read(page);};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':decodeURIComponent(req.url.split('?')[0])));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(f,(e,b)=>e?res.writeHead(404).end():res.writeHead(200,{'content-type':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'application/octet-stream'}).end(b));});
async function routeTo(page,id){await page.locator(`button[data-platform-route="${id}"]:visible`).first().click();}
async function importStudy(page,name){if(!await page.locator('.platform-home').isVisible())await routeTo(page,'/');await page.locator('.platform-home').waitFor();await routeTo(page,'/platform/data');await page.locator('[data-v8-kind]').selectOption('SUPPLY_CHAIN_PERIOD');await page.locator('[data-p5-upload]').setInputFiles(process.env.STCT_UC_WORKBOOK);await page.locator('[data-supply-action="profile-confirm"]').waitFor();await page.locator('[data-supply-field="studyName"]').fill(name);await page.locator('[data-supply-action="profile-confirm"]').click();await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();await page.locator('[data-supply-field="geoConfirmed"]').waitFor();}
async function roadDetails(page){const control=page.locator('[data-supply-action="matrix-generate"]:visible').first();return control;}
(async()=>{let browser;try{const port=await new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server.address().port)));browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--disable-webgl']});const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.hostname==='127.0.0.1'&&url.port==='5001'){log.requests++;if(mode==='held'){held.push(route);return;}const match=decodeURIComponent(url.pathname).split('/').pop().split(';').map(row=>row.split(',').map(Number));return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({code:'Ok',routes:[{distance:12000,duration:-1}],waypoints:match.map(location=>({location,distance:0}))})});}return ['localhost','127.0.0.1'].includes(url.hostname)||['blob:','data:'].includes(url.protocol)?route.continue():route.abort();});
const page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>log.pageErrors.push(e.message));await page.goto(`http://127.0.0.1:${port}/index.html?noWebGL=1#/`);if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.locator('.platform-home').waitFor();await importStudy(page,'Road fault study A');
let button=await roadDetails(page);await button.click();await wait(page);assert.match(await page.locator('.sc-message').first().innerText(),/坐标|coordinate|座標/);assert.equal(log.requests,0);assert.equal((await read(page)).study.distanceRows.length,0);log.stages.push('UNCONFIRMED_COORDINATES_BLOCK_BEFORE_HTTP');
await page.locator('[data-supply-field="geoConfirmed"]').check();button=await roadDetails(page);await button.click();await wait(page);assert.ok(log.requests>0);assert.equal((await read(page)).study.distanceRows.length,0);log.stages.push('NEGATIVE_DURATION_REJECTED_WITH_NO_ZERO_ROWS');
mode='held';button=await roadDetails(page);const count=log.requests;await button.click();await page.waitForTimeout(250);assert.ok(log.requests>count);const hash=(await read(page)).study.inputHash;await page.locator('[data-supply-action="matrix-cancel"]:visible').first().click();await wait(page);assert.equal((await read(page)).study.inputHash,hash);log.stages.push('CANCEL_CONTROL_PRESERVES_INPUTS');
for(const route of held.splice(0))await route.abort().catch(()=>{});button=await roadDetails(page);await button.click();await page.waitForTimeout(250);assert.ok(held.length>0);await importStudy(page,'Road fault study B');const b=await read(page),bhash=b.study.inputHash;
for(const route of held.splice(0))await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({code:'NoRoute'})}).catch(()=>{});await page.waitForTimeout(350);const after=await read(page);assert.equal(after.study.name,'Road fault study B');assert.equal(after.study.inputHash,bhash);assert.equal(after.study.distanceRows.length,0);log.stages.push('OPEN_B_REJECTS_LATE_A_RESULT');assert.deepEqual(log.pageErrors,[]);await page.screenshot({path:path.join(output,'road-fault-final.png'),fullPage:true});log.status='PASS';
}catch(e){log.status='FAIL';log.error=e.stack;process.exitCode=1;}finally{for(const route of held)await route.abort().catch(()=>{});if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));fs.writeFileSync(path.join(output,'browser-summary.json'),JSON.stringify(log,null,2));console.log(JSON.stringify(log));}})();
