'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright'),Map=require('../platform-supply-map-v8.js');
const base=process.env.STCT_UI_URL,out=process.env.STCT_UI_EVIDENCE,binary=process.env.STCT_BROWSER,uc=process.env.STCT_UC_WORKBOOK;assert.ok(base&&out&&binary&&uc);fs.mkdirSync(out,{recursive:true});
const report={status:'RUNNING',tier:'BROWSER_BUSINESS_CONTROLS_NATIVE_CP_SAT',checks:[],pageErrors:[],solveSamples:[]};
const sha=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
let browser,page;const f=n=>page.locator('[data-supply-field="'+n+'"]'),a=n=>page.locator('[data-supply-action="'+n+'"]'),state=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function tool(sel){const button=page.locator(sel),group=button.locator('xpath=ancestor::details[contains(@class,"p7-tool-group")][1]');if(await group.count()&&!await group.evaluate(e=>e.open))await group.locator(':scope > summary').click();await button.click();}
async function openLinked(){if(await page.locator('.p7-map-analysis').evaluate(e=>e.hidden))await tool('[data-p7-analysis]');if(!await page.locator('.p7-linked-analysis').evaluate(e=>e.open))await page.locator('.p7-linked-analysis > summary').click();await page.locator('[data-p7-linked-count]').waitFor();}
async function capture(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});report.checks.push(name);fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));}
async function download(button,name){for(const details of (await button.locator('xpath=ancestor::details').all()).reverse())if(!await details.evaluate(e=>e.open))await details.locator(':scope > summary').click();const [d]=await Promise.all([page.waitForEvent('download',{timeout:60000}),button.click()]);const file=path.join(out,name);await d.saveAs(file);return file;}
async function solve(scope){
 if(await a('step').filter({hasText:'确认分析条件'}).isVisible())await a('step').filter({hasText:'确认分析条件'}).click();
 await f('analysisScope').selectOption(scope);if(scope!=='OUTBOUND_ONLY'){await f('homogeneousDemandConfirmed').check();await f('allowAllSupplierSiteEdgesConfirmed').check();await f('supplierTotalMode').selectOption(scope==='UPSTREAM_ONLY'?'FIXED_OBSERVED':'ADJUSTABLE');}
 await f('geoConfirmed').check();await f('runBudgetSeconds').selectOption('120');
 if(scope!=='UPSTREAM_ONLY'){await f('networkMode').selectOption('MULTI');for(const radio of await page.locator('.sc-sites input[value="adjust"]').all())await radio.check();await f('minSites').fill('2');await f('maxSites').fill('4');}
 assert.match(await page.locator('[data-supply-preflight]').innerText(),/条件已就绪/);const start=Date.now();await a('analyze').click();await page.locator('[data-supply-map-panel]').waitFor({timeout:180000});const s=await state();assert.ok(s.snapshot&&!s.staleResult);assert.ok(s.solverRuns.length);report.solveSamples.push({scope,wallMs:Date.now()-start,solverRuns:s.solverRuns,studyHash:s.study.inputHash,snapshotHash:s.snapshot.snapshotHash});
 fs.writeFileSync(path.join(out,scope+'-native-result.json'),JSON.stringify(s.snapshot,null,2));
 await download(a('package-export'),scope+'.package.json');await download(a('export-html'),scope+'.html');return s;
}
(async()=>{try{
 browser=await chromium.launch({executablePath:binary,headless:true,args:['--disable-webgl']});const ctx=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'});await ctx.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?r.continue():r.abort();});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.pageErrors.push(e.message));
 await page.goto(base);await page.locator('#loginForm .login-btn').click();await page.getByRole('button',{name:/测算供应链方案/}).click();await page.locator('[data-supply-file="workbook"]').setInputFiles(uc);await page.locator('[data-supply-mapping-overview]').waitFor();await a('profile-confirm').click();await page.locator('[data-supply-preflight]').waitFor();
 for(const scope of ['OUTBOUND_ONLY','UPSTREAM_ONLY','FULL_CHAIN']){
  const s=await solve(scope),immutable=sha(s.snapshot),selected=await page.locator('[data-supply-compare="scenarioId"]').inputValue(),model=Map.projectComparison(s.study,s.snapshot,{scenarioId:selected}),expected=Map.analyticalProjection(model);
  await openLinked();assert.equal(Number(await page.locator('[data-p7-linked-count]').getAttribute('data-count')),expected.relations.length);
  for(const g of expected.groups){const metric=page.locator('[data-p7-linked-leg="'+g.kind+'"] [data-metric="quantity"]');assert.equal(Number(await metric.getAttribute('data-after')),g.after.quantity);}
  const known=expected.distributions.distance.findIndex(b=>!b.unknown&&b.count);await page.locator('[data-p7-brush="distance"][data-p7-bin="'+known+'"]').press('Enter');const bin=expected.distributions.distance[known],filtered=Map.analyticalProjection(model,{ranges:{distance:{min:bin.min,max:bin.max,unknown:false}}});
  assert.equal(Number(await page.locator('[data-p7-linked-count]').getAttribute('data-count')),filtered.relations.length);assert.equal(await page.locator('[data-p7-linked-remove="distance"]').count(),1);const dom=await page.locator('[data-p7-linked-row]').evaluateAll(es=>es.map(e=>e.dataset.p7LinkedRow));assert.ok(dom.every(id=>filtered.relationIds.includes(id)));
  if(dom.length){await page.locator('[data-p7-linked-relation]').first().press('Enter');assert.equal((await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics())).viewStates.SUPPLY.selectedRelationId,dom[0]);}
  assert.equal(sha((await state()).snapshot),immutable);await page.locator('[data-p7-linked-clear]').click();
  if(!await page.locator('.p7-view-export').evaluate(e=>e.open))await page.locator('.p7-view-export > summary').click();await page.locator('[data-p7-view-note]').fill('业务备注：仅作地理筛选，不代表费用节省。');
  const viewFile=await download(page.locator('[data-p7-view-export]'),scope+'-analysis-view.json'),viewData=JSON.parse(fs.readFileSync(viewFile,'utf8'));assert.equal(viewData.view.state.note,'业务备注：仅作地理筛选，不代表费用节省。');assert.equal(viewData.view.identity.snapshotHash,s.snapshot.snapshotHash);assert.equal(viewData.scope.total,expected.totalRelations);
  await page.locator('[data-p7-view-import]').setInputFiles(viewFile);await page.getByText('分析视图已回读。备注为用户内容。',{exact:true}).waitFor();
  const tampered=path.join(out,scope+'-tampered-view.json');fs.writeFileSync(tampered,JSON.stringify({...viewData,scope:{filtered:999,total:999}}));await page.locator('[data-p7-view-import]').setInputFiles(tampered);await page.getByText(/视图未回读，现有筛选保留/).waitFor();assert.equal(Number(await page.locator('[data-p7-linked-count]').getAttribute('data-count')),expected.relations.length);
  const ranked=s.snapshot.decision.rankedScenarioIds;if(ranked.length>1){const beforeFocus=s.snapshot.decision.focusScenarioId,other=ranked.find(id=>id!==selected);await page.locator('[data-supply-compare="referenceScenarioId"]').selectOption(other);await page.locator('[data-supply-map-panel][data-reference="CANDIDATE_COMPARISON"]').waitFor();assert.equal((await state()).snapshot.decision.focusScenarioId,beforeFocus);await page.locator('[data-supply-compare="referenceScenarioId"]').selectOption('');}
  if(!await page.locator('.p7-linked-analysis').evaluate(e=>e.open))await page.locator('.p7-linked-analysis > summary').click();
  if(!await page.locator('.p7-spatial-insights').evaluate(e=>e.open))await page.locator('.p7-spatial-insights > summary').click();await page.locator('[data-p7-coverage-metric]').selectOption('travelSeconds');assert.match(await page.locator('.p7-spatial-insights').innerText(),/SLA|未知/);
  const region=path.join(out,'synthetic-region.geojson');fs.writeFileSync(region,JSON.stringify({type:'Polygon',coordinates:[[[100,20],[130,20],[130,45],[100,45],[100,20]]]}));await page.locator('[data-p7-region-upload]').setInputFiles(region);await page.getByText('区域已载入，仅筛选端点。',{exact:true}).waitFor();await page.locator('[data-p7-region-clear]').click();
  await capture(scope+'-linked-filter-spatial-desktop');assert.equal(sha((await state()).snapshot),immutable);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await capture(scope+'-linked-390');await page.setViewportSize({width:1440,height:1000});
  await a('step').filter({hasText:'确认分析条件'}).click();
 }
 assert.deepEqual(report.pageErrors,[]);report.status='PASS';
 }catch(e){report.status='FAIL';report.error=e.stack;if(page){report.body=await page.locator('body').innerText().catch(()=>null);await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});}process.exitCode=1;
 }finally{if(browser)await browser.close();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}})();
