#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const Integrity = require("../integrity-hash-v151.js");
const RoadFixture = require("../road-network-fixture-v16.js");
const Providers = require("../routing-provider-registry-v16.js");
const Twin = require("../execution-twin-v16.js");
const Reducer = require("../execution-reducer-v17.js");
const Reconciliation = require("../driver-reconciliation-v17.js");
const Alerts = require("../operations-alerts-v16.js");
const Telemetry = require("../telemetry-v17.js");
const Matcher = require("../telemetry-matcher-v17.js");
const FleetTracks = require("../fleet-tracks-v17.js");
const PlanActual = require("../multi-vehicle-plan-actual-v17.js");
const ShiftReview = require("../shift-review-v17.js");
const Capsule = require("../operational-capsule-v17.js");
const ReplayValidator = require("../capsule-replay-validator-v17.js");

const assertions = [];
const isSha256 = (value) => /^sha256:[a-f0-9]{64}$/.test(String(value));
function check(requirementId, condition, observed, expected) {
  assert(condition, `${requirementId}: observed=${JSON.stringify(observed)} expected=${JSON.stringify(expected)}`);
  assertions.push({ assertionId: `${requirementId}-A1`, requirementId, status: "PASS", observed: structuredClone(observed), expected: structuredClone(expected), evidence: "tests/test_capsule_replay_equivalence_v17.js" });
}
function reseal(capsule, sectionName) { capsule.sections[sectionName].payloadHash = Integrity.hashValue(capsule.sections[sectionName].payload); capsule.capsuleHash = Capsule.computedCapsuleHash(capsule); return capsule; }
function tamper(capsule, sectionName, mutate) { const value = structuredClone(capsule); mutate(value.sections[sectionName].payload); reseal(value, sectionName); return { capsule: value, report: ReplayValidator.validate(value) }; }

async function fixture() {
  const graph = RoadFixture.createFixture(); const nodes = new Map(graph.nodes.map((node) => [node.nodeId, node])); const provider = Providers.fixtureProvider(); const points = ["DEPOT", "A", "B"].map((nodeId, index) => ({ pointId: index ? `O${index}` : "DEPOT", lon: nodes.get(nodeId).lon, lat: nodes.get(nodeId).lat })); const request = { schemaVersion: "stct-routing-request-v1.6", providerId: provider.id, profile: "LIGHT_TRUCK", points, vehicleProfile: { vehicleType: "LIGHT_TRUCK" }, snapToleranceMeters: 120, distanceUnit: "m", durationUnit: "seconds", allowLowConfidenceSnap: true }; const roadRoute = await provider.route(request); const matrix = await provider.matrix(request);
  const plan = { schemaVersion: "stct-plan-v1.7-capsule-test", planId: "CAPSULE-V17-PLAN", revision: 1, logicalStartMinute: 480, matrixHash: matrix.matrixHash, verification: { status: "PASS" }, routes: [{ routeId: "R1", vehicleId: "V1", orderIds: ["O1", "O2"], geometry: roadRoute.geometry, plannedDistanceMeters: roadRoute.totalDistance }] }; plan.planHash = Integrity.hashValue({ planId: plan.planId, routes: plan.routes, matrixHash: plan.matrixHash });
  const run = Twin.createRun({ scenarioId: "CAPSULE-V17", inputHash: Integrity.hashValue({ input: "CAPSULE-V17" }), planHash: plan.planHash, routeGeometryHash: roadRoute.routeHash, matrixHash: matrix.matrixHash, providerProvenance: roadRoute.providerProvenance, simulationSeed: "17", executionProfile: "ON_TIME", logicalStartMinute: 480, revision: 1 }); const store = Reducer.createStore({ run, plan });
  const event = (eventType, fields = {}) => { const state = store.snapshot(); const runEvent = eventType === "RUN_RELEASED"; return Reducer.createEvent(run, { eventId: fields.eventId || `CAP-${state.acceptedEvents.length + 1}-${eventType}`, sequence: state.acceptedEvents.length + 1, eventType, logicalTime: fields.logicalTime ?? state.latestLogicalTime + 1, routeId: runEvent ? "" : "R1", vehicleId: runEvent ? "" : "V1", orderId: fields.orderId || "", payload: { planRevision: 1, routeRevision: 1, ...(fields.payload || {}) } }); };
  for (const type of ["RUN_RELEASED", "ROUTE_ACCEPTED", "VEHICLE_DEPARTED"]) assert.equal(store.append(event(type)).status, "ACCEPTED"); const rejected = store.append(event("STOP_SKIPPED", { orderId: "O2", eventId: "FUTURE-SKIP" })); assert.equal(rejected.status, "REJECTED"); const executionState = store.snapshot();
  const driverSession = Reconciliation.createSession({ run, plan, store }); driverSession.setOffline(); const stopFields = { routeId: "R1", vehicleId: "V1", orderId: "O1" }; driverSession.queueEvent("STOP_ARRIVED", stopFields); driverSession.queueEvent("SERVICE_STARTED", stopFields); const driverSnapshot = driverSession.snapshot();
  const observation = Telemetry.createObservation({ observationId: "CAP-OBS-1", executionRunHash: run.executionRunHash, vehicleId: "V1", logicalTime: 483, coordinate: [nodes.get("DEPOT").lon, nodes.get("DEPOT").lat], reportedRoadEdgeId: "E_DEPOT_A", reportedDistance: 999999, reportedSpeed: 999, source: "SYNTHETIC_TELEMETRY", accuracyMeters: 5 }); const derived = await Matcher.derive(observation, null, { provider, graph, routeGeometry: roadRoute.geometry, routeId: "R1" }); const telemetryBundles = [{ observation, derived }];
  const trackRows = [{ ...derived, routeId: "R1", routeRevision: 1, handoverId: "BASE" }]; const trackModel = FleetTracks.build(trackRows);
  const inbox = Alerts.createInbox(); const opened = inbox.add(Alerts.createAlert({ alertId: "CAP-ALERT", ruleId: "ETA_RISK", executionRunHash: run.executionRunHash, routeId: "R1", vehicleId: "V1", orderId: "O1", openedLogicalTime: 484, evidence: [{ metric: "etaRiskMinutes", actualValue: 20, thresholdOperator: ">=", thresholdValue: 10, source: "DERIVED_TELEMETRY_ONLY" }], relatedEventIds: [executionState.acceptedEvents.at(-1).eventId] })); inbox.acknowledge(opened.alert.alertId, { owner: "OPS", logicalTime: 485 }); inbox.startHandling(opened.alert.alertId, { owner: "OPS", logicalTime: 486 }); inbox.resolve(opened.alert.alertId, { owner: "OPS", logicalTime: 487, evidence: [{ source: "DERIVED_TELEMETRY", derivedTelemetryHash: derived.derivedTelemetryHash }] }); const alertSnapshot = inbox.snapshot();
  const recoveredPlanHash = Integrity.hashValue({ plan: "RECOVERED" }); const revision = { schemaVersion: "stct-execution-plan-revision-v1.7", revision: 2, parentRevision: 1, parentPlanHash: plan.planHash, newPlanHash: recoveredPlanHash, cutoffLogicalMinute: 500, effectiveFromLogicalMinute: 500 }; revision.revisionHash = Integrity.hashValue(revision); const handover = { schemaVersion: "stct-recovery-handover-v1.7", revision: 2, parentPlanHash: plan.planHash, newPlanHash: recoveredPlanHash, cutoffLogicalMinute: 500, label: "Synthetic recovery handover" }; handover.handoverHash = Integrity.hashValue(handover); const postRevisionEvents = [{ eventId: "POST-REV-1", planRevision: 2, logicalTime: 501, eventHash: Integrity.hashValue({ eventId: "POST-REV-1", planRevision: 2, logicalTime: 501 }) }]; const lineage = { planHashes: [plan.planHash, recoveredPlanHash], revisions: [revision], handovers: [handover], postRevisionEvents };
  const pvaInput = { plan, executionState, tracks: trackModel, alerts: alertSnapshot.alerts, now: 520 }; const pvaReport = PlanActual.build(pvaInput); const shiftInput = { executionState, alerts: alertSnapshot, telemetry: [derived], planActual: pvaReport, reconciliation: driverSnapshot.summary, incidents: [], recoveries: [revision], tracks: trackModel }; const shift = ShiftReview.build(shiftInput);
  const source = { execution: { run, plan, acceptedEvents: executionState.acceptedEvents, rejectedEvents: executionState.rejectedEvents, rejectedEventsPolicy: "SEALED_AUDIT_ONLY_NOT_REPLAYED", executionState, noWebGL: false }, alerts: alertSnapshot, lineage, driver: { queue: driverSnapshot.queue, projection: driverSnapshot.projection, summary: driverSnapshot.summary, noWebGL: false }, telemetry: { bundles: telemetryBundles }, tracks: { rows: trackRows, model: trackModel }, road: { routingProvider: roadRoute.providerProvenance, roadGraph: graph, roadMatrix: matrix, roadRoutes: [roadRoute] }, planActual: { input: pvaInput, report: pvaReport }, shiftReview: { input: shiftInput, review: shift } }; const capsule = Capsule.createCapsule(source, { locale: "en", createdAt: "2026-08-31T12:00:00.000Z" }); return { graph, provider, roadRoute, matrix, plan, run, store, executionState, driverSnapshot, observation, derived, trackRows, trackModel, alertSnapshot, lineage, pvaInput, pvaReport, shiftInput, shift, source, capsule };
}

async function main() {
  const f = await fixture(); const report = ReplayValidator.validate(f.capsule);
  check("T334", report.status === "PASS" && report.checks.find((row) => row.id === "EXECUTION_EVENTS_REBUILT")?.status === "PASS", { status: report.status, check: report.checks.find((row) => row.id === "EXECUTION_EVENTS_REBUILT") }, "events rebuilt execution state");
  const rebuilt = Reducer.createStore({ run: f.run, plan: f.plan }); f.executionState.acceptedEvents.forEach((event) => rebuilt.append(event)); const rebuiltState = rebuilt.snapshot();
  check("T335", rebuiltState.run.status === f.executionState.run.status, rebuiltState.run.status, f.executionState.run.status);
  check("T336", JSON.stringify(rebuiltState.routeStates) === JSON.stringify(f.executionState.routeStates), rebuiltState.routeStates, f.executionState.routeStates);
  check("T337", JSON.stringify(rebuiltState.stopStates) === JSON.stringify(f.executionState.stopStates), rebuiltState.stopStates, f.executionState.stopStates);
  check("T338", JSON.stringify(rebuiltState.vehicleStates) === JSON.stringify(f.executionState.vehicleStates), rebuiltState.vehicleStates, f.executionState.vehicleStates);
  check("T339", rebuiltState.latestLogicalTime === f.executionState.latestLogicalTime, rebuiltState.latestLogicalTime, f.executionState.latestLogicalTime);
  check("T340", rebuiltState.staleStatus === f.executionState.staleStatus, rebuiltState.staleStatus, f.executionState.staleStatus);
  check("T341", rebuiltState.executionStateHash === f.executionState.executionStateHash && report.rebuiltExecutionStateHash === report.storedExecutionStateHash, { rebuilt: rebuiltState.executionStateHash, report: report.rebuiltExecutionStateHash, stored: report.storedExecutionStateHash }, f.executionState.executionStateHash);
  const deepStateTamper = (field, mutate) => tamper(f.capsule, "execution", (execution) => { mutate(execution.executionState[field]); execution.executionState.executionStateHash = Integrity.hashValue(Reducer.stateIdentity(execution.executionState)); });
  const stopTamper = deepStateTamper("stopStates", (states) => { states.O1.state = "COMPLETED"; }); check("T342", stopTamper.report.status === "FAIL" && stopTamper.report.errors.some((error) => error.code === "EXECUTION_STOP_STATES_EQUIVALENT_MISMATCH"), stopTamper.report.errors, "deep stop-state tamper rejected after reseal");
  const routeTamper = deepStateTamper("routeStates", (states) => { states.R1.state = "COMPLETED"; }); check("T343", routeTamper.report.status === "FAIL" && routeTamper.report.errors.some((error) => error.code === "EXECUTION_ROUTE_STATES_EQUIVALENT_MISMATCH"), routeTamper.report.errors, "deep route-state tamper rejected after reseal");
  const vehicleTamper = deepStateTamper("vehicleStates", (states) => { states.V1.state = "COMPLETED"; }); check("T344", vehicleTamper.report.status === "FAIL" && vehicleTamper.report.errors.some((error) => error.code === "EXECUTION_VEHICLE_STATES_EQUIVALENT_MISMATCH"), vehicleTamper.report.errors, "deep vehicle-state tamper rejected after reseal");
  const runTamper = deepStateTamper("run", (run) => { run.status = "COMPLETED"; }); check("T345", runTamper.report.status === "FAIL" && runTamper.report.errors.some((error) => error.code === "EXECUTION_RUN_STATUS_EQUIVALENT_MISMATCH"), runTamper.report.errors, "deep run-status tamper rejected after reseal");
  check("T346", JSON.stringify(rebuiltState.acceptedEvents) === JSON.stringify(f.executionState.acceptedEvents) && report.checks.find((row) => row.id === "ACCEPTED_EVENTS_EQUIVALENT")?.status === "PASS", { accepted: rebuiltState.acceptedEvents.length, hashes: rebuiltState.acceptedEvents.map((event) => event.eventHash) }, "accepted event list equivalent");
  check("T347", f.capsule.sections.execution.payload.rejectedEventsPolicy === "SEALED_AUDIT_ONLY_NOT_REPLAYED" && f.capsule.sections.execution.payload.rejectedEvents.length === 1 && report.rejectedEventsPolicy === "SEALED_AUDIT_ONLY_NOT_REPLAYED", { policy: report.rejectedEventsPolicy, rejected: f.capsule.sections.execution.payload.rejectedEvents }, "rejected events sealed as audit-only");
  const alertCheck = report.checks.find((row) => row.id === "ALERT_WORKFLOW_REPLAY"); check("T348", alertCheck.status === "PASS" && alertCheck.detail.states["CAP-ALERT"] === "RESOLVED", alertCheck.detail, { "CAP-ALERT": "RESOLVED" });
  check("T349", f.alertSnapshot.alerts[0].state === "RESOLVED" && alertCheck.detail.states[f.alertSnapshot.alerts[0].alertId] === f.alertSnapshot.alerts[0].state, { stored: f.alertSnapshot.alerts[0].state, replayed: alertCheck.detail.states[f.alertSnapshot.alerts[0].alertId] }, "alert state replay equivalent");
  check("T350", f.alertSnapshot.auditEvents.every((event) => event.eventHash === Integrity.hashValue((({ eventHash, ...rest }) => rest)(event))), f.alertSnapshot.auditEvents.map((event) => event.eventHash), "alert audit hashes valid");
  const lineageReport = ReplayValidator.validateLineage(f.lineage, f.executionState.acceptedEvents);
  check("T351", f.lineage.revisions.every((revision) => f.lineage.planHashes.includes(revision.parentPlanHash)) && lineageReport.status === "PASS", f.lineage.revisions, "parent plan exists");
  check("T352", f.lineage.revisions.every((revision) => f.lineage.planHashes.includes(revision.newPlanHash)) && lineageReport.status === "PASS", f.lineage.planHashes, "new plan exists");
  check("T353", f.lineage.handovers[0].cutoffLogicalMinute === f.lineage.revisions[0].cutoffLogicalMinute, { revision: f.lineage.revisions[0].cutoffLogicalMinute, handover: f.lineage.handovers[0].cutoffLogicalMinute }, 500);
  check("T354", f.lineage.postRevisionEvents[0].planRevision === 2 && f.lineage.postRevisionEvents[0].logicalTime >= f.lineage.revisions[0].cutoffLogicalMinute && lineageReport.status === "PASS", f.lineage.postRevisionEvents[0], "post-revision event matches revision/cutoff");
  check("T355", f.lineage.handovers[0].revision === f.lineage.revisions[0].revision && lineageReport.status === "PASS", f.lineage.handovers[0], "handover linked to revision");
  const driverReport = ReplayValidator.validateDriver(f.capsule.sections.driver.payload, f.executionState, f.plan);
  check("T356", driverReport.status === "PASS" && driverReport.rebuilt.projectionHash === f.driverSnapshot.projection.projectionHash, { rebuilt: driverReport.rebuilt.projectionHash, stored: f.driverSnapshot.projection.projectionHash }, "Driver Projection rebuilt");
  check("T357", f.driverSnapshot.queue[1].dependsOn.includes(f.driverSnapshot.queue[0].clientEventId) && driverReport.status === "PASS", { first: f.driverSnapshot.queue[0].clientEventId, secondDependsOn: f.driverSnapshot.queue[1].dependsOn }, "pending dependency rebuilt");
  check("T358", driverReport.autoSyncQueue === false && f.store.snapshot().acceptedEvents.length === 3, { autoSyncQueue: driverReport.autoSyncQueue, authoritativeAccepted: f.store.snapshot().acceptedEvents.length }, { autoSyncQueue: false, authoritativeAccepted: 3 });
  const recomputedPva = PlanActual.build(f.pvaInput); check("T359", recomputedPva.reportHash === f.pvaReport.reportHash, recomputedPva.reportHash, f.pvaReport.reportHash);
  check("T360", JSON.stringify(recomputedPva) === JSON.stringify(f.pvaReport) && report.checks.find((row) => row.id === "PLAN_ACTUAL_RECOMPUTE")?.status === "PASS", { recomputed: recomputedPva.reportHash, stored: f.pvaReport.reportHash }, "stored report equals recompute");
  const recomputedShift = ShiftReview.build(f.shiftInput); check("T361", recomputedShift.reviewHash === f.shift.reviewHash, recomputedShift.reviewHash, f.shift.reviewHash);
  check("T362", JSON.stringify(recomputedShift) === JSON.stringify(f.shift) && report.checks.find((row) => row.id === "SHIFT_REVIEW_RECOMPUTE")?.status === "PASS", { recomputed: recomputedShift.reviewHash, stored: f.shift.reviewHash }, "stored Shift Review equals recompute");
  check("T363", report.checks.find((row) => row.id === "TELEMETRY_DEEP_VALIDATION")?.status === "PASS", report.checks.find((row) => row.id === "TELEMETRY_DEEP_VALIDATION"), "DerivedTelemetry deep validation");
  const rebuiltTracks = FleetTracks.build(f.trackRows); check("T364", JSON.stringify(rebuiltTracks) === JSON.stringify(f.trackModel) && report.checks.find((row) => row.id === "TRACK_MODEL_REBUILT")?.status === "PASS", rebuiltTracks.map((track) => track.trackHash), f.trackModel.map((track) => track.trackHash));
  const roadReport = ReplayValidator.validateRoad(f.capsule.sections.road.payload); check("T365", roadReport.provenance.status === "PASS" && roadReport.status === "PASS", roadReport.provenance, "Provider provenance valid");
  check("T366", roadReport.graph.status === "PASS" && roadReport.status === "PASS" && f.matrix.matrixHash && f.roadRoute.routeHash, { graph: roadReport.graph.status, matrixHash: f.matrix.matrixHash, routeHash: f.roadRoute.routeHash }, "Road Graph/Matrix/Route valid");
  check("T367", Capsule.auditCapsule(f.capsule).status === "PASS" && Capsule.computedCapsuleHash(f.capsule) === f.capsule.capsuleHash && report.checks.at(-1).id === "CAPSULE_ROOT_HASH_FINAL", { hash: f.capsule.capsuleHash, finalCheck: report.checks.at(-1) }, "Capsule root hash validated last");
  const legacy = { schemaVersion: Capsule.LEGACY_V16_SCHEMA, evidence: { retained: true } }; const legacyBefore = JSON.stringify(legacy); const legacyImport = Capsule.importCapsule(legacy);
  check("T368", legacyImport.legacy === true && legacyImport.replayVerification === "REPLAY_UNVERIFIED", legacyImport, "v1.6 Replay Unverified");
  check("T369", legacyImport.migrationReport.sourceSchema === Capsule.LEGACY_V16_SCHEMA && legacyImport.migrationReport.targetSchema === Capsule.SCHEMA_VERSION && legacyImport.migrationReport.automaticMigrationApplied === false, legacyImport.migrationReport, "legacy migration report generated");
  check("T370", JSON.stringify(legacy) === legacyBefore && legacyImport.migrationReport.sourceMutated === false, { before: legacyBefore, after: JSON.stringify(legacy), sourceMutated: legacyImport.migrationReport.sourceMutated }, "source not overwritten");
  const imported = Capsule.importCapsule(Capsule.serializeCapsule(f.capsule)); check("T371", imported.mode === "READ_ONLY_REPLAY" && imported.status === "READ_ONLY_REPLAY" && imported.writesCurrentState === false, imported, "read-only default");
  let sandboxGuard = ""; try { Capsule.importCapsule(f.capsule, { mode: "SANDBOX_SIMULATION" }); } catch (error) { sandboxGuard = error.code; } const sandbox = Capsule.importCapsule(f.capsule, { mode: "SANDBOX_SIMULATION", allowSandboxSimulation: true }); check("T372", sandboxGuard === "V17_SANDBOX_EXPLICIT_CONSENT_REQUIRED" && sandbox.mode === "SANDBOX_SIMULATION", { guard: sandboxGuard, mode: sandbox.mode }, "sandbox explicit consent");
  check("T373", imported.autoPlay === false, imported.autoPlay, false);
  check("T374", imported.autoApply === false, imported.autoApply, false);
  check("T375", imported.autoSyncQueue === false, imported.autoSyncQueue, false);
  check("T376", imported.externalRequests === false, imported.externalRequests, false);
  const pollutionAudit = Capsule.auditCapsule('{"schemaVersion":"x","__proto__":{"polluted":true}}'); check("T377", pollutionAudit.status === "FAIL" && pollutionAudit.errors[0].code === "V17_CAPSULE_PROTOTYPE_POLLUTION" && ({}).polluted === undefined, pollutionAudit.errors[0], "prototype pollution rejected");
  const sizeAudit = Capsule.auditCapsule(JSON.stringify(f.capsule), { limits: { bytes: 100 } }); let deep = {}; let cursor = deep; for (let index = 0; index < 55; index += 1) { cursor.next = {}; cursor = cursor.next; } const depthIssues = Capsule.scanSecurity(deep, { ...Capsule.DEFAULT_LIMITS, depth: 10 }); check("T378", sizeAudit.errors[0].code === "V17_CAPSULE_SIZE_LIMIT" && depthIssues.some((issue) => issue.code === "V17_CAPSULE_DEPTH_LIMIT"), { size: sizeAudit.errors[0], depth: depthIssues.find((issue) => issue.code === "V17_CAPSULE_DEPTH_LIMIT") }, "size and depth limits");
  check("T379", Capsule.scanSecurity({ path: "/Users/example/private.json" }).some((issue) => issue.code === "V17_CAPSULE_ABSOLUTE_PATH") && Capsule.scanSecurity(f.capsule).every((issue) => issue.code !== "V17_CAPSULE_ABSOLUTE_PATH"), Capsule.scanSecurity({ path: "/Users/example/private.json" }), "absolute path scan");
  check("T380", Capsule.scanSecurity({ apiKey: "example" }).some((issue) => issue.code === "V17_CAPSULE_SECRET") && Capsule.scanSecurity(f.capsule).every((issue) => issue.code !== "V17_CAPSULE_SECRET"), Capsule.scanSecurity({ apiKey: "example" }), "secret key scan");
  check("T381", Capsule.scanSecurity({ source: "raw-customer.xlsx" }).some((issue) => issue.code === "V17_CAPSULE_RAW_EXCEL") && !JSON.stringify(f.capsule).match(/\.xlsx?\b/i), Capsule.scanSecurity({ source: "raw-customer.xlsx" }), "raw Excel excluded");
  const extracted = Capsule.randomExtraction(f.capsule, 7); check("T382", extracted.verified === true && Capsule.SECTION_NAMES.includes(extracted.sectionName) && extracted.payloadHash === Integrity.hashValue(extracted.payload), extracted, "random extraction verified");
  const locales = Capsule.LOCALES.map((locale) => { const value = Capsule.createCapsule(f.source, { locale, createdAt: "2026-08-31T12:00:00.000Z" }); const replay = Capsule.importCapsule(value); return { locale, replayLocale: replay.locale, title: replay.copy.title }; }); check("T383", locales.every((row) => row.locale === row.replayLocale && row.title), locales, "zh/en/ja replay");
  const seal = Capsule.capsuleSeal(f.capsule); check("T384", seal.label === "Capsule Seal" && seal.digitalSignature === false && /not a digital signature/i.test(seal.note), seal, "integrity seal not signature");
  check("T385", report.status === "PASS" && report.checks.length >= 18 && isSha256(report.reportHash) && report.readOnly === true, { status: report.status, checks: report.checks.length, hash: report.reportHash, readOnly: report.readOnly }, "complete Replay Equivalence report");
  check("T386", ["V17_CAPSULE_HASH_MISMATCH", "V17_CAPSULE_PROTOTYPE_POLLUTION", "V17_REPLAY_EQUIVALENCE_FAILED"].every((code) => Capsule.ERROR_CODES.includes(code)) && stopTamper.report.errors[0].code, { capsuleCodes: Capsule.ERROR_CODES, replayCode: stopTamper.report.errors[0].code }, "stable error codes");
  const derivedTamper = tamper(f.capsule, "telemetry", (telemetry) => { telemetry.bundles[0].derived.derivedSpeedKph += 1; }); const eventTamper = tamper(f.capsule, "execution", (execution) => { execution.acceptedEvents[1].routeId = "OTHER"; execution.acceptedEvents[1].eventHash = Integrity.hashValue(Reducer.eventIdentity(execution.acceptedEvents[1])); }); check("T387", derivedTamper.report.status === "FAIL" && eventTamper.report.status === "FAIL" && stopTamper.report.status === "FAIL" && routeTamper.report.status === "FAIL", { derived: derivedTamper.report.errors, event: eventTamper.report.errors.slice(0, 2), stop: stopTamper.report.errors.slice(0, 2), route: routeTamper.report.errors.slice(0, 2) }, "deep tamper adversarial pass");
  check("T388", stopTamper.report.errors.some((error) => error.code === "EXECUTION_STOP_STATES_EQUIVALENT_MISMATCH") && stopTamper.capsule.sections.execution.payload.executionState.executionStateHash !== f.executionState.executionStateHash, { errors: stopTamper.report.errors, tamperedHash: stopTamper.capsule.sections.execution.payload.executionState.executionStateHash, originalHash: f.executionState.executionStateHash }, "event/state contradiction rejected despite reseal");
  const randomDir = fs.mkdtempSync(path.join(os.tmpdir(), "stct-v17-replay-")); const capsulePath = path.join(randomDir, "capsule.json"); fs.writeFileSync(capsulePath, Capsule.serializeCapsule(f.capsule), "utf8"); const randomReport = ReplayValidator.validate(fs.readFileSync(capsulePath, "utf8")); fs.rmSync(randomDir, { recursive: true, force: true }); check("T389", randomReport.status === "PASS" && randomReport.reportHash === report.reportHash, { status: randomReport.status, reportHash: randomReport.reportHash, originalReportHash: report.reportHash }, "delivery Capsule replayed from random directory");

  process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, assertions }, null, 2)}\n`);
}

main().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exit(1); });
