'use strict';
const path=require('node:path'),assert=require('node:assert/strict');
const R=path.resolve(__dirname,'..');
const D=require(R+'/supply-chain-design-v19.js'),Report=require(R+'/supply-chain-report-v19.js'),C=require(R+'/supply-chain-controller-v19.js'),Explanation=require(R+'/supply-chain-explanation-v19.js');
const P='P1',edge=(a,b,km)=>({fromNodeId:a,toNodeId:b,distanceKm:km,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_REVIEW'});
const raw={studyId:'REVIEW',classification:'SYNTHETIC_TEST',nodes:[{nodeId:'S',role:'SUPPLIER'},{nodeId:'W1',role:'DC',capacityByPeriod:{[P]:5}},{nodeId:'W2',role:'DC',capacityByPeriod:{[P]:100}},{nodeId:'C',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'W1',period:P,quantity:10,unit:'m3'}],observedInbound:[{flowId:'I',fromNodeId:'S',toNodeId:'W1',period:P,quantity:10,unit:'m3'}],distanceRows:[edge('S','W1',1),edge('S','W2',2),edge('W1','C',1),edge('W2','C',2)],rates:[{kind:'INBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',amount:0,status:'CONFIRMED_ZERO'},{kind:'HANDLING',basis:'PER_UNIT',amount:0,status:'CONFIRMED_ZERO'}],costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'}};
const study=D.createStudy(raw),baseline=D.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),scenario={scenarioId:'MORE_EXPENSIVE_FEASIBLE',type:'NETWORK_CANDIDATE',objective:'COST',objectiveScope:'TWO_END',distanceBasis:'VERIFIED_ROAD',selectedSiteIds:['W2'],facilityCounts:[1],sourcePlan:[{sourceNodeId:'S',siteNodeId:'W2',share:1}]},candidate=D.evaluatePortfolio(study,scenario,[{demandId:'D',siteId:'W2'}]),snapshot=Report.createSnapshot(study,baseline,[candidate],[],scenario);
const observations=[{name:'invalid_baseline_keep_reference',baselineStatus:baseline.status,baselineIssues:baseline.issues,candidateStatus:candidate.status,baselineCost:baseline.metrics.steadyStateCost,candidateCost:candidate.metrics.steadyStateCost,decision:snapshot.decision}];
const brief=Explanation.businessBrief(snapshot),html=Report.toHtml(study,snapshot);observations.push({name:'fixed_source_two_end_scope_mismatch',configuredScope:scenario.objectiveScope,decisionScope:snapshot.decision.scope,briefScope:brief.scope,briefText:Explanation.describeBrief(brief,'zh'),htmlSaysBothEnds:html.includes('入库与配送均已纳入本次目标。')});
const unmatched=D.createStudy({...raw,nodes:raw.nodes.map(row=>row.role==='DC'?{...row,capacityByPeriod:{[P]:100}}:row),observedInbound:raw.observedInbound.map(row=>({...row,quantity:20}))}),unmatchedBase=D.evaluatePortfolio(unmatched,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),sameNetwork={...scenario,scenarioId:'SAME-NETWORK-DIFFERENT-INBOUND',selectedSiteIds:['W1'],sourcePlan:[{sourceNodeId:'S',siteNodeId:'W1',share:1}]},unmatchedCandidate=D.evaluatePortfolio(unmatched,sameNetwork,[{demandId:'D',siteId:'W1'}]),comparison=D.compare(unmatched,unmatchedBase,unmatchedCandidate),unmatchedSnapshot=Report.createSnapshot(unmatched,unmatchedBase,[unmatchedCandidate],[],sameNetwork);
observations.push({name:'unmatched_inbound_cost_scope',baselineStatus:unmatchedBase.status,candidateStatus:unmatchedCandidate.status,baselineInbound:unmatchedBase.metrics.inbound.totalVolume,candidateInbound:unmatchedCandidate.metrics.inbound.totalVolume,baselineCost:unmatchedBase.metrics.steadyStateCost,candidateCost:unmatchedCandidate.metrics.steadyStateCost,completeCost:comparison.completeOperatingCost,improvement:comparison.steadyStateImprovementRate,inboundSameTotal:comparison.inboundCommon.sameTotalVolume,decision:unmatchedSnapshot.decision});
assert.notEqual(snapshot.decision.kind,'KEEP_REFERENCE');assert.equal(snapshot.decision.referenceFeasible,false);assert.equal(brief.scope,'TWO_END');assert.ok(!Explanation.describeBrief(brief,'zh').some(text=>text.includes('入库未纳入本次优化')));
assert.equal(comparison.inboundScopeComparable,false);assert.equal(comparison.completeOperatingCost,false);assert.equal(comparison.steadyStateImprovementRate,null);assert.ok(!comparison.comparableCostParts.includes('inboundTransport'));assert.notEqual(unmatchedSnapshot.decision.kind,'FINANCIAL_RECOMMENDATION');
const fixedCandidate=(current,config=sameNetwork)=>D.evaluatePortfolio(current,config,[{demandId:'D',siteId:config.selectedSiteIds[0]}]);
function checkCostScope(name,input,config,expected){const current=D.createStudy(input),before=D.evaluatePortfolio(current,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),after=fixedCandidate(current,config),comparison=D.compare(current,before,after);assert.equal(comparison.inboundScopeComparable,expected,name);assert.equal(comparison.completeOperatingCost,expected,name);if(!expected){assert.equal(comparison.steadyStateImprovementRate,null,name);assert.ok(!comparison.comparableCostParts.includes('inboundTransport'),name);}observations.push({name,baselineInbound:before.metrics.inbound.totalVolume,candidateInbound:after.metrics.inbound.totalVolume,inboundScopeComparable:comparison.inboundScopeComparable,completeCost:comparison.completeOperatingCost,comparableCostParts:comparison.comparableCostParts});}
const feasibleNodes=raw.nodes.map(row=>row.role==='DC'?{...row,capacityByPeriod:{P1:100,P2:100}}:row),sameVolumePeriods={...raw,nodes:feasibleNodes,periodDemand:['P1','P2'].map(period=>({...raw.periodDemand[0],period})),observedInbound:[{...raw.observedInbound[0],quantity:15},{...raw.observedInbound[0],flowId:'I2',period:'P2',quantity:5}]};
checkCostScope('same_total_different_period',sameVolumePeriods,sameNetwork,false);
checkCostScope('same_total_different_supplier',{...raw,nodes:[...feasibleNodes,{nodeId:'T',role:'SUPPLIER'}],distanceRows:[...raw.distanceRows,edge('T','W1',1),edge('T','W2',1)]},{...sameNetwork,sourcePlan:[{sourceNodeId:'T',siteNodeId:'W1',share:1}]},false);
checkCostScope('same_source_period_different_receiving_warehouse',{...raw,nodes:feasibleNodes},scenario,true);
for(const modifier of [{minimumCharge:100},{tiers:[{upTo:10,amount:3}]}]){const nonLinear=D.createStudy({...raw,nodes:feasibleNodes,rates:raw.rates.map(rate=>rate.kind==='INBOUND_TRANSPORT'?{...rate,...modifier}:rate)}),evaluated=fixedCandidate(nonLinear);assert.equal(evaluated.metrics.inbound.cost,null);assert.throws(()=>D.solverRequest(nonLinear,{...sameNetwork,type:'FIXED_SITE_REASSIGNMENT'}),{code:'SUPPLY_COST_OBJECTIVE_INCOMPLETE'});}
const missingReference={schemaVersion:'stct-supply-chain-v5-snapshot-v1',analysisScope:'FULL_CHAIN',scenario:{objective:'VOLUME_KM'},baseline,planningReference:null,rows:[]},missingDecision=Explanation.selection(missingReference);assert.equal(missingDecision.referenceStatus,'MISSING');assert.ok(!Explanation.decisionText(missingReference,'zh').includes('已知硬约束'));assert.match(Explanation.decisionText(missingReference,'zh'),/已验证/);
// Controlled Worker for snapshot lifecycle only; this does not run a solver or browser.
const workers=[];global.Worker=class{constructor(){workers.push(this)}postMessage(value){this.input=value}terminate(){this.terminated=true}complete(){const {requestId,input}=this.input;this.onmessage({data:{type:'RESULT',requestId,result:Report.createSnapshot(...input.args)}})}};
(async()=>{const c=C.createController();c.loadStudy(raw);c.calculateBaseline('VERIFIED_ROAD');c.configureScenario(scenario);c.evaluateConfigured([{demandId:'D',siteId:'W2'}]);const first=c.compareAsync().catch(e=>e.code),second=c.compareAsync().catch(e=>e.code);await first;observations.push({name:'older_compare_cancel_overwrites_new_compare',statusAfterOlderAbort:c.viewState().status,activeNewWorker:!workers[1].terminated,firstWorkerTerminated:workers[0].terminated});assert.equal(c.viewState().status,'VERIFYING');workers[1].complete();await second;observations.push({name:'new_compare_completion',status:c.viewState().status});delete global.Worker;let signal;const healthController=C.createController({fetch:(_url,init)=>{signal=init.signal;return new Promise(()=>{});}}),started=performance.now(),health=await healthController.health(),elapsedMs=performance.now()-started;assert.equal(health.available,false);assert.equal(health.error,'SUPPLY_JOB_CONNECTION_TIMEOUT');assert.ok(signal.aborted);assert.ok(elapsedMs<6500);observations.push({name:'controlled_health_timeout',elapsedMs,health,signalAborted:signal.aborted});console.log(JSON.stringify({suite:'SUPPLY_CHAIN_V7_REVIEW_GUARDS',status:'PASS',method:'SYNTHETIC_MODULE_AND_CONTROLLED_WORKER_NO_NATIVE_SOLVER_NO_BROWSER',observations},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
