'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const net=require('node:net');
const path=require('node:path');
const {spawn}=require('node:child_process');
const {chromium}=require('playwright');
const XLSX=require('../vendor/xlsx/xlsx.full.min.js');
const root=path.resolve(__dirname,'..');
const evidence=process.env.STCT_V71_PERIOD_DIR||'/tmp/stct-v71-period-browser';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function ensureVisible(locator){if(await locator.isVisible())return;const summary=locator.locator('xpath=ancestor::details[1]/summary');if(await summary.count())await summary.click();await locator.waitFor({state:'visible'});}
const freePort=()=>new Promise((resolve,reject)=>{const socket=net.createServer();socket.once('error',reject);socket.listen(0,'127.0.0.1',()=>{const port=socket.address().port;socket.close(()=>resolve(port));});});
function workbook(count){const book=XLSX.utils.book_new(),periods=Array.from({length:count},(_,index)=>`2026-${String(index+1).padStart(2,'0')}`);XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['name','code','role','coordinate'],['Supplier Alpha','S1','SUPPLIER','120,30'],['Supplier Beta','S2','SUPPLIER','121,30'],['Depot West','W1','DC','120.1,30'],['Depot East','W2','DC','121.1,30']]),'Locations');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['flowId','fromNodeId','toNodeId',...periods],['I1','S1','W2',...periods.map(()=>10)],['I2','S2','W1',...periods.map(()=>10)]]),'Inbound');return Buffer.from(XLSX.write(book,{bookType:'xlsx',type:'buffer'}));}
const server=http.createServer((request,response)=>{const target=path.resolve(root,'.'+new URL(request.url,'http://127.0.0.1').pathname);if(!target.startsWith(root+path.sep))return response.writeHead(403).end();const type=target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':target.endsWith('.json')?'application/json':'text/html';fs.readFile(target,(error,bytes)=>error?response.writeHead(404).end():response.writeHead(200,{'content-type':type}).end(bytes));});
(async()=>{fs.mkdirSync(evidence,{recursive:true});const port=await freePort(),optimizer=spawn('python3',['optimizer/ortools_service.py'],{cwd:root,env:{...process.env,OPT_PORT:String(port)},stdio:'ignore'});let browser;try{
  for(let i=0;i<100;i++){if(optimizer.exitCode!==null)throw new Error('optimizer exited');try{const response=await fetch(`http://127.0.0.1:${port}/health`);if(response.ok&&(await response.json()).available)break;}catch(_){}if(i===99)throw new Error('optimizer unavailable');await sleep(100);}
  const webPort=await new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server.address().port)));
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox','--disable-webgl']});const errors=[],results=[];
  for(const count of [2,7]){const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${webPort}/index.html?optPort=${port}&noWebGL=1#/design/supply-chain-study`);await page.locator('#loginForm .login-btn').click();await page.waitForSelector('.supply-chain-study.sc-business');
    await page.locator('[data-supply-action="step"][data-supply-id="0"]').click();await page.locator('[data-supply-file="workbook"]').setInputFiles({name:`synthetic-${count}-periods.xlsx`,mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:workbook(count)});await page.locator('[data-supply-action="profile-confirm"]').click();await page.locator('[data-supply-action="analyze"]').waitFor();await page.getByText(`http://127.0.0.1:${port}/facility-optimize-v19`,{exact:false}).first().waitFor();await page.screenshot({path:path.join(evidence,`synthetic-${count}-service.png`)});assert.equal(await page.locator('[data-supply-field="analysisScope"]').inputValue(),'UPSTREAM_ONLY');await page.locator('[data-supply-field="geoConfirmed"]').check();await page.locator('[data-supply-field="homogeneousDemandConfirmed"]').check();await page.locator('[data-supply-field="allowAllSupplierSiteEdgesConfirmed"]').check();await page.locator('[data-supply-field="supplierTotalMode"]').selectOption('FIXED_OBSERVED');await page.locator('[data-supply-action="analyze"]').click();await page.waitForFunction(expected=>{const value=window.STCTPlatformV19.instance.designAdapter.supplySnapshot();return value.snapshot?.analysisScope==='UPSTREAM_ONLY'&&value.study.periods.length===expected;},count,{timeout:90000});await page.locator('[data-supply-action="export-html"]').waitFor({state:'visible'});const button=page.locator('[data-supply-action="package-export"]');await ensureVisible(button);const pending=page.waitForEvent('download');await button.click();const download=await pending,target=path.join(evidence,`synthetic-${count}-periods.package.json`);await download.saveAs(target);const snap=JSON.parse(fs.readFileSync(target)).snapshot;const focus=snap.rows.find(row=>row.scenarioId===snap.decision.focusScenarioId);const changed=focus.relationRows.filter(row=>row.change!=='UNCHANGED'),unique=new Set(changed.map(row=>JSON.stringify([row.supplierId,row.siteId])));assert.equal(snap.backendIdentity?.endpoint,`http://127.0.0.1:${port}/facility-optimize-v19`);results.push({periods:count,uniqueChangedRelations:unique.size,changedPeriodRecords:changed.length,focus:snap.decision.focusScenarioId,backendInstanceId:snap.backendIdentity.instanceId,runSpecHash:snap.backendIdentity.runSpecHash});await context.close();
  }
  assert.ok(results[0].uniqueChangedRelations>0,results);assert.equal(results[0].uniqueChangedRelations,results[1].uniqueChangedRelations);assert.equal(results[1].changedPeriodRecords,results[0].changedPeriodRecords*7/2);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(evidence,'period-comparison.json'),JSON.stringify({status:'PASS',method:'BROWSER_BUSINESS_CONTROLS_NATIVE_ORTOOLS',results},null,2));console.log(JSON.stringify({status:'PASS',results}));
}finally{if(browser)await browser.close();if(server.listening)await new Promise(resolve=>server.close(resolve));if(optimizer.exitCode===null){const closed=new Promise(resolve=>optimizer.once('exit',resolve));optimizer.kill('SIGTERM');await Promise.race([closed,sleep(5000)]);}}})().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
