'use strict';
const assert=require('node:assert/strict');
const Contract=require('../network-contract-v18.js');
const Data=require('../design-data-adapter-v19.js');
const Facility=require('../facility-location-mvp1-v19.js');
const Portfolio=require('../facility-portfolio-adapter-v19.js');
const Envelope=require('../operational-validation-contract-v19.js');
const Result=require('../operational-validation-result-v19.js');
const Command=require('../command-operational-context-v19.js');
const StudyService=require('../platform-study-service-v19.js');
function memoryRepository(){const stores=new Map(),key=(store,id)=>`${store}:${id}`;return{record:(id,payload,refs=[])=>({id,payload:structuredClone(payload),refs:structuredClone(refs),contentHash:Contract.hashArtifact(payload)}),async read(store,id){return structuredClone(stores.get(key(store,id))||null);},async list(store){return[...stores.entries()].filter(([id])=>id.startsWith(`${store}:`)).map(([,row])=>structuredClone(row));},async commit({records={},pointer,catalogEntries=[],expectedRevision=0}){const current=stores.get(key('pointers',pointer.id));if((current?.revision||0)!==expectedRevision)throw Object.assign(new Error('REVISION_CONFLICT'),{code:'REVISION_CONFLICT'});for(const [store,rows] of Object.entries(records))for(const row of rows)stores.set(key(store,row.id),structuredClone(row));for(const row of catalogEntries)stores.set(key('pointers',row.id),structuredClone(row));const saved={...structuredClone(pointer),revision:expectedRevision+1,savedAt:'2026-09-06T00:00:00Z'};stores.set(key('pointers',saved.id),saved);return{status:'SAVED',pointer:structuredClone(saved)};},close(){}};}

(async()=>{
  const base=Data.createSyntheticStudy({orderCount:12,depotCount:5,vehicleCount:20}).scenario;
  const study=Facility.fromScenario(base,{facilityCounts:[1,2,3],timeLimitSeconds:10});
  const repository=memoryRepository(),controller=Facility.createController({repository,endpoint:process.env.FACILITY_URL||'http://127.0.0.1:8791/facility-optimize-v19'});controller.load(study);await controller.run();const state=controller.snapshot();
  assert.equal(state.verification.status,'PASS');assert.equal(state.resultSet.engine.id,'OR_TOOLS_CP_SAT');assert.equal(state.resultSet.results.filter(row=>row.rank===1&&row.status==='OPTIMAL').length,3);
  const command=Command.createContext({fixture:{vehicleCount:4,stopsPerVehicle:4,positionsPerVehicle:6}});await command.ready;await command.driver.acceptRoute();await command.driver.depart();await command.driver.goOffline();await command.driver.arrive();await command.driver.startService();await command.driver.complete();const pendingBefore=command.offlineQueue.summary().counts.LOCAL_PENDING;assert.equal(pendingBefore,3);const before=Contract.hashArtifact(command.snapshot());
  const selected=state.resultSet.results.filter(row=>row.rank===1&&['OPTIMAL','FEASIBLE'].includes(row.status)).slice(0,2),operational=[];
  for(const portfolio of selected){const adapter=Portfolio.toOperationalScenario({study:state.study,portfolio,verification:state.verification,baseScenario:base});const envelope=Envelope.createFacilityEnvelope({adapter,savedPointer:{id:'FACILITY:SAVED:1',type:'FACILITY_STUDY',verification:'PASS'}},{operationalDate:'2026-09-06',confirmDateAssumption:true});assert.equal(Envelope.validateEnvelope(envelope).status,'PASS');const result=Result.execute(envelope,{sessionId:`FACILITY-P${portfolio.facilityCount}`});assert.equal(Result.admit(envelope,result).admission.status,'PASS');assert.equal(result.comparabilityReport.label,'SCENARIO_CHANGED');assert.ok(result.comparabilityReport.inputDiff.includes('SCOPE_NOT_COMPARABLE'));operational.push({facilityCount:portfolio.facilityCount,service:result.metrics.serviceRate,cost:result.metrics.operationalCost});}
  assert.equal(Contract.hashArtifact(command.snapshot()),before);assert.equal(command.offlineQueue.summary().counts.LOCAL_PENDING,pendingBefore);
  const saved=await controller.save(0);await controller.reopen(saved.pointer.id);assert.equal(controller.snapshot().verification.status,'PASS');const service=StudyService.createService(repository),pack=await service.exportPackage([saved.pointer.id]);assert.equal(service.inspectPackage(pack).status,'READY');assert.equal(pack.records.facilityStudies.length,1);assert.equal(pack.records.facilityResults.length,1);
  const freshRepository=memoryRepository(),freshService=StudyService.createService(freshRepository),importedPackage=await freshService.importPackage(pack),freshCatalog=await freshService.list();assert.equal(importedPackage.status,'SAVED');assert.ok(freshCatalog.some(row=>row.id===saved.pointer.id));assert.ok(freshCatalog.some(row=>row.id===`BACKUP:${pack.packageHash}`));assert.equal((await freshRepository.list('facilityStudies')).length,1);assert.equal((await freshRepository.list('facilityMatrices')).length,1);assert.equal((await freshRepository.list('facilityResults')).length,1);assert.equal((await freshRepository.list('facilityVerifications')).length,1);freshRepository.close();
  const imported=structuredClone(state.study);imported.matrix={mode:'IMPORTED_IMPEDANCE_MATRIX',providerId:'PRIVATE_GRID',providerVersion:'1',rows:state.matrix.rows};const importedStudy=Facility.normalizeStudy(imported),importedMatrix=Facility.buildMatrix(importedStudy),fakePortfolio=selected[0],fakeVerification={status:'PASS'};assert.throws(()=>Portfolio.toOperationalScenario({study:importedStudy,portfolio:fakePortfolio,verification:fakeVerification,baseScenario:base}),{code:'FACILITY_OPERATIONAL_ROUTING_CONTEXT_UNSUPPORTED'});
  console.log(JSON.stringify({suite:'FACILITY_MVP1_P6_INTEGRATION',status:'PASS',solver:state.resultSet.engine,operational,commandState:'UNCHANGED',pendingAckQueue:{before:pendingBefore,after:command.offlineQueue.summary().counts.LOCAL_PENDING},savedAndReopened:true,packageStatus:'READY',freshProfileImport:'PASS'},null,2));repository.close();
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
