#!/usr/bin/env node
"use strict";

const assert = require("assert");
const path = require("path");
const { spawnSync } = require("child_process");
const Contract = require("../network-contract-v18.js");
const Assignment = require("../depot-assignment-v18.js");
const Trip = require("../trip-chain-v18.js");
const Custody = require("../pickup-custody-v18.js");
const DockWave = require("../dock-wave-v18.js");
const Network = require("../network-solver-v18.js");
const { makeNetwork } = require("./fixtures/network-v18-fixture.js");

const assertions = [];
function check(requirementId, condition, observed, expected, negative = false) {
  const row = { assertionId: `${requirementId}-A1`, requirementId, status: condition ? "PASS" : "FAIL", observed, expected, negative, evidence: "tests/test_network_solver_v18.js" };
  assertions.push(row); assert(condition, `${requirementId}: ${JSON.stringify({ observed, expected })}`);
}
const clone = (value) => structuredClone(value);
function sourceFixture(orderCount = 20, depotCount = 2, vehicleCount = 4) { const source = makeNetwork({ depotCount, vehicleCount, orderCount }); source.depots.forEach((depot) => { depot.capacity.volume = 100000; depot.capacity.weight = 100000; }); return source; }

const root = path.resolve(__dirname, "..");
const probeRun = spawnSync("python3", [path.join(root, "optimizer/network_solver_v18.py"), "--nodes", "12", "--compact"], { encoding: "utf8" });
const ortoolsEvidence = probeRun.status === 0 ? JSON.parse(probeRun.stdout) : { status: "FAIL", actualOrtoolsRun: false, stderr: probeRun.stderr };
const source = sourceFixture(); const plan = Network.solveNetwork(source, { actualOrtoolsEvidence: ortoolsEvidence, maxStopsPerTrip: 4 }); const verification = Network.verifyNetworkPlan(source, plan); const identities = Contract.identityBundle(source, plan.solveOptions);

check("T0407", plan.schemaVersion === "stct-network-plan-v1.8" && plan.solveOptions.objective && plan.engine.requested && plan.networkInputHash, { schemaVersion: plan.schemaVersion, solveOptions: plan.solveOptions }, "solver input schema");
check("T0408", plan.solveContextHash === identities.solveContextHash, [plan.solveContextHash, identities.solveContextHash], "solve context hash");
check("T0409", plan.routingContextHash === Contract.identityBundle(source).routingContextHash, plan.routingContextHash, "routing context hash");
check("T0410", new Set(plan.stages.map((row) => row.subproblemId)).size === plan.stages.length, plan.stages.map((row) => row.subproblemId), "unique subproblem IDs");
check("T0411", plan.stages.every((row) => row.parentSolveContextHash === plan.solveContextHash), plan.stages.map((row) => row.parentSolveContextHash), "parent hash");
check("T0412", plan.stages.every((row) => Array.isArray(row.entityIds) && new Set(row.entityIds).size === row.entityIds.length), plan.stages.map((row) => [row.stage, row.entityIds.length]), "entity sets");
check("T0413", plan.stages.every((row) => row.subproblemHash === Contract.hashArtifact(Network.subproblemProjection(row))), plan.stages.map((row) => row.subproblemHash), "subproblem hashes");
check("T0414", plan.stages.every((row) => row.resultHash === Contract.hashArtifact(row.result)), plan.stages.map((row) => row.resultHash), "result hashes");
check("T0415", Assignment.verifyAssignment(source, plan.assignment).status === "PASS", Assignment.verifyAssignment(source, plan.assignment), "assignment stage verifiable");
check("T0416", plan.allocation.conservedOrders && plan.allocation.allocations.every((row) => row.capacityStatus === "PASS"), plan.allocation, "wave capacity allocation verifiable");
check("T0417", Trip.verifyTripPlan(source, plan.trip).status === "PASS", Trip.verifyTripPlan(source, plan.trip), "trip stage verifiable");
check("T0418", plan.routes.status === "BEST_FOUND" && plan.routes.routes.every((row) => Contract.isSha256(row.roadRouteHash) && row.matrixHash === plan.routingContextHash), plan.routes, "route stage verifiable");
check("T0419", DockWave.verifyDockSchedule(source, plan.trip, plan.dock, { custodyPlan: plan.custody }).status === "PASS", DockWave.verifyDockSchedule(source, plan.trip, plan.dock, { custodyPlan: plan.custody }), "dock stage verifiable");
check("T0420", plan.repair.terminated && plan.repair.maxIterations === 3 && plan.repair.stopCondition, plan.repair, "repair stop condition");
const failed = Network.solveNetwork(source, { failStage: "TRIP_GENERATION" });
check("T0421", failed.status === "FAILED" && failed.failedStage === "TRIP_GENERATION" && !failed.trip, failed, "stage failure stops false success", true);
const firstStage = plan.stages[0]; const staleSource = clone(source); staleSource.policies.serviceFirst = false;
check("T0422", Network.verifySubproblem(source, firstStage, plan.solveOptions).status === "PASS" && Network.verifySubproblem(staleSource, firstStage, plan.solveOptions).status === "FAIL", Network.verifySubproblem(staleSource, firstStage, plan.solveOptions), "stale result rejected", true);
const depotMutation = clone(source); depotMutation.depots[0].capacity.dailyOrders += 1;
check("T0423", Network.verifySubproblem(depotMutation, firstStage, plan.solveOptions).issues.includes("STALE_NETWORK_INPUT"), Network.verifySubproblem(depotMutation, firstStage, plan.solveOptions).issues, "depot mutation stale", true);
const dockMutation = clone(source); dockMutation.docks[0].simultaneousCapacity += 1;
check("T0424", Network.verifySubproblem(dockMutation, firstStage, plan.solveOptions).issues.includes("STALE_NETWORK_INPUT"), Network.verifySubproblem(dockMutation, firstStage, plan.solveOptions).issues, "dock mutation stale", true);
const matrixMutation = clone(source); matrixMutation.routingContext.matrixVersion = "v2";
check("T0425", Network.verifySubproblem(matrixMutation, firstStage, plan.solveOptions).issues.includes("STALE_ROUTING_CONTEXT"), Network.verifySubproblem(matrixMutation, firstStage, plan.solveOptions).issues, "matrix mutation stale", true);
check("T0426", Network.verifySubproblem(staleSource, firstStage, plan.solveOptions).issues.includes("STALE_NETWORK_INPUT"), Network.verifySubproblem(staleSource, firstStage, plan.solveOptions).issues, "policy mutation stale", true);
const engineOptions = { ...plan.solveOptions, engineVersion: `${plan.solveOptions.engineVersion}-changed` };
check("T0427", Contract.identityBundle(source, plan.solveOptions).solveContextHash !== Contract.identityBundle(source, engineOptions).solveContextHash, [Contract.identityBundle(source, plan.solveOptions).solveContextHash, Contract.identityBundle(source, engineOptions).solveContextHash], "engine version changes solve context");
check("T0428", plan.trip.trips.every((row) => row.physicalVehicleId === row.vehicleId && row.virtualVehicle === false), plan.trip.trips.map((row) => [row.vehicleId, row.physicalVehicleId]), "virtual trips map to physical vehicle");
const overlap = clone(plan); overlap.trip.trips[1].startMinute = overlap.trip.trips[0].startMinute;
check("T0429", Network.verifyNetworkPlan(source, overlap).issues.some((row) => row.includes("VEHICLE_TRIP_OVERLAP")), Network.verifyNetworkPlan(source, overlap).issues, "physical overlap rejected", true);
const capacitySource = clone(source); capacitySource.vehicles.forEach((row) => { row.capacity.volume = 0.1; row.capacity.weight = 1; });
check("T0430", Network.verifyNetworkPlan(capacitySource, plan).issues.includes("VEHICLE_CAPACITY_EXCEEDED"), Network.verifyNetworkPlan(capacitySource, plan).issues, "vehicle capacity recomputed", true);
const dutySource = clone(source); dutySource.drivers.forEach((row) => { row.maxDutyMinutes = 1; });
check("T0431", Network.verifyNetworkPlan(dutySource, plan).issues.some((row) => row.includes("DRIVER_DUTY_LIMIT")), Network.verifyNetworkPlan(dutySource, plan).issues, "driver duty recomputed", true);
const breakSource = sourceFixture(6, 1, 1); breakSource.drivers[0].requiredBreaks[0].triggerDrivingMinutes = 10; breakSource.drivers[0].requiredBreaks[0].earliestStart = "06:00"; breakSource.drivers[0].requiredBreaks[0].latestStart = "20:00"; const breakPlan = Network.solveNetwork(breakSource, { maxStopsPerTrip: 2 }); const noBreak = clone(breakPlan); noBreak.trip.breakEvents = []; noBreak.trip.timelineEvents = noBreak.trip.timelineEvents.filter((row) => row.kind !== "BREAK"); noBreak.trip.executionEvents = noBreak.trip.executionEvents.filter((row) => row.kind !== "BREAK");
check("T0432", Network.verifyNetworkPlan(breakSource, noBreak).issues.some((row) => row.includes("REQUIRED_BREAK_MISSING")), Network.verifyNetworkPlan(breakSource, noBreak).issues, "break recomputed", true);
const pairSource = makeNetwork({ depotCount: 1, vehicleCount: 2, orderCount: 2, pickupDelivery: true }); const pairPlan = Network.solveNetwork(pairSource, { maxStopsPerTrip: 2 }); const precedenceTamper = clone(pairPlan); precedenceTamper.custody.shipments[0].events[1].startMinute = precedenceTamper.custody.shipments[0].events[0].startMinute - 1;
check("T0433", Network.verifyNetworkPlan(pairSource, precedenceTamper).issues.some((row) => row.includes("DELIVERY_BEFORE_PICKUP")), Network.verifyNetworkPlan(pairSource, precedenceTamper).issues, "pickup precedence recomputed", true);
const rideSource = clone(pairSource); rideSource.pickupDeliveryPairs[0].maxRideTime = 1;
check("T0434", Network.verifyNetworkPlan(rideSource, pairPlan).issues.some((row) => row.includes("MAX_RIDE_TIME_EXCEEDED")), Network.verifyNetworkPlan(rideSource, pairPlan).issues, "ride time recomputed", true);
const custodyGap = clone(pairPlan); custodyGap.custody.custodyEvents = [];
check("T0435", Network.verifyNetworkPlan(pairSource, custodyGap).issues.some((row) => row.includes("CUSTODY_CHAIN_GAP")), Network.verifyNetworkPlan(pairSource, custodyGap).issues, "custody recomputed", true);
const dockOverlap = clone(plan); const sameDockRows = dockOverlap.dock.reservations.filter((row) => row.dockId === dockOverlap.dock.reservations[0].dockId).slice(0, 2); sameDockRows[1].startMinute = sameDockRows[0].startMinute; sameDockRows[1].endMinute = sameDockRows[0].endMinute;
check("T0436", Network.verifyNetworkPlan(source, dockOverlap).issues.some((row) => row.includes("DOCK_CAPACITY_EXCEEDED")), Network.verifyNetworkPlan(source, dockOverlap).issues, "dock overlap recomputed", true);
const waveCutoff = clone(plan); waveCutoff.waves.waves[0].cutoffMinute = 9999; waveCutoff.waves.waves[0].risks = waveCutoff.waves.waves[0].risks.filter((row) => row.reasonCode !== "WAVE_CUTOFF_RISK");
check("T0437", Network.verifyNetworkPlan(source, waveCutoff).issues.some((row) => row.includes("WAVE_CUTOFF_RISK_IGNORED")), Network.verifyNetworkPlan(source, waveCutoff).issues, "wave cutoff recomputed", true);
const routeTamper = clone(plan); routeTamper.trip.routes[0].matrixHash = Contract.hashArtifact("wrong");
check("T0438", Network.verifyNetworkPlan(source, routeTamper).issues.includes("ROUTE_MATRIX_MISMATCH"), Network.verifyNetworkPlan(source, routeTamper).issues, "route/matrix recomputed", true);
const repositionSource = sourceFixture(4, 2, 2); repositionSource.vehicles[0].allowedStartDepotIds = ["D1", "D2"]; repositionSource.vehicles[0].maxTrips = 4; repositionSource.constraints.maxTripsPerVehicle = 4; const repositionPlan = Network.solveNetwork(repositionSource, { maxStopsPerTrip: 1, tripOptions: { vehicleIds: ["V1"] } });
check("T0439", repositionPlan.trip.repositionLegs.length > 0 && Network.verifyNetworkPlan(repositionSource, repositionPlan).status === "PASS", repositionPlan.trip.metrics, "empty reposition recomputed");
const costTamper = clone(plan); costTamper.metrics.totalCost += 1;
check("T0440", Network.verifyNetworkPlan(source, costTamper).issues.includes("NETWORK_METRIC_MISMATCH"), Network.verifyNetworkPlan(source, costTamper).issues, "cost recomputed", true);
const carbonTamper = clone(plan); carbonTamper.metrics.totalCarbonKg += 1;
check("T0441", Network.verifyNetworkPlan(source, carbonTamper).issues.includes("NETWORK_METRIC_MISMATCH"), Network.verifyNetworkPlan(source, carbonTamper).issues, "carbon recomputed", true);
const handlingTamper = clone(plan); handlingTamper.metrics.handlingCost += 1;
check("T0442", Network.verifyNetworkPlan(source, handlingTamper).issues.includes("NETWORK_METRIC_MISMATCH"), Network.verifyNetworkPlan(source, handlingTamper).issues, "handling cost recomputed", true);
const crossSource = makeNetwork({ depotCount: 2, vehicleCount: 2, orderCount: 2, pickupDelivery: true, crossDock: true }); crossSource.pickupDeliveryPairs[0].sameVehicleRequired = false; crossSource.pickupDeliveryPairs[0].sameTripRequired = false; const crossPlan = Network.solveNetwork(crossSource, { crossDock: true, maxStopsPerTrip: 2 });
check("T0443", crossPlan.metrics.transferCost > 0 && Network.verifyNetworkPlan(crossSource, crossPlan).status === "PASS", crossPlan.metrics, "transfer cost recomputed");
const penaltySource = sourceFixture(6, 1, 1); penaltySource.vehicles[0].maxTrips = 1; penaltySource.constraints.maxTripsPerVehicle = 1; penaltySource.policies.unassignedPenalty = 12345; const penaltyPlan = Network.solveNetwork(penaltySource, { maxStopsPerTrip: 1 });
check("T0444", penaltyPlan.trip.unassigned.length === 5 && penaltyPlan.metrics.unassignedPenalty === 5 * 12345, penaltyPlan.metrics, "unassigned penalty recomputed");
check("T0445", verification.status === "PASS" && verification.recomputedMetrics.assignedOrders + verification.recomputedMetrics.unassignedOrders + verification.recomputedMetrics.blockedOrders === source.orders.length, verification, "network conservation");
const duplicateOrder = clone(plan); duplicateOrder.trip.trips[1].orderIds.push(duplicateOrder.trip.trips[0].orderIds[0]); duplicateOrder.trip.routes[1].stops.push(clone(duplicateOrder.trip.routes[0].stops[0]));
check("T0446", Network.verifyNetworkPlan(source, duplicateOrder).issues.includes("ORDER_DUPLICATE"), Network.verifyNetworkPlan(source, duplicateOrder).issues, "duplicate order fails", true);
const missingOrder = clone(plan); missingOrder.trip.trips[0].orderIds.shift(); missingOrder.trip.routes[0].stops.shift();
check("T0447", Network.verifyNetworkPlan(source, missingOrder).issues.includes("ORDER_MISSING"), Network.verifyNetworkPlan(source, missingOrder).issues, "missing order fails", true);
const crossGap = clone(crossPlan); crossGap.custody.custodyEvents.splice(2, 1);
check("T0448", Network.verifyNetworkPlan(crossSource, crossGap).issues.some((row) => row.includes("CUSTODY_CHAIN_GAP")), Network.verifyNetworkPlan(crossSource, crossGap).issues, "shipment custody gap fails", true);
check("T0449", Network.verifyNetworkPlan(source, overlap).issues.some((row) => row.includes("VEHICLE_TRIP_OVERLAP")), Network.verifyNetworkPlan(source, overlap).issues, "vehicle double use fails", true);
check("T0450", Network.verifyNetworkPlan(source, overlap).issues.some((row) => row.includes("DRIVER_SHIFT_OVERLAP")), Network.verifyNetworkPlan(source, overlap).issues, "driver double use fails", true);
check("T0451", Network.verifyNetworkPlan(source, dockOverlap).issues.some((row) => row.includes("DOCK_CAPACITY_EXCEEDED")), Network.verifyNetworkPlan(source, dockOverlap).issues, "dock overbooking fails", true);
const waveMismatch = clone(plan); waveMismatch.waves.waves[0].tripIds.shift();
check("T0452", Network.verifyNetworkPlan(source, waveMismatch).issues.some((row) => row.includes("WAVE_TRIP_CONSERVATION")), Network.verifyNetworkPlan(source, waveMismatch).issues, "wave mismatch fails", true);
const hashTamper = clone(plan); hashTamper.statusWording += " tampered";
check("T0453", Network.verifyNetworkPlan(source, hashTamper).issues.includes("NETWORK_PLAN_HASH_MISMATCH"), Network.verifyNetworkPlan(source, hashTamper).issues, "plan hash tamper fails", true);
check("T0454", Network.verifyNetworkPlan(source, costTamper).issues.includes("NETWORK_METRIC_MISMATCH"), Network.verifyNetworkPlan(source, costTamper).issues, "reported metrics tamper fails", true);
check("T0455", verification.factsSource === "CANONICAL_INPUT_AND_ARTIFACT_EVENTS_ONLY", verification.factsSource, "canonical facts only");
const solverCoordinateTamper = clone(plan); solverCoordinateTamper.canonicalCoordinates.orders[0].coordinate = [0, 0];
check("T0456", Network.canonicalCoordinates(source).orders[0].coordinate[0] !== 0 && Network.verifyNetworkPlan(source, solverCoordinateTamper).status === "FAIL", Network.canonicalCoordinates(source).orders[0], "solver coordinates untrusted", true);
check("T0457", plan.objectiveDisclosure.objective === plan.objective && plan.objectiveDisclosure.serviceFirst && plan.objectiveDisclosure.optimality === "NOT_PROVEN", plan.objectiveDisclosure, "objective disclosed");
check("T0458", plan.status === "BEST_FOUND" && plan.statusWording.includes("global optimality is not claimed"), [plan.status, plan.statusWording], "BEST_FOUND wording");
check("T0459", Network.terminalStatus("TIMEOUT").status === "TIMEOUT" && Network.terminalStatus("TIMEOUT").success === false, Network.terminalStatus("TIMEOUT"), "timeout status");
check("T0460", Network.terminalStatus("CANCELLED").status === "CANCELLED" && Network.terminalStatus("CANCELLED").success === false, Network.terminalStatus("CANCELLED"), "cancel status");
const partial = Network.solveNetwork(source, { skipStageVerification: true });
check("T0461", partial.status === "PARTIAL" && Network.verifyNetworkPlan(source, partial).issues.includes("STAGE_VERIFICATION_INCOMPLETE"), { status: partial.status, issues: Network.verifyNetworkPlan(source, partial).issues }, "partial stage status");
const fallback = Network.solveNetwork(source);
check("T0462", fallback.engine.used === "LOCAL_HEURISTIC" && fallback.engine.fallbackCapability === "DEPOT_TRIP_DOCK_LOCAL_DETERMINISTIC", fallback.engine, "fallback capability");
check("T0463", fallback.engine.fullNetworkParity === false && fallback.engine.actualOrtoolsRun === false, fallback.engine, "fallback not full parity");
check("T0464", probeRun.status === 0 && ortoolsEvidence.status === "PASS" && ortoolsEvidence.actualOrtoolsRun === true && ortoolsEvidence.engine === "OR_TOOLS" && ortoolsEvidence.route.length === 13, ortoolsEvidence, "real OR-Tools run");
const compileRun = spawnSync("python3", ["-c", `compile(open(${JSON.stringify(path.join(root, "optimizer/network_solver_v18.py"))}, encoding='utf-8').read(), 'network_solver_v18.py', 'exec')`], { encoding: "utf8" });
check("T0465", compileRun.status === 0, { status: compileRun.status, stderr: compileRun.stderr }, "Python compile");
const syntaxRun = spawnSync(process.execPath, ["--check", path.join(root, "network-solver-v18.js")], { encoding: "utf8" });
check("T0466", syntaxRun.status === 0, { status: syntaxRun.status, stderr: syntaxRun.stderr }, "JS syntax");
const normalized = Contract.normalizeScenario(source); const pythonIdentityRun = spawnSync("python3", [path.join(root, "optimizer/network_contract_v18.py")], { input: JSON.stringify({ mode: "identity", value: normalized, solveOptions: plan.solveOptions }), encoding: "utf8" }); const pythonIdentity = JSON.parse(pythonIdentityRun.stdout);
check("T0467", pythonIdentityRun.status === 0 && pythonIdentity.networkInputHash === identities.networkInputHash && pythonIdentity.solveContextHash === identities.solveContextHash && pythonIdentity.routingContextHash === identities.routingContextHash, { js: identities, python: pythonIdentity }, "cross-language fixture");
const fiveHundredSource = sourceFixture(500, 1, 100); fiveHundredSource.depots[0].capacity.handlingMinutes = 100000; fiveHundredSource.docks.forEach((row) => { row.simultaneousCapacity = 100; }); const largeStarted = performance.now(); const fiveHundred = Network.solveNetwork(fiveHundredSource, { maxStopsPerTrip: 10, maxOrders: 500 }); const largeElapsed = performance.now() - largeStarted;
check("T0468", fiveHundred.status === "BEST_FOUND" && fiveHundred.metrics.assignedOrders === 500 && Network.verifyNetworkPlan(fiveHundredSource, fiveHundred).status === "PASS", { status: fiveHundred.status, metrics: fiveHundred.metrics, elapsedMs: largeElapsed }, "500-order fixture");
const thousandSource = sourceFixture(1000, 1, 100); const protectedPlan = Network.solveNetwork(thousandSource, { maxOrders: 500 });
check("T0469", protectedPlan.status === "PROTECTED_DECOMPOSITION_REQUIRED" && protectedPlan.partitionCount === 2 && Network.verifyNetworkPlan(thousandSource, protectedPlan).status === "PASS", protectedPlan, "1000-order protection/decomposition");
const singleSource = sourceFixture(3, 1, 1); const single = Network.solveNetwork(singleSource, { maxStopsPerTrip: 10 });
check("T0470", single.trip.trips.length === 1 && Network.verifyNetworkPlan(singleSource, single).status === "PASS", single.metrics, "single-depot single-trip regression");
check("T0471", plan.assignment.assignments.some((row) => row.assignedDepotId === "D1") && plan.assignment.assignments.some((row) => row.assignedDepotId === "D2") && plan.trip.tripChains.some((row) => row.tripIds.length > 1) && verification.status === "PASS", { depots: new Set(plan.assignment.assignments.map((row) => row.assignedDepotId)).size, chains: plan.trip.tripChains }, "multi-depot multi-trip");
check("T0472", Network.verifyNetworkPlan(source, partial).issues.includes("STAGE_VERIFICATION_INCOMPLETE"), Network.verifyNetworkPlan(source, partial).issues, "skip verifier mutation killed", true);
check("T0473", Network.verifyNetworkPlan(source, costTamper).issues.includes("NETWORK_METRIC_MISMATCH"), Network.verifyNetworkPlan(source, costTamper).issues, "trust reported cost mutation killed", true);
check("T0474", Object.keys(plan.performanceBreakdownMs).includes("TOTAL") && Network.STAGES.slice(0, 7).every((stage) => Number.isFinite(plan.performanceBreakdownMs[stage])), plan.performanceBreakdownMs, "solver performance breakdown");
check("T0475", plan.stages.every((row) => row.subproblemHash && row.resultHash && row.verification.status === "PASS"), plan.stages.map((row) => ({ id: row.subproblemId, subproblemHash: row.subproblemHash, resultHash: row.resultHash })), "subproblem evidence saved");
const labels = Network.candidateLabels([plan, fallback]);
check("T0476", labels.length === 2 && labels.every((row) => row.label.includes("service") && row.networkInputHash), labels, "candidate pool network labels");
const frontier = Network.observedFrontier([plan, fallback]);
check("T0477", frontier.length >= 1 && frontier.every((row) => row.wording.includes("Observed Network Frontier") && row.wording.includes("not a global Pareto proof")), frontier, "observed network frontier");
check("T0478", ["zh", "en", "ja"].every((locale) => ["BEST_FOUND", "TIMEOUT", "CANCELLED", "PARTIAL", "FAILED"].every((code) => Network.statusText(code, locale) !== code)), ["zh", "en", "ja"].map((locale) => Network.statusText("BEST_FOUND", locale)), "Chinese English Japanese solver status");
check("T0479", plan.audit.length === plan.stages.length && plan.audit.every((row) => row.subproblemId && row.stage && row.subproblemHash && row.resultHash && row.verificationStatus === "PASS"), plan.audit, "complete solver audit");

assert.strictEqual(assertions.length, 73, "Gate 6 must contain exactly T0407-T0479");
process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, ortoolsEvidence, performanceMs: plan.performanceBreakdownMs, largeFixtureMs: largeElapsed, metrics: plan.metrics, assertions }, null, 2)}\n`);
