'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const Design=require('../supply-chain-design-v19.js');
const Joint=require('../supply-chain-joint-v19.js');
const Results=require('../supply-chain-v5-results-v19.js');
const road=(fromNodeId,toNodeId,distanceKm)=>({fromNodeId,toNodeId,distanceKm,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_EXACT_MATRIX',observedAt:'2026-09-25',strategy:'TEST'});
const input={studyId:'V5-EXACT',name:'Synthetic exact v5',classification:'SYNTHETIC_TEST',currency:'CNY',coordinateUse:'UNCONFIRMED',costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'},nodes:[
  {nodeId:'S1',name:'Supplier One',role:'SUPPLIER'},{nodeId:'S2',name:'Supplier Two',role:'SUPPLIER'},
  {nodeId:'W1',name:'Warehouse One',role:'DC'},{nodeId:'W2',name:'Warehouse Two',role:'DC'},
  {nodeId:'C1',name:'Customer One',role:'CUSTOMER'},{nodeId:'C2',name:'Customer Two',role:'CUSTOMER'}
],periodDemand:[{demandId:'D1',customerNodeId:'C1',period:'2026-01',quantity:10,unit:'m3',currentSiteId:'W1',source:{sheet:'Demand',rowNumber:2}},{demandId:'D2',customerNodeId:'C2',period:'2026-01',quantity:10,unit:'m3',currentSiteId:'W2',source:{sheet:'Demand',rowNumber:3}}],observedInbound:[{flowId:'I1',fromNodeId:'S2',toNodeId:'W1',period:'2026-01',quantity:10,unit:'m3',source:{sheet:'Inbound',rowNumber:2}},{flowId:'I2',fromNodeId:'S1',toNodeId:'W2',period:'2026-01',quantity:10,unit:'m3',source:{sheet:'Inbound',rowNumber:3}}],distanceRows:[road('S1','W1',1),road('S1','W2',10),road('S2','W1',10),road('S2','W2',1),road('W1','C1',1),road('W1','C2',10),road('W2','C1',10),road('W2','C2',1)],rates:[{kind:'INBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',amount:0,status:'CONFIRMED_ZERO'},{kind:'HANDLING',basis:'PER_UNIT',amount:0,status:'CONFIRMED_ZERO'}]};
const study=Design.createStudy(input),period='2026-01';
const basic={scenarioId:'EXACT',analysisScope:'FULL_CHAIN',type:'NETWORK_CANDIDATE',objective:'VOLUME_KM',distanceBasis:'VERIFIED_ROAD',facilityCounts:[2],sourceMode:'FREE',supplierTotalMode:'ADJUSTABLE',capacityPolicy:'UNBOUNDED_SCREENING',homogeneousDemandConfirmed:true,allowAllSupplierSiteEdgesConfirmed:true,timeLimitSeconds:5,maxCandidates:5};
const python='import json,sys,ortools\nfrom ortools.sat.python import cp_model\nfrom supply_chain_joint_v19 import solve_joint\nprint(json.dumps(solve_joint(json.load(sys.stdin),cp_model,ortools.__version__)))';
function solve(current,scenario,reference=false){const request=Joint.buildRequest(current,scenario,{reference}),run=spawnSync('python3',['-c',python],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(request.payload),encoding:'utf8',timeout:120000,maxBuffer:20*1024*1024});assert.equal(run.status,0,run.stderr);const response=JSON.parse(run.stdout),verified=Joint.verify(current,scenario,request,response);return{request,response,verified};}
const two=solve(study,basic),twoRow=two.verified[0];
assert.equal(twoRow.objectiveValue,40);
assert.deepEqual(new Set(twoRow.selectedSiteIds),new Set(['W1','W2']));
assert.deepEqual(new Set(twoRow.sourceFlows.map(row=>`${row.supplierId}-${row.siteId}`)),new Set(['S1-W1','S2-W2']));
const one=solve(study,{...basic,facilityCounts:[1]}),oneRow=one.verified[0];
assert.equal(oneRow.objectiveValue,130);
const frozen=solve(study,{...basic,sourceMode:'FIXED',sourceRules:[{supplierId:'S2',siteId:'W1',mode:'FIXED_AMOUNT',quantityByPeriod:{[period]:10}},{supplierId:'S1',siteId:'W2',mode:'FIXED_AMOUNT',quantityByPeriod:{[period]:10}}]}),frozenRow=frozen.verified[0];
assert.equal(frozenRow.objectiveValue,220);
const upstream=solve(study,{...basic,analysisScope:'UPSTREAM_ONLY',facilityCounts:[2],supplierTotalMode:'FIXED_OBSERVED'}),upRow=upstream.verified[0];
assert.equal(upRow.objectiveValue,20);
assert.equal(Design.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}).metrics.inbound.numeratorVolumeKm,200);
assert.equal(upRow.assignments.length,0);
assert.deepEqual(new Set(upRow.sourceFlows.map(row=>`${row.supplierId}-${row.siteId}`)),new Set(['S1-W1','S2-W2']));
const limited=solve(study,{...basic,supplierCapacityByPeriod:{S1:{[period]:{max:10}}}}).verified[0];
assert.equal(limited.sourceFlows.filter(row=>row.supplierId==='S1').reduce((total,row)=>total+row.quantity,0),10);
const lowerBound=solve(study,{...basic,capacityPolicy:'PROVIDED',supplierCapacityByPeriod:{S1:{[period]:{min:15,max:20}},S2:{[period]:{max:20}}}}).verified[0];
assert.ok(lowerBound.sourceFlows.filter(row=>row.supplierId==='S1').reduce((total,row)=>total+row.quantity,0)>=15);
const locked=solve(study,{...basic,sourceMode:'PARTIAL',sourceRules:[{supplierId:'S2',siteId:'W1',mode:'FIXED_AMOUNT',quantityByPeriod:{[period]:10}}]}).verified[0];
assert.equal(locked.sourceFlows.find(row=>row.supplierId==='S2'&&row.siteId==='W1')?.quantity,10);
const shared=solve(study,{...basic,sourceMode:'PARTIAL',sourceRules:[{supplierId:'S1',siteId:'W1',mode:'FIXED_SHARE',share:0.5}]}).verified[0];
assert.equal(shared.sourceFlows.find(row=>row.supplierId==='S1'&&row.siteId==='W1')?.quantity,5);
const required=solve(study,{...basic,facilityCounts:[1],requiredSiteIds:['W1'],forbiddenSiteIds:['W2']}).verified[0];
assert.deepEqual(required.selectedSiteIds,['W1']);
assert.equal(required.objectiveValue,130);
const scarce=solve(study,{...basic,supplierCapacityByPeriod:{S1:{[period]:{max:9}},S2:{[period]:{max:9}}}});
assert.equal(scarce.verified.length,0);
assert.equal(scarce.response.results[0].status,'INFEASIBLE');
const peakStudy=Design.createStudy({...input,nodes:input.nodes.map(row=>row.nodeId==='W1'?{...row,capacityByPeriod:{[period]:9}}:row.nodeId==='W2'?{...row,capacityByPeriod:{[period]:9}}:row)});
assert.equal(solve(peakStudy,basic).response.results[0].status,'INFEASIBLE');
const monthly=Design.createStudy({...input,nodes:input.nodes.map(row=>['W1','W2'].includes(row.nodeId)?{...row,capacityByPeriod:{'2026-01':8,'2026-02':8}}:row),periodDemand:[...input.periodDemand,...input.periodDemand.map(row=>({...row,period:'2026-02',quantity:5}))],observedInbound:[...input.observedInbound,...input.observedInbound.map(row=>({...row,flowId:`${row.flowId}-FEB`,period:'2026-02',quantity:5}))]});
assert.equal(solve(monthly,basic).response.results[0].status,'INFEASIBLE');
const mismatched=Design.createStudy({...input,observedInbound:input.observedInbound.map(row=>row.fromNodeId==='S1'?{...row,quantity:5}:row)});
assert.equal(solve(mismatched,{...basic,supplierTotalMode:'FIXED_OBSERVED'}).response.results[0].status,'INFEASIBLE');
assert.throws(()=>Joint.buildRequest(study,{...basic,sourceMode:'FIXED',sourceRules:[]}),{code:'SUPPLY_FIXED_SOURCE_RULES_REQUIRED'});
assert.throws(()=>Joint.buildRequest(study,{...basic,allowAllSupplierSiteEdgesConfirmed:false,allowedSourceEdges:[]}),{code:'SUPPLY_SOURCE_EDGES_UNCONFIRMED'});
assert.throws(()=>Joint.buildRequest(study,{...basic,allowAllSupplierSiteEdgesConfirmed:false,allowedSourceEdges:[{supplierId:'S1',siteId:'W1'}]}),{code:'SUPPLY_SOURCE_EDGES_UNCONFIRMED'});
assert.equal(solve(study,{...basic,allowedSourcesBySite:{W1:['S1'],W2:['S2']}}).request.payload.inboundEdges.length,2);
assert.throws(()=>Joint.buildRequest(study,{...basic,allowAllSupplierSiteEdgesConfirmed:false,allowedSourceEdgesConfirmed:true,allowedSourceEdges:[{supplierId:'S2',siteId:'W1'}],allowedSourcesBySite:{W1:['S1']}}),{code:'SUPPLY_SOURCE_UNQUALIFIED'});
const costInput={...input,periodDemand:input.periodDemand.slice(0,1),observedInbound:input.observedInbound.slice(0,1),distanceRows:input.distanceRows,rates:[{kind:'INBOUND_TRANSPORT',fromNodeId:'S1',toNodeId:'W1',basis:'PER_UNIT_KM',amount:100,status:'KNOWN'},{kind:'INBOUND_TRANSPORT',fromNodeId:'S2',toNodeId:'W1',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',amount:0,status:'CONFIRMED_ZERO'},{kind:'HANDLING',basis:'PER_UNIT',amount:0,status:'CONFIRMED_ZERO'}]};
const costStudy=Design.createStudy(costInput),costBase={...basic,type:'FIXED_SITE_REASSIGNMENT',selectedSiteIds:['W1'],facilityCounts:[1],allowedSourceEdges:[{supplierId:'S1',siteId:'W1'},{supplierId:'S2',siteId:'W1'}],allowedSourceEdgesConfirmed:true,allowAllSupplierSiteEdgesConfirmed:false};
const distanceChoice=solve(costStudy,costBase).verified[0],costChoice=solve(costStudy,{...costBase,objective:'COST'}).verified[0];
assert.equal(distanceChoice.objectiveValue,20);
assert.equal(distanceChoice.sourceFlows[0].supplierId,'S1');
assert.equal(costChoice.objectiveValue,110);
assert.equal(costChoice.sourceFlows[0].supplierId,'S2');
const costSolved=solve(costStudy,{...costBase,objective:'COST',oneTimeConversionCost:50});
assert.equal(Results.fromVerified(costStudy,{...costBase,objective:'COST',oneTimeConversionCost:50},costSolved.request,costSolved.verified[0],1).metrics.firstPeriodCost,160);
const fixedCostStudy=Design.createStudy({...input,rates:input.rates.map(rate=>rate.kind==='FIXED_OPERATING'?{...rate,amount:100,status:'KNOWN'}:rate)}),fixedCostChoice=solve(fixedCostStudy,{...basic,objective:'COST',facilityCounts:[1,2]});
assert.equal(fixedCostChoice.verified[0].facilityCount,1);
assert.equal(fixedCostChoice.verified[0].objectiveValue,230);
assert.equal(Results.fromVerified(fixedCostStudy,{...basic,objective:'COST'},fixedCostChoice.request,fixedCostChoice.verified[0],1).metrics.operatingCost,230);
assert.throws(()=>Joint.buildRequest(Design.createStudy({...input,rates:[]}),{...basic,objective:'COST'}),{code:'SUPPLY_COST_OBJECTIVE_INCOMPLETE'});
const ref=solve(study,basic,true),baseline=Design.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),reference=Results.fromVerified(study,basic,ref.request,ref.verified[0],0),candidates=two.verified.map((row,index)=>Results.fromVerified(study,basic,two.request,row,index+1));
const snapshot=Results.createSnapshot(study,baseline,basic,reference,candidates,[{attempted:two.response.attempted,feasible:two.response.feasible,timedOut:two.response.timedOut}],two.request);
assert.equal(snapshot.rows[0].metrics.totalVolumeKm,40);
assert.match(Results.toCsv(study,snapshot),/S1/);
assert.match(Results.toHtml(study,snapshot),/40/);
assert.throws(()=>Results.toJson(Design.createStudy({...input,name:'changed'}),snapshot),/SUPPLY_SNAPSHOT_STALE/);
const tampered=structuredClone(two.response);tampered.results[0].sourceFlows[0].quantity=9;
assert.throws(()=>Joint.verify(study,basic,two.request,tampered),{code:'SUPPLY_JOINT_SITE_BALANCE_FAILED'});
const unmatched=Design.commonDistance([{demandId:'A',period,quantity:10,unit:'m3',volumeKm:10},{demandId:'B',period,quantity:10,unit:'m3',volumeKm:null}],[{demandId:'A',period,quantity:10,unit:'m3',volumeKm:null},{demandId:'B',period,quantity:10,unit:'m3',volumeKm:100}]);
assert.equal(unmatched.commonVolume,0);
assert.equal(unmatched.beforeWeightedKm,null);
const partial=Design.commonDistance([{demandId:'A',period,quantity:10,unit:'m3',volumeKm:10},{demandId:'B',period,quantity:10,unit:'m3',volumeKm:null}],[{demandId:'A',period,quantity:10,unit:'m3',volumeKm:20},{demandId:'B',period,quantity:10,unit:'m3',volumeKm:100}]);
assert.equal(partial.commonVolume,10);
assert.equal(partial.coverageRatio,0.5);
assert.equal(partial.afterWeightedKm,2);
console.log(JSON.stringify({suite:'SUPPLY_CHAIN_JOINT_V5',status:'PASS',twoSite:twoRow.objectiveValue,oneSite:oneRow.objectiveValue,frozen:frozenRow.objectiveValue,upstreamBefore:200,upstreamAfter:upRow.objectiveValue,costDistanceChoice:distanceChoice.sourceFlows[0].supplierId,costCostChoice:costChoice.sourceFlows[0].supplierId,infeasible:scarce.response.results[0].status}));
