'use strict';
const assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),path=require('node:path');
const D=require('../supply-chain-design-v19.js');
const input={studyId:'SYNTHETIC-V86-PERIOD-FEE',classification:'SYNTHETIC_TEST',costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'},nodes:[{nodeId:'F',role:'SUPPLIER'},{nodeId:'W1',role:'DC',capacityByPeriod:{P1:50,P2:50}},{nodeId:'W2',role:'DC',capacityByPeriod:{P1:50,P2:50}},{nodeId:'C1',role:'CUSTOMER'},{nodeId:'C2',role:'CUSTOMER'}],periodDemand:['P1','P2'].flatMap(period=>['1','2'].map(i=>({demandId:'D'+i,customerNodeId:'C'+i,currentSiteId:'W1',period,quantity:5,unit:'m3'}))),observedInbound:['P1','P2'].map(period=>({flowId:'I',fromNodeId:'F',toNodeId:'W1',period,quantity:10,unit:'m3'})),distanceRows:['W1','W2'].flatMap(w=>[{fromNodeId:'F',toNodeId:w,distanceKm:1},...['C1','C2'].map(toNodeId=>({fromNodeId:w,toNodeId,distanceKm:w==='W1'?15:7.5}))]).map(r=>({...r,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_NOT_ACTUAL_ROAD',travelSeconds:60})),rates:[{kind:'INBOUND_TRANSPORT',basis:'PER_PERIOD',amount:100,status:'KNOWN',toNodeId:'W1'},{kind:'INBOUND_TRANSPORT',basis:'PER_PERIOD',amount:170,status:'KNOWN',toNodeId:'W2'},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',amount:0,status:'CONFIRMED_ZERO'},{kind:'HANDLING',basis:'PER_UNIT',amount:0,status:'CONFIRMED_ZERO'}]};
const study=D.createStudy(input),scenario={scenarioId:'EXACT-ACTIVATION',type:'NETWORK_CANDIDATE',objective:'COST',objectiveScope:'TWO_END',distanceBasis:'VERIFIED_ROAD',facilityCounts:[1],sourcePlan:['W1','W2'].map(siteNodeId=>({sourceNodeId:'F',siteNodeId,share:1})),oneTimeConversionCost:0,timeLimitSeconds:5};
const solve=scenario=>{const request=D.solverRequest(study,scenario),python='import json,sys,ortools\nfrom ortools.sat.python import cp_model\nfrom facility_mvp1 import solve_facility\nprint(json.dumps(solve_facility(json.load(sys.stdin),cp_model,ortools.__version__)))',run=spawnSync('python3',['-c',python],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(request.payload),encoding:'utf8'});assert.equal(run.status,0,run.stderr);const response=JSON.parse(run.stdout);return {request,response,candidates:D.candidateResults(study,scenario,response)};};
const exact=solve(scenario);assert.equal(exact.candidates[0].selectedSiteIds[0],'W2');assert.equal(exact.candidates[0].solverEvidence.objectiveValue,490);assert.equal(exact.candidates[0].metrics.steadyStateCost,490);
const enumerated=['W1','W2'].map(w=>({site:w,independent:2*(w==='W1'?100:170)+20*(w==='W1'?15:7.5),ledger:D.evaluatePortfolio(study,{...scenario,selectedSiteIds:[w]},['D1','D2'].map(demandId=>({demandId,siteNodeId:w}))).metrics.steadyStateCost}));assert.deepEqual(enumerated.map(r=>r.ledger),[500,490]);for(const row of enumerated)assert.equal(row.ledger,row.independent);
// Exact solve output used as a valid base for request-bound adversarial response mutations.
const all=solve({...scenario,facilityCounts:[1,2]}),one=all.response.results.find(r=>r.facilityCount===1&&['OPTIMAL','FEASIBLE'].includes(r.status));
assert.throws(()=>D.candidateResults(study,{...scenario,facilityCounts:[2]},{...all.response,results:[one]}),{code:'SUPPLY_SOLVER_RESULT_INVALID'});
const free=solve({...scenario,objective:'VOLUME_KM',maxReassignments:2});const row=structuredClone(free.response.results[0]);delete row.maxReassignments;delete row.changedDemands;
assert.throws(()=>D.candidateResults(study,{...scenario,objective:'VOLUME_KM',maxReassignments:0},{...free.response,results:[row]}),e=>e.code==='SUPPLY_SOLVER_RESULT_INVALID'&&e.detail.issues.includes('REASSIGNMENT_BUDGET_EXCEEDED'));
const forbidden=D.createStudy({...input,nodes:[...input.nodes,{nodeId:'X',role:'DC'}]});assert.doesNotThrow(()=>D.solverRequest(forbidden,{...scenario,forbiddenSiteIds:['X']}));
assert.throws(()=>D.createStudy({...input,nodes:[null]}),{code:'SUPPLY_STUDY_ARRAY_OBJECTS_REQUIRED'});
console.log(JSON.stringify({kind:'NATIVE_CP_SAT_PLUS_INDEPENDENT_ENUMERATION_AND_ADVERSARIAL_VECTORS',enumerated,request:exact.request.payload,response:exact.response,candidates:exact.candidates},null,2));
