'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');

const root=path.resolve(__dirname,'..');
const evidenceDir=path.resolve(process.env.STCT_EVIDENCE_DIR||path.join(root,'test-results','p6-browser'));
const screenshotDir=path.join(evidenceDir,'screenshots');fs.mkdirSync(screenshotDir,{recursive:true});
const fixture=path.resolve(process.env.STCT_P6_FIXTURE||path.join(root,'tests','fixtures','p6-network.xlsx'));
if(!fs.existsSync(fixture))throw new Error(`P6 fixture missing: ${fixture}`);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
const server=http.createServer((request,response)=>{const url=new URL(request.url,'http://127.0.0.1'),relative=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),file=path.resolve(root,`.${relative}`);if(!file.startsWith(root+path.sep)){response.writeHead(403).end('Forbidden');return;}fs.readFile(file,(error,bytes)=>{if(error){response.writeHead(404).end('Not found');return;}response.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store'});response.end(bytes);});});
const listen=()=>new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve(server.address().port));});
const close=()=>new Promise(resolve=>server.close(resolve));
const checks=[];const pass=(id,detail)=>checks.push({id,status:'PASS',detail});
async function login(page,base,route){await page.goto(`${base}#${route}`,{waitUntil:'load'});await page.waitForFunction(()=>window.STCTPlatformV19?.instance);await page.locator('#loginForm .login-btn').click();await page.waitForFunction(()=>!document.querySelector('.app')?.classList.contains('locked'));}
async function navigate(page,route){await page.evaluate(value=>window.STCTPlatformV19.instance.navigate(value),route);await page.waitForFunction(value=>location.hash.includes(value),route);}
async function screenshot(page,name){const file=path.join(screenshotDir,name);await page.screenshot({path:file,fullPage:true});return{file,bytes:fs.statSync(file).size};}

(async()=>{
  const port=await listen(),base=`http://127.0.0.1:${port}/index.html`,browser=await chromium.launch({headless:true,executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
  const context=await browser.newContext({acceptDownloads:true}),page=await context.newPage();await page.setViewportSize({width:1440,height:900});
  const pageErrors=[],consoleErrors=[],publicServiceRequests=[];
  page.on('pageerror',error=>pageErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('request',request=>{const url=request.url();if(!url.startsWith(`http://127.0.0.1:${port}`)&&/(directions|matrix|route\/v1|optimi[sz]|openai|anthropic)/i.test(url))publicServiceRequests.push(url);});
  await login(page,base,'/platform/data');await navigate(page,'/platform/data');await page.waitForSelector('[data-p5-upload]');
  await page.locator('[data-p5-upload]').setInputFiles(fixture);await page.waitForSelector('[data-p5-action="validate"]');await page.locator('[data-p5-field="observationPeriod"]').fill('2026-09-06');await page.locator('[data-p5-confirm]').check();await page.locator('[data-p5-action="validate"]').click();await page.waitForTimeout(500);if(!await page.locator('[data-p5-action="save-data"]').count()){const diagnostic={message:await page.locator('[data-p5-message]').textContent(),text:(await page.locator('.platform-services').innerText()).slice(0,4000),pageErrors,consoleErrors};fs.writeFileSync(path.join(evidenceDir,'upload-validation-blocked.json'),JSON.stringify(diagnostic,null,2)+'\n');await screenshot(page,'upload-validation-blocked.png');throw Object.assign(new Error('P6 browser upload validation did not reach READY'),{diagnostic});}
  await page.locator('[data-p5-action="save-data"]').click();await page.waitForFunction(()=>document.querySelector('[data-p5-message]')?.textContent.includes('SAVED'));const adopt=page.locator('[data-p5-action="adopt"]').last();await adopt.click();await page.waitForSelector('[data-design-route="/design/network-scenarios"]');
  pass('J6-03-REAL-SAVED-SOURCE-UPLOAD',{fixture,path:await page.evaluate(()=>location.hash)});

  await navigate(page,'/platform/scenarios');await page.waitForSelector('[data-p5-action="save-baseline"]');await page.locator('[data-p5-field="scenarioName"]').fill('P6 Browser Baseline');await page.locator('[data-p5-action="save-baseline"]').click();await page.waitForFunction(()=>document.querySelector('[data-p5-message]')?.textContent.includes('SAVED'));
  await navigate(page,'/design/operational-validation');await page.waitForSelector('[data-design-route="/design/operational-validation"]');await page.locator('[data-design-validation-date]').fill('2026-09-06');await page.locator('[data-design-validation-confirm]').check();
  const commandBefore=await page.evaluate(async()=>{const context=window.STCTPlatformV19.instance.commandAdapter.createOperationalContext();await context.ready;return{plan:context.snapshot().plan.planHash,run:context.snapshot().execution.run.executionRunHash,events:context.snapshot().execution.acceptedEvents.map(row=>row.eventHash),pending:context.offlineQueue.summary().pending};});
  await page.locator('[data-design-action="validate-operations"]').click();await page.waitForSelector('.p6-validation-banner');const commandHeader=await page.locator('.p6-validation-banner').innerText();assert.match(commandHeader,/方案试跑|Operational validation|運用検証/);pass('T0380-T0386-REAL-BRIDGE-ENTRY',commandHeader.slice(0,500));
  await page.locator('[data-p5-action="p6-run"]').click();await page.waitForSelector('[data-p5-action="p6-save"]',{timeout:60000});const commandShot=await screenshot(page,'p6-command-result-desktop.png');
  const resultState=await page.evaluate(()=>window.STCTPlatformV19.instance.diagnostics().services?.bridge||null).catch(()=>null);const resultText=await page.locator('.platform-services').innerText();assert.match(resultText,/PASS/);assert.match(resultText,/vehicles/);pass('J6-06-CONTROL-GROUP-RESULT',{text:resultText.slice(0,800),diagnostics:resultState,screenshot:commandShot});
  const commandAfter=await page.evaluate(async()=>{const context=window.STCTPlatformV19.instance.commandAdapter.createOperationalContext();await context.ready;return{plan:context.snapshot().plan.planHash,run:context.snapshot().execution.run.executionRunHash,events:context.snapshot().execution.acceptedEvents.map(row=>row.eventHash),pending:context.offlineQueue.summary().pending};});assert.deepEqual(commandAfter,commandBefore);pass('J6-05-COMMAND-UNCHANGED',commandAfter);
  await page.locator('[data-p5-action="p6-save"]').click();await page.waitForFunction(()=>document.querySelector('[data-p5-message]')?.textContent.includes('SAVED'));await page.locator('[data-p5-action="p6-return"]').click();await page.waitForSelector('[data-design-route="/design/operational-validation"]');await page.waitForSelector('.design-scenario-list article');const designShot=await screenshot(page,'p6-design-return-desktop.png');pass('J6-09-RETURN-ATTACHMENT',{rows:await page.locator('.design-scenario-list article').count(),screenshot:designShot});

  const localeText={};for(const locale of ['zh','en','ja']){await page.evaluate(value=>window.STCTPlatformV19.instance.setLocale(value),locale);await navigate(page,'/command/validation');await page.waitForSelector('.p6-validation-banner');localeText[locale]=(await page.locator('.p6-validation-banner h2').textContent()).trim();assert.ok(localeText[locale]);}pass('J6-15-TRILINGUAL',localeText);
  await page.evaluate(()=>{window.STCTPlatformV19.instance.setNoWebGL(true);window.STCTPlatformV19.instance.setReducedMotion(true);});await navigate(page,'/design/operational-validation');await page.setViewportSize({width:390,height:844});const mobile=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,heading:document.querySelector('.design-page-heading h1')?.textContent||'',noWebGL:window.STCTPlatformV19.instance.snapshot().noWebGL,reducedMotion:window.STCTPlatformV19.instance.snapshot().reducedMotion}));assert.ok(mobile.width<=mobile.viewport+1);assert.equal(mobile.noWebGL,true);assert.equal(mobile.reducedMotion,true);const mobileShot=await screenshot(page,'p6-design-mobile-no-webgl.png');pass('J6-15-MOBILE-NO-WEBGL-REDUCED-MOTION',{...mobile,screenshot:mobileShot});

  await page.setViewportSize({width:1440,height:900});await navigate(page,'/platform/scenarios');const validationRow=page.locator('[data-p5-entry^="VALIDATION:"]').first();await validationRow.waitFor();const downloadPromise=page.waitForEvent('download');await validationRow.locator('[data-p5-action="export"]').click();const download=await downloadPromise,packageFile=path.join(evidenceDir,'p6-browser-export.study.json');await download.saveAs(packageFile);assert.ok(fs.statSync(packageFile).size>0);
  const fresh=await browser.newContext(),freshPage=await fresh.newPage();await login(freshPage,base,'/platform/scenarios');await navigate(freshPage,'/platform/scenarios');await freshPage.locator('[data-p5-package]').setInputFiles(packageFile);await freshPage.waitForSelector('[data-p5-action="import-package"]',{timeout:60000});await freshPage.locator('[data-p5-action="import-package"]').click();await freshPage.waitForFunction(()=>document.querySelector('[data-p5-message]')?.textContent.includes('SAVED'),{timeout:60000});assert.ok(await freshPage.locator('[data-p5-entry^="VALIDATION:"]').count());pass('J6-13-EMPTY-PROFILE-MIGRATION',{packageFile,bytes:fs.statSync(packageFile).size,entries:await freshPage.locator('[data-p5-entry]').count()});
  assert.equal(publicServiceRequests.length,0);assert.equal(pageErrors.length,0);pass('P6-BROWSER-RUNTIME-HEALTH',{pageErrors,consoleErrors,publicServiceRequests});
  const output={schemaVersion:'stct-v1.9-p6-browser-e2e-v1',status:'PASS',checks,fixture,packageFile,screenshots:fs.readdirSync(screenshotDir).filter(name=>name.startsWith('p6-')).sort(),pageErrors,consoleErrors,publicServiceRequests};fs.writeFileSync(path.join(evidenceDir,'p6-browser-e2e.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));await fresh.close();await context.close();await browser.close();await close();
})().catch(async error=>{console.error(error.stack);try{await close();}catch(_){}process.exitCode=1;});
