#!/usr/bin/env node
'use strict';
// Public business controls reopen native result packages; no study-state injection or solve.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_MAP_EVIDENCE,packages=process.env.STCT_MAP_PACKAGES,nonUC=process.env.STCT_NON_UC_PACKAGE;
assert.ok(out&&packages&&nonUC,'Set STCT_MAP_EVIDENCE, STCT_MAP_PACKAGES and STCT_NON_UC_PACKAGE');
fs.mkdirSync(out,{recursive:true});
const hash=value=>crypto.createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
const live=process.env.STCT_MAP_LIVE==='1',liveSmoke=process.env.STCT_SHOWCASE_LIVE_SMOKE==='1';
const packagePath=scope=>path.join(packages,fs.existsSync(path.join(packages,scope+'.package.json'))?scope+'.package.json':({OUTBOUND_ONLY:'uc-outbound',UPSTREAM_ONLY:'uc-upstream',FULL_CHAIN:'uc-full'}[scope]+'.package.json'));
const fixtures={OUTBOUND_ONLY:packagePath('OUTBOUND_ONLY'),UPSTREAM_ONLY:packagePath('UPSTREAM_ONLY'),FULL_CHAIN:packagePath('FULL_CHAIN'),NON_UC:nonUC};
const sourceFiles=()=>['platform-map-runtime-v19.js','platform-map-v19.css','platform-supply-map-v8.js','supply-chain-view-v19.js','index.html',...fs.readdirSync(root).filter(f=>/^platform-map-showcase.*\.js$/.test(f))];
const sourceHashes=()=>Object.fromEntries(sourceFiles().map(f=>[f,hash(fs.readFileSync(path.join(root,f)))]));
const report={status:'RUNNING',tier:'BROWSER_NATIVE_PACKAGE_REOPEN_NO_NEW_SOLVE',method:'Home → business entry → native package file input → visible map controls. Read-only model, layer and diagnostic inspection.',basemap:live?'Live OpenFreeMap':'Explicit neutral offline style fixture; actual local MapLibre layers and SVG rendering.',checks:[],pageErrors:[],consoleErrors:[],fixtures:Object.fromEntries(Object.entries(fixtures).map(([key,file])=>[key,{file,sha256:hash(fs.readFileSync(file))}])),sourceSHA256Before:sourceHashes(),testSHA256:hash(fs.readFileSync(__filename))};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,data)=>error?res.writeHead(404).end():res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream'}).end(data));});
let browser,context,page,base;
const host=()=>page.locator('.p7-map-workspace:visible');
const diag=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());
const model=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.snapshot());
const supply=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function expose(locator){for(const details of (await locator.locator('xpath=ancestor::details').all()).reverse())if(!await details.evaluate(e=>e.open))await details.locator(':scope > summary').click();}
async function click(selector){const locator=page.locator(selector);await expose(locator);await locator.click();}
async function option(selector,value){const locator=page.locator(selector);await expose(locator);await locator.selectOption(value);}
async function ready(){await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-facilities'));}
async function maps(fn){return page.evaluate(text=>{const maps=(window.__showcaseQAMaps||[]).filter(m=>m.getCanvas().isConnected);return new Function('maps','return ('+text+')(maps)')(maps);},fn.toString());}
async function layerVisibility(){return maps(ms=>{const map=ms.find(m=>m.getSource('p7-supply'));return Object.fromEntries(map.getStyle().layers.filter(l=>l.id.startsWith('p7-supply')).map(l=>[l.id,map.getLayoutProperty(l.id,'visibility')||'visible']));});}
async function phasePaint(){return page.locator('[data-showcase-side]').evaluateAll(es=>Object.fromEntries(['reference','candidate'].map(side=>[side,es.filter(e=>e.dataset.showcaseSide===side).map(e=>Number(e.getAttribute('opacity')))])));}
async function assertWarehousePhase(side){const expected=(await model()).features.filter(f=>f.geometry.type==='Point'&&f.properties.kind==='facility'&&f.properties[side+'Selected']).map(f=>f.properties.entityId).sort(),actual=await page.locator('[data-showcase-warehouse]').evaluateAll(es=>es.filter(e=>Number(e.getAttribute('opacity'))>0).map(e=>e.dataset.showcaseWarehouse).sort());assert.deepEqual(actual,expected,'Presentation warehouse labels follow the active reference/candidate plan');assert.equal(await host().locator('.p7-map-labels').evaluate(e=>getComputedStyle(e).visibility),'hidden','Base warehouse labels must not duplicate or contradict the animated phase');}
async function positions(){return page.locator('[data-showcase-pulse]').evaluateAll(es=>es.map(e=>({id:e.dataset.showcasePulse,cx:e.getAttribute('cx'),cy:e.getAttribute('cy')})));}
async function shot(name){await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,name+'.png')});}
async function persist(){fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(report,null,2));}
async function check(id,fn){const item={id,status:'RUNNING'},start=Date.now();try{item.evidence=await fn();item.status='PASS';}catch(error){item.status='FAIL';item.error=error.stack;await shot(id+'-failure').catch(()=>{});}item.wallMs=Date.now()-start;report.checks.push(item);await persist();console.log(id,item.status);}
async function closeShowcase(){if((await diag()).showcase?.open)await click('[data-showcase-action="close"]');}
async function start(mode){await closeShowcase();await click('[data-p7-showcase="'+mode+'"]');await page.locator('.p7-showcase').waitFor();await page.waitForFunction(mode=>window.STCTPlatformV19.mapRuntime.diagnostics().showcase?.mode===mode,mode);}
async function openStudy(scope,{width=1440,reducedMotion=false,noWebGL=false}={}){
 if(context)await context.close();
 context=await browser.newContext({viewport:{width,height:width===390?844:1000},reducedMotion:reducedMotion?'reduce':'no-preference',acceptDownloads:true});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(!live&&url.hostname==='tiles.openfreemap.org'&&url.pathname.startsWith('/styles/'))return route.fulfill({contentType:'application/json',body:JSON.stringify({version:8,sources:{},layers:[{id:'qa-neutral-basemap',type:'background',paint:{'background-color':url.pathname.includes('dark')?'#101722':'#edf1f7'}}]})});if(['127.0.0.1','localhost'].includes(url.hostname)&&url.pathname.endsWith('/vendor/maplibre/maplibre-gl.js')){return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'vendor/maplibre/maplibre-gl.js'),'utf8')+'\n;(()=>{const RealMap=maplibregl.Map;maplibregl.Map=class ObservedMap extends RealMap{constructor(...args){super(...args);(window.__showcaseQAMaps||=[]).push(this)}}})();'});}return ['127.0.0.1','localhost'].includes(url.hostname)||['blob:','data:'].includes(url.protocol)||live&&url.hostname==='tiles.openfreemap.org'?route.continue():route.abort();});
 page=await context.newPage();page.setDefaultTimeout(18000);page.on('pageerror',e=>report.pageErrors.push({scope,error:e.message}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({scope,text:m.text()});});
 await page.goto(base+(noWebGL?'&noWebGL=1':'')+'#/');if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.getByRole('button',{name:/测算供应链方案/}).click();const input=page.locator('[data-supply-file="study"]');await expose(input);await input.setInputFiles(fixtures[scope]);await page.locator('[data-supply-map-panel]').waitFor();if(!noWebGL)await ready();return JSON.parse(fs.readFileSync(fixtures[scope],'utf8'));
}
(async()=>{try{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}/index.html?forceHeuristic=1`;report.service={pid:process.pid,host:'127.0.0.1',port:server.address().port,optimizerStarted:false};
 browser=await chromium.launch({executablePath:process.env.STCT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 for(const scope of (liveSmoke?['FULL_CHAIN']:Object.keys(fixtures))){
  await openStudy(scope);if(live)await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().renderedBasemapFeatureCount>0,{},{timeout:25000});const before=hash((await supply()).snapshot),originalModel=hash(await model()),visibility=await layerVisibility();
  await check(scope+'_PULSE_ACTUAL_MOVEMENT_PAUSE',async()=>{await start('pulse');await page.locator('[data-showcase-pulse]').first().waitFor();const a=await positions();await page.waitForFunction(a=>JSON.stringify([...document.querySelectorAll('[data-showcase-pulse]')].map(e=>({id:e.dataset.showcasePulse,cx:e.getAttribute('cx'),cy:e.getAttribute('cy')})))!==JSON.stringify(a),a,{timeout:4000});const b=await positions();assert.ok(a.length>0);assert.notDeepEqual(a,b,'Rendered SVG particle positions must change, not only status text');await click('[data-showcase-action="pause"]');assert.equal((await diag()).showcase.playing,false);const paused=await positions();await page.waitForTimeout(240);assert.deepEqual(await positions(),paused,'Pause must freeze actual particles');const d=(await diag()).showcase;assert.equal(d.pendingFrame,false);await shot(scope+'-pulse-paused');await closeShowcase();assert.deepEqual(await layerVisibility(),visibility,'Exit must restore all map layer visibility');assert.equal(hash(await model()),originalModel);assert.equal(hash((await supply()).snapshot),before);return {renderedParticles:a.length,diagnostics:d,actualPositionsChanged:true,pausedPositionsFrozen:true};});
  await check(scope+'_CHANGE_PHASES_RESTORE',async()=>{await start('change');await click('[data-showcase-action="phase"][data-phase="0"]');assert.equal((await diag()).showcase.phase,'reference');assert.ok(await page.locator('[data-showcase-side="reference"]').count()>0);let paint=await phasePaint();assert.ok(paint.reference.some(v=>v>0));assert.ok(paint.candidate.every(v=>v===0));await assertWarehousePhase('reference');await click('[data-showcase-action="phase"][data-phase="1"]');assert.equal((await diag()).showcase.phase,'changes');await click('[data-showcase-action="phase"][data-phase="2"]');assert.equal((await diag()).showcase.phase,'candidate');assert.ok(await page.locator('[data-showcase-side="candidate"]').count()>0);paint=await phasePaint();assert.ok(paint.candidate.some(v=>v>0));assert.ok(paint.reference.every(v=>v===0));await assertWarehousePhase('candidate');assert.equal((await diag()).showcase.playing,false);await shot(scope+'-change-candidate');await click('[data-showcase-action="reset"]');const reset=(await diag()).showcase;assert.equal(reset.phaseIndex,0);await closeShowcase();assert.deepEqual(await layerVisibility(),visibility);assert.equal(hash((await supply()).snapshot),before);return {threeManualStages:true,reset,immutableSnapshot:true};});
  if(scope==='FULL_CHAIN'&&!liveSmoke){
   await check('MAP_PAN_OVERLAY_ALIGNMENT',async()=>{await start('pulse');await click('[data-showcase-action="pause"]');const beforePositions=await positions(),beforeCenter=await maps(ms=>ms.find(m=>m.getSource('p7-supply')).getCenter().toArray());const anchored=await maps(ms=>{const map=ms.find(m=>m.getSource('p7-supply'));return [...document.querySelectorAll('[data-showcase-pulse]')].slice(0,10).map(e=>({id:e.dataset.showcasePulse,coordinate:map.unproject([Number(e.getAttribute('cx')),Number(e.getAttribute('cy'))]).toArray()}));});await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();const box=await host().locator('.p7-map-canvas canvas').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+35,{steps:12});await page.mouse.up();await page.waitForTimeout(180);const afterPositions=await positions(),afterCenter=await maps(ms=>ms.find(m=>m.getSource('p7-supply')).getCenter().toArray());assert.notDeepEqual(afterCenter,beforeCenter,'Real map drag must move the camera');assert.notDeepEqual(afterPositions,beforePositions,'Paused SVG must reproject when map camera moves');assert.equal((await diag()).showcase.playing,false);const expected=await page.evaluate(points=>{const map=window.__showcaseQAMaps.find(m=>m.getCanvas().isConnected&&m.getSource('p7-supply'));return points.map(p=>({id:p.id,point:map.project(p.coordinate)}));},anchored);for(const point of expected){const actual=afterPositions.find(p=>p.id===point.id);assert.ok(Math.abs(Number(actual.cx)-point.point.x)<1&&Math.abs(Number(actual.cy)-point.point.y)<1,'Paused particle follows MapLibre camera to within 1px');}await shot('pulse-map-pan-aligned');await closeShowcase();await click('[data-p7-fit]');return {beforeCenter,afterCenter,particlesReprojected:true};});
   await check('THREE_CYCLE_LIFECYCLE',async()=>{await closeShowcase();const before=(await diag()).mapEventListeners;for(let i=0;i<3;i++){await start('pulse');assert.equal(await page.locator('.p7-showcase-overlay').count(),1);await click('[data-showcase-action="pause"]');assert.equal((await diag()).showcase.pendingFrame,false);await closeShowcase();assert.equal(await page.locator('.p7-showcase-overlay').count(),0);assert.equal((await diag()).showcase.pendingFrame,false);}assert.deepEqual((await diag()).mapEventListeners,before,'Open/close must not accumulate map listeners');return {cycles:3,overlaysAfterClose:0,listenersRestored:true};});
   await check('ONE_SHOT_CHANGE_FINISHES',async()=>{await start('change');await page.waitForFunction(()=>{const s=window.STCTPlatformV19.mapRuntime.diagnostics().showcase;return s?.phase==='candidate'&&!s.playing;},{},{timeout:22000});const final=(await diag()).showcase;await page.waitForTimeout(200);assert.deepEqual((await diag()).showcase,final,'Change walkthrough must not loop');await closeShowcase();return final;});
   await check('WAREHOUSE_FOCUS_RESTORED',async()=>{const warehouse=host().locator('[data-p7-coverage-warehouse]:not([data-p7-coverage-warehouse=""])').first(),id=await warehouse.getAttribute('data-p7-coverage-warehouse');await warehouse.click();const focused=(await diag()).viewStates.SUPPLY.selectedEntityId,focusedModel=await model();assert.equal(focused,id);await start('pulse');const keys=await page.locator('[data-showcase-pulse]').evaluateAll(es=>es.map(e=>e.dataset.showcasePulse));assert.ok(keys.length>0);for(const key of keys){const relationId=JSON.parse(key)[0],parts=decodeURIComponent(relationId).split('\0');assert.ok(parts.slice(1).includes(id),'Focused pulse must belong to the selected warehouse');}const state=(await diag()).showcase;await closeShowcase();assert.equal((await diag()).viewStates.SUPPLY.selectedEntityId,id);assert.equal(hash(await model()),hash(focusedModel));await click('[data-p7-coverage-warehouse=""]');return {warehouse:id,renderedPulseKeys:keys,diagnostics:state};});
   await check('PERIOD_CANDIDATE_MODEL_SWITCH_CANCELS',async()=>{await start('pulse');const periods=await page.locator('[data-supply-compare="period"] option').evaluateAll(es=>es.map(e=>e.value));await option('[data-supply-compare="period"]',periods.find(p=>p!=='ALL'));assert.equal((await diag()).showcase.open,false);assert.equal(await page.locator('.p7-showcase-overlay').count(),0);await option('[data-supply-compare="period"]','ALL');const candidates=await page.locator('[data-supply-compare="scenarioId"] option').evaluateAll(es=>es.map(e=>e.value));const current=await page.locator('[data-supply-compare="scenarioId"]').inputValue(),next=candidates.find(c=>c!==current);assert.ok(next,'Fixture provides multiple candidate scenarios');await start('pulse');await option('[data-supply-compare="scenarioId"]',next);assert.equal((await diag()).showcase.open,false);await option('[data-supply-compare="scenarioId"]',current);await start('pulse');await option('[data-supply-compare="leg"]','INBOUND');assert.equal((await diag()).showcase.open,false);await option('[data-supply-compare="leg"]','BOTH');return {period:true,candidate:true,leg:true};});
   await check('THEME_FULLSCREEN_ESCAPE',async()=>{await start('pulse');await click('[data-p7-map-theme]');await ready();await start('pulse');await page.locator('[data-showcase-pulse]').first().waitFor();await shot('pulse-dark');await closeShowcase();await click('[data-p7-expand]');await page.locator('dialog.p7-map-fullscreen[open]').waitFor();await start('pulse');assert.ok(await page.locator('dialog.p7-map-fullscreen .p7-showcase').isVisible());await page.keyboard.press('Escape');assert.equal((await diag()).showcase.open,false);assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),1,'First Escape closes showcase, retains fullscreen');await page.keyboard.press('Escape');assert.equal(await page.locator('dialog.p7-map-fullscreen[open]').count(),0);await click('[data-p7-map-theme]');await ready();return {dark:true,fullscreen:true,escapeOrdering:true};});
   for(const locale of ['zh','en','ja'])await check('I18N_'+locale+'_390_FULLSCREEN',async()=>{await closeShowcase();await page.locator('[data-platform-locale]').selectOption(locale);await page.setViewportSize({width:390,height:844});await click('[data-p7-expand]');await start('pulse');await page.locator('[data-showcase-pulse]').first().waitFor();const panel=page.locator('.p7-showcase');assert.ok(await panel.isVisible());assert.ok((await panel.innerText()).trim().length>20);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'Showcase controls should not overflow at 390px');const box=await host().locator('.p7-map-viewport').boundingBox(),visibleHeight=Math.min(844,box.y+box.height)-Math.max(0,box.y);assert.ok(visibleHeight>=150,'At least 150px of map remains visible when mobile presentation opens');await shot('pulse-'+locale+'-390-fullscreen');await start('change');await click('[data-showcase-action="phase"][data-phase="1"]');assert.ok(await page.locator('.p7-showcase').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await shot('change-'+locale+'-390-fullscreen');await closeShowcase();await click('[data-p7-fullscreen-close]');await page.setViewportSize({width:1440,height:1000});return {locale,panelText:await host().locator('[data-p7-showcase="pulse"]').innerText(),viewport:390,mapInitiallyVisible:visibleHeight};});
   assert.equal(hash((await supply()).snapshot),before,'All map demonstration controls preserve the native result snapshot');
  }
 }
 if(!liveSmoke)await check('REDUCED_MOTION_STATIC_AND_MANUAL',async()=>{await openStudy('FULL_CHAIN',{reducedMotion:true});await start('pulse');let d=(await diag()).showcase;assert.equal(d.reducedMotion,true);assert.equal(d.playing,false);assert.equal(d.pendingFrame,false);const a=await positions();await page.waitForTimeout(300);assert.deepEqual(await positions(),a);await start('change');await click('[data-showcase-action="phase"][data-phase="2"]');d=(await diag()).showcase;assert.equal(d.phase,'candidate');assert.equal(d.pendingFrame,false);await shot('reduced-motion-manual-candidate');return {staticPulse:true,manualStages:true,diagnostics:d};});
 if(!liveSmoke)await check('NO_WEBGL_CLEAR_FALLBACK',async()=>{await openStudy('NON_UC',{width:390,noWebGL:true});assert.equal((await diag()).mode,'SCHEMATIC');await click('[data-p7-showcase="pulse"]');const d=(await diag()).showcase;assert.equal(d.available,false);assert.equal(d.pendingFrame,false);const text=await page.locator('.p7-showcase').innerText();assert.match(text,/WebGL|示意|schematic|fallback|利用|不可|无法|静态/i);await shot('no-webgl');return {diagnostics:d,text};});
 report.status=report.checks.every(item=>item.status==='PASS')&&!report.pageErrors.length?'PASS':'FAIL';
 }catch(error){report.status='BLOCKED';report.setupError=error.stack;if(page){report.body=(await page.locator('body').innerText().catch(()=>'' )).slice(-12000);await shot('setup-failure').catch(()=>{});}}
 finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));report.serviceClosed=true;report.sourceSHA256After=sourceHashes();report.sourceBindingStable=JSON.stringify(report.sourceSHA256Before)===JSON.stringify(report.sourceSHA256After);if(!report.sourceBindingStable)report.status='FAIL';await persist();console.log(JSON.stringify({status:report.status,checks:report.checks.length,failed:report.checks.filter(c=>c.status!=='PASS').map(c=>({id:c.id,error:c.error?.split('\n')[0]})),pageErrors:report.pageErrors,setupError:report.setupError,sourceBindingStable:report.sourceBindingStable}));if(report.status!=='PASS')process.exitCode=1;}
})();
