'use strict';
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),XLSX=require('../vendor/xlsx/xlsx.full.min.js'),Budget=require('../import-budget-v19.js');
const code=fs.readFileSync(require.resolve('../main.js'),'utf8');
function named(name){const start=code.indexOf('function '+name+'('),end=code.indexOf('\nfunction ',start+1);assert.ok(start>=0);return code.slice(code.slice(start-6,start)==='async '?start-6:start,end<0?undefined:end);}
const context={window:{XLSX,STCTImportBudget:Budget},XLSX,Uint8Array,TextEncoder,hasRawWorkbook:w=>w.SheetNames.includes('Orders'),excelToRawData:w=>({kind:'raw',sheets:w.SheetNames}),excelToFlowData:w=>({sheets:w.SheetNames})};vm.createContext(context);vm.runInContext(named('parseExcelFile')+'\n'+named('parseUploadedText'),context);
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
(async()=>{
let reads=0;await assert.rejects(context.parseExcelFile({size:Budget.LIMITS.fileBytes+1,arrayBuffer:async()=>{reads++;}}),/IMPORT_FILE_TOO_LARGE/);assert.equal(reads,0);checks++;
check('JSON byte budget before parse',()=>assert.throws(()=>context.parseUploadedText('"'+'汉'.repeat(3e6)+'"'),/IMPORT_FILE_TOO_LARGE/));
check('JSON depth boundary',()=>{assert.equal(context.parseUploadedText('['.repeat(30)+'0'+']'.repeat(30)).length,1);assert.throws(()=>context.parseUploadedText('['.repeat(31)+'0'+']'.repeat(31)),/IMPORT_DEPTH_LIMIT/);});
check('Classic wrappers and literal markup preserved',()=>assert.equal(context.parseUploadedText('window.FLOWMAP_DATA = {"label":"<script>literal</script> & \\\"q\\\""};').label,'<script>literal</script> & "q"'));
check('Brackets in JSON strings do not count as nesting',()=>assert.equal(context.parseUploadedText('{"value":"[[{{"}').value,'[[{{'));
check('JSON string/row budgets',()=>{assert.throws(()=>context.parseUploadedText(JSON.stringify({label:'x'.repeat(100001)})),/IMPORT_STRING_LIMIT/);assert.throws(()=>context.parseUploadedText(JSON.stringify({routes:Array(10001).fill({})})),/IMPORT_ROW_LIMIT/);});
check('Workbook rows/columns/sheets including fullref',()=>{for(const ref of ['A1:A10001','A1:CW1'])assert.throws(()=>Budget.checkWorkbook({SheetNames:['S'],Sheets:{S:{'!ref':'A1','!fullref':ref}}},XLSX),/IMPORT_TABLE_LIMIT/);assert.throws(()=>Budget.checkWorkbook({SheetNames:Array(25).fill('S'),Sheets:{S:{}}},XLSX),/IMPORT_SHEET_LIMIT/);Budget.checkWorkbook({SheetNames:Array(24).fill('S'),Sheets:{S:{'!ref':'A1:CV10000'}}},XLSX);});
for(const type of ['xlsx','xls']){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Orders'],['普通文字 & <b>']]),'Orders');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Vehicles'],['V-01']]),'Vehicles');const bytes=XLSX.write(wb,{type:'buffer',bookType:type});const result=await context.parseExcelFile({size:bytes.length,arrayBuffer:async()=>bytes});assert.equal(result.__rawUpload,true);checks++;console.log('PASS actual '+type+' read');}
const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['OK']]),'S');const bytes=Uint8Array.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}));const view=new DataView(bytes.buffer);let at=0;for(;at<bytes.length-46;at++)if(view.getUint32(at,true)===0x02014b50)break;view.setUint32(at+24,Budget.LIMITS.expandedBytes+1,true);let parseCalls=0;context.XLSX={...XLSX,read:()=>{parseCalls++;throw Error('parse must not run');}};context.window.XLSX=context.XLSX;await assert.rejects(context.parseExcelFile({name:'renamed.xls',size:bytes.length,arrayBuffer:async()=>bytes}),/IMPORT_EXPANDED_SIZE_LIMIT/);assert.equal(parseCalls,0);checks++;
const w={};vm.runInNewContext(fs.readFileSync(require.resolve('../validator.js'),'utf8'),{window:w,structuredClone});
check('CSV formula prefixes and ordinary values',()=>{for(const prefix of ['=','+','-','@'])for(const space of ['',' ','\uFEFF',' \uFEFF','\n'])assert.ok(w.STCTUtils.csvSafe(space+prefix+'1').startsWith('"\''));for(const value of [0,-3,'0001','normal & <b>'])assert.equal(w.STCTUtils.csvSafe(value),'"'+value+'"');});
check('Classic alternate CSV consumer delegates to shared encoder',()=>assert.match(code,/function csvEscape\(v\) \{\s*return window\.STCTUtils\.csvSafe\(v\);/));
console.log(JSON.stringify({status:'PASS',checks,method:'PRODUCTION_PARSERS_WITH_REAL_XLSX_XLS_AND_PRE_PARSE_SPIES'}));
})().catch(e=>{console.error(e);process.exitCode=1});
