 'use strict';
const assert=require('node:assert/strict'),Intake=require('../platform-import-session-v19.js').tabularIntake,Import=require('../supply-chain-import-v19.js'),Public=require('../platform-import-session-v19.js'),XLSX=require('../vendor/xlsx/xlsx.full.min.js'),Display=require('../platform-import-session-v19.js').businessNumber;
const wb=XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Monthly planning export'],['编号','客户编号','客户名称','经度','纬度','2026/01 箱数'],['D','C','Alpha',120,30,0.25],['编号','客户编号','客户名称','经度','纬度','2026/01 箱数']]),'Customers');
const inspected=Import.inspectWorkbook(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),'titles.xlsx'),profile=Intake.template(inspected),block=profile.blocks[0];
assert.equal(block.startRow,3);assert.deepEqual(block.headerRows,[2]);assert.equal(block.fields.customerNodeId,2);assert.equal(block.fields.customerName,3);assert.equal(block.periodColumns[0].unit,'boxes');assert.equal(block.primaryMeasure,'boxes');assert.equal(block.excludeRows[0].rowNumber,4);
const imported=Import.applyProfile(inspected,profile);assert.equal(imported.periodDemand[0].quantity,0.25);assert.equal(imported.periodDemand[0].unit,'boxes');assert.deepEqual(imported.nodes[0].coordinate,[120,30]);assert.equal(imported.excludedRows[0].reasonCode,'REPEATED_HEADER');assert.equal(imported.periodDemand[0].source.rowNumber,3);
const bytes=Buffer.from('编号;客户名称;月份;物量;单位\nD;Alpha;2026-01;1.25;m3\nD;Alpha;2026-02;2.5;m3','utf8');
const longBook=Import.inspectWorkbook(bytes,'long.csv'),longProfile=Intake.template(longBook);assert.equal(longProfile.blocks[0].layout,'LONG');
const long=Import.applyProfile(longBook,longProfile);assert.equal(long.periodDemand.length,2);assert.equal(long.periodDemand[1].quantity,2.5);assert.equal(long.nodes.length,1);assert.equal(long.periodDemand[1].source.rowNumber,3);
const duplicate=structuredClone(longBook);duplicate.sheets[0].rows[2].values[2]='2026/01';assert.throws(()=>Import.applyProfile(duplicate,longProfile),e=>e.code==='SC_IMPORT_DEMAND_ID_DUPLICATE');
assert.equal(Intake.suggest(longBook),'SUPPLY_CHAIN_PERIOD');assert.equal(Intake.suggest({sheets:[{rows:[{rowNumber:1,values:['memo','remark']}]}]}),null);
assert.equal(Intake.csvDelimiter('"a;b",c\n1,2'),',');assert.equal(Intake.period('202601'),'2026-01');assert.equal(Intake.period('2026-13'),null);assert.equal(Intake.quantity('2026-01').unit,'');
assert.equal(Intake.period('Jan2026'),'2026-01');
const wide=Import.inspectWorkbook(Buffer.from('编号,客户名称,2026-01m3\nD,Alpha,1'),'wide.csv'),saved=Intake.template(wide);saved.matchSignature=Import.profileSignature(wide,saved);
const appended=Import.inspectWorkbook(Buffer.from('编号,客户名称,2026-01m3,2026-02m3\nD,Alpha,1,2'),'wide.csv'),matched=Import.matchProfile(appended,saved);
assert.equal(matched.requiresReview,true);assert.equal(matched.profile.blocks[0].periodColumns.length,2);assert.equal(Import.applyProfile(appended,matched.profile).periodDemand.length,2);
const rolled=Import.inspectWorkbook(Buffer.from('编号,客户名称,2026-02m3\nD,Alpha,1'),'wide.csv'),rollMatch=Import.matchProfile(rolled,saved);assert.equal(rollMatch.requiresReview,true);assert.equal(rollMatch.profile.blocks[0].periodColumns[0].period,'2026-02');
assert.deepEqual(rollMatch.changes.map(row=>[row.before,row.after]),[['2026-01m3','2026-02m3']]);
const lostUnit=Import.matchProfile(Import.inspectWorkbook(Buffer.from('编号,客户名称,2026-02\nD,Alpha,1'),'wide.csv'),saved);
assert.equal(lostUnit.requiresReview,true);assert.equal(lostUnit.profile.blocks[0].periodColumns[0].unit,'');
assert.throws(()=>Import.applyProfile(Import.inspectWorkbook(Buffer.from('编号,客户名称,2026-02\nD,Alpha,1'),'wide.csv'),lostUnit.profile),e=>e.code==='SC_PROFILE_PERIOD_INVALID');
const manual=Import.inspectWorkbook(Buffer.from('编号;客户名称;2026-01m3\nD;Alpha;1'),'manual.csv',{csvDelimiter:';'});
assert.equal(manual.sheets[0].columnCount,3);assert.equal(manual.sheets[0].rows[1].values[0],'D');
assert.throws(()=>Import.inspectWorkbook(Buffer.from('a|b\n1|2'),'manual.csv',{csvDelimiter:'|'}),e=>e.code==='SC_IMPORT_DELIMITER_INVALID');
assert.equal(Display.number(123.456),'123.5');assert.equal(Display.number(null),'—');assert.equal(Display.number(0),'0');assert.equal(Display.number(0.00001),'<0.1');assert.equal(Display.percent(.9996),'<100%');assert.equal(Display.percent(1.0004),'>100%');assert.equal(Display.exact(123.456),'123.456');assert.equal(Display.filename('a:b / c','report','html'),'a_b _ c_report.html');
for(const value of [1e-15,-1e-15,1.234567890123456])assert.equal(Number(Display.exact(value)),value,'Exact tooltip must not round its source number');
for(const value of [[],{},true,'   ']){assert.equal(Display.number(value),'—');assert.equal(Display.exact(value),'—');}
(async()=>{const csv=Buffer.from('业务资料\n订单编号;经度;纬度;物量\nO1;120;30;0.25','utf8');const session=await Public.readFiles([{name:'delivery.csv',size:csv.length,arrayBuffer:async()=>csv.buffer.slice(csv.byteOffset,csv.byteOffset+csv.length)}]);assert.equal(session.tables[0].kind,'orders');assert.equal(session.tables[0].headerRow,2);assert.equal(session.mapping[0]['物量'],'demand.volume');assert.equal(session.tables[0].rowNumbers[0],3);assert.equal(session.tables[0].records[0]['订单编号'],'O1');console.log(JSON.stringify({status:'PASS',method:'ACTUAL_XLSX_CSV_AND_PRODUCTION_MAPPING',vectors:['merged-title','separate-coordinates','name-vs-id','boxes-not-m3','repeated-header','long-periods','canonical-duplicate-period','csv-delimiter','public-business-aliases','display-boundaries','windows-filename']}));})().catch(e=>{console.error(e);process.exitCode=1});
