'use strict';
const assert=require('node:assert/strict'),Map=require('../platform-supply-map-v8.js');
const node=(nodeId,role,coordinate)=>({nodeId,role,name:nodeId,coordinate,coordinateSystem:'WGS84'});
const leg=(fromNodeId,toNodeId,quantity,distanceKm,cost)=>({fromNodeId,toNodeId,quantity,distanceKm,cost,period:'P1',distanceQuality:distanceKm==null?null:'GEOGRAPHIC_SCREENING',distanceSource:distanceKm==null?null:'SYNTHETIC',distanceTimestamp:'2027-01-01',distanceStrategy:'TEST'});
const study={studyId:'SYNTHETIC-SPATIAL',inputHash:'INPUT',unit:'m3',periods:['P1'],nodes:[node('W','DC',[110,30]),node('Z','DC',[115,30]),node('C','CUSTOMER',[111,30]),node('D','CUSTOMER',[112,30]),node('M','CUSTOMER',null)]};
const snapshot={studyHash:'INPUT',snapshotHash:'SNAP',analysisScope:'OUTBOUND_ONLY',baseline:{outbound:[leg('W','C',5,10,4),leg('W','D',2,100,6),leg('W','M',3,null,null)]},rows:[{scenarioId:'PLAN',selectedSiteIds:['W','Z'],outbound:[leg('Z','C',5,20,8),leg('W','D',2,100,6),leg('W','M',3,null,null)]}],decision:{focusScenarioId:'PLAN'}};
const original=JSON.stringify({study,snapshot}),model=Map.projectComparison(study,snapshot),before=JSON.stringify(model);
const all=Map.analyticalProjection(model);
assert.equal(all.totalRelations,4);assert.equal(all.scopeRelations,4);assert.equal(all.groups[0].before.quantity,10);assert.equal(all.groups[0].after.quantity,10);assert.equal(all.groups[0].after.weightedKm,300/7);assert.equal(all.groups[0].after.cost,null);
assert.equal(all.distributions.distance.reduce((n,b)=>n+b.count,0),4);
assert.equal(all.distributions.distance.at(-1).count,1);
const short=Map.analyticalProjection(model,{ranges:{distance:{min:0,max:50,unknown:false}}});
assert.deepEqual(short.relations.map(r=>[r.fromNodeId,r.toNodeId]),[['W','C'],['Z','C']]);assert.equal(short.groups[0].before.quantity,5);assert.equal(short.groups[0].after.quantity,5);
const unknown=Map.analyticalProjection(model,{ranges:{distance:{unknown:true}}});assert.equal(unknown.relations[0].toNodeId,'M');assert.equal(unknown.groups[0].after.quantity,3);assert.equal(unknown.groups[0].after.weightedKm,null);assert.equal(unknown.missingMappedRelations,1);
assert.equal(Map.analyticalProjection(model,{scope:'SELECTED',ids:[]}).relations.length,0);
assert.equal(Map.analyticalProjection(model,{scope:'VIEWPORT',bounds:[110.5,29,111.5,31]}).relations.length,2);
assert.equal(Map.analyticalProjection({...model,features:[]}).groups[0].after.quantity,10,'Full ledger is independent of rendering limits');
const geo={type:'Polygon',coordinates:[[[110,29],[114,29],[114,32],[110,32],[110,29]],[[111.5,29.5],[112.5,29.5],[112.5,30.5],[111.5,30.5],[111.5,29.5]]]};
assert.deepEqual(Map.regionMembers(model,geo,'DESTINATION'),short.relationIds);
assert.ok(Map.regionMembers(model,geo,'ORIGIN').includes(model.relations.find(r=>r.fromNodeId==='W'&&r.toNodeId==='M').relationId));
assert.equal(Map.regionMembers(model,{type:'Polygon',coordinates:[[[110,30],[111,30],[111,31],[110,31],[110,30]]]},'DESTINATION').length,2,'Boundary nodes are included');
assert.throws(()=>Map.regionPolygons({type:'LineString',coordinates:[]}),/REGION_GEOMETRY_INVALID/);
assert.throws(()=>Map.regionPolygons({type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[2,2]]]}),/REGION_GEOMETRY_INVALID/);
const grid=Map.fixedGrid(model,all.relations,'outbound',1);
assert.equal(grid.cells.reduce((n,c)=>n+c.before,0)+grid.missingBefore,10);assert.equal(grid.cells.reduce((n,c)=>n+c.after,0)+grid.missingAfter,10);assert.equal(grid.missingRelations.length,1);
assert.equal(grid.cells.reduce((n,c)=>n+c.delta,0),0,'Redistribution does not create demand change');
const coverage=Map.coverage({coverageRows:[{nodeId:'C',sites:[{siteId:'W',distanceKm:10,travelSeconds:null},{siteId:'Z',distanceKm:20,travelSeconds:null}]},{nodeId:'D',sites:[{siteId:'W',distanceKm:100},{siteId:'Z',distanceKm:null}]}]},50);
assert.equal(coverage[0].status,'OVERLAP');assert.equal(coverage[1].status,'UNKNOWN');assert.equal(Map.coverage({coverageRows:[{sites:[{siteId:'W',distanceKm:0}]}]},0)[0].status,'REACHABLE');
assert.equal(Map.coverage({coverageRows:[{sites:[{siteId:'W',distanceKm:10,travelSeconds:null}]}]},1800,'travelSeconds')[0].status,'UNKNOWN');
assert.throws(()=>Map.coverage(model,-1),/COVERAGE_THRESHOLD_INVALID/);
assert.deepEqual(model.relations.find(r=>r.fromNodeId==='Z').distanceEvidence.after[0].sources,['SYNTHETIC']);
assert.equal(JSON.stringify({study,snapshot}),original);assert.equal(JSON.stringify(model),before);
console.log(JSON.stringify({status:'PASS',tier:'SYNTHETIC_PURE_PROJECTION',networkQuantity:10,knownWeightedKm:300/7,unknownQuantity:3,gridTotals:10,snapshotUnchanged:true}));
