#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const os = require("os");
const net = require("net");
const crypto = require("crypto");
const child = require("child_process");

function arg(name, fallback) { const index = process.argv.indexOf(name); return index >= 0 ? process.argv[index + 1] : fallback; }
const root = path.resolve(__dirname, ".."); const deliveryDir = path.resolve(arg("--delivery-dir", "/Users/gz/Documents/STCT-v1.7-operational-truth-multi-vehicle-execution-20260831")); const distDir = path.resolve(arg("--dist-dir", "/tmp/lospollos-v1.7-demo-dist")); const auditDir = path.resolve(arg("--audit-dir", "/tmp/lospollos-v1.7-audit-bundle")); const baseline = path.resolve(arg("--baseline", "/tmp/lospollos-v1.7-baseline-20260831_175714")); const v16Delivery = path.resolve(arg("--v16-delivery", "/Users/gz/Documents/STCT-v1.6-road-aware-dynamic-operations-20260831")); const evidencePath = path.join(deliveryDir, "STCT-v1.7-DELIVERY-GATE.json");
const assertions = []; const sha256 = (file) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
function check(requirementId, condition, observed, expected) { const row = { assertionId: `${requirementId}-A1`, requirementId, status: condition ? "PASS" : "FAIL", observed, expected, evidence: "tests/test_delivery_v17.js" }; assertions.push(row); assert(condition, `${requirementId}: ${JSON.stringify({ observed, expected })}`); }
function run(command, args, cwd = root) { const result = child.spawnSync(command, args, { cwd, encoding: "utf8", maxBuffer: 1024 * 1024 * 64 }); return { command: [command, ...args].join(" "), exitCode: result.status, stdout: result.stdout, stderr: result.stderr }; }
function list(dir, prefix = "") { return fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, "en")).flatMap((entry) => { const relative = path.join(prefix, entry.name).split(path.sep).join("/"); const target = path.join(dir, entry.name); return entry.isDirectory() ? list(target, relative) : entry.isFile() ? [relative] : []; }); }
function textFiles(dir) { return list(dir).filter((file) => ![".png", ".jpg", ".jpeg", ".xlsx", ".zip"].includes(path.extname(file).toLowerCase())); }
function scan(dir, regex) { return textFiles(dir).flatMap((file) => { const matches = fs.readFileSync(path.join(dir, file), "utf8").match(regex); return matches ? [{ file, match: matches[0] }] : []; }); }
function portClosed(port) { return new Promise((resolve) => { const socket = net.createConnection({ host: "127.0.0.1", port }); const done = (value) => { socket.destroy(); resolve(value); }; socket.setTimeout(300); socket.once("connect", () => done(false)); socket.once("timeout", () => done(true)); socket.once("error", () => done(true)); }); }
function proposedFiles(file) { return fs.readFileSync(file, "utf8").split("\n").map((line) => line.trim()).filter((line) => /^(?!Proposed|Commit|Exact|Suggested|git |$)[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)*$/.test(line)); }

async function main() {
  const changed = JSON.parse(fs.readFileSync(path.join(deliveryDir, "CHANGED_FILES.json"), "utf8")); const changedPaths = changed.files.map((row) => row.path); const actions = JSON.parse(fs.readFileSync(path.join(auditDir, "DELIVERY_ACTIONS.json"), "utf8"));
  check("T612", changed.schemaVersion === "stct-v17-changed-files-v1.7" && changedPaths.length > 20, changedPaths.length, ">20 changed files"); check("T613", fs.statSync(path.join(deliveryDir, "TRACKED_DIFF.patch")).size > 100, "tracked diff", "non-empty"); check("T614", fs.statSync(path.join(deliveryDir, "UNTRACKED_DIFF.patch")).size > 100, "untracked diff", "non-empty"); check("T615", fs.readFileSync(path.join(deliveryDir, "BINARY_SHA256.txt"), "utf8").split("\n").filter(Boolean).length >= 8, "binary SHA", ">=8 baseline binaries");
  const diffCheck = run("git", ["diff", "--check"]); check("T616", diffCheck.exitCode === 0, diffCheck.stderr, "exit 0"); const branch = run("git", ["branch", "--show-current"]).stdout.trim(); const head = run("git", ["rev-parse", "HEAD"]).stdout.trim(); check("T617", branch === fs.readFileSync(path.join(baseline, "branch.txt"), "utf8").trim(), branch, "baseline branch"); check("T618", head === fs.readFileSync(path.join(baseline, "head.txt"), "utf8").trim(), head, "baseline HEAD");
  const excelRows = fs.readFileSync(path.join(baseline, "original-excel-sha256.txt"), "utf8").split("\n").filter(Boolean).map((line) => ({ hash: line.slice(0, 64), file: line.slice(66) })); const excelCurrent = excelRows.map((row) => ({ ...row, actual: fs.existsSync(path.resolve(root, row.file)) ? sha256(path.resolve(root, row.file)) : fs.existsSync(row.file) ? sha256(row.file) : "MISSING" })); check("T619", excelCurrent.every((row) => row.hash === row.actual), excelCurrent, "all original Excel SHA unchanged");
  check("T620", actions.stopUserService === false, actions, false); const ports = await Promise.all([19230, 19231, 19232].map(async (port) => ({ port, closed: await portClosed(port) }))); check("T621", ports.every((row) => row.closed), ports, "all v1.7 test ports closed"); check("T622", actions.commit === false && head === changed.head, actions, "no commit"); check("T623", actions.push === false, actions.push, false); check("T624", actions.deploy === false, actions.deploy, false); check("T625", actions.install === false, actions.install, false); check("T626", actions.downloadBinary === false, actions.downloadBinary, false); check("T627", actions.dockerPull === false, actions.dockerPull, false); check("T628", actions.publicOSRM === false, actions.publicOSRM, false); check("T629", actions.publicValhalla === false, actions.publicValhalla, false); check("T630", actions.publicVROOM === false, actions.publicVROOM, false); check("T631", /OpenFreeMap.*network access/i.test(fs.readFileSync(path.join(distDir, "README-DIST.md"), "utf8")), actions.mapNetworkDisclosure, "map network disclosed");
  const distFiles = list(distDir); check("T632", distFiles.length > 60 && distFiles.every((file) => !file.startsWith("tests/") && !file.startsWith("audit/")), distFiles.length, "runtime whitelist"); check("T633", !distFiles.some((file) => file.includes(".git")), true, true); check("T634", distFiles.filter((file) => file.endsWith(".xlsx")).join() === "templates/raw-dispatch-template.xlsx", distFiles.filter((file) => file.endsWith(".xlsx")), ["templates/raw-dispatch-template.xlsx"]); check("T635", fs.readFileSync(path.join(distDir, "DATA_CLASSIFICATION.md"), "utf8").includes("blank upload template"), "classified", "blank template"); check("T636", !distFiles.some((file) => /audit/i.test(file)), distFiles.filter((file) => /audit/i.test(file)), []); check("T637", scan(distDir, /\/Users\/|\/home\/|\/tmp\/|file:\/\/\/Users/).length === 0, scan(distDir, /\/Users\/|\/home\/|\/tmp\/|file:\/\/\/Users/), []); check("T638", scan(distDir, /(sk-[A-Za-z0-9]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY)/).length === 0, "scan", "clean");
  const distManifest = fs.readFileSync(path.join(distDir, "SHA256SUMS.txt"), "utf8").split("\n").filter(Boolean); check("T639", distManifest.every((line) => /^[a-f0-9]{64}  \.\//.test(line)), distManifest.slice(0, 2), "relative"); check("T640", !distManifest.some((line) => line.endsWith("./SHA256SUMS.txt")), true, true);
  const extract = fs.mkdtempSync(path.join(os.tmpdir(), "stct-v17-dist-check-")); const unzip = run("unzip", ["-q", path.join(deliveryDir, "lospollos-v1.7-demo-dist.zip"), "-d", extract]); const extractedRoot = path.join(extract, path.basename(distDir)); const extractedManifest = run("shasum", ["-a", "256", "-c", "SHA256SUMS.txt"], extractedRoot); check("T641", unzip.exitCode === 0 && extractedManifest.exitCode === 0, { unzip: unzip.exitCode, manifest: extractedManifest.exitCode }, "random extract PASS");
  const scripts = distFiles.filter((file) => file.endsWith(".js")); const syntax = scripts.map((file) => run("node", ["--check", file], extractedRoot)); check("T642", syntax.every((row) => row.exitCode === 0) && fs.existsSync(path.join(extractedRoot, "index.html")), syntax.filter((row) => row.exitCode), "Release smoke"); const fallback = run("node", ["-e", "const m=require('./fleet-tracks-v17.js');if(!m.noWebGLTable&&!m.fleetTable)process.exit(1);const t=require('./telemetry-v17.js');if(!t.noWebGLTable)process.exit(2)"] , extractedRoot); check("T643", fallback.exitCode === 0, fallback.stderr, "Fallback smoke"); const multi = run("node", ["-e", "const f=require('./fleet-replay-v17.js');const s=f.syntheticScenario({vehicleCount:20,stopsPerVehicle:12});if(s.routes.length!==20||s.stops.length!==240)process.exit(1)"], extractedRoot); check("T644", multi.exitCode === 0, multi.stderr, "20 vehicles / 240 stops"); const offline = run("node", ["-e", "const d=require('./driver-reconciliation-v17.js');if(typeof d.createSession!=='function'||typeof d.memoryStorage!=='function')process.exit(1)"], extractedRoot); check("T645", offline.exitCode === 0, offline.stderr, "offline module smoke"); const capsule = run("node", ["-e", "const c=require('./operational-capsule-v17.js');const r=require('./capsule-replay-validator-v17.js');if(typeof c.importCapsule!=='function'||typeof r.validate!=='function')process.exit(1)"], extractedRoot); check("T646", capsule.exitCode === 0, capsule.stderr, "capsule replay module smoke"); fs.rmSync(extract, { recursive: true, force: true });
  const auditFiles = list(auditDir); check("T647", auditFiles.length > 30 && auditFiles.every((file) => !/\.(xlsx|xls|zip|gz|tar)$/i.test(file)), auditFiles.length, "audit whitelist"); const auditManifest = run("shasum", ["-a", "256", "-c", "SHA256SUMS.txt"], auditDir); check("T648", auditManifest.exitCode === 0, auditManifest.stderr, "audit manifest PASS"); check("T649", scan(auditDir, /\/Users\/|\/private\/tmp\/|file:\/\/\/Users/).length === 0 && fs.existsSync(path.join(auditDir, "PATH_REDACTION_MAP.md")), "redacted", "no local paths"); check("T650", scan(auditDir, /(sk-[A-Za-z0-9]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY)/).length === 0, "scan", "clean"); check("T651", !auditFiles.some((file) => file.includes(".git")), true, true); check("T652", !auditFiles.some((file) => /\.(xlsx|xls)$/i.test(file)), true, true); check("T653", auditFiles.filter((file) => file.startsWith("before/")).length === 12 && auditFiles.some((file) => file.startsWith("after/")), auditFiles.filter((file) => /^(before|after)\//.test(file)).length, 13); check("T654", auditFiles.some((file) => file.includes("MUTATION-SUMMARY")), auditFiles.filter((file) => /adversarial/.test(file)), "mutation evidence"); check("T655", auditFiles.filter((file) => file.endsWith(".png")).length >= 11, auditFiles.filter((file) => file.endsWith(".png")).length, ">=11 screenshots"); check("T656", auditFiles.some((file) => file.includes("PERFORMANCE.json")), true, true); check("T657", JSON.parse(fs.readFileSync(path.join(auditDir, "requirements-v17.json"), "utf8")).requirements.length === 674, 674, 674); check("T658", auditFiles.includes("TRACKED_DIFF.patch") && auditFiles.includes("UNTRACKED_DIFF.patch"), auditFiles.filter((file) => file.endsWith(".patch")), "full diff"); check("T659", fs.readFileSync(path.join(auditDir, "STCT-v1.7-OPEN_SOURCE_INSPIRATION.md"), "utf8").includes("No AGPL source code was copied"), true, true); check("T660", fs.readFileSync(path.join(root, "DATA_CLASSIFICATION.md"), "utf8").includes("v1.7 Operational Truth Boundary"), true, true); check("T661", fs.readFileSync(path.join(root, "NOTICE.md"), "utf8").includes("v1.7 Operational Truth"), true, true);
  const commitFiles = ["PROPOSED_COMMIT_1_V17_EXECUTION_TELEMETRY.txt", "PROPOSED_COMMIT_2_V17_MULTI_VEHICLE_UI.txt", "PROPOSED_COMMIT_3_V17_TRACEABILITY_DELIVERY.txt"].map((name) => path.join(deliveryDir, name)); const commitLists = commitFiles.map(proposedFiles); check("T662", commitLists[0].length > 5 && commitLists[0].every((file) => changedPaths.includes(file)), commitLists[0], "exact paths"); check("T663", commitLists[1].length > 5 && commitLists[1].every((file) => changedPaths.includes(file)), commitLists[1], "exact paths"); check("T664", commitLists[2].length > 5 && commitLists[2].every((file) => changedPaths.includes(file)), commitLists[2], "exact paths"); const union = commitLists.flat(); check("T665", new Set(union).size === union.length, { total: union.length, unique: new Set(union).size }, "no duplicates"); check("T666", [...new Set(union)].sort().join("\n") === [...changedPaths].sort().join("\n"), { union: union.length, changed: changedPaths.length }, "union equals changed files"); const dispositionText = fs.readFileSync(path.join(deliveryDir, "FILE_DISPOSITION.md"), "utf8"); check("T667", changedPaths.every((file) => dispositionText.includes(`\`${file}\``)), changedPaths.filter((file) => !dispositionText.includes(`\`${file}\``)), []);
  const v16Manifest = run("shasum", ["-a", "256", "-c", path.join(baseline, "v16-delivery-sha256.txt")], v16Delivery); check("T668", v16Manifest.exitCode === 0, v16Manifest.stderr, "v1.6 Dist unchanged"); check("T669", v16Manifest.exitCode === 0, v16Manifest.stderr, "v1.6 Audit unchanged"); const zipEntries = ["lospollos-v1.7-demo-dist.zip", "lospollos-v1.7-audit-bundle.zip"].flatMap((name) => run("unzip", ["-Z1", path.join(deliveryDir, name)]).stdout.split("\n")); check("T670", !zipEntries.some((entry) => entry.includes("__MACOSX")), zipEntries.filter((entry) => entry.includes("__MACOSX")), []);
  const finalText = fs.readFileSync(path.join(deliveryDir, "STCT-v1.7-FINAL_REPORT.md"), "utf8"); check("T671", finalText.includes("not production-ready") && !/production-ready[^:\n]*\./i.test(finalText.replace("not production-ready", "")), "boundary present", "no production claim"); check("T672", finalText.includes("no live GPS"), "no live GPS", "explicit boundary"); check("T673", finalText.includes("lexical ID coverage is auxiliary only"), "semantic registry", "ID text alone not coverage"); check("T674", finalText.includes("Overall: COMPLETED") && Array.from({ length: 12 }, (_, index) => `Gate ${index}: PASS`).every((line) => finalText.includes(line)), "component statuses", "COMPLETED with 12 PASS gates");
  const report = { schemaVersion: "stct-v17-delivery-gate-v1.7", status: "PASS", assertions, paths: { deliveryDir, distDir, auditDir }, boundaries: actions }; fs.writeFileSync(evidencePath, `${JSON.stringify(report, null, 2)}\n`); process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, evidencePath }, null, 2)}\n`);
}
main().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exit(1); });
