'use strict';
// Private acceptance: only aggregate assertions and temporary local evidence.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const http = require('node:http');
const net = require('node:net');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const evidenceDir = path.resolve(process.env.STCT_UC_EVIDENCE_DIR || '/tmp/stct-supply-chain-v4-uc');
const sourcePath = process.env.STCT_UC_WORKBOOK || '/Users/gz/Downloads/经纬度追加-天津、沈阳、西安、东莞相关入、出库物量数据  202601~07-001 物量数据(1).xlsx';
const profile = require('./fixtures/supply-chain-uc-profile-v19.json');
const hash = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png' };
const server = http.createServer((request, response) => {
  const pathname = decodeURIComponent(new URL(request.url, 'http://127.0.0.1').pathname);
  const file = path.resolve(root, `.${pathname === '/' ? '/index.html' : pathname}`);
  if (!file.startsWith(root + path.sep)) return response.writeHead(403).end('Forbidden');
  fs.readFile(file, (error, bytes) => error ? response.writeHead(404).end('Not found') : response.writeHead(200, { 'content-type': mime[path.extname(file)] || 'application/octet-stream', 'cache-control': 'no-store' }).end(bytes));
});
const freePort = () => new Promise((resolve, reject) => { const socket = net.createServer(); socket.once('error', reject); socket.listen(0, '127.0.0.1', () => { const port = socket.address().port; socket.close(() => resolve(port)); }); });
const listen = () => new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', () => resolve(server.address().port)); });
const close = () => new Promise(resolve => server.close(resolve));
async function ready(port, child) { for (let i = 0; i < 100; i++) { if (child.exitCode !== null) throw new Error('Optimizer exited'); try { const r = await fetch(`http://127.0.0.1:${port}/health`); if (r.ok && (await r.json()).available) return; } catch (_) {} await new Promise(resolve => setTimeout(resolve, 150)); } throw new Error('Optimizer not ready'); }

(async () => {
  fs.mkdirSync(evidenceDir, { recursive: true });
  const originalHash = hash(sourcePath), temp = fs.mkdtempSync(path.join(os.tmpdir(), 'stct-uc-v3-browser-')), copyPath = path.join(temp, path.basename(sourcePath));
  fs.copyFileSync(sourcePath, copyPath); assert.equal(hash(copyPath), originalHash); assert.equal(originalHash, profile.sourceWorkbookSha256);
  const optPort = await freePort(), optimizer = spawn(process.env.STCT_PYTHON || 'python3', ['optimizer/ortools_service.py'], { cwd: root, env: { ...process.env, OPT_PORT: String(optPort) }, stdio: ['ignore', 'pipe', 'pipe'] });
  let browser, log = '';
  optimizer.stderr.on('data', chunk => { log = (log + chunk.toString()).slice(-1500); });
  optimizer.stdout.on('data', chunk => { log = (log + chunk.toString()).slice(-1500); });
  try {
    await ready(optPort, optimizer);
    const staticPort = await listen();
    browser = await chromium.launch({ headless: true, executablePath: process.env.STCT_BROWSER || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--no-sandbox', '--disable-webgl'] });
    const page = await browser.newPage({ acceptDownloads: true, viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
    const errors = [], requests = [], external = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.url().startsWith(`http://127.0.0.1:${optPort}/supply-chain-jobs-v6`) && request.method() === 'POST') requests.push(...(request.postDataJSON()?.requests || []).filter(item => item.kind === 'FACILITY').map(item => item.payload)); else if (request.url().startsWith(`http://127.0.0.1:${optPort}/facility-optimize-v19`)) requests.push(request.postDataJSON()); else if (!request.url().startsWith(`http://127.0.0.1:${staticPort}`) && !request.url().startsWith(`http://127.0.0.1:${optPort}`) && /(matrix|route\/v1|optimizer|openai)/i.test(request.url())) external.push(request.url()); });
    await page.goto(`http://127.0.0.1:${staticPort}/index.html?optPort=${optPort}&noWebGL=1#/design/supply-chain-study`);
    await page.locator('#loginForm .login-btn').click();
    await page.waitForSelector('.supply-chain-study.sc-business');
    await page.locator('[data-supply-file="workbook"]').setInputFiles(copyPath);
    await page.waitForFunction(() => document.querySelector('.sc-card')?.textContent.includes('257') || document.querySelector('[data-supply-action="profile-confirm"]'));
    assert.match(await page.locator('.sc-card').nth(1).textContent(), /已按工作表和表头匹配映射/);
    assert.equal(await page.locator('.sc-advanced textarea:visible').count(), 0);
    await page.locator('[data-supply-action="profile-confirm"]').click();
    await page.waitForSelector('[data-supply-action="analyze"]');
    await page.waitForFunction(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.savedPointer?.status === 'DRAFT');
    let state = await page.evaluate(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
    assert.equal(state.imported.summary.demandBusinessRows, 257);
    assert.equal(state.imported.summary.inboundBusinessRows, 12);
    assert.equal(state.study.periodDemand.length, 1799);
    assert.equal(state.study.observedInbound.length, 84);
    assert.equal(state.study.periods.length, 7);
    assert.ok(Math.abs(state.imported.summary.periodDemandTotals.m3 - 115934.168) < 1e-6);
    assert.ok(Math.abs(state.imported.summary.observedInboundTotals.m3 - 97370.239) < 1e-6);
    assert.equal(state.savedPointer.status, 'DRAFT');
    await page.reload();
    if (await page.locator('#loginForm .login-btn').isVisible()) await page.locator('#loginForm .login-btn').click();
    await page.waitForSelector('.supply-chain-study.sc-business');
    await page.locator('[data-supply-action="step"][data-supply-id="0"]').click();
    await page.locator('[data-supply-action="study-list"]').click();
    await page.locator('[data-supply-action="study-open"]').first().click();
    await page.waitForFunction(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.study?.periodDemand?.length === 1799);
    state = await page.evaluate(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
    assert.equal(state.study.periodDemand.length, 1799);
    assert.equal(state.snapshot, null);
    await page.locator('[data-supply-field="geoConfirmed"]').check();
    await page.locator('[data-supply-action="analyze"]').click();
    await page.waitForFunction(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.snapshot?.rows?.length > 0, null, { timeout: 120000 });
    state = await page.evaluate(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
    assert.equal(state.baseline.outbound.length, 1799);
    assert.equal(state.baseline.inbound.length, 84);
    assert.equal(state.baseline.distanceBasis, 'GEOGRAPHIC_SCREENING');
    assert.equal(state.snapshot.recommendation, null);
    assert.ok(state.candidates.length > 0);
    assert.deepEqual(requests.at(-1).options.facilityCounts, [4]);
    assert.equal(requests.at(-1).demands.length, 257);
    assert.equal(requests.at(-1).sites.length, 4);
    const fixed = state.snapshot.explanation.rows[0];
    assert.equal(fixed.affected.businessRecords, 34);
    assert.ok(Math.abs(fixed.affected.volume - 7867.270) < 0.001);
    assert.ok(Math.abs(fixed.outbound.before.weightedKm - 213.5389735747) < 0.0001);
    assert.ok(Math.abs(fixed.outbound.after.weightedKm - 204.3504057652) < 0.0001);
    assert.ok(Math.abs(state.snapshot.explanation.baselineInbound.knownVolumeKmSubtotal - 92334005.534344) < 0.01);
    const pending = page.waitForEvent('download');
    await page.locator('[data-supply-action="export-html"]').click();
    const report = await pending; assert.equal(report.suggestedFilename(), 'supply-chain-study.html');
    const saved = path.join(evidenceDir, 'uc-fixed-report-v4.html'); await report.saveAs(saved);
    const reportHtml = fs.readFileSync(saved, 'utf8');
    assert.ok(reportHtml.includes('单方案对比') && reportHtml.includes('14,124.075'));
    assert.ok(!reportHtml.includes(state.snapshot.snapshotHash) && !reportHtml.includes('<th>运输段</th>'));
    await page.locator('.sc-conclusion').scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(evidenceDir, 'uc-fixed-page-v4.png'), fullPage: true });
    await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();
    await page.locator('[data-supply-field="networkMode"]').selectOption('MULTI');
    for (const row of await page.locator('.sc-sites tbody tr').all()) await row.locator('input[value="adjust"]').check();
    await page.locator('[data-supply-field="minSites"]').fill('2');
    await page.locator('[data-supply-field="maxSites"]').fill('4');
    await page.locator('[data-supply-action="analyze"]').click();
    await page.waitForFunction(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.snapshot?.rows?.length >= 5, null, { timeout: 120000 });
    await page.waitForSelector('.sc-conclusion');
    state = await page.evaluate(() => window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
    assert.deepEqual(requests.at(-1).options.facilityCounts, [2, 3, 4]);
    assert.ok(state.snapshot.explanation.rows.length >= 5);
    assert.equal(new Set(state.snapshot.explanation.rows.map(row => row.selectedSites.map(site => site.siteId).sort().join('|'))).size, state.snapshot.explanation.rows.length);
    assert.equal(state.snapshot.explanation.solver.displayed, state.snapshot.rows.length);
    await page.locator('.sc-conclusion').scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(evidenceDir, 'uc-multi-page-v4.png'), fullPage: true });
    const multiPending = page.waitForEvent('download');
    await page.locator('[data-supply-action="export-html"]').click();
    const multiReport = await multiPending;
    await multiReport.saveAs(path.join(evidenceDir, 'uc-multi-report-v4.html'));
    const multiHtml = fs.readFileSync(path.join(evidenceDir, 'uc-multi-report-v4.html'), 'utf8');
    assert.ok(multiHtml.includes('多方案比较') && !multiHtml.includes('<th>运输段</th>'));
    assert.ok(multiHtml.includes('改配方向') && multiHtml.includes('处理量') && multiHtml.includes('费用未计算'));
    const csvPending = page.waitForEvent('download');
    await page.locator('[data-supply-action="export-csv"]').click();
    const csvDownload = await csvPending;
    await csvDownload.saveAs(path.join(evidenceDir, 'uc-multi-detail-v4.csv'));
    const csvLines = fs.readFileSync(path.join(evidenceDir, 'uc-multi-detail-v4.csv'), 'utf8').trimEnd().split('\n').length;
    assert.equal(csvLines, 1 + 1799 + 84 + 1799 * state.snapshot.rows.length);
    for (const [format, filename] of [['json', 'uc-multi-technical-v4.json'], ['md', 'uc-multi-technical-v4.md']]) {
      await page.locator(`[data-supply-action="export-${format}"]`).locator('xpath=ancestor::details[1]/summary').click();
      const pending = page.waitForEvent('download', { timeout: 90000 });
      await page.locator(`[data-supply-action="export-${format}"]`).click();
      await (await pending).saveAs(path.join(evidenceDir, filename));
    }
    assert.equal(JSON.parse(fs.readFileSync(path.join(evidenceDir, 'uc-multi-technical-v4.json'), 'utf8')).snapshot.snapshotHash, state.snapshot.snapshotHash);
    for (const [locale, expected] of [['en', 'Multiple network scenarios'], ['ja', '複数網案の比較']]) {
      await page.locator('[data-platform-locale]').selectOption(locale);
      const localizedPending = page.waitForEvent('download');
      await page.locator('[data-supply-action="export-html"]').click();
      const localized = await localizedPending;
      const pathName = path.join(evidenceDir, `uc-multi-report-v4-${locale}.html`);
      await localized.saveAs(pathName);
      assert.ok(fs.readFileSync(pathName, 'utf8').includes(expected));
    }
    await page.locator('[data-platform-locale]').selectOption('zh');
    fs.writeFileSync(path.join(evidenceDir, 'uc-v4-summary.json'), JSON.stringify({ inputHash: state.study.inputHash, snapshotHash: state.snapshot.snapshotHash, fixedCandidates: 1, multiCandidates: state.snapshot.rows.length, solver: state.snapshot.explanation.solver, businessRecords: state.snapshot.explanation.records.businessDemand, outboundVolume: state.snapshot.explanation.records.demandVolume, inboundKnownSubtotal: state.snapshot.explanation.baselineInbound.knownVolumeKmSubtotal, csvLines, originalUnchanged: hash(sourcePath) === originalHash }, null, 2));
    assert.deepEqual(errors, []); assert.deepEqual(external, []);
    console.log(JSON.stringify({ status: 'PASS', dataset: 'UC_PRIVATE', noJsonInput: true, demandBusinessRows: 257, inboundBusinessRows: 12, periods: 7, fixedCandidates: 1, multiCandidates: state.candidates.length, localSolverRequests: requests.length, screeningOnly: state.snapshot.recommendation === null, draftReopened: true, originalUnchanged: hash(sourcePath) === originalHash, evidenceDir }));
  } catch (error) { console.error(error.stack || error, log); process.exitCode = 1; }
  finally { if (browser) await browser.close(); if (server.listening) await close(); if (optimizer.exitCode === null) optimizer.kill('SIGTERM'); fs.rmSync(temp, { recursive: true, force: true }); }
})();
