'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const Design=require('../supply-chain-design-v19.js');
const Joint=require('../supply-chain-joint-v19.js');
const V5=require('../supply-chain-v5-results-v19.js');
const period='P1';
const road=(a,b,km)=>({fromNodeId:a,toNodeId:b,distanceKm:km,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_TEST',observedAt:'2026-09-28',strategy:'TEST'});
const input={studyId:'V82-QUANTITY',name:'Synthetic quantity',classification:'SYNTHETIC_TEST',currency:'CNY',coordinateUse:'UNCONFIRMED',costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'},nodes:[{nodeId:'S',role:'SUPPLIER'},{nodeId:'W',role:'DC',capacityByPeriod:{P1:10.123456}},{nodeId:'C',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'W',period,quantity:10.123456,unit:'m3'}],observedInbound:[{flowId:'I',fromNodeId:'S',toNodeId:'W',period,quantity:10.123456,unit:'m3'}],distanceRows:[road('S','W',5),road('W','C',3)],rates:[]};
const study=Design.createStudy(input),scenario={scenarioId:'SYNTHETIC',analysisScope:'FULL_CHAIN',type:'NETWORK_CANDIDATE',objective:'VOLUME_KM',distanceBasis:'VERIFIED_ROAD',facilityCounts:[1],sourceMode:'FREE',supplierTotalMode:'ADJUSTABLE',capacityPolicy:'UNBOUNDED_SCREENING',homogeneousDemandConfirmed:true,allowAllSupplierSiteEdgesConfirmed:true,timeLimitSeconds:5,maxCandidates:1};
const request=Joint.buildRequest(study,scenario);assert.equal(request.payload.schemaVersion,'stct-supply-chain-joint-request-v2');assert.equal(request.payload.quantityScale,1000000);
const py='import json,sys,ortools;from ortools.sat.python import cp_model;from supply_chain_joint_v19 import solve_joint;print(json.dumps(solve_joint(json.load(sys.stdin),cp_model,ortools.__version__)))';
const run=spawnSync('python3',['-c',py],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(request.payload),encoding:'utf8',timeout:30000});assert.equal(run.status,0,run.stderr);const response=JSON.parse(run.stdout),verified=Joint.verify(study,scenario,request,response);assert.equal(response.engine.quantityPrecision,0.000001);assert.equal(verified.length,1);assert.equal(verified[0].sourceFlows[0].quantity,10.123456);const result=V5.fromVerified(study,scenario,request,verified[0],1);assert.equal(result.solver.quantityPrecision,0.000001);assert.equal(result.capacityStatus,'PASS');
const wrong=structuredClone(response);wrong.engine.quantityPrecision=0.0001;assert.throws(()=>Joint.verify(study,scenario,request,wrong),{code:'SUPPLY_JOINT_RESPONSE_MISMATCH'});
const tiny=Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity:0.0000001}]});assert.throws(()=>Joint.buildRequest(tiny,scenario),{code:'SUPPLY_JOINT_QUANTITY_PRECISION'});
const lossy=Joint.previewQuantities(tiny,scenario);assert.equal(lossy.canRun,false);assert.equal(lossy.lossyPreview.status,'NOT_APPLIED');assert.equal(lossy.lossyPreview.affectedBusinessRows,1);assert.equal(lossy.lossyPreview.rows[0].original,0.0000001);assert.equal(lossy.lossyPreview.rows[0].suggested,0);assert.equal(lossy.lossyPreview.periods[0].difference,-0.0000001);
const unsafeCapacity=Joint.previewQuantities(study,{...scenario,capacityByPeriod:{W:{P1:0.0000001}}});assert.equal(unsafeCapacity.canRun,false);assert.equal(unsafeCapacity.lossyPreview.affectedConstraints,1);assert.equal(unsafeCapacity.lossyPreview.constraints[0].kind,'SCENARIO_CAPACITY');
const over=Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity:10000000.123456}]});assert.throws(()=>Joint.buildRequest(over,scenario),{code:'SUPPLY_JOINT_VOLUME_LIMIT'});
const hugeDistance=Design.createStudy({...input,distanceRows:[road('S','W',1e12),road('W','C',3)]});assert.throws(()=>Joint.buildRequest(hugeDistance,scenario),{code:'SUPPLY_JOINT_OBJECTIVE_RANGE'});
function nativeStatus(studyValue,conditions){const prepared=Joint.buildRequest(studyValue,conditions),executed=spawnSync('python3',['-c',py],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(prepared.payload),encoding:'utf8',timeout:30000});assert.equal(executed.status,0,executed.stderr);return JSON.parse(executed.stdout).results[0].status;}
const balanced=Design.createStudy({...input,periodDemand:[0.33335,0.33335,0.33330].map((quantity,index)=>({...input.periodDemand[0],demandId:`D${index}`,quantity})),observedInbound:[{...input.observedInbound[0],quantity:1}],nodes:input.nodes.map(row=>row.nodeId==='W'?{...row,capacityByPeriod:{P1:1}}:row)});
assert.equal(nativeStatus(balanced,{...scenario,supplierTotalMode:'FIXED_OBSERVED'}),'OPTIMAL');
const capacityConflict=Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity:0.00006}],observedInbound:[{...input.observedInbound[0],quantity:0.00006}],nodes:input.nodes.map(row=>row.nodeId==='W'?{...row,capacityByPeriod:{P1:0.00005}}:row)});
assert.equal(nativeStatus(capacityConflict,scenario),'INFEASIBLE');
const fixedSupplyConflict=Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity:11}],observedInbound:[{...input.observedInbound[0],quantity:10}],nodes:input.nodes.map(row=>row.nodeId==='W'?{...row,capacityByPeriod:{P1:20}}:row)});
assert.equal(nativeStatus(fixedSupplyConflict,{...scenario,supplierTotalMode:'FIXED_OBSERVED'}),'INFEASIBLE');
const zero=Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity:0}],observedInbound:[{...input.observedInbound[0],quantity:0}]});
assert.equal(Joint.previewQuantities(zero,scenario).reason,'SUPPLY_JOINT_ZERO_DEMAND');
assert.throws(()=>Joint.buildRequest(zero,scenario),{code:'SUPPLY_JOINT_ZERO_DEMAND'});
for(const quantity of [-1,Infinity,'invalid'])assert.throws(()=>Design.createStudy({...input,periodDemand:[{...input.periodDemand[0],quantity}]}),{code:'SUPPLY_QUANTITY_INVALID'});
const frozen=Design.createStudy({...input,nodes:[...input.nodes.map(row=>row.nodeId==='W'?{...row,capacityByPeriod:{P1:5}}:row),{nodeId:'X',role:'EXTERNAL'}],observedInbound:[{...input.observedInbound[0],quantity:1},{flowId:'UNKNOWN',fromNodeId:'X',toNodeId:'W',period,quantity:10,unit:'m3'}]});
assert.equal(nativeStatus(frozen,{...scenario,analysisScope:'UPSTREAM_ONLY',supplierTotalMode:'FIXED_OBSERVED'}),'INFEASIBLE');
console.log(JSON.stringify({suite:'V82_QUANTITY',status:'PASS',scale:request.payload.quantityScale,precision:response.engine.quantityPrecision,verified:verified.length,balanced:'OPTIMAL',capacityConflict:'INFEASIBLE',fixedSupplyConflict:'INFEASIBLE',frozenUnknownSourceConflict:'INFEASIBLE'}));
