'use strict';
const assert=require('node:assert/strict'),Intake=require('../platform-import-session-v19.js'),Facility=require('../facility-location-mvp1-v19.js'),XLSX=require('../vendor/xlsx/xlsx.full.min.js');
const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['需求编号','需求名称','经度','纬度','物量'],['D1','Alpha',120,30,1.25]]),'需求点');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['候选仓编号','仓库名称','经度','纬度','固定费用','处理费率','处理能力'],['S1','Harbor',120,30,10,1,100]]),'候选仓库');
(async()=>{const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),session=await Intake.readFiles([{name:'facility.xlsx',size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)}]);const settings={confirmed:true,coordinateSystem:'WGS84',classification:'SYNTHETIC',observationPeriod:'MONTH',basis:'volume',volumeUnit:'m3',currency:'CNY',costPeriod:'MONTH',transportRate:1,siteCount:1};
assert.throws(()=>Intake.facilityStudy(session,{...settings,observationPeriod:'YEAR'}),{code:'FACILITY_PERIOD_CONVERSION_UNSUPPORTED'});assert.deepEqual(session.tables.map(t=>t.kind),['facilityDemands','facilitySites']);assert.throws(()=>Intake.facilityStudy(session,{...settings,confirmed:false}),{code:'FACILITY_ASSUMPTION_CONFIRM_REQUIRED'});assert.throws(()=>Intake.facilityStudy(session,{...settings,transportRate:''}),{code:'FACILITY_IMPORT_VALUE_INVALID'});
const value=Intake.facilityStudy(session,settings),study=Facility.normalizeStudy(value),matrix=Facility.buildMatrix(study);assert.equal(study.demands[0].demand.volume,1.25);assert.equal(study.sites[0].fixedCost,10);assert.equal(study.sites[0].handlingCostPerUnit,1);assert.equal(study.assumptions.factor,1);assert.equal(study.sourceRefs[0].sourceRows[0].rowNumber,2);assert.equal(matrix.rows.length,1);assert.equal(Facility.preflight(study,matrix).status,'PASS');
const missing=structuredClone(session);missing.tables[1].records[0]['固定费用']='';assert.throws(()=>Intake.facilityStudy(missing,settings),{code:'FACILITY_IMPORT_VALUE_INVALID'});const blank=structuredClone(session);blank.tables[0].records[0]['经度']='';assert.throws(()=>Intake.facilityStudy(blank,settings),{code:'FACILITY_IMPORT_COORDINATE_INVALID'});for(const raw of [' ', '\t', null, false, true, []]){
 for(const [table,field,code]of [[0,'经度','FACILITY_IMPORT_COORDINATE_INVALID'],[1,'固定费用','FACILITY_IMPORT_VALUE_INVALID'],[1,'处理费率','FACILITY_IMPORT_VALUE_INVALID'],[0,'物量','FACILITY_IMPORT_VALUE_INVALID']]){const invalid=structuredClone(session);invalid.tables[table].records[0][field]=raw;assert.throws(()=>Intake.facilityStudy(invalid,settings),{code},`${field}: ${JSON.stringify(raw)}`);}
}
const unknown=structuredClone(session);unknown.tables[1].records[0]['处理能力']=' ';assert.deepEqual(Intake.facilityStudy(unknown,settings).sites[0].capacity,{});
const zero=structuredClone(session);zero.tables[1].records[0]['固定费用']=0;assert.equal(Intake.facilityStudy(zero,settings).sites[0].fixedCost,0);
assert.throws(()=>Intake.facilityStudy(session,{...settings,transportRate:' '}),{code:'FACILITY_IMPORT_VALUE_INVALID'});
console.log(JSON.stringify({status:'PASS',method:'PRODUCTION_FACILITY_ADAPTER_AND_CONTRACT_NO_SOLVER',preservedSource:true,unknownCostsBlocked:true,explicitAssumptions:true}));})().catch(e=>{console.error(e);process.exitCode=1});
