'use strict';
const assert=require('node:assert/strict');
const Road=require('../local-road-client-v86.js'),Controller=require('../supply-chain-controller-v19.js');
const response=body=>({ok:true,json:async()=>body});
const ok={code:'Ok',routes:[{distance:12000,duration:900}],waypoints:[{location:[110,30],distance:0},{location:[111,30],distance:0}]};
const study=id=>({studyId:id,coordinateUse:'ASSUMED_WGS84_SCREENING',nodes:[{nodeId:'W',role:'DC',coordinate:[110,30]},{nodeId:'C',role:'CUSTOMER',coordinate:[111,30]}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'W',period:'P',quantity:1,unit:'m3'}]});
const testResults=[];
async function test(name,run){await run();testResults.push({name,status:'PASS',kind:'ISOLATED_REQUEST_FAULT_INJECTION'});}
(async()=>{
  await test('engine success is estimated with provenance',async()=>{let url,init;const r=await Road.route([[110,30],[111,30]],{coordinateUse:'WGS84',fetch:async(u,i)=>{url=u;init=i;return response(ok)}});assert.equal(r.quality,'ESTIMATED_ROAD');assert.equal(r.distanceKm,12);assert.equal(init.redirect,'error');assert.ok(url.startsWith('http://127.0.0.1:5001/'));assert.equal(r.evidence.truckRestrictions,'NOT_VERIFIED');});
  for(const [name,body,code] of [['negative duration',{...ok,routes:[{distance:10,duration:-1}]},'ROAD_METRIC_INVALID'],['unreachable',{...ok,code:'NoRoute'},'ROAD_UNREACHABLE'],['missing snaps',{...ok,waypoints:[]},'ROAD_SNAP_EVIDENCE_MISSING'],['snap too far',{...ok,waypoints:[ok.waypoints[0],{location:[111,30],distance:1001}]},'ROAD_SNAP_LIMIT_EXCEEDED']])await test(name,()=>assert.rejects(Road.route([[110,30],[111,30]],{coordinateUse:'WGS84',fetch:async()=>response(body)}),{code}));
  await test('unknown CRS and public endpoint rejected before fetch',async()=>{let called=0;const fetch=()=>{called++;};await assert.rejects(Road.route([[110,30],[111,30]],{fetch}),{code:'ROAD_COORDINATE_SYSTEM_UNCONFIRMED'});await assert.rejects(Road.route([[110,30],[111,30]],{fetch,coordinateUse:'WGS84',localRoadEndpoint:'https://router.project-osrm.org'}),{code:'ROAD_LOCAL_ENDPOINT_REQUIRED'});assert.equal(called,0);});
  await test('remote snapped location cannot hide behind reported zero offset',()=>assert.rejects(Road.route([[110,30],[111,30]],{coordinateUse:'WGS84',fetch:async()=>response({...ok,waypoints:[ok.waypoints[0],{location:[112,30],distance:0}]})}),{code:'ROAD_SNAP_LIMIT_EXCEEDED'}));
  await test('request timeout aborts even uncooperative request',async()=>{let signal;await assert.rejects(Road.route([[110,30],[111,30]],{coordinateUse:'WGS84',roadRequestTimeoutMs:15,fetch:async(u,i)=>{signal=i.signal;return new Promise(()=>{})}}),{code:'ROAD_REQUEST_TIMEOUT'});assert.equal(signal.aborted,true);});
  await test('A late response never changes B',async()=>{let resolve,signal;const c=Controller.createController({fetch:(u,i)=>{signal=i.signal;return new Promise(r=>{resolve=r})}});c.loadStudy(study('A'));const pending=c.generateRoadDistances();c.loadStudy(study('B'));assert.equal(signal.aborted,true);resolve(response(ok));await assert.rejects(pending,e=>['ROAD_CANCELLED','SUPPLY_ROAD_OBSOLETE'].includes(e.code));assert.equal(c.snapshot().study.studyId,'B');assert.equal(c.snapshot().study.distanceRows.length,0);});
  await test('same ID edited coordinates reject old import preview',async()=>{const c=Controller.createController();c.loadStudy(study('A'));const token=c.inputToken();c.updateStudy({nodes:study('A').nodes.map(n=>n.nodeId==='C'?{...n,coordinate:[112,30]}:n)});assert.throws(()=>c.commitDistances([],token),{code:'SUPPLY_ROAD_OBSOLETE'});});
  await test('explicit cancel aborts and leaves inputs untouched',async()=>{let signal;const c=Controller.createController({fetch:(u,i)=>{signal=i.signal;return new Promise(()=>{})}});c.loadStudy(study('A'));const hash=c.snapshot().study.inputHash,pending=c.generateRoadDistances();c.cancelRoad();await assert.rejects(pending,{code:'ROAD_CANCELLED'});assert.equal(signal.aborted,true);assert.equal(c.snapshot().study.inputHash,hash);});
  await test('whole budget bounded independent of request timeout',async()=>{const r=await Road.matrix(study('A'),[[study('A').nodes[0],study('A').nodes[1]]],{roadBudgetMs:15,roadRequestTimeoutMs:10000,fetch:()=>new Promise(()=>{})});assert.equal(r.status,'PARTIAL_BUDGET_EXPIRED');assert.ok(r.elapsedMs<1000);assert.equal(r.rows.length,0);});
  console.log(JSON.stringify(testResults,null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
