'use strict';
// KEEP: focused public import UI/controller contract; no browser, solver, service or persisted business data.
const assert=require('node:assert/strict'),Intake=require('../platform-import-session-v19.js'),SupplyImport=require('../supply-chain-import-v19.js'),Facility=require('../facility-location-mvp1-v19.js'),Context=require('../platform-study-context-v8.js'),Directory=require('../platform-service-directory-v8.js'),Settings=require('../platform-settings-v19.js'),Kinds=require('../platform-study-kind-registry-v8.js'),XLSX=require('../vendor/xlsx/xlsx.full.min.js');
const current=Facility.normalizeStudy({studyId:'KEEP-EXISTING',name:'Protected synthetic study',coordinateSystem:'WGS84',dataClassification:'SYNTHETIC',observationPeriod:'MONTH',demands:[{demandId:'D',coordinate:[120,30],demand:{volume:1}}],sites:[{siteId:'S',coordinate:[120,30],fixedCost:1,handlingCostPerUnit:1}],options:{transportBasis:'volume',transportCostPerUnitKm:1,currency:'CNY',costPeriod:'MONTH',facilityCounts:[1]}});
const studyContext=Context.createContext({studyKind:'FACILITY',studyId:current.studyId,inputHash:current.studyHash,classification:'SYNTHETIC'}),handlers={},downloads=[],blobs=new Map(),navigation=[];
let capturedFacility,focused=null,scrolled=null,confirm=true;
let catalogRows=[],supplyState={};
const repository={async list(store){return store==='pointers'?catalogRows:[];},async read(){return null;},diagnostics(){return{};},close(){}};
global.STCTPlatformV19={importSession:Intake,tabularIntake:Intake.tabularIntake,businessNumber:Intake.businessNumber,supplyChainImport:SupplyImport,facilityLocationMvp1:Facility,studyContext:Context,serviceDirectory:Directory,settingsRegistry:Settings,supplyChainController:{createController:()=>({viewState:()=>supplyState})},studyService:{createService:()=>({status:()=> 'NOT_SAVED'})},operationalValidationBridge:{create:()=>({subscribe:()=>()=>{},snapshot:()=>({}),exit(){}})},studyKindRegistry:Kinds};
global.XLSX=XLSX;
const originalCreate=URL.createObjectURL,originalRevoke=URL.revokeObjectURL,originalTimer=global.setTimeout;
URL.createObjectURL=blob=>{const url=`blob:focused-test-${blobs.size}`;blobs.set(url,blob);return url;};URL.revokeObjectURL=()=>{};
global.setTimeout=(fn,ms,...args)=>{const timer=originalTimer(fn,ms,...args);if(ms===30000)timer.unref();return timer;};
global.document={activeElement:null,body:{append(){}},createElement:()=>({click(){downloads.push({name:this.download,blob:blobs.get(this.href)});},remove(){}})};
function node(dataset,value,files){return {dataset,value,files,matches(selector){const attr=selector.match(/^\[data-([^\]]+)\]$/)?.[1],key=attr?.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase());return key!==undefined&&Object.hasOwn(dataset,key);},closest(){return this;},focus(){focused=this;global.document.activeElement=this;},scrollIntoView(){scrolled=this;}};}
const mappingNodes=()=>[...target.innerHTML.matchAll(/<select data-p5-(map|kind)="([^"]+)"(?: data-p5-header="([^"]+)")?/g)].map(match=>node(match[1]==='map'?{p5Map:match[2],p5Header:match[3]}:{p5Kind:match[2]}));
const mappingPanel={open:false};
const target={innerHTML:'',contains:()=>false,querySelector(selector){if(selector==='[data-p5-confirm]')return{checked:confirm};if(selector==='[data-p5-mapping]')return mappingPanel;return null;},querySelectorAll(selector){return selector==='[data-p5-map],[data-p5-kind]'?mappingNodes():[];}};
const adapter={hasStudy:()=>false,setFacilityController(value){capturedFacility=value;},hydrateFacility(){}};
const file=(name,value)=>{const bytes=typeof value==='string'?Buffer.from(value):Buffer.from(value);return{name,size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length),text:async()=>bytes.toString('utf8')};};
const change=(dataset,value,files)=>handlers.change({target:node(dataset,value,files)});
const click=(action,id='')=>handlers.click({target:node({p5Action:action,p5Id:String(id)})});
const unchanged=()=>{assert.equal(studyContext.snapshot().current.studyId,current.studyId);assert.equal(capturedFacility.snapshot().study.studyHash,current.studyHash);};
const catalogEntries=()=>[...target.innerHTML.matchAll(/<tr data-p5-entry="([^"]+)">([\s\S]*?)<\/tr>/g)].map(match=>({id:match[1],html:match[2]}));
const catalogIds=()=>catalogEntries().map(row=>row.id);
function visiblePreviewCancel(){const actions=target.innerHTML.match(/<div class="p5-toolbar" data-p5-preview-actions>([\s\S]*?)<\/div>/)?.[1];assert.ok(actions,'A pending preview exposes actions outside the collapsed import details');assert.match(actions,/<button[^>]*data-p5-action="cancel"[^>]*>取消<\/button>/);assert.doesNotMatch(actions,/<button[^>]*\sdisabled/);assert.ok(target.innerHTML.indexOf('data-p5-preview-actions')<target.innerHTML.indexOf('<details class="p5-import-context"'),'Preview cancel is outside import details');}
(async()=>{
 const ui=require('../platform-services-v19.js').create({repository,studyContext,designAdapter:adapter,commandAdapter:{}});await ui.ready;capturedFacility.load(current);
 ui.mount({logicalPath:'/platform/data',scope:{listen(_target,event,handler){handlers[event]=handler;}}},{target,controller:{navigate(path){navigation.push(path);}},snapshot:{locale:'zh',workspaceStates:{PLATFORM:{previousBusinessWorkspace:'DESIGN'}}}});await new Promise(resolve=>originalTimer(resolve,0));
 await change({v8Kind:''},'NETWORK_ORDERS');
 let sourceReads=0;const csv=file('orders.csv','订单编号;经度;纬度;物量;custom.path\nO1;120;30;oops;keep-original');const read=csv.arrayBuffer;csv.arrayBuffer=async()=>{sourceReads++;return read();};
 await change({p5Upload:''},undefined,[csv]);assert.equal(sourceReads,1);assert.match(target.innerHTML,/CSV 分隔符/);assert.match(target.innerHTML,/订单编号 · 必填/);assert.match(target.innerHTML,/需求体积 · 必填/);assert.match(target.innerHTML,/<optgroup label="高级字段路径">[\s\S]*custom.path/);
 await change({p5Field:'observationPeriod'},'MONTH');await click('validate');assert.match(target.innerHTML,/需求体积<\/td>/);assert.match(target.innerHTML,/&quot;oops&quot;/);assert.doesNotMatch(target.innerHTML,/>NaN</);assert.match(target.innerHTML,/<td>O1<\/td><td>—<\/td><td>—<\/td>/);assert.match(target.innerHTML,/物量为空、不是数值或为负数/);assert.match(target.innerHTML,/orders.csv \/ Sheet1:2/);assert.match(target.innerHTML,/data-p5-action="issue-map"/);assert.match(target.innerHTML,/<span>1 待处理记录<\/span>/);assert.doesNotMatch(target.innerHTML,/<span>1 有效<\/span>/);
 for(const [locale,label] of [['zh','需修正数据'],['en','Data needs correction'],['ja','データの修正が必要']]){ui.sync({locale});assert.ok(target.innerHTML.includes(`<span data-p5-validation-status data-state="BLOCKED" title="BLOCKED">${label}</span>`));}ui.sync({locale:'zh'});
 await click('issue-map',0);assert.equal(mappingPanel.open,true);assert.equal(focused.dataset.p5Header,'物量');assert.equal(scrolled,focused);unchanged();
 await change({p5CsvDelimiter:''},',');await click('csv-reparse');assert.equal(sourceReads,1);assert.match(target.innerHTML,/订单编号;经度;纬度;物量;custom.path/);
 await change({p5CsvDelimiter:''},';');await click('csv-reparse');assert.equal(sourceReads,1);assert.match(target.innerHTML,/data-p5-header="物量"/);assert.match(target.innerHTML,/oops/);assert.doesNotMatch(target.innerHTML,/data-p5-validation-status/);unchanged();
 await click('cancel');assert.doesNotMatch(target.innerHTML,/data-p5-map=/);assert.doesNotMatch(target.innerHTML,/p5-csv-preview/);unchanged();
 await change({v8Kind:''},'AUTO');await change({p5Upload:''},undefined,[file('orders.csv','订单编号,经度,纬度,物量\nO1,120,30,1')]);visiblePreviewCancel();await click('cancel');unchanged();
 await change({v8Kind:''},'FACILITY');assert.match(target.innerHTML,/accept=".xlsx,.json" data-p5-upload/);assert.match(target.innerHTML,/下载设施 JSON 样例（合成）/);assert.match(target.innerHTML,/下载双表 Excel 模板（合成）/);
 await click('facility-json-template');const native=JSON.parse(await downloads.at(-1).blob.text());assert.equal(native.dataClassification,'SYNTHETIC');assert.match(native.assumptions.exampleNotice,/Fully synthetic/);assert.equal(Facility.normalizeStudy(native).studyHash,native.studyHash);
 await click('facility-excel-template');const excel=await downloads.at(-1).blob.arrayBuffer();assert.deepEqual(XLSX.read(excel,{type:'array'}).SheetNames,['需求点','候选仓库']);const session=await Intake.readFiles([file('sample.xlsx',Buffer.from(excel))]);assert.deepEqual(session.tables.map(table=>table.kind),['facilityDemands','facilitySites']);const sample=Intake.facilityStudy(session,{confirmed:true,coordinateSystem:'WGS84',classification:'SYNTHETIC',observationPeriod:'MONTH',costPeriod:'MONTH',basis:'volume',volumeUnit:'m3',currency:'CNY',transportRate:1,siteCount:1});assert.equal(Facility.preflight(Facility.normalizeStudy(sample),Facility.buildMatrix(sample)).status,'PASS');unchanged();
 await change({p5Upload:''},undefined,[file('sample.json',JSON.stringify(native))]);assert.match(target.innerHTML,/设施研究文件预览/);assert.match(target.innerHTML,/data-p5-action="adopt-facility"/);visiblePreviewCancel();assert.equal((target.innerHTML.match(/data-p5-action="cancel"/g)||[]).length,1);unchanged();assert.deepEqual(navigation,[]);
 await click('cancel');assert.doesNotMatch(target.innerHTML,/设施研究文件预览/);unchanged();
 await change({p5Upload:''},undefined,[file('sample.json',JSON.stringify(native))]);await click('adopt-facility');assert.equal(studyContext.snapshot().current.studyId,native.studyId);assert.equal(capturedFacility.snapshot().study.studyHash,native.studyHash);assert.deepEqual(navigation,['/design/facility-location']);
 catalogRows=[['SUPPLY_CHAIN_STUDY','COMPLETE','PASS'],['FACILITY_STUDY','COMPLETE','NOT_RUN'],['DESIGN_STUDY','DRAFT','FAIL'],['SUPPLY_CHAIN_STUDY','COMPLETE',undefined],['DESIGN_STUDY',undefined,'PASS'],['FACILITY_STUDY','COMPLETE','UNVERIFIABLE'],['FACILITY_STUDY','COMPLETE','PASS']].map(([type,status,verification],i)=>({id:`CATALOG-${i}`,type,name:`Synthetic catalog ${i}`,scope:'DESIGN',status,verification,archived:i===6}));const originalCatalog=structuredClone(catalogRows);
 supplyState={study:{studyId:'DISPLAY-SUPPLY',name:'Synthetic display fixture',inputHash:'SYNTHETIC-DISPLAY-HASH'},snapshot:{}};studyContext.select({studyKind:'SUPPLY_CHAIN_PERIOD',studyId:'DISPLAY-SUPPLY'});
 ui.mount({logicalPath:'/platform/scenarios',scope:{listen(_target,event,handler){handlers[event]=handler;}}},{target,controller:{navigate(){}},snapshot:{locale:'zh',workspaceStates:{PLATFORM:{previousBusinessWorkspace:'DESIGN'}}}});await new Promise(resolve=>originalTimer(resolve,0));
 for(const [locale,labels]of [['zh',['结果与当前方案一致','全部','验证通过','尚未执行','已归档','设施选址研究']],['en',['Result matches the current portfolio','All','Verified','Not run','Archived','Facility location study']],['ja',['現在の案と一致','すべて','検証済み','未実行','アーカイブ済み','施設配置研究']]]){
  ui.sync({locale,workspaceStates:{PLATFORM:{previousBusinessWorkspace:'DESIGN'}}});assert.ok(target.innerHTML.includes(`<p data-p5-save-state data-state="CURRENT" title="CURRENT">${labels[0]}</p>`));for(const [value,label]of [['ALL',labels[1]],['PASS',labels[2]],['NOT_RUN',labels[3]],['ARCHIVED',labels[4]],['FACILITY_STUDY',labels[5]]])assert.ok(target.innerHTML.includes(`<option value="${value}"${value==='ALL'?' selected':''}>${label}</option>`));
  const [heading,complete,draft,saved,pass,notRun,fail,unknown,unverifiable]={zh:['独立验证','已完成','草稿','已保存','通过','未执行','未通过','验证状态未提供','无法独立验证'],en:['Independent verification','Completed','Draft','Saved','Passed','Not run','Failed','Verification status not provided','Cannot independently verify'],ja:['独立検証','完了','下書き','保存済み','合格','未実行','不合格','検証状況未提供','独立検証不可']}[locale];assert.ok(target.innerHTML.includes(`<th>${heading}</th>`));assert.deepEqual(catalogIds(),['CATALOG-0','CATALOG-1','CATALOG-2','CATALOG-3','CATALOG-4','CATALOG-5']);
  for(const [id,status,token,label]of [['CATALOG-0',complete,'PASS',pass],['CATALOG-1',complete,'NOT_RUN',notRun],['CATALOG-2',draft,'FAIL',fail],['CATALOG-3',complete,'UNKNOWN',unknown],['CATALOG-4',saved,'PASS',pass],['CATALOG-5',complete,'UNVERIFIABLE',unverifiable]])assert.ok(catalogEntries().find(row=>row.id===id).html.includes(`<td>${status}</td><td data-p5-verification="${token}" title="${token}">${label}</td>`));
  await change({p5Field:'statusFilter'},'PASS');assert.deepEqual(catalogIds(),['CATALOG-0','CATALOG-4']);assert.ok(target.innerHTML.includes('<option value="PASS" selected>'));await change({p5Field:'statusFilter'},'NOT_RUN');assert.deepEqual(catalogIds(),['CATALOG-1']);assert.ok(catalogEntries()[0].html.includes(`<td>${complete}</td><td data-p5-verification="NOT_RUN" title="NOT_RUN">${notRun}</td>`));await change({p5Field:'statusFilter'},'ALL');
 }
 supplyState.snapshot=null;supplyState.staleResult={};ui.sync({locale:'zh'});assert.match(target.innerHTML,/data-state="STALE" title="STALE">需要重算<\/p>/);supplyState.staleResult=null;ui.sync({locale:'zh'});assert.match(target.innerHTML,/data-state="DRAFT" title="DRAFT">草稿<\/p>/);
 await change({p5Field:'typeFilter'},'FACILITY_STUDY');assert.deepEqual(catalogIds(),['CATALOG-1','CATALOG-5']);await change({p5Field:'typeFilter'},'ALL');await handlers.change({target:{...node({p5Archives:''}),checked:true}});await change({p5Field:'statusFilter'},'ARCHIVED');assert.deepEqual(catalogIds(),['CATALOG-6']);assert.ok(catalogEntries()[0].html.includes('<td>已归档</td><td data-p5-verification="PASS" title="PASS">通过</td>'));assert.deepEqual(catalogRows,originalCatalog);
 ui.destroy();console.log(JSON.stringify({status:'PASS',method:'PRODUCTION_PUBLIC_UI_EVENTS_WITH_REAL_XLSX_CSV_FACILITY_ADAPTER_NO_BROWSER',checks:['required-by-table','advanced-path-group','original-value-reason-source-row','issue-focus','csv-cached-byte-reparse','narrow-facility-accept','valid-synthetic-json-xlsx-downloads','native-facility-preview-before-adoption','cancel-retains-active-study','catalog-business-status-and-filter-labels-preserve-tokens','real-catalog-lifecycle-independent-verification-and-filtered-ids']}));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{URL.createObjectURL=originalCreate;URL.revokeObjectURL=originalRevoke;global.setTimeout=originalTimer;delete global.document;});
