'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('../supply-chain-design-v19.js'),R=require('../supply-chain-report-v19.js'),W=require('../supply-chain-report-workspace-v01.js'),X=require('../vendor/xlsx/xlsx.full.min.js');
const study=D.createStudy({studyId:'EXCEL-SYNTHETIC',name:'中文供应链研究',classification:'SYNTHETIC',nodes:[{nodeId:'001',name:'原仓',role:'DC'},{nodeId:'002',name:'新仓',role:'DC'},{nodeId:'0003',name:'=HYPERLINK("https://invalid.test")',role:'CUSTOMER',address:'中文地址,甲\n乙'}],periodDemand:[{demandId:'00001',customerNodeId:'0003',currentSiteId:'001',period:'2026-01',quantity:0.123456,unit:'m3'}],distanceRows:[['001',10],['002',5]].map(([fromNodeId,distanceKm])=>({fromNodeId,toNodeId:'0003',distanceKm,unit:'km',quality:'VERIFIED_ROAD',source:'中文有向矩阵',observedAt:'2026-10-08',strategy:'SYNTHETIC'}))});
const config={type:'NETWORK_CANDIDATE',objective:'VOLUME_KM',objectiveScope:'OUTBOUND_ONLY',facilityCounts:[1],distanceBasis:'VERIFIED_ROAD'},base=D.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),candidate=D.evaluatePortfolio(study,{...config,scenarioId:'新方案',selectedSiteIds:['002']},[{demandId:'00001',siteNodeId:'002'}]),snapshot=R.createSnapshot(study,base,[candidate],[],config),state={study,snapshot},before=JSON.stringify(state);
for(const locale of ['zh','en','ja']){
 const bytes=W.toExcel(state,X,locale);assert.equal(Buffer.from(bytes).subarray(0,2).toString(),'PK');const book=X.read(bytes,{type:'array',cellNF:true});assert.equal(book.SheetNames.length,4);
 const sheet=book.Sheets[book.SheetNames[2]],rows=X.utils.sheet_to_json(sheet,{header:1,defval:null});assert.equal(rows.length,2);const cell=(heading)=>sheet[X.utils.encode_cell({r:1,c:rows[0].findIndex(h=>h.includes(heading))})];
 assert.equal(cell('From ID').v,'002');assert.equal(cell('From ID').t,'s');assert.equal(cell('Demand ID').v,'00001');assert.equal(cell('Demand ID').t,'s');assert.equal(cell('From name').v,'新仓');assert.equal(cell('To name').v,'=HYPERLINK("https://invalid.test")');assert.equal(cell('To name').t,'s');assert.equal(cell('To name').f,undefined);assert.equal(cell('To address').v,'中文地址,甲\n乙');assert.equal(cell('Quantity').v,.123456);assert.equal(cell('Quantity').z,'0.0');assert.equal(cell('Distance km').v,5);assert.equal(cell('Distance source').v,'中文有向矩阵');assert.equal(cell('Observed at').v,'2026-10-08');assert.equal(cell('Snapshot hash').v,snapshot.snapshotHash);assert.equal(rows[1][rows[0].findIndex(h=>h.endsWith(' Cost'))],null,'Unknown cost remains blank, not zero');
 for(const name of book.SheetNames)for(const [key,c]of Object.entries(book.Sheets[name]))if(!key.startsWith('!'))assert.equal(c.f,undefined,'No formula execution from business strings');
 if(process.env.STCT_EXCEL_EVIDENCE)fs.writeFileSync(path.join(process.env.STCT_EXCEL_EVIDENCE,'synthetic-'+locale+'.xlsx'),bytes);
}
assert.equal(JSON.stringify(state),before);assert.throws(()=>W.toExcel({...state,study:D.createStudy({...study,name:'changed'})},X),{code:'SUPPLY_SNAPSHOT_STALE'});
assert.throws(()=>W.toExcel(state,null),{code:'SUPPLY_EXCEL_RUNTIME_UNAVAILABLE'});
const forged=structuredClone(snapshot);forged.rows[0].result.outbound[0].distanceKm=0;forged.snapshotHash=D.hash(Object.fromEntries(Object.entries(forged).filter(([k])=>k!=='snapshotHash')));assert.throws(()=>W.toExcel({study,snapshot:forged},X),{code:'SUPPLY_SNAPSHOT_VERIFICATION_FAILED'});
console.log('PASS native XLSX: Unicode, typed/leading-zero IDs, literal formula text, unknown cost, unchanged precision, ledger distance/provenance, three locales, immutable and stale/forged result protection (module, not Windows Excel)');
