#!/usr/bin/env node
'use strict';
// Public business controls reopen native result packages; no study-state injection or solve.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_MAP_ADVANCED_EVIDENCE,packages=process.env.STCT_MAP_PACKAGES,nonUC=process.env.STCT_NON_UC_PACKAGE;
assert.ok(out&&packages&&nonUC,'Set STCT_MAP_EVIDENCE, STCT_MAP_PACKAGES and STCT_NON_UC_PACKAGE');
fs.mkdirSync(out,{recursive:true});
const hash=value=>crypto.createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
const live=process.env.STCT_MAP_LIVE==='1',liveSmoke=process.env.STCT_SHOWCASE_LIVE_SMOKE==='1';
const packagePath=scope=>path.join(packages,fs.existsSync(path.join(packages,scope+'.package.json'))?scope+'.package.json':({OUTBOUND_ONLY:'uc-outbound',UPSTREAM_ONLY:'uc-upstream',FULL_CHAIN:'uc-full'}[scope]+'.package.json'));
const fixtures={OUTBOUND_ONLY:packagePath('OUTBOUND_ONLY'),UPSTREAM_ONLY:packagePath('UPSTREAM_ONLY'),FULL_CHAIN:packagePath('FULL_CHAIN'),NON_UC:nonUC};
const sourceFiles=()=>['platform-map-runtime-v19.js','platform-map-v19.css','platform-supply-map-v8.js','supply-chain-view-v19.js','index.html',...fs.readdirSync(root).filter(f=>/^platform-map-showcase.*\.js$/.test(f))];
const sourceHashes=()=>Object.fromEntries(sourceFiles().map(f=>[f,hash(fs.readFileSync(path.join(root,f)))]));
const report={status:'RUNNING',tier:'BROWSER_NATIVE_PACKAGE_REOPEN_NO_NEW_SOLVE',method:'Home → business entry → native package file input → visible map controls. Read-only model, layer and diagnostic inspection.',basemap:live?'Live OpenFreeMap':'Explicit neutral offline style fixture; actual local MapLibre layers and SVG rendering.',checks:[],pageErrors:[],consoleErrors:[],fixtures:Object.fromEntries(Object.entries(fixtures).map(([key,file])=>[key,{file,sha256:hash(fs.readFileSync(file))}])),sourceSHA256Before:sourceHashes(),testSHA256:hash(fs.readFileSync(__filename))};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,data)=>error?res.writeHead(404).end():res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream'}).end(data));});
let browser,context,page,base;
const host=()=>page.locator('.p7-map-workspace:visible');
const diag=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());
const model=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.snapshot());
const supply=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function expose(locator){for(const details of (await locator.locator('xpath=ancestor::details').all()).reverse())if(!await details.evaluate(e=>e.open))await details.locator(':scope > summary').click();}
async function click(selector){const locator=page.locator(selector);await expose(locator);await locator.click();}
async function option(selector,value){const locator=page.locator(selector);await expose(locator);await locator.selectOption(value);}
async function ready(){await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-facilities'));}
async function maps(fn){return page.evaluate(text=>{const maps=(window.__showcaseQAMaps||[]).filter(m=>m.getCanvas().isConnected);return new Function('maps','return ('+text+')(maps)')(maps);},fn.toString());}
async function layerVisibility(){return maps(ms=>{const map=ms.find(m=>m.getSource('p7-supply'));return Object.fromEntries(map.getStyle().layers.filter(l=>l.id.startsWith('p7-supply')).map(l=>[l.id,map.getLayoutProperty(l.id,'visibility')||'visible']));});}
async function phasePaint(){return page.locator('[data-showcase-side]').evaluateAll(es=>Object.fromEntries(['reference','candidate'].map(side=>[side,es.filter(e=>e.dataset.showcaseSide===side).map(e=>Number(e.getAttribute('opacity')))])));}
async function assertWarehousePhase(side){const expected=(await model()).features.filter(f=>f.geometry.type==='Point'&&f.properties.kind==='facility'&&f.properties[side+'Selected']).map(f=>f.properties.entityId).sort(),actual=await page.locator('[data-showcase-warehouse]').evaluateAll(es=>es.filter(e=>Number(e.getAttribute('opacity'))>0).map(e=>e.dataset.showcaseWarehouse).sort());assert.deepEqual(actual,expected,'Presentation warehouse labels follow the active reference/candidate plan');assert.equal(await host().locator('.p7-map-labels').evaluate(e=>getComputedStyle(e).visibility),'hidden','Base warehouse labels must not duplicate or contradict the animated phase');}
async function positions(){return page.locator('[data-showcase-pulse]').evaluateAll(es=>es.map(e=>({id:e.dataset.showcasePulse,cx:e.getAttribute('cx'),cy:e.getAttribute('cy')})));}
async function shot(name){await host().locator('.p7-map-viewport').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,name+'.png')});}
async function persist(){fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(report,null,2));}
async function check(id,fn){const item={id,status:'RUNNING'},start=Date.now();try{item.evidence=await fn();item.status='PASS';}catch(error){item.status='FAIL';item.error=error.stack;await shot(id+'-failure').catch(()=>{});}item.wallMs=Date.now()-start;report.checks.push(item);await persist();console.log(id,item.status);}
async function closeShowcase(){if((await diag()).showcase?.open)await click('[data-showcase-action="close"]');}
async function start(mode){await closeShowcase();await click('[data-p7-showcase="'+mode+'"]');await page.locator('.p7-showcase').waitFor();await page.waitForFunction(mode=>window.STCTPlatformV19.mapRuntime.diagnostics().showcase?.mode===mode,mode);}
async function openStudy(scope,{width=1440,reducedMotion=false,noWebGL=false}={}){
 if(context)await context.close();
 context=await browser.newContext({viewport:{width,height:width===390?844:1000},reducedMotion:reducedMotion?'reduce':'no-preference',acceptDownloads:true});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(!live&&url.hostname==='tiles.openfreemap.org'&&url.pathname.startsWith('/styles/'))return route.fulfill({contentType:'application/json',body:JSON.stringify({version:8,sources:{},layers:[{id:'qa-neutral-basemap',type:'background',paint:{'background-color':url.pathname.includes('dark')?'#101722':'#edf1f7'}}]})});if(['127.0.0.1','localhost'].includes(url.hostname)&&url.pathname.endsWith('/vendor/maplibre/maplibre-gl.js')){const response=await route.fetch();return route.fulfill({response,body:(await response.text())+'\n;(()=>{const RealMap=maplibregl.Map;maplibregl.Map=class ObservedMap extends RealMap{constructor(...args){super(...args);(window.__showcaseQAMaps||=[]).push(this)}}})();'});}return ['127.0.0.1','localhost'].includes(url.hostname)||['blob:','data:'].includes(url.protocol)||live&&url.hostname==='tiles.openfreemap.org'?route.continue():route.abort();});
 page=await context.newPage();page.setDefaultTimeout(18000);page.on('pageerror',e=>report.pageErrors.push({scope,error:e.message}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({scope,text:m.text()});});
 await page.goto(base+(noWebGL?'&noWebGL=1':'')+'#/');if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.getByRole('button',{name:/测算供应链方案/}).click();const input=page.locator('[data-supply-file="study"]');await expose(input);await input.setInputFiles(fixtures[scope]);await page.locator('[data-supply-map-panel]').waitFor();if(!noWebGL)await ready();return JSON.parse(fs.readFileSync(fixtures[scope],'utf8'));
}
(async()=>{try{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}/index.html?forceHeuristic=1`;report.service={pid:process.pid,host:'127.0.0.1',port:server.address().port,optimizerStarted:false};
 browser=await chromium.launch({executablePath:process.env.STCT_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const advanced=async()=>(await diag()).advanced;
 async function exit(){if((await advanced()).active)await click('[data-advanced-close]');}
 async function open(mode){await exit();await click('[data-p7-advanced="'+mode+'"]');await page.locator('.p7-advanced').waitFor();assert.equal((await advanced()).mode,mode);}
 for(const scope of ['FULL_CHAIN','OUTBOUND_ONLY','UPSTREAM_ONLY','NON_UC']){
  await openStudy(scope);const original=hash((await supply()).snapshot);
  await check(scope+'_ARCS_GPU_HOVER_RESTORE',async()=>{const camera=await maps(ms=>{const m=ms.find(m=>m.getSource('p7-supply'));return {pitch:m.getPitch(),bearing:m.getBearing(),center:m.getCenter().toArray(),zoom:m.getZoom()};}),visibility=await layerVisibility();await open('arcs');await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().advanced.arcFrames>0);let d=await advanced();assert.ok(d.arcTriangles>0);assert.ok(d.renderedRelations<=120);assert.ok((await maps(ms=>ms.find(m=>m.getSource('p7-supply')).getPitch()))>30);const anchor=await page.evaluate(()=>{const m=window.__showcaseQAMaps.find(m=>m.getCanvas().isConnected&&m.getSource('p7-supply')),layer=m.getLayer('p7-showcase-advanced').implementation,canvas=m.getCanvas(),box=canvas.getBoundingClientRect();for(const row of layer.rows)for(const i of [8,16,24]){const a=window.STCTPlatformV19.mapAdvanced.screenPoint(row.path[i],layer.state.matrix,canvas.clientWidth,canvas.clientHeight);if(a&&a[0]>10&&a[0]<box.width-10&&a[1]>10&&a[1]<box.height-10&&document.elementFromPoint(box.x+a[0],box.y+a[1])===canvas)return {x:box.x+a[0],y:box.y+a[1],relationId:row.relationId};}return null;});assert.ok(anchor,'At least one visible arc is available for pointer hit-testing');await page.mouse.move(anchor.x,anchor.y);await page.waitForTimeout(100);assert.match(await page.locator('[data-advanced-detail]').innerText(),/→/);await shot(scope+'-arcs');await exit();assert.deepEqual(await layerVisibility(),visibility);assert.equal((await maps(ms=>ms.find(m=>m.getSource('p7-supply')).getPitch())),camera.pitch);assert.ok(!(await diag()).layers.includes('p7-showcase-advanced'));return d;});
  await check(scope+'_DEMAND_COLUMNS',async()=>{await open('columns');if(scope==='UPSTREAM_ONLY'){assert.match(await page.locator('.p7-advanced').innerText(),/没有|No |ありません/);assert.ok(!(await diag()).layers.includes('p7-showcase-advanced'));}else{assert.ok((await advanced()).hexes>0);await page.waitForFunction(()=>{const m=window.__showcaseQAMaps.find(m=>m.getCanvas().isConnected&&m.getSource('p7-supply'));return m&&m.isSourceLoaded('p7-showcase-advanced')&&m.queryRenderedFeatures({layers:['p7-showcase-advanced']}).length>0;});const hex=await maps(ms=>ms.find(m=>m.getSource('p7-supply')).getSource('p7-showcase-advanced')._data.features);const expected=(await model()).features.filter(f=>f.geometry.type==='LineString'&&f.properties.comparison==='candidate'&&decodeURIComponent(f.properties.relationId).startsWith('outbound\0')).reduce((sum,f)=>sum+f.properties.quantity,0);assert.ok(Math.abs(hex.reduce((sum,f)=>sum+f.properties.quantity,0)-expected)<1e-6);assert.ok(hex.every(f=>f.geometry.type==='Polygon'&&f.properties.height>0));await shot(scope+'-columns');}await exit();return {scope};});
  await check(scope+'_NETWORK_ZOOM_AND_MEMBERS',async()=>{await open('network');assert.ok((await advanced()).groups>0);const before=await advanced();const g=page.locator('[data-advanced-group]').first();await g.focus();await page.keyboard.press('Enter');assert.ok((await page.locator('[data-advanced-detail]').innerText()).length>10);await page.waitForTimeout(500);assert.match(await page.locator('[data-advanced-detail]').innerText(),/→/,'Member ledger remains visible after zoom animation');await shot(scope+'-network');const after=await advanced();assert.ok(after.groups>=before.groups);await exit();return {before,after};});
  await check(scope+'_LENS_DRAG_KEYBOARD_CLIP_METRICS',async()=>{await open('lens');assert.equal(await page.locator('[data-advanced-side="reference"]').count(),1);assert.equal(await page.locator('[data-advanced-side="candidate"]').count(),1);const lens=page.locator('.p7-advanced-lens');await lens.focus();const a=(await advanced()).center;await page.keyboard.press('ArrowRight');const b=(await advanced()).center;assert.ok(b[0]>a[0]);const box=await lens.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+12);await page.mouse.down();await page.mouse.move(box.x+box.width/2-40,box.y+35,{steps:5});await page.mouse.up();assert.notDeepEqual((await advanced()).center,b);assert.match(await page.locator('[data-advanced-detail]').innerText(),/变化|Changed|変更/);await shot(scope+'-lens');await page.keyboard.press('Escape');assert.equal((await advanced()).active,false);return {keyboard:true,pointer:true};});
  await check(scope+'_MONTHLY_PLAYBACK_NATIVE_REPAINT',async()=>{await open('playback');await click('[data-advanced-play]');assert.equal((await advanced()).playing,true);await page.waitForTimeout(5400);const d=await advanced();assert.equal(d.active,true);const periodCount=(await model()).relationContext.periods.length;assert.equal(d.playing,periodCount>2);assert.equal(d.periodIndex,Math.min(2,periodCount-1));assert.equal((await model()).provenance.period,d.period);const p=(await model()).relationContext.period;assert.ok(await page.locator('.p7-advanced').isVisible());await shot(scope+'-monthly');if(d.playing)await click('[data-advanced-play]');const paused=await advanced();assert.equal(paused.timerPending,false);await page.waitForTimeout(2800);assert.equal((await advanced()).period,paused.period);await exit();return {d,paused,p};});
  assert.equal(hash((await supply()).snapshot),original,'Visual tools never change native result snapshot');
 }
 await check('EXCLUSIVE_MODES_CYCLES_AND_INPUT_CANCEL',async()=>{await openStudy('FULL_CHAIN');const original=hash((await supply()).snapshot),before=(await diag()).mapEventListeners;for(let i=0;i<3;i++){for(const mode of ['arcs','columns','network','lens','playback']){await open(mode);assert.equal(await page.locator('.p7-advanced').count(),1);await exit();assert.equal(await page.locator('.p7-advanced-overlay,.p7-advanced-lens').count(),0);assert.equal((await advanced()).timerPending,false);}}const activeCounts=counts=>Object.fromEntries(Object.entries(counts).filter(([,count])=>count>0));assert.deepEqual(activeCounts((await diag()).mapEventListeners),activeCounts(before));await open('arcs');await start('pulse');assert.equal((await advanced()).active,false);assert.equal((await diag()).showcase.active,true);await open('network');assert.equal((await diag()).showcase.active,false);await option('[data-supply-compare="leg"]','INBOUND');assert.equal((await advanced()).active,false);await option('[data-supply-compare="leg"]','BOTH');assert.equal(hash((await supply()).snapshot),original);return {cycles:3,modes:5,exclusive:true,changedInputCancels:true};});
 for(const locale of ['zh','en','ja'])await check('MOBILE_390_'+locale,async()=>{await exit();await page.locator('[data-platform-locale]').selectOption(locale);await page.setViewportSize({width:390,height:844});await click('[data-p7-expand]');for(const mode of ['arcs','columns','network','lens','playback']){await open(mode);assert.ok(await page.locator('.p7-advanced').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(mode==='lens')await shot('lens-'+locale+'-390');await exit();}await click('[data-p7-fullscreen-close]');await page.setViewportSize({width:1440,height:1000});return {locale,width:390};});
 await check('REDUCED_MOTION_AND_STYLE_CLEANUP',async()=>{await openStudy('FULL_CHAIN',{reducedMotion:true});await open('playback');assert.equal(await page.locator('[data-advanced-play]').isDisabled(),true);await click('[data-advanced-step="1"]');assert.equal((await advanced()).periodIndex,1);assert.equal((await advanced()).timerPending,false);await exit();await open('arcs');await click('[data-p7-map-theme]');await ready();assert.equal((await advanced()).active,false);assert.ok(!(await diag()).layers.includes('p7-showcase-advanced'));return {manualOnly:true,styleCloses:true};});
 await check('NO_WEBGL',async()=>{await openStudy('NON_UC',{noWebGL:true,width:390});for(const mode of ['arcs','columns','network','lens','playback']){await open(mode);assert.match(await page.locator('.p7-advanced').innerText(),/地图|map|地図/);assert.equal((await advanced()).timerPending,false);await exit();}return {modes:5};});
 report.status=report.checks.every(item=>item.status==='PASS')&&!report.pageErrors.length?'PASS':'FAIL';
 }catch(error){report.status='BLOCKED';report.setupError=error.stack;if(page){report.body=(await page.locator('body').innerText().catch(()=>'' )).slice(-12000);await shot('setup-failure').catch(()=>{});}}
 finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));report.serviceClosed=true;report.sourceSHA256After=sourceHashes();report.sourceBindingStable=JSON.stringify(report.sourceSHA256Before)===JSON.stringify(report.sourceSHA256After);if(!report.sourceBindingStable)report.status='FAIL';await persist();console.log(JSON.stringify({status:report.status,checks:report.checks.length,failed:report.checks.filter(c=>c.status!=='PASS').map(c=>({id:c.id,error:c.error?.split('\n')[0]})),pageErrors:report.pageErrors,setupError:report.setupError,sourceBindingStable:report.sourceBindingStable}));if(report.status!=='PASS')process.exitCode=1;}
})();
