'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const I=require('../platform-import-session-v19.js'),C=require('../network-contract-v18.js'),Settings=require('../platform-settings-v19.js'),Service=require('../platform-study-service-v19.js'),Store=require('../design-study-store-v19.js'),Context=require('../design-strategic-context-v19.js'),Data=require('../design-data-adapter-v19.js'),Repo=require('../platform-repository-v19.js');
const settings={scope:'DESIGN',coordinateSystem:'WGS84',weightUnit:'kg',volumeUnit:'m3',observationPeriod:'2026-09-01',costPeriod:'MODEL_RUN',currency:'CNY',classification:'SYNTHETIC'};
const observations=[];
async function check(id,fn){await fn();observations.push({id,status:'PASS'});}
(async()=>{
 const dir=process.argv[2],file=name=>new File([fs.readFileSync(path.join(dir,name))],name);
 const xlsx=await I.readFiles([file('network.xlsx')]),json=await I.readFiles([file('network.json')]),csv=await I.readFiles(fs.readdirSync(dir).filter(name=>name.endsWith('.csv')).map(file));
 const base=I.validate(xlsx,settings);
 await check('J03-DECLARED-CLASSIFICATION-NOT-RELABELLED',()=>{for(const classification of ['ANONYMIZED','PERSONAL','CONFIDENTIAL']){const report=I.validate(xlsx,{...settings,classification});assert.equal(report.status,'READY');assert.equal(report.normalizedScenario.dataClassification,classification);}});
 await check('J03-CANDIDATE-SITE-NOT-OPEN-DEPOT',()=>{const source=structuredClone(json);source.tables.push({fileName:'network.json',sheet:'candidateSites',kind:'candidateSites',records:[{siteId:'SYNTHETIC-CANDIDATE',coordinate:[117.2,39.1]}],headers:['siteId','coordinate'],formulaRows:[]});const report=I.validate(source,settings);assert.equal(report.status,'READY');assert.equal(report.normalizedScenario.depots.length,2);assert.equal(report.records.candidateSites.length,(base.records.candidateSites?.length||0)+1);assert.ok(!report.normalizedScenario.depots.some(row=>row.depotId==='SYNTHETIC-CANDIDATE'));});
 await check('T0305-T0308-ADAPTER-ISOLATION',()=>{const scenario=structuredClone(base.normalizedScenario),design=Data.adoptNetworkScenario(scenario),reference={scope:'DESIGN',ids:['0001']},operational=require('../operational-scenario-adapter-v19.js').project(reference);scenario.orders[0].demand.volume=99999;reference.ids.push('MUTATION');assert.notEqual(design.scenario.orders[0].demand.volume,99999);assert.deepEqual(operational.source.ids,['0001']);assert.equal(operational.mode,'BRIDGE_AVAILABLE');assert.equal(operational.bridgeStatus,'P6_OPERATIONAL_VALIDATION_BRIDGE_ACTIVE');assert.equal(operational.canApply,false);});
 await check('J04-XLSX-CSV-JSON-PARITY',()=>{assert.equal(base.status,'READY');assert.equal(I.validate(json,settings).canonicalDataHash,base.canonicalDataHash);assert.equal(I.validate(csv,settings).canonicalDataHash,base.canonicalDataHash);});
 await check('J04-MULTI-ISSUE-ROW-CONSERVATION',()=>{const bad=structuredClone(xlsx),table=bad.tables.find(row=>row.kind==='orders');table.records[1].orderId=table.records[0].orderId;table.records[1].coordinate='';table.records[1].demand='{"volume":-1}';const report=I.validate(bad,settings);const badKeys=[...new Set(report.issues.map(row=>row.rowKey).filter(Boolean))];assert.equal(badKeys.length,1);assert.ok(report.issues.length>=3);assert.equal(report.status,'BLOCKED');const fixed=I.validate(bad,{...settings,excludedRows:badKeys,confirmExclusion:true});assert.equal(fixed.rejectedRecords,1);assert.equal(fixed.totalRecords,fixed.acceptedRecords+fixed.rejectedRecords);assert.equal(fixed.normalizedScenario.orders.length,11);assert.throws(()=>I.validate(bad,{...settings,excludedRows:badKeys}));});
 await check('J04-FORMULA-REJECTED',()=>{const bad=structuredClone(xlsx);bad.tables.find(row=>row.kind==='orders').formulaRows=[{row:2,field:'demand'}];assert.ok(I.validate(bad,settings).issues.some(row=>row.code==='IMPORT_FORMULA_UNSUPPORTED'));});
 await check('J04-UNKNOWN-DEPOT-REJECTED',()=>{const bad=structuredClone(xlsx);bad.tables.find(row=>row.kind==='orders').records[0].allowedDepotIds='["UNKNOWN"]';assert.ok(I.validate(bad,settings).issues.some(row=>row.code==='IMPORT_UNKNOWN_DEPOT'));});
 await check('J04-FORMAT-ENCODING-LIMITS',async()=>{await assert.rejects(I.readFiles([new File(['x'],'test.xls')]));await assert.rejects(I.readFiles([new File([new Uint8Array([255,255])],'test.csv')]));assert.throws(()=>I.parseJson('{"__proto__":{"x":1}}'));assert.throws(()=>I.parseJson('['.repeat(40)+'0'+']'.repeat(40)));});
 await check('J04-UNITS-LEADING-ZEROS-QUOTED-CSV',async()=>{
  const source=structuredClone(json);for(const table of source.tables)for(const row of table.records)for(const key of ['demand','capacity'])if(row[key]?.weight!==undefined)row[key].weight/=1000;
  assert.equal(I.validate(source,{...settings,weightUnit:'tonne'}).canonicalDataHash,base.canonicalDataHash);
  const parsed=await I.readFiles([new File(['orderId,name\r\n0001,"A, B\nC"\r\n'],'orders.csv')]);assert.equal(parsed.tables[0].records[0].orderId,'0001');assert.equal(parsed.tables[0].records[0].name,'A, B\nC');
 });
 await check('J09-EXPLICIT-PERIOD-AND-CURRENCY',()=>{
  const rows=[{amount:100,period:'MONTH',currency:'CNY'},{amount:10,period:'DAY',currency:'CNY'},{amount:7,period:'ONE_TIME',currency:'CNY'}];
  assert.throws(()=>Settings.normalizePeriods(rows));const normalized=Settings.normalizePeriods(rows,{target:'YEAR',monthlyPeriodsPerYear:12,annualBusinessDays:250});assert.deepEqual(normalized.rows.map(row=>row.amount),[1200,2500,7]);assert.equal(normalized.oneTime[0].amount,7);assert.throws(()=>Settings.normalizePeriods(normalized.rows,{target:'YEAR',monthlyPeriodsPerYear:12,annualBusinessDays:250}));assert.throws(()=>Settings.normalizePeriods([...rows,{amount:1,period:'DAY',currency:'USD'}]));
 });
 await check('J09-COST-SETTING-REAL-REVISION',()=>{const store=Store.createStore({context:Context.createContext({dataSource:Data.adoptNetworkScenario(base.normalizedScenario)})}),before=store.snapshot();store.applyBusinessSettings({tollPerKm:10});assert.notEqual(store.snapshot().activeInputHash,before.activeInputHash);assert.equal(store.snapshot().evaluation,null);store.evaluate();assert.ok(store.snapshot().evaluation.accounting.cost.total>before.evaluation.accounting.cost.total);});
 await check('J09-UPLOADED-COST-CONTEXT-EXPLICIT-CONVERSION',()=>{
  const source=structuredClone(json),records=[{costKey:'monthly-fixed',amount:100,currency:'CNY',period:'MONTH',basis:'per_period'},{costKey:'daily-variable',amount:10,currency:'CNY',period:'DAY',basis:'per_period'},{costKey:'opening',amount:7,currency:'CNY',period:'ONE_TIME',basis:'per_period'}];source.tables.push({fileName:'network.json',sheet:'costParameters',kind:'costParameters',records,headers:Object.keys(records[0]),formulaRows:[]});
  assert.equal(I.validate(source,settings).status,'BLOCKED');
  const report=I.validate(source,{...settings,normalizationTarget:'YEAR',annualBusinessDays:250,confirmNormalization:true});assert.equal(report.status,'READY');assert.deepEqual(report.records.assumptions.preparedCostContext.rows.map(row=>row.amount),[1200,2500,7]);assert.equal(report.records.costParameters[0].amount,100);
  const store=Store.createStore({context:Context.createContext({dataSource:Data.adoptNetworkScenario(report.normalizedScenario)})}),before=store.snapshot();store.applyBusinessSettings({tollPerKm:0.05,costNormalization:{target:'YEAR',monthlyPeriodsPerYear:12,annualBusinessDays:200}});assert.equal(store.snapshot().evaluation,null);assert.notEqual(store.snapshot().activeInputHash,before.activeInputHash);assert.deepEqual(store.snapshot().activeRecord.scenario.assumptions.preparedCostContext.rows.map(row=>row.amount),[1200,2000,7]);
  const changed=structuredClone(source);changed.tables.at(-1).records[0].currency='USD';assert.equal(I.validate(changed,{...settings,normalizationTarget:'YEAR',annualBusinessDays:250,confirmNormalization:true}).status,'BLOCKED');
 });
 await check('J14-DEEP-REHASHED-PACKAGE-ATTACKS',()=>{
  const store=Store.createStore({context:Context.createContext({dataSource:Data.adoptNetworkScenario(base.normalizedScenario)})});
  const snapshot=store.exportSnapshot();const repo=Repo.createRepository();const service=Service.createService(repo);
  function pack(value){const record=repo.record('SNAPSHOT',value);const payload={schemaVersion:'stct-study-package-p5',records:{studyVersions:[record]},pointers:[{id:'S',refs:[{store:'studyVersions',id:record.id}]}]};return{...payload,packageHash:C.hashArtifact(payload)};}
  assert.equal(service.inspectPackage(pack(snapshot)).status,'READY');
  for(const mutate of [row=>row.accounting.cost.total+=100,row=>row.plan.assignment.assignments[0].assignedDepotId='FAKE',row=>row.accounting.assumptions.tollPerKm=555]){const value=structuredClone(snapshot);mutate(value.results[0]);assert.throws(()=>service.inspectPackage(pack(value)));}
  const broken=pack(snapshot);broken.pointers[0].refs[0].id='MISSING';delete broken.packageHash;broken.packageHash=C.hashArtifact(broken);assert.throws(()=>service.inspectPackage(broken));
 });
 await check('J15-LEGACY-AND-MISSING-DEPENDENCIES',()=>{const repo=Repo.createRepository(),service=Service.createService(repo),store=Store.createStore({context:Context.createContext({dataSource:Data.adoptNetworkScenario(base.normalizedScenario)})});assert.equal(service.inspectPackage(store.exportReadOnly()).status,'LEGACY_READ_ONLY');const snapshot=store.exportSnapshot();delete snapshot.dataSource.scenario.routingContext.providerId;const payload={schemaVersion:'stct-study-package-p5',records:{studyVersions:[repo.record('MISSING-CONTEXT',snapshot)]},pointers:[]};payload.packageHash=C.hashArtifact(payload);assert.equal(service.inspectPackage(payload).status,'READ_ONLY_NEEDS_REVALIDATION');});
 console.log(JSON.stringify({suite:'P5_DATA_CONTRACT',observations},null,2));
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
