'use strict';
const assert=require('node:assert/strict');
const D=require('../supply-chain-design-v19.js'),R=require('../supply-chain-report-v19.js'),E=require('../supply-chain-explanation-v19.js');
const edge=(a,b,d)=>({fromNodeId:a,toNodeId:b,distanceKm:d,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC'});
const raw={studyId:'FOCUS-SYNTHETIC',name:'Focus consistency',classification:'SYNTHETIC',nodes:[{nodeId:'F',role:'FACTORY'},{nodeId:'A',name:'Original warehouse',role:'DC',capacityByPeriod:{P:100}},{nodeId:'B',name:'Nearby warehouse',role:'DC',capacityByPeriod:{P:100}},{nodeId:'C',name:'Customer',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'A',period:'P',quantity:10,unit:'m3'}],observedInbound:[{flowId:'I',fromNodeId:'F',toNodeId:'A',period:'P',quantity:10,unit:'m3'}],distanceRows:[edge('A','C',10),edge('B','C',5),edge('F','A',2),edge('F','B',30)],costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'}};
const cfg={type:'NETWORK_CANDIDATE',objective:'VOLUME_KM',objectiveScope:'OUTBOUND_ONLY',facilityCounts:[1],distanceBasis:'VERIFIED_ROAD'};
function make(study,id,site){return D.evaluatePortfolio(study,{...cfg,scenarioId:id,selectedSiteIds:[site],sourcePlan:[{sourceNodeId:'F',siteNodeId:site,share:1}]},[{demandId:'D',siteNodeId:site}]);}
const study=D.createStudy(raw),baseline=D.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),far=make(study,'FIRST','A'),near=make(study,'SECOND','B');
for(const rows of [[far,near],[near,far]]){
 const snap=R.createSnapshot(study,baseline,rows,[],cfg);assert.equal(snap.decision.focusScenarioId,'SECOND');assert.equal(E.businessBrief(snap).candidateId,'SECOND');assert.deepEqual(E.businessBrief(snap).siteNames,['Nearby warehouse']);assert.equal(snap.decision.kind,'THEORETICAL_DISTANCE_SCREENING');
 for(const locale of ['zh','en','ja']){const html=R.toHtml(study,snap,locale);assert.ok(html.includes('10 → 5 km'));assert.ok(html.includes('Nearby warehouse'));assert.ok(html.includes('SECOND'));assert.match(html,/<div class="scroll"><table/);assert.ok(E.describeBrief(E.businessBrief(snap),locale)[0].includes('Nearby warehouse'));}
}
const renamed=R.createSnapshot(study,baseline,[make(study,'ZZZ','B'),make(study,'AAA','A')],[],cfg);assert.deepEqual(E.businessBrief(renamed).siteNames,['Nearby warehouse']);
const tied=R.createSnapshot(study,baseline,[make(study,'TWO','B'),make(study,'ONE','B')],[],cfg);assert.equal(tied.decision.tiedScenarioIds.length,2);
const costStudy=D.createStudy({...raw,rates:[['INBOUND_TRANSPORT','PER_UNIT_KM',1],['OUTBOUND_TRANSPORT','PER_UNIT_KM',1],['FIXED_OPERATING','PER_PERIOD',0],['HANDLING','PER_UNIT',0]].map(([kind,basis,amount])=>({kind,basis,amount,status:'KNOWN'}))});
const costBase=D.evaluatePortfolio(costStudy,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'}),expensive=make(costStudy,'SHORTER_BUT_EXPENSIVE','B'),keep=R.createSnapshot(costStudy,costBase,[expensive],[],cfg);
assert.equal(keep.decision.kind,'KEEP_REFERENCE');assert.equal(keep.recommendation,null);assert.match(E.decisionText(keep,'zh'),/维持参照/);assert.match(R.toHtml(costStudy,keep),/维持参照/);
const forbidden=D.evaluatePortfolio(study,{...cfg,scenarioId:'INFEASIBLE',selectedSiteIds:['B'],forbiddenSiteIds:['B']},[{demandId:'D',siteNodeId:'B'}]);const reject=R.createSnapshot(study,baseline,[forbidden,far],[],cfg);assert.notEqual(reject.decision.focusScenarioId,'INFEASIBLE');assert.equal(R.createSnapshot(study,baseline,[forbidden],[],cfg).decision.kind,'NO_FEASIBLE_CANDIDATE');
for(const selectedSiteIds of [['A','GHOST'],['A','A']])assert.throws(()=>D.evaluatePortfolio(study,{...cfg,selectedSiteIds},[{demandId:'D',siteId:'A'}]),{code:'SUPPLY_SELECTED_SITE_SET_INVALID'});
for(const assignments of [[{demandId:'D',siteId:'A'},{demandId:'EXTRA',siteId:'A'}],[{demandId:'D',siteId:'A'},{demandId:'D',siteId:'B'}]])assert.throws(()=>D.evaluatePortfolio(study,{...cfg,selectedSiteIds:['A']},assignments),{code:'SUPPLY_ASSIGNMENTS_INVALID'});
console.log(JSON.stringify({status:'PASS',method:'CONFIGURATION_EVALUATION_NOT_SOLVER',checks:['permutation','cosmetic_id_change','ties','same_focus_all_languages','shorter_but_more_expensive_keep_reference','infeasible_excluded','configured_ghost_and_duplicate_sites_rejected','configured_duplicate_and_extra_assignments_rejected']}));
