'use strict';
const assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const Design=require('../supply-chain-design-v19.js'),Joint=require('../supply-chain-joint-v19.js'),Results=require('../supply-chain-v5-results-v19.js');
const P='2026-01',road=(fromNodeId,toNodeId,distanceKm)=>({fromNodeId,toNodeId,distanceKm,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_V7_EXACT'});
const raw={studyId:'V7-CONTRACT-SYNTHETIC',classification:'SYNTHETIC_TEST',nodes:[{nodeId:'S',role:'SUPPLIER'},{nodeId:'W1',role:'DC',capacityByPeriod:{[P]:100}},{nodeId:'W2',role:'DC',capacityByPeriod:{[P]:100}},{nodeId:'C',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'W1',period:P,quantity:10,unit:'m3'}],observedInbound:[{flowId:'I',fromNodeId:'S',toNodeId:'W1',period:P,quantity:10,unit:'m3'}],distanceRows:[road('S','W1',1),road('S','W2',2),road('W1','C',1),road('W2','C',2)],rates:[{kind:'INBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',amount:1,status:'KNOWN'},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',amount:10,status:'KNOWN'},{kind:'HANDLING',basis:'PER_UNIT',amount:1,status:'KNOWN'}],costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'}};
const study=Design.createStudy(raw),scenario={scenarioId:'V7',analysisScope:'FULL_CHAIN',objective:'VOLUME_KM',distanceBasis:'VERIFIED_ROAD',sourceMode:'FREE',supplierTotalMode:'ADJUSTABLE',capacityPolicy:'UNBOUNDED_SCREENING',homogeneousDemandConfirmed:true,allowAllSupplierSiteEdgesConfirmed:true,facilityCounts:[2],maxCandidates:1,timeLimitSeconds:5};
const native=[];
function solve(current=study,config=scenario){const request=Joint.buildRequest(current,config),run=spawnSync('python3',['-c','import json,sys,ortools;from ortools.sat.python import cp_model;from supply_chain_joint_v19 import solve_joint;print(json.dumps(solve_joint(json.load(sys.stdin),cp_model,ortools.__version__)))'],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(request.payload),encoding:'utf8',timeout:30000});assert.equal(run.status,0,run.stderr);const response=JSON.parse(run.stdout),verified=Joint.verify(current,config,request,response);native.push({scenario:config.scenarioId,objective:config.objective,engine:response.engine,results:response.results});return{request,response,verified};}
const distance=solve(),cost=solve(study,{...scenario,objective:'COST'});
assert.equal(distance.verified[0].objectiveValue,20);assert.equal(cost.verified[0].objectiveValue,50);
const fineStudy=Design.createStudy({...raw,periodDemand:raw.periodDemand.map(row=>({...row,quantity:10.0001}))}),fine=solve(fineStudy,{...scenario,scenarioId:'FOUR_DECIMAL_DEMAND'});
assert.equal(fine.response.engine.quantityPrecision,0.0001);assert.equal(fine.verified[0].sourceFlows.reduce((total,row)=>total+row.quantity,0),10.0001);
for(const solution of [distance,cost]){const projected=Results.fromVerified(study,scenario,solution.request,solution.verified[0],1);assert.equal(projected.metrics.inbound.cost,10);assert.equal(projected.metrics.outbound.cost,10);assert.equal(projected.metrics.costParts.fixedOperating,20);assert.equal(projected.metrics.costParts.handling,10);assert.equal(projected.metrics.operatingCost,50);}
// Native rule semantics: fixed share, minimum share, amount, and per-period shared capacity.
const ruleStudy=Design.createStudy({...raw,nodes:[...raw.nodes,{nodeId:'S2',role:'SUPPLIER'}],distanceRows:[...raw.distanceRows,road('S2','W1',10),road('S2','W2',10)]}),ruleBase={...scenario,facilityCounts:[1],requiredSiteIds:['W1'],forbiddenSiteIds:['W2'],sourceMode:'PARTIAL'};
for(const [mode,extra,expected]of [['FIXED_SHARE',{share:0.5},5],['MIN_SHARE',{share:0.5},10],['FIXED_AMOUNT',{quantityByPeriod:{[P]:4}},4]]){const solved=solve(ruleStudy,{...ruleBase,scenarioId:mode,sourceRules:[{supplierId:'S',siteId:'W1',mode,...extra}]});assert.equal(solved.verified[0].sourceFlows.find(flow=>flow.supplierId==='S').quantity,expected);}
const next='2026-02',sharedStudy=Design.createStudy({...raw,nodes:[...raw.nodes,{nodeId:'S2',role:'SUPPLIER'},{nodeId:'C2',role:'CUSTOMER'}],periodDemand:[P,next].flatMap(period=>[{demandId:'D',customerNodeId:'C',currentSiteId:'W1',period,quantity:10,unit:'m3'},{demandId:'D2',customerNodeId:'C2',currentSiteId:'W2',period,quantity:10,unit:'m3'}]),distanceRows:[...raw.distanceRows,road('S2','W1',10),road('S2','W2',10),road('W1','C2',2),road('W2','C2',1)]}),shared=solve(sharedStudy,{...scenario,scenarioId:'SHARED-PER-PERIOD',assignmentLocks:{D:'W1',D2:'W2'},supplierCapacityByPeriod:{S:{[P]:{max:12},[next]:{max:12}}}});
for(const period of [P,next])assert.equal(shared.verified[0].sourceFlows.filter(row=>row.supplierId==='S'&&row.period===period).reduce((sum,row)=>sum+row.quantity,0),12);
const upstreamUnknownInventory=Design.createStudy({...raw,costApplicability:{}}),upstreamCost=solve(upstreamUnknownInventory,{...scenario,scenarioId:'UPSTREAM-COST-SCOPE',analysisScope:'UPSTREAM_ONLY',objective:'COST',supplierTotalMode:'FIXED_OBSERVED'});assert.equal(upstreamCost.verified[0].objectiveValue,10);
// FULL_CHAIN uses the same visible observed-source confirmation as UPSTREAM_ONLY.
// Confirming an observed amount preserves it exactly; it never balances history to demand.
const confirmedFixed={...scenario,scenarioId:'FULL-FIXED-OBSERVED-CONFIRMED',sourceMode:'FIXED',confirmObservedSourceRules:true,allowAllSupplierSiteEdgesConfirmed:false},confirmed=solve(study,confirmedFixed);
assert.equal(confirmed.request.payload.sourceRules[0].mode,'FIXED_AMOUNT');assert.equal(confirmed.request.payload.sourceRules[0].quantityByPeriod[P],10);assert.equal(confirmed.verified[0].sourceFlows[0].quantity,10);
const unbalancedStudy=Design.createStudy({...raw,observedInbound:raw.observedInbound.map(row=>({...row,quantity:9}))}),unbalancedFixed=solve(unbalancedStudy,{...confirmedFixed,scenarioId:'FULL-FIXED-OBSERVED-UNBALANCED'});
assert.equal(unbalancedFixed.request.payload.sourceRules[0].quantityByPeriod[P],9);assert.equal(unbalancedFixed.response.results[0].status,'INFEASIBLE');assert.equal(unbalancedFixed.verified.length,0);
// INPUT CONTRACT VECTORS: validation only, not solver executions.
const vectors=[];
function input(name,change){const value=structuredClone(distance.request.payload);change(value);let error;try{Joint.validateRequest(value);}catch(e){error=e.code;}assert.ok(error,name);vectors.push({name,payload:value,jsCode:error});}
input('unknown_source_mode',p=>p.sourceMode='TYPO_MODE');input('typed_source_mode',p=>p.sourceMode={});input('unknown_total_mode',p=>p.supplierTotalMode='TYPO');
input('duplicate_supplier',p=>p.suppliers.push(p.suppliers[0]));input('duplicate_site',p=>p.sites.push(p.sites[0]));input('duplicate_demand',p=>p.demands.push(p.demands[0]));input('duplicate_period',p=>p.periods.push(P));input('non_string_period',p=>p.periods[0]=0);
input('quantity_overflow',p=>p.demands[0].quantitiesByPeriod[P]=1e300);input('objective_overflow',p=>p.inboundEdges[0].distanceKm=1e300);input('quantity_extra_period',p=>p.demands[0].quantitiesByPeriod.EXTRA=1);input('quantity_precision',p=>p.demands[0].quantitiesByPeriod[P]=1.00001);input('quantity_negative',p=>p.demands[0].quantitiesByPeriod[P]=-1);input('quantity_string',p=>p.demands[0].quantitiesByPeriod[P]='10');
input('unknown_locked_site',p=>p.demands[0].lockedSiteId='GHOST');input('unknown_inbound_site',p=>p.inboundEdges[0].siteId='GHOST');input('unknown_supplier',p=>p.inboundEdges[0].supplierId='GHOST');input('unknown_outbound_demand',p=>p.outboundEdges[0].demandId='GHOST');input('duplicate_inbound',p=>p.inboundEdges.push(p.inboundEdges[0]));input('negative_distance',p=>p.inboundEdges[0].distanceKm=-1);
input('negative_known_cost_distance_objective',p=>p.sites[0].fixedCostByPeriod[P]=-1);input('extra_period_cost',p=>p.inboundEdges[0].unitCostByPeriod.EXTRA=1);input('capacity_precision',p=>p.sites[0].capacityByPeriod[P]=1.00001);input('capacity_extra_period',p=>p.sites[0].capacityByPeriod.EXTRA=1);input('supplier_bounds_conflict',p=>{p.suppliers[0].minByPeriod[P]=20;p.suppliers[0].maxByPeriod[P]=10;});
input('fixed_total_missing_period',p=>p.supplierTotalMode='FIXED_OBSERVED');input('duplicate_count',p=>p.siteCounts=[2,2]);input('fractional_count',p=>p.siteCounts=[1.5]);input('boolean_count',p=>p.siteCounts=[true]);input('forbidden_edge',p=>{p.siteCounts=[1];p.sites[1].status='FORBIDDEN';});
input('unknown_rule_mode',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'TYPO'}];});input('free_with_rule',p=>p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'}]);input('fixed_with_no_rule',p=>p.sourceMode='FIXED');input('fixed_with_extra_free_edge',p=>{p.sourceMode='FIXED';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'}];});input('share_precision',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'FIXED_SHARE',share:0.1234567}];});input('share_above_one',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'MIN_SHARE',share:1.1}];});input('fixed_quantity_missing_period',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'FIXED_AMOUNT',quantityByPeriod:{}}];});input('rule_missing_edge',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'}];p.inboundEdges=p.inboundEdges.slice(1);});input('duplicate_rule',p=>{p.sourceMode='PARTIAL';p.sourceRules=[{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'},{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'}];});input('invalid_budget',p=>p.timeLimitSeconds=-2);input('invalid_candidate_limit',p=>p.maxResultsPerCount=1.5);
const validationProgram=`import json,sys\nfrom supply_chain_joint_v19 import _validate,SupplyChainSolveError\nresults=[]\nfor row in json.load(sys.stdin):\n try:\n  _validate(row['payload']);results.append({'name':row['name'],'code':None})\n except SupplyChainSolveError as e:results.append({'name':row['name'],'code':e.code})\nprint(json.dumps(results))`;
const validation=spawnSync('python3',['-c',validationProgram],{cwd:path.join(__dirname,'../optimizer'),input:JSON.stringify(vectors),encoding:'utf8'});assert.equal(validation.status,0,validation.stderr);const pythonVectors=JSON.parse(validation.stdout);for(const row of pythonVectors){assert.ok(row.code,row.name);assert.equal(row.code,vectors.find(v=>v.name===row.name).jsCode,row.name);}
// RESULT ADVERSARIAL VECTORS: modified copies of an actual response, never reported as solver outputs.
const rejected=[];function result(name,change){const response=structuredClone(distance.response);change(response,response.results[0]);assert.throws(()=>Joint.verify(study,scenario,distance.request,response),e=>{rejected.push({name,code:e.code});return!!e.code;});}
result('unknown_selected_warehouse',(_,r)=>r.selectedSiteIds=['W1','GHOST']);result('duplicate_selected_warehouse',(_,r)=>r.selectedSiteIds=['W1','W2','W2']);result('wrong_site_count',(_,r)=>r.facilityCount=1);result('duplicate_assignment',(_,r)=>r.assignments.push(r.assignments[0]));result('missing_assignment',(_,r)=>r.assignments=[]);result('extra_assignment',(_,r)=>r.assignments.push({demandId:'GHOST',siteId:'W1'}));result('extra_flow',(_,r)=>r.sourceFlows.push({...r.sourceFlows[0]}));result('missing_flow',(_,r)=>r.sourceFlows=[]);result('unknown_period_flow',(_,r)=>r.sourceFlows[0].period='EXTRA');result('unknown_supplier_flow',(_,r)=>r.sourceFlows[0].supplierId='GHOST');result('negative_flow',(_,r)=>r.sourceFlows[0].quantity=-1);result('nan_flow',(_,r)=>r.sourceFlows[0].quantity=NaN);result('infinite_flow',(_,r)=>r.sourceFlows[0].quantity=Infinity);result('imprecise_flow',(_,r)=>r.sourceFlows[0].quantity=10.00001);result('wrong_quantity_precision',r=>r.engine.quantityPrecision=1);result('wrong_coefficient_precision',r=>r.engine.coefficientPrecision=1);result('nonfinite_objective',(_,r)=>r.objectiveValue=NaN);result('wrong_scaled_objective',(_,r)=>r.objectiveScaledValue=100);result('impossible_bound',(_,r)=>r.bestBound=100);result('unknown_result_status',(_,r)=>r.status='SUCCESS');
assert.throws(()=>Joint.buildRequest(study,{...scenario,sourceMode:'PARTIAL',sourceRules:[{supplierId:'S',siteId:'W1',mode:'TYPO_MODE'}]}),{code:'SUPPLY_JOINT_RULE_INVALID'});
assert.throws(()=>Joint.buildRequest(study,{...scenario,sourceMode:'FIXED',sourceRules:[{supplierId:'S',siteId:'W1',mode:'EXCLUSIVE'}],allowedSourcesBySite:{W1:[]}}),{code:'SUPPLY_SOURCE_UNQUALIFIED'});
assert.throws(()=>Joint.buildRequest(study,{...scenario,selectedSiteIds:['W1','W1']}),{code:'SUPPLY_JOINT_DUPLICATE_ID'});
assert.throws(()=>Joint.verify(study,{...scenario,allowedSourcesBySite:{W1:[]}},distance.request,distance.response),{code:'SUPPLY_SOURCE_UNQUALIFIED'});
const partialCostStudy=Design.createStudy({...raw,rates:raw.rates.filter(row=>row.kind!=='INBOUND_TRANSPORT')}),partialCostRequest=Joint.buildRequest(partialCostStudy,scenario);assert.equal(partialCostRequest.payload.sites[0].fixedCostByPeriod[P],10);assert.equal(partialCostRequest.payload.sites[0].handlingPerUnitByPeriod[P],1);assert.equal(partialCostRequest.payload.inboundEdges[0].unitCostByPeriod[P],null);
const qualifiedRequest=Joint.buildRequest(study,{...scenario,allowedSourceEdgesConfirmed:true,allowedSourceEdges:[{supplierId:'S',siteId:'W1'}]});assert.equal(qualifiedRequest.payload.inboundEdges.length,1);assert.throws(()=>Joint.buildRequest(study,{...scenario,sourceMode:'FIXED',sourceRules:[{supplierId:'S',siteId:'W2',mode:'EXCLUSIVE'}],allowedSourceEdgesConfirmed:true,allowedSourceEdges:[{supplierId:'S',siteId:'W1'}]}),{code:'SUPPLY_SOURCE_UNQUALIFIED'});
const moved=Design.createStudy({...raw,nodes:[...raw.nodes,{nodeId:'C2',role:'CUSTOMER'}],periodDemand:[...raw.periodDemand,{...raw.periodDemand[0],period:'2026-02',customerNodeId:'C2'}]});assert.throws(()=>Joint.buildRequest(moved,scenario),{code:'SUPPLY_DEMAND_CUSTOMER_CHANGED'});
const nonLinear=Design.createStudy({...raw,rates:raw.rates.map(row=>row.kind==='INBOUND_TRANSPORT'?{...row,minimumCharge:100}:row)});assert.equal(Joint.buildRequest(nonLinear,scenario).payload.inboundEdges[0].unitCostByPeriod[P],null);assert.throws(()=>Joint.buildRequest(nonLinear,{...scenario,objective:'COST'}),{code:'SUPPLY_COST_OBJECTIVE_INCOMPLETE'});
for(const value of [NaN,Infinity]){const p=structuredClone(distance.request.payload);p.inboundEdges[0].distanceKm=value;assert.throws(()=>Joint.validateRequest(p),{code:'SUPPLY_JOINT_NUMBER_INVALID'});}
console.log(JSON.stringify({suite:'SUPPLY_CHAIN_V7_CONTRACTS',status:'PASS',classification:'SYNTHETIC_TEST',nativeSolves:native,inputValidationOnly:vectors.map(({name,jsCode})=>({name,jsCode,pythonCode:pythonVectors.find(row=>row.name===name).code})),resultAdversarialOnly:rejected,independentArithmetic:'10 inbound + 10 outbound + 20 fixed + 10 handling = 50 for the same configuration under both objectives'},null,2));
