#!/usr/bin/env node
"use strict";

const assert = require("assert");
const Integrity = require("../integrity-hash-v151.js");
const Twin = require("../execution-twin-v16.js");
const Reducer = require("../execution-reducer-v17.js");
const RollingRecovery = require("../rolling-recovery-v16.js");
const Alerts = require("../operations-alerts-v16.js");
const Reconciliation = require("../driver-reconciliation-v17.js");
const Telemetry = require("../telemetry-v17.js");
const FleetReplay = require("../fleet-replay-v17.js");
const Workspace = require("../operations-workspace-v17.js");

const assertions = [];
const isSha256 = (value) => /^sha256:[a-f0-9]{64}$/.test(String(value));
function check(requirementId, condition, observed, expected) {
  assert(condition, `${requirementId}: observed=${JSON.stringify(observed)} expected=${JSON.stringify(expected)}`);
  assertions.push({ assertionId: `${requirementId}-A1`, requirementId, status: "PASS", observed: structuredClone(observed), expected: structuredClone(expected), evidence: "tests/test_domain_wiring_v17.js" });
}
function delayGate() { let release; const promise = new Promise((resolve) => { release = resolve; }); return { promise, release }; }

function plan(suffix = "BASE", stopCount = 5) {
  const orderIds = Array.from({ length: stopCount }, (_, index) => `${suffix}-O${index + 1}`); const value = { schemaVersion: "stct-plan-v1.7-test", planId: `PLAN-${suffix}`, revision: 1, logicalStartMinute: 480, matrixHash: Integrity.hashValue({ matrix: suffix }), verification: { status: "PASS" }, routes: [{ routeId: `R-${suffix}`, vehicleId: `V-${suffix}`, orderIds, geometry: orderIds.map((_, index) => [121.45 + index * 0.001, 31.2]) }] }; value.planHash = Integrity.hashValue({ planId: value.planId, routes: value.routes }); return value;
}
function recoveryFixture(base = plan("RECOVERY", 4)) {
  const context = { contextHash: Integrity.hashValue({ context: base.planHash }), cutoffLogicalMinute: 510, executionRunHash: Integrity.hashValue({ run: base.planHash }), executionStateHash: Integrity.hashValue({ state: base.planHash }), matrixHash: base.matrixHash, transferPolicy: "PIN_COMPLETED_AND_ACTIVE" }; const incidentHash = Integrity.hashValue({ incident: base.planHash }); const real = RollingRecovery.createSession({ basePlan: base, context, incidentHash }); const candidate = { ...plan("RECOVERED", 6), candidateType: "LOCAL_REPAIR", matrixHash: base.matrixHash, incidentHash, verification: { status: "PASS", checks: ["CAPACITY", "TIME_WINDOW"] }, integrationEvidence: { status: "LOCAL_DETERMINISTIC" }, changePenalty: { total: 3, movedStops: 2 }, unassignedOrderIds: [] }; const pool = { requestHash: Integrity.hashValue({ request: incidentHash }), candidates: [{ ...base, candidateType: "CURRENT_PLAN_REFERENCE", reference: true, matrixHash: base.matrixHash, verification: { status: "PASS" }, changePenalty: { total: 0 } }, candidate] };
  const calls = { ingest: 0, preview: 0, apply: 0, undo: 0, counter: 0 }; const spy = { ingest: (...args) => { calls.ingest += 1; return real.ingest(...args); }, preview: (...args) => { calls.preview += 1; return real.preview(...args); }, apply: (...args) => { calls.apply += 1; return real.apply(...args); }, undo: (...args) => { calls.undo += 1; return real.undo(...args); }, createCounterRecovery: (...args) => { calls.counter += 1; return real.createCounterRecovery(...args); }, snapshot: (...args) => real.snapshot(...args), recordPostRecoveryEvent: (...args) => real.recordPostRecoveryEvent(...args), beginGeneration: (...args) => real.beginGeneration(...args), exportLineage: (...args) => real.exportLineage(...args) };
  return { base, context, incidentHash, candidate, pool, real, spy, calls };
}

function driverFixture() {
  const p = plan("DRIVER", 2); const run = Twin.createRun({ scenarioId: "DRIVER", inputHash: Integrity.hashValue({ input: "driver" }), planHash: p.planHash, routeGeometryHash: Integrity.hashValue(p.routes[0].geometry), matrixHash: p.matrixHash, providerProvenance: { providerId: "SYNTHETIC_ROAD_FIXTURE" }, simulationSeed: "17", executionProfile: "ON_TIME", logicalStartMinute: 480, revision: 1 }); const store = Reducer.createStore({ run, plan: p });
  const append = (eventType, fields = {}) => { const state = store.snapshot(); const runEvent = eventType === "RUN_RELEASED"; const result = store.append(Reducer.createEvent(run, { eventId: `DRIVER-${state.acceptedEvents.length + 1}-${eventType}`, sequence: state.acceptedEvents.length + 1, eventType, logicalTime: state.latestLogicalTime + 1, routeId: runEvent ? "" : p.routes[0].routeId, vehicleId: runEvent ? "" : p.routes[0].vehicleId, orderId: fields.orderId || "", payload: { planRevision: 1, routeRevision: 1 } })); assert.equal(result.status, "ACCEPTED"); };
  append("RUN_RELEASED"); append("ROUTE_ACCEPTED"); append("VEHICLE_DEPARTED"); const session = Reconciliation.createSession({ run, plan: p, store }); session.setOffline(); const fields = { routeId: p.routes[0].routeId, vehicleId: p.routes[0].vehicleId, orderId: p.routes[0].orderIds[0] }; session.queueEvent("STOP_ARRIVED", fields); session.queueEvent("SERVICE_STARTED", fields); session.queueEvent("SERVICE_COMPLETED", fields); return { plan: p, run, store, session };
}

async function main() {
  const recovery = recoveryFixture(); const workspace = Workspace.createWorkspace({ appliedPlan: recovery.base, recoverySession: recovery.spy, locale: "en" });
  const created = workspace.createExecutionFromPlan(recovery.base); check("T273", created.source === "CURRENT_APPLIED_PLAN" && created.plan.planHash === recovery.base.planHash && created.run.planHash === recovery.base.planHash, created, "execution run from current applied plan");
  const actions = workspace.actionRegistry(); check("T274", typeof actions.loadSyntheticDemo === "function" && Workspace.COPY.en.loadSynthetic === "Load Synthetic Operations Demo", { action: typeof actions.loadSyntheticDemo, label: Workspace.COPY.en.loadSynthetic }, "explicit synthetic demo button action");
  check("T275", workspace.snapshot().execution.plan.routes[0].orderIds.length === 4 && workspace.snapshot().execution.plan.routes[0].orderIds.length !== 3, workspace.snapshot().execution.plan.routes[0].orderIds.length, "arbitrary plan stop count");
  const candidates = workspace.ingestRecoveryPool(recovery.pool); const candidateView = candidates[0];
  check("T276", candidateView.source === "ROLLING_RECOVERY_SESSION" && recovery.calls.ingest === 1, { source: candidateView.source, ingestCalls: recovery.calls.ingest }, "candidate from recovery session");
  check("T277", candidateView.planHash === recovery.candidate.planHash && isSha256(candidateView.planHash), candidateView.planHash, recovery.candidate.planHash);
  check("T278", candidateView.matrixHash === recovery.candidate.matrixHash && isSha256(candidateView.matrixHash), candidateView.matrixHash, recovery.candidate.matrixHash);
  check("T279", candidateView.verification.status === "PASS" && candidateView.integrationEvidence.status === "LOCAL_DETERMINISTIC" && candidateView.changePenalty.total === 3, candidateView, "real candidate verification/evidence/change penalty");
  const preview = workspace.previewRecovery(recovery.candidate.planHash); check("T280", recovery.calls.preview === 1 && preview.status === "PREVIEW", { calls: recovery.calls.preview, status: preview.status }, { calls: 1, status: "PREVIEW" });
  const applied = workspace.applyRecovery(recovery.candidate.planHash); check("T281", recovery.calls.apply === 1 && applied.status === "APPLIED", { calls: recovery.calls.apply, status: applied.status }, { calls: 1, status: "APPLIED" });
  check("T284", workspace.snapshot().planRevision === 2 && workspace.snapshot().appliedPlan.revision === 2, { workspaceRevision: workspace.snapshot().planRevision, planRevision: workspace.snapshot().appliedPlan.revision }, 2);
  check("T285", workspace.snapshot().mapHandover.newPlanHash === recovery.candidate.planHash && workspace.snapshot().mapHandover.planRevision === 2, workspace.snapshot().mapHandover, "map handover updated");
  check("T286", workspace.snapshot().timelineHandover.newPlanHash === recovery.candidate.planHash && workspace.snapshot().timelineHandover.planRevision === 2, workspace.snapshot().timelineHandover, "timeline handover updated");
  const undone = workspace.undoRecovery(); check("T282", recovery.calls.undo === 1 && undone.status === "UNDONE" && workspace.snapshot().appliedPlan.planHash === recovery.base.planHash, { calls: recovery.calls.undo, status: undone.status, planHash: workspace.snapshot().appliedPlan.planHash }, { calls: 1, status: "UNDONE", planHash: recovery.base.planHash });
  workspace.previewRecovery(recovery.candidate.planHash); workspace.applyRecovery(recovery.candidate.planHash); recovery.spy.recordPostRecoveryEvent({ eventId: "ACK-1", eventHash: Integrity.hashValue({ ack: 1 }), eventType: "EVENT_ACKNOWLEDGED", logicalTime: 520, ackId: "ACK-1", accepted: true }); const counter = workspace.createCounterRecovery("ACK_ACCEPTED"); check("T283", recovery.calls.counter === 1 && isSha256(counter.counterRecoveryHash), { calls: recovery.calls.counter, hash: counter.counterRecoveryHash }, "real counter-recovery method");

  const capsuleCalls = { create: 0, audit: 0, serialize: 0, import: 0, download: 0 }; const capsuleApi = { createCapsule: (source) => { capsuleCalls.create += 1; return { schemaVersion: "test-capsule", source, capsuleHash: Integrity.hashValue(source) }; }, auditCapsule: (capsule) => { capsuleCalls.audit += 1; return { status: capsule.capsuleHash ? "PASS" : "FAIL", errors: [] }; }, serializeCapsule: (capsule) => { capsuleCalls.serialize += 1; return JSON.stringify(capsule); }, importCapsule: () => { capsuleCalls.import += 1; return { status: "READ_ONLY_REPLAY", mode: "READ_ONLY_REPLAY", autoPlay: false, autoApplyRecovery: false, writesCurrentState: false, externalRequests: false }; } }; const capWorkspace = Workspace.createWorkspace({ capsuleApi, downloader: async (content, filename) => { capsuleCalls.download += 1; return { status: "DOWNLOADED", filename, bytes: content.length }; } });
  const exported = await capWorkspace.exportCapsule({ evidence: "real-domain-source" }, { filename: "v17-capsule.json" });
  check("T287", capsuleCalls.create === 1 && capsuleCalls.audit === 1 && capsuleCalls.serialize === 1 && exported.status === "EXPORTED", { calls: capsuleCalls, exported }, "create/audit/serialize called");
  check("T289", capsuleCalls.download === 1 && exported.filename === "v17-capsule.json" && exported.bytes > 0, { calls: capsuleCalls.download, filename: exported.filename, bytes: exported.bytes }, "real downloader completed");
  const imported = capWorkspace.importCapsule("serialized"); check("T314", capsuleCalls.import === 1 && imported.mode === "READ_ONLY_REPLAY" && imported.autoPlay === false && imported.autoApplyRecovery === false && imported.autoSyncQueue === false, { calls: capsuleCalls.import, imported }, "read-only import with no automatic side effects");
  const badCapsuleApi = { createCapsule: () => ({ capsuleHash: "bad" }), auditCapsule: () => ({ status: "FAIL", errors: [{ code: "CAPSULE_BAD", message: "bad" }] }), serializeCapsule: () => { throw new Error("must not serialize"); }, importCapsule: () => ({}) }; let badDownloads = 0; const badWorkspace = Workspace.createWorkspace({ capsuleApi: badCapsuleApi, downloader: () => { badDownloads += 1; } }); const failedExport = await badWorkspace.exportCapsule({ bad: true });
  check("T288", failedExport.status === "FAILED" && badDownloads === 0 && badWorkspace.snapshot().lastExport === null, { result: failedExport, downloads: badDownloads, lastExport: badWorkspace.snapshot().lastExport }, "failure never announces export success");

  const focused = workspace.focus({ routeId: recovery.base.routes[0].routeId, orderId: recovery.base.routes[0].orderIds[0] }, "EVENT"); const focusSnapshot = workspace.snapshot();
  check("T290", focused.orderId === recovery.base.routes[0].orderIds[0] && focusSnapshot.mapFocuses.at(-1).orderId === focused.orderId, { focused, map: focusSnapshot.mapFocuses.at(-1) }, "Selection Controller focused map");
  check("T291", focusSnapshot.timelineFocuses.at(-1).orderId === focused.orderId && focusSnapshot.timelineFocuses.at(-1).source === focused.source, focusSnapshot.timelineFocuses.at(-1), "Selection Controller synchronized timeline");

  const inbox = Alerts.createInbox(); const makeAlert = (id, severity = "HIGH") => Alerts.createAlert({ alertId: id, ruleId: "ETA_RISK", severity, executionRunHash: created.run.executionRunHash, routeId: recovery.base.routes[0].routeId, vehicleId: recovery.base.routes[0].vehicleId, orderId: recovery.base.routes[0].orderIds[0], openedLogicalTime: id.charCodeAt(id.length - 1), evidence: [{ metric: "etaRiskMinutes", actualValue: 20, thresholdOperator: ">=", thresholdValue: 10, source: "DERIVED_TELEMETRY_ONLY" }], deduplicationKey: id }); inbox.add(makeAlert("ALERT-A", "HIGH")); inbox.add(makeAlert("ALERT-B", "MEDIUM")); inbox.add(makeAlert("ALERT-C", "CRITICAL")); const alertWorkspace = Workspace.createWorkspace({ alertStore: inbox });
  check("T292", alertWorkspace.listAlerts().length === inbox.snapshot().alerts.length && alertWorkspace.snapshot().alerts.alerts.every((alert) => isSha256(alert.alertHash)), alertWorkspace.snapshot().alerts.alerts.map((alert) => alert.alertId), "AlertStore snapshot");
  const filtered = alertWorkspace.listAlerts({ severity: "CRITICAL" }); check("T293", filtered.length === 1 && filtered[0].alertId === "ALERT-C", filtered, "filter applies to store snapshot");
  const acknowledged = alertWorkspace.acknowledgeAlert("ALERT-A", { owner: "OPS", logicalTime: 100 }); check("T294", acknowledged.alert.state === "ACKNOWLEDGED" && acknowledged.event.eventType === "ALERT_ACKNOWLEDGED", acknowledged, "real acknowledge transition");
  const handling = alertWorkspace.startHandlingAlert("ALERT-A", { owner: "OPS", logicalTime: 101 }); check("T295", handling.alert.state === "IN_PROGRESS" && handling.event.eventType === "ALERT_HANDLING_STARTED", handling, "real start-handling transition");
  let resolveGuard = ""; try { alertWorkspace.resolveAlert("ALERT-A", { logicalTime: 102 }); } catch (error) { resolveGuard = error.code; } const resolved = alertWorkspace.resolveAlert("ALERT-A", { logicalTime: 102, evidence: [{ source: "OPERATOR", note: "verified" }] }); check("T296", resolveGuard === "ALERT_RESOLUTION_EVIDENCE_REQUIRED" && resolved.alert.state === "RESOLVED", { guard: resolveGuard, state: resolved.alert.state }, { guard: "ALERT_RESOLUTION_EVIDENCE_REQUIRED", state: "RESOLVED" });
  let dismissGuard = ""; try { alertWorkspace.dismissAlert("ALERT-B", { logicalTime: 103 }); } catch (error) { dismissGuard = error.code; } const dismissed = alertWorkspace.dismissAlert("ALERT-B", { logicalTime: 103, reason: "Duplicate signal" }); check("T297", dismissGuard === "ALERT_DISMISS_REASON_REQUIRED" && dismissed.alert.state === "DISMISSED", { guard: dismissGuard, state: dismissed.alert.state }, { guard: "ALERT_DISMISS_REASON_REQUIRED", state: "DISMISSED" });

  const driver = driverFixture(); const driverWorkspace = Workspace.createWorkspace({ driverSession: driver.session }); let driverNotifications = 0; driverWorkspace.subscribeDriver(() => { driverNotifications += 1; }); driverWorkspace.focus({ routeId: driver.plan.routes[0].routeId, orderId: driver.plan.routes[0].orderIds[0] }, "MAP"); const focusBeforeRefresh = driverWorkspace.snapshot().selection; const driverState = driverWorkspace.refreshDriver();
  check("T298", driverState.projection.projectedStopStates[driver.plan.routes[0].orderIds[0]].state === "COMPLETED" && driverNotifications === 1, { state: driverState.projection.projectedStopStates[driver.plan.routes[0].orderIds[0]].state, notifications: driverNotifications }, "Driver UI subscribed to Projection");
  check("T299", driverState.queue.length === 3 && driverState.summary.pending === 3, { queue: driverState.queue.length, pending: driverState.summary.pending }, 3);
  check("T300", driverState.authoritative.stopStates[driver.plan.routes[0].orderIds[0]].state === "EN_ROUTE", driverState.authoritative.stopStates[driver.plan.routes[0].orderIds[0]], "Authoritative subscription remains distinct");
  check("T301", JSON.stringify(driverWorkspace.snapshot().selection) === JSON.stringify(focusBeforeRefresh), { before: focusBeforeRefresh, after: driverWorkspace.snapshot().selection }, "background refresh preserves focus");
  check("T302", driverWorkspace.viewModel().status.stale === driver.store.snapshot().staleStatus, driverWorkspace.viewModel().status, driver.store.snapshot().staleStatus);
  check("T303", driverWorkspace.viewModel().status.offline === "OFFLINE", driverWorkspace.viewModel().status, { offline: "OFFLINE" });

  const report = workspace.computePlanActual({ plan: recovery.base, executionState: { routeStates: { [recovery.base.routes[0].routeId]: { state: "DEPARTED" } }, stopStates: Object.fromEntries(recovery.base.routes[0].orderIds.map((orderId) => [orderId, { orderId, state: "PENDING" }])) }, tracks: [], alerts: [], now: 520 }); check("T304", workspace.viewModel().businessSource.report === "PLAN_ACTUAL_REPORT" && workspace.snapshot().report.reportHash === report.reportHash, { source: workspace.viewModel().businessSource.report, hash: report.reportHash }, "report sourced from PlanActual module");
  const raw = Telemetry.createObservation({ observationId: "UI-TEL", executionRunHash: created.run.executionRunHash, vehicleId: recovery.base.routes[0].vehicleId, logicalTime: 500, coordinate: [121.45, 31.2], reportedDistance: 999, reportedSpeed: 999, source: "SYNTHETIC", accuracyMeters: 5 }); const derived = Telemetry.createDerived({ observationHash: raw.observationHash, executionRunHash: raw.executionRunHash, vehicleId: raw.vehicleId, logicalTime: raw.logicalTime, matchedCoordinate: raw.coordinate, matchedEdgeId: "E1", matchConfidence: "HIGH", matchStatus: "ROAD_MATCHED", derivedSegmentDistanceMeters: 0, derivedDurationSeconds: 0, derivedSpeedKph: 0, routeCorridorDistanceMeters: 0, offRoute: false, plausibility: { status: "PASS", reasons: [] }, providerProvenance: { providerId: "SYNTHETIC_ROAD_FIXTURE", providerVersion: "1" } }); const inspector = workspace.inspectTelemetry(raw, derived); check("T305", workspace.viewModel().businessSource.telemetry === "DERIVED_TELEMETRY" && inspector.derived.segmentDistanceMeters === 0 && inspector.reported.reportedDistance === 999, { source: workspace.viewModel().businessSource.telemetry, inspector }, "Telemetry Inspector from Derived");
  const fleetScenario = FleetReplay.syntheticScenario({ vehicleCount: 2, stopsPerVehicle: 2, positionsPerVehicle: 3 }); const replay = workspace.createFleetReplay(fleetScenario); check("T306", workspace.viewModel().businessSource.replay === "EXECUTION_EVENTS" && replay.events().length === 6 && workspace.snapshot().replay.eventCount === 6, { source: workspace.viewModel().businessSource.replay, events: replay.events().length }, "Fleet Replay from execution events");
  check("T307", workspace.viewModel().staticBusinessFactsAllowed === false && workspace.viewModel().businessSource.candidates === "ROLLING_RECOVERY_SESSION", workspace.viewModel().businessSource, "no static candidate card business facts");
  check("T308", workspace.viewModel().staticBusinessFactsAllowed === false && workspace.viewModel().businessSource.report === "PLAN_ACTUAL_REPORT", workspace.viewModel().businessSource, "no static metric business facts");
  const syntheticResult = workspace.loadSyntheticDemo({ vehicleCount: 3, stopsPerVehicle: 4, positionsPerVehicle: 2 }); check("T309", workspace.viewModel().fixtureClassification === "SYNTHETIC_DEMO" && syntheticResult.scenario.dataClassification === "SYNTHETIC" && syntheticResult.scenario.liveFleetClaim === false, { classification: workspace.viewModel().fixtureClassification, boundary: syntheticResult.scenario.boundary }, "explicit Synthetic fixture");
  check("T310", created.run.executionRunHash && workspace.events().some((event) => event.eventType === "EXECUTION_CREATED_FROM_APPLIED_PLAN"), { runHash: created.run.executionRunHash, eventTypes: workspace.events().map((event) => event.eventType) }, "user Plan execution E2E");
  check("T311", syntheticResult.status === "SYNTHETIC_DEMO_LOADED" && syntheticResult.replay.tracks.length === 3, { status: syntheticResult.status, tracks: syntheticResult.replay.tracks.length }, "synthetic execution E2E");
  check("T312", workspace.events().some((event) => event.eventType === "RECOVERY_PREVIEWED") && workspace.events().some((event) => event.eventType === "RECOVERY_APPLIED") && isSha256(counter.counterRecoveryHash), workspace.events().filter((event) => event.eventType.includes("RECOVERY")).map((event) => event.eventType), "recovery E2E");
  check("T313", exported.status === "EXPORTED" && capWorkspace.events().some((event) => event.eventType === "CAPSULE_EXPORTED"), { exported, eventTypes: capWorkspace.events().map((event) => event.eventType) }, "Capsule Export E2E");
  check("T315", driverState.projection.projectedStopStates[driver.plan.routes[0].orderIds[0]].state === "COMPLETED" && driverState.authoritative.stopStates[driver.plan.routes[0].orderIds[0]].state === "EN_ROUTE" && driverState.queue.length === 3, { projected: driverState.projection.projectedStopStates[driver.plan.routes[0].orderIds[0]].state, authoritative: driverState.authoritative.stopStates[driver.plan.routes[0].orderIds[0]].state, queue: driverState.queue.length }, "Driver Offline E2E");
  const incident = alertWorkspace.alertToIncident("ALERT-C", { logicalTime: 110, reason: "Critical ETA" }); check("T316", isSha256(incident.incidentHash) && alertWorkspace.events().some((event) => event.eventType === "ALERT_CONVERTED_TO_INCIDENT"), incident, "Alert to Incident E2E");
  let incidentFactoryInput = ""; const incidentRecovery = recoveryFixture(plan("INCIDENT", 2)); alertWorkspace.incidentToRecovery(incident, (value) => { incidentFactoryInput = value.incidentHash; return incidentRecovery.spy; }); check("T317", incidentFactoryInput === incident.incidentHash && alertWorkspace.events().some((event) => event.eventType === "INCIDENT_LINKED_TO_RECOVERY"), { incidentFactoryInput, eventTypes: alertWorkspace.events().map((event) => event.eventType) }, "Incident to Recovery E2E");
  const continued = workspace.continueExecution({ scenarioId: "CONTINUED" }); check("T318", continued.plan.planHash === workspace.snapshot().appliedPlan.planHash && workspace.events().some((event) => event.eventType === "EXECUTION_CONTINUED_AFTER_RECOVERY"), { planHash: continued.plan.planHash, revision: continued.plan.revision }, "Recovery to continued execution E2E");
  const requiredEventTypes = ["EXECUTION_CREATED_FROM_APPLIED_PLAN", "RECOVERY_PREVIEWED", "RECOVERY_APPLIED", "PLAN_ACTUAL_REPORT_COMPUTED", "TELEMETRY_INSPECTED", "FLEET_REPLAY_CREATED_FROM_EXECUTION_EVENTS"]; check("T319", requiredEventTypes.every((type) => workspace.events().some((event) => event.eventType === type)) && workspace.events().every((event) => isSha256(event.eventHash)), workspace.events().map((event) => event.eventType), requiredEventTypes);
  const beforeFailure = workspace.snapshot().appliedPlan.planHash; let failureCode = ""; try { workspace.applyRecovery("missing-plan"); } catch (error) { failureCode = error.code; } check("T320", failureCode === "RECOVERY_APPLY_NOT_ALLOWED" && workspace.snapshot().appliedPlan.planHash === beforeFailure && workspace.snapshot().lastFailure.code === failureCode, { failureCode, before: beforeFailure, after: workspace.snapshot().appliedPlan.planHash, lastFailure: workspace.snapshot().lastFailure }, "failure preserves domain state");

  const submitGate = delayGate(); const submitWorkspace = Workspace.createWorkspace({ capsuleApi, downloader: async (content, filename) => { await submitGate.promise; return { status: "DOWNLOADED", filename, bytes: content.length }; } }); const firstSubmit = submitWorkspace.exportCapsule({ x: 1 }); const duplicateSubmit = await submitWorkspace.exportCapsule({ x: 1 }); const loadingState = submitWorkspace.jobState("EXPORT_CAPSULE");
  check("T321", duplicateSubmit.status === "IGNORED_DUPLICATE_SUBMIT", duplicateSubmit, "duplicate submit prevented");
  check("T322", loadingState.loading === true && loadingState.disabled === true && loadingState.status === "RUNNING", loadingState, { loading: true, disabled: true, status: "RUNNING" }); submitGate.release(); await firstSubmit;
  const cancelGate = delayGate(); const cancelWorkspace = Workspace.createWorkspace(); const cancelPromise = cancelWorkspace.runJob("LONG_JOB", async () => { await cancelGate.promise; return { status: "SHOULD_NOT_SHOW" }; }); const cancelled = cancelWorkspace.cancelJob("LONG_JOB"); cancelGate.release(); const cancelledResult = await cancelPromise; check("T323", cancelled.status === "CANCELLED" && cancelledResult.status === "CANCELLED" && cancelWorkspace.events().some((event) => event.eventType === "JOB_CANCELLED"), { cancel: cancelled, result: cancelledResult }, "real job cancellation");
  const staleGate = delayGate(); const staleWorkspace = Workspace.createWorkspace(); const stalePromise = staleWorkspace.runJob("STALE_JOB", async () => { await staleGate.promise; return { status: "SHOULD_NOT_SHOW" }; }); staleWorkspace.invalidateJob("STALE_JOB", "PLAN_CHANGED"); staleGate.release(); const staleResult = await stalePromise; check("T324", staleResult.status === "STALE_REJECTED" && staleWorkspace.jobState("STALE_JOB").status === "SUPERSEDED", { result: staleResult, job: staleWorkspace.jobState("STALE_JOB") }, "stale response not displayed");

  const modeSource = workspace.viewModel().businessSource; const noWebGLView = workspace.viewModel({ noWebGL: true }); const reducedView = workspace.viewModel({ reducedMotion: true }); const mobileView = workspace.viewModel({ platform: "MOBILE" });
  check("T325", noWebGLView.noWebGL === true && JSON.stringify(noWebGLView.businessSource) === JSON.stringify(modeSource), { noWebGL: noWebGLView.noWebGL, source: noWebGLView.businessSource }, "No-WebGL preserves domain side effects");
  check("T326", reducedView.reducedMotion === true && JSON.stringify(reducedView.businessSource) === JSON.stringify(modeSource), { reducedMotion: reducedView.reducedMotion, source: reducedView.businessSource }, "Reduced Motion preserves domain side effects");
  check("T327", mobileView.platform === "MOBILE" && JSON.stringify(mobileView.businessSource) === JSON.stringify(modeSource), { platform: mobileView.platform, source: mobileView.businessSource }, "Mobile preserves domain side effects");
  const semanticHashes = []; for (const locale of ["zh", "en", "ja"]) { workspace.setLocale(locale); semanticHashes.push(Integrity.hashValue({ execution: workspace.snapshot().execution?.run.executionRunHash, plan: workspace.snapshot().appliedPlan.planHash, report: workspace.snapshot().report.reportHash })); } check("T328", new Set(semanticHashes).size === 1, semanticHashes, "zh/en/ja business state identical");
  const audit = workspace.wiringAudit(); check("T329", audit.consoleErrorCount === 0, audit.consoleErrorCount, 0);
  check("T330", audit.inertPrimaryControls.length === 0 && audit.primaryActions.length >= 15, { inert: audit.inertPrimaryControls, actions: audit.primaryActions }, "no inert primary control");
  check("T331", audit.announceOnlyActions.length === 0, audit.announceOnlyActions, []);
  check("T332", audit.booleanOnlyApply === false && workspace.events().filter((event) => event.eventType === "RECOVERY_APPLIED").every((event) => event.detail.planHash && event.detail.revision), { booleanOnlyApply: audit.booleanOnlyApply, applyEvents: workspace.events().filter((event) => event.eventType === "RECOVERY_APPLIED") }, "Apply returns plan/revision and domain event");
  check("T333", audit.status === "PASS" && isSha256(audit.auditHash) && audit.domainEventTypes.includes("RECOVERY_APPLIED"), audit, "Domain Wiring Audit generated");

  process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, assertions }, null, 2)}\n`);
}

main().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exit(1); });
