'use strict';
const assert=require('node:assert/strict');
const D=require('../supply-chain-design-v19.js'),R=require('../supply-chain-report-v19.js'),V=require('../supply-chain-v5-results-v19.js'),J=require('../supply-chain-joint-v19.js'),C=require('../supply-chain-controller-v19.js');
const edge=(fromNodeId,toNodeId,distanceKm)=>({fromNodeId,toNodeId,distanceKm,unit:'km',quality:'VERIFIED_ROAD',source:'SYNTHETIC_EXACT'});
const input={studyId:'ENTERPRISE-INTEGRITY-SYNTHETIC',classification:'SYNTHETIC_TEST',nodes:[{nodeId:'S',role:'SUPPLIER'},{nodeId:'A',role:'DC',capacityByPeriod:{P:100}},{nodeId:'B',role:'DC',capacityByPeriod:{P:100}},{nodeId:'C',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',currentSiteId:'A',period:'P',quantity:2,unit:'m3'}],observedInbound:[{flowId:'I',fromNodeId:'S',toNodeId:'A',period:'P',quantity:2,unit:'m3'}],distanceRows:[edge('S','A',3),edge('S','B',4),edge('A','C',5),edge('B','C',2)],rates:[{kind:'INBOUND_TRANSPORT',basis:'PER_UNIT_KM',status:'KNOWN',amount:1},{kind:'OUTBOUND_TRANSPORT',basis:'PER_UNIT_KM',status:'KNOWN',amount:1},{kind:'FIXED_OPERATING',basis:'PER_PERIOD',status:'CONFIRMED_ZERO',amount:0},{kind:'HANDLING',basis:'PER_UNIT',status:'CONFIRMED_ZERO',amount:0}],costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'}};
const scenario={scenarioId:'PLAN',type:'NETWORK_CANDIDATE',objective:'VOLUME_KM',objectiveScope:'TWO_END',distanceBasis:'VERIFIED_ROAD',selectedSiteIds:['B'],facilityCounts:[1],sourcePlan:[{sourceNodeId:'S',siteNodeId:'B',share:1}]};
const c=C.createController();c.loadStudy(input);c.calculateBaseline('VERIFIED_ROAD');c.configureScenario(scenario);c.evaluateConfigured([{demandId:'D',siteId:'B'}]);c.compare();
const packed=JSON.parse(c.exportPackage()),study=D.createStudy(packed.study),before=JSON.stringify(packed);
R.assertCurrent(study,packed.snapshot);assert.equal(JSON.stringify(packed),before);assert.equal(C.createController().importPackage(packed).status,'SNAPSHOT_READY');
function seal(p){if(p.snapshot.baseline){delete p.snapshot.baseline.resultHash;p.snapshot.baseline.resultHash=D.hash(p.snapshot.baseline);p.snapshot.baselineHash=p.snapshot.baseline.resultHash;}for(const row of p.snapshot.rows){if(row.result){delete row.result.resultHash;row.result.resultHash=D.hash(row.result);row.resultHash=row.result.resultHash;}}delete p.snapshot.snapshotHash;p.snapshot.snapshotHash=D.hash(p.snapshot);delete p.packageHash;p.packageHash=D.hash(p);return p;}
let checks=3;
for(const mutate of [p=>{p.snapshot.rows[0].result.outbound=[];},p=>{p.snapshot.rows[0].result.outbound.push(p.snapshot.rows[0].result.outbound[0]);},p=>{p.snapshot.baseline.outbound[0].quantity=1;},p=>{p.snapshot.rows[0].result.metrics.steadyStateCost=0;},p=>{p.snapshot.rows[0].result.capacityByPeriod[0].status='EXCEEDED';},p=>{p.snapshot.decision.focusScenarioId='GHOST';},p=>{p.snapshot.decision.rankedScenarioIds.push(p.snapshot.decision.rankedScenarioIds[0]);}]){
 const bad=structuredClone(packed);mutate(bad);seal(bad);const current=C.createController();current.importPackage(packed);const retained=current.snapshot();assert.throws(()=>current.importPackage(bad));assert.deepEqual(current.snapshot(),retained);assert.throws(()=>R.toHtml(study,bad.snapshot));checks+=3;
}
const cfg={...scenario,sourcePlan:[],analysisScope:'FULL_CHAIN',homogeneousDemandConfirmed:true,sourceMode:'FREE',supplierTotalMode:'ADJUSTABLE',capacityPolicy:'UNBOUNDED_SCREENING',allowAllSupplierSiteEdgesConfirmed:true};
const base=D.evaluatePortfolio(study,{type:'OBSERVED_BASELINE',distanceBasis:'VERIFIED_ROAD'});
function controlled(request,siteId){const p=request.payload,objective=2*p.inboundEdges.find(e=>e.siteId===siteId).distanceKm+2*p.outboundEdges.find(e=>e.siteId===siteId).distanceKm;return J.verify(study,cfg,request,{schemaVersion:'stct-supply-chain-joint-result-v1',requestId:p.requestId,studyHash:study.inputHash,scope:p.scope,objective:p.objective,engine:{id:'OR_TOOLS_CP_SAT',workers:1,quantityPrecision:1/(p.quantityScale||1000),quantityScale:p.quantityScale||1000,coefficientPrecision:0.001},results:[{status:'FEASIBLE',facilityCount:1,selectedSiteIds:[siteId],assignments:[{demandId:'D',siteId}],sourceFlows:[{supplierId:'S',siteId,period:'P',quantity:2}],objectiveValue:objective,bestBound:0,relativeGap:1,solveTimeMs:1}]})[0];}
const request=J.buildRequest(study,cfg),refRequest=J.buildRequest(study,cfg,{reference:true}),candidate=V.fromVerified(study,cfg,request,controlled(request,'B'),1),reference=V.fromVerified(study,cfg,refRequest,controlled(refRequest,'A'),0);
const snapshot=V.createSnapshot(study,base,cfg,reference,[candidate],[],request),joint=structuredClone(snapshot),bytes=JSON.stringify(joint);V.assertCurrent(study,joint);assert.equal(JSON.stringify(joint),bytes);checks+=2;
for(const mutate of [p=>{p.rows[0].assignments=[];p.rows[0].outbound=[];},p=>{p.rows[0].sourceFlows[0].quantity=1;},p=>{p.rows[0].metrics.operatingCost=0;},p=>{p.planningReference.outbound[0].distanceKm=0;},p=>{p.quantityAudit.modelTotal=1;},p=>{p.rows[0].relationRows=[];},p=>{p.decision.rankedScenarioIds=['GHOST'];}]){const bad=structuredClone(snapshot);mutate(bad);delete bad.snapshotHash;bad.snapshotHash=D.hash(bad);assert.throws(()=>V.assertCurrent(study,bad));assert.throws(()=>V.toHtml(study,bad));checks+=2;}
const legacy=structuredClone(packed.snapshot);legacy.scenario=null;delete legacy.snapshotHash;legacy.snapshotHash=D.hash(legacy);assert.throws(()=>R.assertCurrent(study,legacy),{code:'SUPPLY_SNAPSHOT_UNVERIFIABLE'});checks++;
D.assertResultEquivalent({value:Math.PI},{value:Math.PI+Number.EPSILON});assert.throws(()=>D.assertResultEquivalent({quantity:2},{quantity:1.999999}));checks+=2;
console.log(JSON.stringify({suite:'ENTERPRISE_SNAPSHOT_INTEGRITY',status:'PASS',checks,method:'Synthetic evaluation and controlled joint response vectors; no native solving claim',originalBytesPreserved:true}));
