'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{chromium}=require('playwright'),XLSX=require('../vendor/xlsx/xlsx.full.min.js');
const base=process.env.STCT_UI_URL,out=process.env.STCT_UI_EVIDENCE,binary=process.env.STCT_BROWSER,ucDir=process.env.STCT_NATIVE_UC_RESULTS;assert.ok(base&&out&&binary&&ucDir);fs.mkdirSync(out,{recursive:true});
const report={status:'RUNNING',tier:'BROWSER_BUSINESS_CONTROLS_NATIVE_NON_UC_AND_MAP_RENDERING',checks:[],errors:[],feedbackSamples:[],solverSamples:[]};let browser,page;
const hash=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const f=name=>page.locator('[data-supply-field="'+name+'"]'),a=name=>page.locator('[data-supply-action="'+name+'"]'),state=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function expose(locator){for(const d of (await locator.locator('xpath=ancestor::details').all()).reverse())if(!await d.evaluate(el=>el.open))await d.locator(':scope > summary').click();}
async function option(locator,value){await expose(locator);await locator.selectOption(value);}
async function fill(locator,value){await expose(locator);await locator.fill(value);await locator.press('Tab');}
async function download(locator,name){await expose(locator);const [d]=await Promise.all([page.waitForEvent('download'),locator.click()]);const file=path.join(out,name);await d.saveAs(file);return file;}
async function shot(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});report.checks.push(name);}
async function login(){await page.goto(base);if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.locator('.platform-home').waitFor();}
async function openAnalysis(){await page.getByRole('button',{name:/测算供应链方案/}).click();}
async function mapTool(selector){const el=page.locator(selector);await expose(el);await el.click();}
function syntheticWorkbook(){const b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['role','coordinate','code','name'],['FACTORY','118,31','P','Factory Pine'],['DC','118.1,31','E','Depot Elm'],['DC','119.1,31','W','Depot Willow']]),'Asset register');XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['2027/09','customer','coordinate','number','assignedDepot','2027/03'],[8.12501,'Outlet Amber','118.2,31','A','E',5.25],[11.5,'Outlet Blue','119.2,31','B','W',7.875]]),'Sales periods');XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['2027/09','toNodeId','flowId','2027/03','fromNodeId'],[8.12501,'E','IE',5.25,'P'],[11.5,'W','IW',7.875,'P']]),'Receipts periods');return Buffer.from(XLSX.write(b,{type:'buffer',bookType:'xlsx'}));}
(async()=>{try{
 browser=await chromium.launch({executablePath:binary,headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='tiles.openfreemap.org'&&u.pathname.startsWith('/styles/'))return r.fulfill({contentType:'application/json',body:JSON.stringify({version:8,sources:{},layers:[{id:'synthetic-basemap',type:'background',paint:{'background-color':'#e9eef7'}}]})});return ['localhost','127.0.0.1'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?r.continue():r.abort();});
 page=await ctx.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>report.errors.push(e.message));await login();await openAnalysis();await page.locator('[data-supply-file="workbook"]').setInputFiles({name:'SYNTHETIC-Larch-quantities.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:syntheticWorkbook()});
 for(const index of [1,2]){await f('blockIndex').selectOption(String(index));await f('blockUnit').selectOption('m3');if(index===1)await page.locator('[data-supply-map-field="currentSiteId"]').selectOption('5');}
 await f('classification').selectOption('SYNTHETIC');await a('profile-confirm').click();await f('analysisScope').selectOption('FULL_CHAIN');await f('homogeneousDemandConfirmed').check();await f('allowAllSupplierSiteEdgesConfirmed').check();await f('geoConfirmed').check();await f('networkMode').selectOption('MULTI');for(const site of await page.locator('.sc-sites input[value="adjust"]').all())await site.check();await f('minSites').fill('1');await f('maxSites').fill('2');await f('costMode').selectOption('ASSUMED');
 for(const [kind,amount]of [['INBOUND_TRANSPORT','0.12'],['OUTBOUND_TRANSPORT','0.35'],['FIXED_OPERATING','50'],['HANDLING','0.2']]){await option(page.locator('select[data-supply-rate="'+kind+'"]'),'ASSUMED');await fill(page.locator('input[data-supply-rate="'+kind+'"]'),amount);}
 for(const el of await page.locator('select[data-supply-site-fixed]').all())await option(el,'ASSUMED');for(const el of await page.locator('input[data-supply-site-fixed]').all())await fill(el,'50');for(const key of ['inventoryHolding','transferTransport']){const el=page.locator('[data-supply-scope="'+key+'"]');await expose(el);await el.check();}
 await f('objective').selectOption('COST');assert.match(await page.locator('[data-supply-preflight]').innerText(),/条件已就绪/);const started=Date.now();await a('analyze').click();await page.locator('[data-supply-map-panel]').waitFor({timeout:180000});let s=await state();assert.equal(s.snapshot.analysisScope,'FULL_CHAIN');assert.equal(s.scenario.objective,'COST');assert.ok(s.solverRuns.length);assert.ok(s.snapshot.decision.rankedScenarioIds.length);report.solverSamples.push({wallMs:Date.now()-started,runs:s.solverRuns});const original=hash(s.snapshot);const file=await download(a('package-export'),'non-UC-cost.package.json');assert.equal(JSON.parse(fs.readFileSync(file)).study.classification,'SYNTHETIC');
 const insight=page.locator('.sc-scenario-insights');await insight.locator('summary').click();assert.ok(await page.locator('[data-cost-component]').count()>0);assert.ok(await page.locator('[data-capacity-status="UNKNOWN"]').count()>0);await shot('non-UC-cost-conditions');
 for(const locale of ['zh','en','ja']){await page.locator('[data-platform-locale]').selectOption(locale);await download(a('export-html'),'non-UC-cost-'+locale+'.html');await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('non-UC-'+locale+'-390');await page.setViewportSize({width:1440,height:1000});}await page.locator('[data-platform-locale]').selectOption('zh');assert.equal(hash((await state()).snapshot),original);
 await page.reload();if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.locator('[data-supply-map-panel]').waitFor();assert.equal(hash((await state()).snapshot),original);report.checks.push('NON_UC_COST_NATIVE_SAVE_REFRESH_SAME_SNAPSHOT');
 // A saved native UC package is reopened through the business file picker. Only the basemap is a controlled rendering fixture.
 await a('step').filter({hasText:'上传数据'}).click();await expose(page.locator('[data-supply-file="study"]'));await page.locator('[data-supply-file="study"]').setInputFiles(path.join(ucDir,'FULL_CHAIN.package.json'));await page.locator('[data-supply-map-panel]').waitFor();await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-relations-candidate'));
 await mapTool('[data-p7-analysis]');if(!await page.locator('.p7-linked-analysis').evaluate(e=>e.open))await page.locator('.p7-linked-analysis > summary').click();await expose(page.locator('[data-p7-grid-display]'));await page.locator('[data-p7-grid-display]').selectOption('delta');await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-analysis-grid-fill'));let d=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());assert.ok(d.layers.includes('p7-analysis-grid-line'));report.checks.push('ACTUAL_MAPLIBRE_GRID_SOURCE_LAYERS');
 await page.locator('[data-p7-grid-cell]').first().press('Enter');d=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());assert.equal(d.viewStates.SUPPLY.linkedScope,'SELECTED');const ids=d.viewStates.SUPPLY.analysisIds;await page.locator('[data-p7-linked-relation]').first().press('Enter');assert.deepEqual((await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics())).viewStates.SUPPLY.analysisIds,ids);await page.locator('[data-p7-linked-clear]').click();
 const session=await ctx.newCDPSession(page);await session.send('Performance.enable');const before=(await session.send('Performance.getMetrics')).metrics;for(let i=0;i<10;i++){const start=Date.now();await page.locator('[data-p7-brush="distance"]').nth(i%2).press('Enter');report.feedbackSamples.push({iteration:i,wallMs:Date.now()-start,relationCount:await page.locator('[data-p7-linked-count]').getAttribute('data-count')});}const after=(await session.send('Performance.getMetrics')).metrics;report.mainThreadMetrics={before,after,method:'Chromium Performance metrics: TaskDuration/ScriptDuration are main-thread accumulated durations, not solver CPU.'};await page.locator('[data-p7-linked-clear]').click();
 await page.locator('[data-p7-expand]').click();await page.locator('dialog.p7-map-fullscreen[open]').waitFor();assert.ok(await page.locator('.p7-map-analysis').evaluate(e=>e.hidden));await mapTool('[data-p7-analysis]');assert.equal(await page.locator('.p7-map-analysis').evaluate(e=>getComputedStyle(e).position),'absolute');await page.locator('[data-p7-analysis-close]').click();await page.locator('[data-p7-map-theme]').click();await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-relations-candidate'));await shot('UC-native-fullscreen-linked-map');await page.locator('[data-p7-fullscreen-close]').click();
 const protectedSupply=hash((await state()).snapshot);await page.locator('[data-platform-workspace="COMMAND"]').first().click();for(const route of ['/command/overview','/command/dispatch','/command/execution','/command/alerts','/command/recovery']){const el=page.locator('[data-platform-route="'+route+'"]:visible').first();await el.click();await page.locator('[data-command-task]').waitFor();const task=await page.locator('[data-command-task]').getAttribute('data-command-task');assert.ok(task);assert.match(await page.locator('[data-command-task]').innerText(),/当前计划|GPS/);await shot(task+'-task-context');}
 assert.equal(hash((await state()).snapshot),protectedSupply);assert.deepEqual(report.errors,[]);report.status='PASS';
 }catch(e){report.status='FAIL';report.error=e.stack;if(page){report.body=await page.locator('body').innerText().catch(()=>null);await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});}process.exitCode=1;}
 finally{if(browser)await browser.close();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks,error:report.error}));}
})();
