#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),net=require('node:net'),crypto=require('node:crypto');
const {spawn}=require('node:child_process');
const {chromium}=require('playwright');
const XLSX=require('../vendor/xlsx/xlsx.full.min.js');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_V81_BROWSER_DIR||path.join(os.tmpdir(),'stct-v81-browser');
const original=process.env.STCT_UC_WORKBOOK||'/Users/gz/Downloads/经纬度追加-天津、沈阳、西安、东莞相关入、出库物量数据  202601~07-001 物量数据(1).xlsx';
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const json=(name,value)=>fs.writeFileSync(path.join(out,name),JSON.stringify(value,null,2)+'\n');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
const server=http.createServer((request,response)=>{const pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname),file=path.resolve(root,`.${pathname==='/'?'/index.html':pathname}`);if(!file.startsWith(root+path.sep))return response.writeHead(403).end();fs.readFile(file,(error,data)=>error?response.writeHead(404).end():response.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store'}).end(data));});
const freePort=()=>new Promise((resolve,reject)=>{const socket=net.createServer();socket.once('error',reject);socket.listen(0,'127.0.0.1',()=>{const port=socket.address().port;socket.close(()=>resolve(port));});});
async function ready(port,child){for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error(`Owned optimizer exited ${child.exitCode}`);try{const response=await fetch(`http://127.0.0.1:${port}/health`);if(response.ok&&(await response.json()).available)return;}catch(_){}await pause(100);}throw Error('Owned optimizer unavailable');}
async function route(page,url){await page.locator(`button[data-platform-route="${url}"]:visible`).first().click();await page.waitForFunction(value=>location.hash.split('?')[0]===`#${value}`,url);}
async function login(page,url){await page.goto(url,{waitUntil:'load'});const button=page.locator('#loginForm .login-btn');if(await button.isVisible())await button.click();await page.locator('.platform-home').waitFor();}
async function supply(page){return page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());}
async function context(page){return page.evaluate(()=>window.STCTPlatformV19.instance.studyContext.snapshot().current);}
async function facility(page){return page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot());}
async function waitSupply(page,test,timeout=180000){const start=Date.now();let last=null;while(Date.now()-start<timeout){const value=await supply(page);last=value;if(test(value))return value;if(value?.status==='FAILED')throw Error(JSON.stringify(value.lastError));await pause(150);}throw Error(`Supply timed out: ${JSON.stringify({status:last?.status,error:last?.lastError,job:last?.job?.status})}`);}
async function download(page,selector,name){const control=page.locator(selector);if(!await control.isVisible()){const details=control.locator('xpath=ancestor::details[1]');if(await details.count())await details.locator('summary').click();}const event=page.waitForEvent('download');await control.click();await(await event).saveAs(path.join(out,name));return hash(path.join(out,name));}
async function catalogOpen(page,name){await route(page,'/platform/scenarios');await page.locator('[data-p5-field="search"]').fill(name);await page.locator('[data-p5-field="search"]').press('Tab');const row=page.getByRole('link',{name,exact:true}).locator('xpath=ancestor::tr[1]');await row.waitFor();await row.locator('[data-p5-action="open"]').click();return row;}
async function setUcFullChain(page){await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();await page.locator('[data-supply-field="analysisScope"]').selectOption('FULL_CHAIN');await page.locator('[data-supply-field="geoConfirmed"]').check();await page.locator('[data-supply-field="homogeneousDemandConfirmed"]').check();await page.locator('[data-supply-field="allowAllSupplierSiteEdgesConfirmed"]').check();await page.locator('[data-supply-field="sourceMode"]').selectOption('FREE');await page.locator('[data-supply-field="supplierTotalMode"]').selectOption('ADJUSTABLE');await page.locator('[data-supply-field="networkMode"]').selectOption('MULTI');for(const row of await page.locator('.sc-sites tbody tr:has(input[data-supply-site])').all())await row.locator('input[value="adjust"]').check();await page.locator('[data-supply-field="minSites"]').fill('2');await page.locator('[data-supply-field="maxSites"]').fill('4');}
function workbook(upstreamOnly=false){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['role','coordinate','code','name'],['FACTORY','118,31','P','Factory Pine'],['FACTORY','119,31','Q','Factory Quartz'],['FACTORY','120,31','R','Factory River'],['DC','118.1,31','E','Depot Elm'],['DC','119.1,31','W','Depot Willow'],['DC','120.1,31','N','Depot North']]),'Asset register');if(!upstreamOnly)XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['2027/09','customer','coordinate','number','assignedDepot','2027/03'],[8,'Outlet Amber','118.2,31','A','E',5],[11,'Outlet Blue','119.2,31','B','W',7],[12,'Outlet Coral','120.2,31','C','N',3],[13,'Outlet Dune','118.3,31','D','E',9]]),'Sales periods');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['2027/09','toNodeId','flowId','2027/03','fromNodeId'],[21,'E','IE',14,'P'],[11,'W','IW',7,'Q'],[12,'N','IN',3,'R']]),'Receipts periods');return XLSX.write(book,{bookType:'xlsx',type:'buffer'});}
async function main(){fs.mkdirSync(out,{recursive:true});const originalHash=hash(original),temp=fs.mkdtempSync(path.join(os.tmpdir(),'stct-v81-input-')),uc=path.join(temp,path.basename(original));fs.copyFileSync(original,uc);assert.equal(hash(uc),originalHash);const fixture=path.join(temp,'synthetic-facility-b.json');fs.writeFileSync(fixture,JSON.stringify({studyId:'V81-FACILITY-B',name:'V8.1 Synthetic Facility B',coordinateSystem:'WGS84',dataClassification:'SYNTHETIC',sourceRefs:['SYNTHETIC_V81_B'],demands:[{demandId:'D1',coordinate:[120,30],demand:{quantity:10,weight:0,volume:0}},{demandId:'D2',coordinate:[121,30],demand:{quantity:10,weight:0,volume:0}}],sites:[{siteId:'S1',name:'Site One',coordinate:[120,30],capacity:{quantity:30,weight:0,volume:0},fixedCost:20},{siteId:'S2',name:'Site Two',coordinate:[121,30],capacity:{quantity:30,weight:0,volume:0},fixedCost:20}],options:{facilityCounts:[1,2],costPeriod:'P1',currency:'CNY',transportCostPerUnitKm:1}}));
  const optPort=await freePort(),optimizer=spawn(process.env.STCT_PYTHON||'python3',['optimizer/ortools_service.py'],{cwd:root,env:{...process.env,OPT_PORT:String(optPort)},stdio:['ignore','pipe','pipe']});let serviceLog='',browser,staticPort,page,stage='STARTUP';const summary={status:'RUNNING',method:'PLAYWRIGHT_VISIBLE_BUSINESS_CONTROLS_WITH_NATIVE_SOLVER',stages:[],pageErrors:[],originalSha256:originalHash};optimizer.stdout.on('data',chunk=>serviceLog+=chunk);optimizer.stderr.on('data',chunk=>serviceLog+=chunk);
  try{await ready(optPort,optimizer);staticPort=await new Promise(resolve=>server.listen(0,'127.0.0.1',()=>resolve(server.address().port)));summary.services={optimizerPid:optimizer.pid,optimizerPort:optPort,staticPort};browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--disable-webgl']});const browserContext=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:900},reducedMotion:'reduce'});await browserContext.route('**/*',handler=>{const url=new URL(handler.request().url());return ['127.0.0.1','localhost'].includes(url.hostname)||['data:','blob:','file:'].includes(url.protocol)?handler.continue():handler.abort();});page=await browserContext.newPage();page.setDefaultTimeout(25000);page.on('pageerror',error=>summary.pageErrors.push(error.message));const url=`http://127.0.0.1:${staticPort}/index.html?optPort=${optPort}&noWebGL=1`;
    stage='J1_COLD_FACILITY';await login(page,url);await page.locator('.platform-home button[data-platform-workspace="DESIGN"]').click();await page.locator('[data-design-route="/design/overview"]').waitFor();assert.equal(await page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.diagnostics().study),null);await route(page,'/platform/data');await page.locator('select[data-v8-kind]').selectOption('FACILITY');await page.locator('input[data-p5-upload]').setInputFiles(fixture);await page.getByRole('button',{name:'建立设施选址研究',exact:true}).click();await page.locator('[data-design-route="/design/facility-location"]').waitFor();await page.getByText('V8.1 Synthetic Facility B').first().waitFor();const before=await facility(page);assert.equal((await context(page)).studyId,before.study.studyId);assert.equal(before.study.studyId,'V81-FACILITY-B');await page.screenshot({path:path.join(out,'01-cold-facility.png'),fullPage:true});await page.locator('[data-design-action="p7-step"][data-design-id="2"]').first().click();await page.locator('[data-p7-option="facilityCounts"]').fill('1,2');await page.locator('[data-p7-option="facilityCounts"]').press('Tab');await page.locator('[data-design-action="p7-step"][data-design-id="3"]').first().click();await page.locator('[data-design-action="facility-run"]').click();await page.locator('[data-p7-map-slot]').waitFor();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot()?.status==='RESULT_READY',{timeout:120000});const solved=await facility(page);assert.equal(solved.verification.status,'PASS');assert.equal(solved.study.studyId,before.study.studyId);await page.locator('[data-design-action="p7-step"][data-design-id="5"]').first().click();await page.locator('[data-design-action="facility-save"]').click();await page.getByText('方案已保存').first().waitFor();const facilityHtmlHash=await download(page,'[data-design-action="facility-export-html"]','facility-b.html');await route(page,'/platform/scenarios');const facilityPackageHash=await download(page,'[data-p5-entry]:has-text("V8.1 Synthetic Facility B") [data-p5-action="export"]','facility-b.package.json');summary.facility={studyId:solved.study.studyId,studyHash:solved.study.studyHash,resultHash:solved.resultSet.resultSetHash,reportSha256:facilityHtmlHash,packageSha256:facilityPackageHash};summary.stages.push(stage);
    stage='J2_DEMO_A_THEN_B';const secondContext=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:900},reducedMotion:'reduce'});await secondContext.route('**/*',handler=>{const url=new URL(handler.request().url());return ['127.0.0.1','localhost'].includes(url.hostname)||['data:','blob:','file:'].includes(url.protocol)?handler.continue():handler.abort();});page=await secondContext.newPage();page.setDefaultTimeout(25000);page.on('pageerror',error=>summary.pageErrors.push(error.message));await login(page,url);await page.locator('.platform-home button[data-platform-workspace="DESIGN"]').click();await page.locator('[data-design-action="p7-demo"]').click();const demo=await page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.snapshot());assert.ok(demo.studyRef?.studyId);await route(page,'/platform/scenarios');await page.locator('[data-p5-field="scenarioName"]').fill('V81 Demo A');await page.locator('[data-p5-action="save-study"]').click();await page.locator('[data-p5-entry]').filter({hasText:'V81 Demo A'}).waitFor();await page.locator('[data-p5-package]').setInputFiles(path.join(out,'facility-b.package.json'));await page.locator('[data-p5-action="import-package"]').waitFor();await page.locator('[data-p5-action="import-package"]').click();await page.locator('[data-design-route="/design/facility-location"]').waitFor();assert.equal((await facility(page)).study.studyHash,solved.study.studyHash);assert.equal((await context(page)).studyId,'V81-FACILITY-B');await catalogOpen(page,'V8.1 Synthetic Facility B');await page.locator('[data-design-route="/design/facility-location"]').waitFor();await route(page,'/design/overview');assert.match(await page.locator('[data-design-route="/design/overview"]').innerText(),/V8\.1 Synthetic Facility B/);await route(page,'/design/cost-to-serve');assert.match(await page.locator('[data-design-route="/design/cost-to-serve"]').innerText(),/V8\.1 Synthetic Facility B/);await route(page,'/design/facility-location');await page.reload({waitUntil:'load'});const loginButton=page.locator('#loginForm .login-btn');if(await loginButton.isVisible())await loginButton.click();await page.locator('[data-design-route="/design/facility-location"]').waitFor();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot()?.study?.studyId==='V81-FACILITY-B');assert.equal((await facility(page)).study.studyHash,solved.study.studyHash);summary.demoA={studyId:demo.studyRef.studyId};summary.stages.push(stage);
    stage='J3_UC_FULL_CHAIN';await route(page,'/platform/data');await page.locator('select[data-v8-kind]').selectOption('SUPPLY_CHAIN_PERIOD');await page.locator('input[data-p5-upload]').setInputFiles(uc);await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();await page.locator('[data-supply-action="profile-confirm"]').waitFor();await page.locator('[data-supply-field="studyName"]').fill('V81 UC Full Chain C');await page.locator('[data-supply-action="profile-confirm"]').click();let current=await waitSupply(page,value=>value?.study&&value.savedPointer?.status==='DRAFT');assert.equal(current.imported.summary.demandBusinessRows,257);assert.equal(current.imported.summary.inboundBusinessRows,12);assert.equal(current.study.periodDemand.length,1799);assert.equal(current.study.observedInbound.length,84);const parentId=current.study.studyId;await setUcFullChain(page);await page.locator('[data-supply-action="analyze"]').click();current=await waitSupply(page,value=>value?.snapshot?.analysisScope==='FULL_CHAIN'&&value.snapshot.rows?.length>0,240000);assert.deepEqual(current.scenario.facilityCounts,[2,3,4]);const parentHash=current.study.inputHash,parentSnapshotHash=current.snapshot.snapshotHash;await download(page,'[data-supply-action="export-html"]','uc-c-full.html');await download(page,'[data-supply-action="export-md"]','uc-c-full.md');await download(page,'[data-supply-action="export-csv"]','uc-c-full.csv');await download(page,'[data-supply-action="package-export"]','uc-c-full.package.json');summary.ucC={studyId:parentId,inputHash:parentHash,snapshotHash:parentSnapshotHash,demandRows:1799,inboundRows:84};summary.stages.push(stage);
    stage='J4_TYPED_ROUTES';await route(page,'/design/facility-location');assert.match(await page.locator('[data-design-route="/design/facility-location"]').innerText(),/当前是期间供应链研究/);await route(page,'/design/operational-validation');assert.match(await page.locator('[data-design-route="/design/operational-validation"]').innerText(),/期间物量不是派车订单/);assert.equal((await context(page)).studyId,parentId);assert.equal((await supply(page)).study.inputHash,parentHash);summary.stages.push(stage);
    stage='J5_GROWTH';await route(page,'/design/demand-growth');await page.locator('[data-design-action="supply-demand-10"]').click();const grown=await waitSupply(page,value=>value?.study?.studyId!==parentId&&value?.scenario?.analysisScope==='FULL_CHAIN'&&value.savedPointer?.status==='DRAFT');assert.deepEqual(grown.scenario.facilityCounts,[2,3,4]);assert.equal(grown.snapshot,null);assert.equal(grown.staleResult?.reason,'PARENT_RESULT_NOT_CURRENT_FOR_GROWTH');const sum=grown.study.periodDemand.reduce((total,row)=>total+row.quantity,0);assert.ok(Math.abs(sum-127527.5848)<1e-6);await route(page,'/design/supply-chain-study');await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();assert.equal(await page.locator('[data-supply-field="analysisScope"]').inputValue(),'FULL_CHAIN');assert.equal(await page.locator('[data-supply-field="minSites"]').inputValue(),'2');assert.equal(await page.locator('[data-supply-field="maxSites"]').inputValue(),'4');await page.locator('[data-supply-action="analyze"]').click();const rerun=await waitSupply(page,value=>value?.snapshot?.analysisScope==='FULL_CHAIN'&&value.snapshot.rows?.length>0,240000);assert.ok(rerun.snapshot.planningReference);assert.equal(rerun.study.studyId,grown.study.studyId);await download(page,'[data-supply-action="export-html"]','uc-c2-full.html');await download(page,'[data-supply-action="package-export"]','uc-c2-full.package.json');summary.ucC2={studyId:rerun.study.studyId,inputHash:rerun.study.inputHash,snapshotHash:rerun.snapshot.snapshotHash,demandTotal:sum,facilityCounts:rerun.scenario.facilityCounts};await catalogOpen(page,'V81 UC Full Chain C +10%');await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();assert.equal((await supply(page)).snapshot.snapshotHash,rerun.snapshot.snapshotHash);await page.reload({waitUntil:'load'});if(await loginButton.isVisible())await loginButton.click();await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();await waitSupply(page,value=>value?.snapshot?.snapshotHash===rerun.snapshot.snapshotHash);summary.stages.push(stage);

    stage='V82_C3_C4_GROWTH';let active=rerun;const chain=[];
    for(const [label,total,precision] of [['C3',140280.34328,0.00001],['C4',154308.377608,0.000001]]){
      const previous=active;await route(page,'/design/demand-growth');await page.locator('[data-design-action="supply-demand-10"]').click();
      active=await waitSupply(page,value=>value?.study?.studyId!==previous.study.studyId&&value?.scenario?.analysisScope==='FULL_CHAIN'&&value.savedPointer?.status==='DRAFT');
      assert.deepEqual(active.scenario.facilityCounts,[2,3,4]);assert.equal(active.snapshot,null);assert.equal(active.study.assumptions.demandGrowth.parentInputHash,previous.study.inputHash);assert.equal(active.study.assumptions.demandGrowth.rootStudyId,parentId);
      assert.ok(Math.abs(active.study.periodDemand.reduce((sum,row)=>sum+row.quantity,0)-total)<1e-6);
      await route(page,'/design/supply-chain-study');await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();
      assert.equal(await page.locator('[data-supply-field="analysisScope"]').inputValue(),'FULL_CHAIN');assert.equal(await page.locator('[data-supply-field="minSites"]').inputValue(),'2');assert.equal(await page.locator('[data-supply-field="maxSites"]').inputValue(),'4');
      await page.locator('[data-quantity-exact] summary').click();assert.ok((await page.locator('[data-quantity-exact]').innerText()).includes(String(total)));
      await page.locator('[data-supply-action="analyze"]').click();active=await waitSupply(page,value=>value?.snapshot?.analysisScope==='FULL_CHAIN'&&value?.snapshot?.rows?.length>0,240000);
      assert.equal(active.snapshot.quantityAudit.precision,precision);assert.equal(active.snapshot.quantityAudit.adjustedBusinessRows,0);assert.equal(active.snapshot.quantityAudit.difference,0);assert.equal(active.snapshot.planningReference.solver.quantityPrecision,precision);assert.ok(active.snapshot.rows.every(row=>row.solver.quantityPrecision===precision));
      assert.ok((await page.locator('[data-quantity-audit]').getAttribute('title')).includes(String(total)));
      await download(page,'[data-supply-action="export-html"]',`uc-${label.toLowerCase()}-full.html`);await download(page,'[data-supply-action="export-md"]',`uc-${label.toLowerCase()}-full.md`);await download(page,'[data-supply-action="package-export"]',`uc-${label.toLowerCase()}-full.package.json`);
      chain.push({label,studyId:active.study.studyId,inputHash:active.study.inputHash,snapshotHash:active.snapshot.snapshotHash,total:active.snapshot.quantityAudit.modelTotal,precision,facilityCounts:active.scenario.facilityCounts,reference:active.snapshot.planningReference.scenarioId,candidates:active.snapshot.rows.length});
      await catalogOpen(page,active.study.name);await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();assert.equal((await supply(page)).snapshot.snapshotHash,active.snapshot.snapshotHash);
    }
    await page.reload({waitUntil:'load'});if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();await waitSupply(page,value=>value?.snapshot?.snapshotHash===active.snapshot.snapshotHash);
    await route(page,'/design/cost-to-serve');await route(page,'/design/network-scenarios');await route(page,'/design/demand-growth');assert.equal((await context(page)).studyId,active.study.studyId);
    summary.ucGrowthChain=chain;summary.stages.push(stage);
    stage='V82_MOBILE_REPORT';await route(page,'/design/supply-chain-study');await page.setViewportSize({width:390,height:844});await page.locator('[data-supply-action="step"][data-supply-id="2"]').click();
    const mobile=await page.evaluate(()=>({viewport:innerWidth,body:document.body.scrollWidth,quantityAudit:document.querySelector('[data-quantity-audit]')?.textContent||''}));assert.equal(mobile.body,390);assert.match(mobile.quantityAudit,/154,308\.4/);assert.match(await page.locator('[data-quantity-audit]').getAttribute('title'),/154308\.377608/);await page.screenshot({path:path.join(out,'uc-c4-mobile-390.png'),fullPage:true});summary.mobile=mobile;summary.stages.push(stage);await page.setViewportSize({width:1440,height:900});
    stage='V82_TWO_TAB_CONFLICT';const tabB=await secondContext.newPage();tabB.setDefaultTimeout(25000);await login(tabB,url);await tabB.locator('.platform-home button[data-platform-workspace="DESIGN"]').click();await catalogOpen(tabB,active.study.name);await tabB.locator('[data-design-route="/design/supply-chain-study"]').waitFor();
    await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();await tabB.locator('[data-supply-action="step"][data-supply-id="1"]').click();const oldRevision=(await supply(page)).savedPointer.revision;assert.equal((await supply(tabB)).savedPointer.revision,oldRevision);
    await page.locator('[data-supply-field="planName"]').fill('C4 first-tab edit');await page.locator('[data-supply-field="planName"]').press('Tab');await page.locator('[data-supply-action="draft-save"]').click();await waitSupply(page,value=>value?.savedPointer?.revision>oldRevision);
    await tabB.locator('[data-supply-field="planName"]').fill('C4 second-tab unsaved edit');await tabB.locator('[data-supply-field="planName"]').press('Tab');await tabB.locator('[data-supply-action="draft-save"]').click();await tabB.locator('[data-supply-action="save-as-branch"]').waitFor();assert.match(await tabB.locator('.sc-message.is-error').innerText(),/保存版本冲突/);const conflictDraftHash=await download(tabB,'[data-supply-action="package-export"]','conflicted-c4.draft.json');assert.equal((await supply(tabB)).scenario.scenarioId,'C4 second-tab unsaved edit');await tabB.locator('[data-supply-action="save-as-branch"]').click();const branched=await waitSupply(tabB,value=>value?.study?.studyId.includes('-BRANCH-')&&value.savedPointer?.status==='DRAFT');assert.equal(branched.study.assumptions.branchOf.studyId,active.study.studyId);summary.twoTab={originalStudyId:active.study.studyId,oldRevision,firstRevision:(await supply(page)).savedPointer.revision,branchStudyId:branched.study.studyId,draftSha256:conflictDraftHash};await tabB.close();summary.stages.push(stage);
    stage='V82_SIBLINGS_AND_DOUBLE_CLICK';await catalogOpen(page,'V81 UC Full Chain C');await page.locator('[data-design-route="/design/supply-chain-study"]').waitFor();const originalC=await supply(page);assert.equal(originalC.study.inputHash,parentHash);await route(page,'/platform/scenarios');await page.locator('[data-p5-field="search"]').fill('');await page.locator('[data-p5-field="search"]').press('Tab');await page.locator('[data-p5-entry]').first().waitFor();const beforeSiblings=await page.locator('[data-p5-entry]').count();await route(page,'/design/demand-growth');await page.locator('[data-design-action="supply-demand-10"]').dblclick({delay:0});const siblingA=await waitSupply(page,value=>value?.study?.studyId!==parentId&&value.savedPointer?.status==='DRAFT');assert.equal(siblingA.study.assumptions.demandGrowth.parentStudyId,parentId);await route(page,'/platform/scenarios');await page.locator(`[data-p5-entry="SUPPLY:${siblingA.study.studyId}"]`).waitFor();assert.equal(await page.locator('[data-p5-entry]').count(),beforeSiblings+1);
    await catalogOpen(page,'V81 UC Full Chain C');await route(page,'/design/demand-growth');await page.locator('[data-design-action="supply-demand-10"]').click();const siblingB=await waitSupply(page,value=>value?.study?.studyId!==parentId&&value?.study?.studyId!==siblingA.study.studyId&&value.savedPointer?.status==='DRAFT');assert.equal(siblingB.study.assumptions.demandGrowth.parentStudyId,parentId);assert.deepEqual(siblingB.scenario,siblingA.scenario);assert.deepEqual(siblingB.study.periodDemand,siblingA.study.periodDemand);await route(page,'/platform/scenarios');await page.locator('[data-p5-field="search"]').fill('');await page.locator('[data-p5-field="search"]').press('Tab');await page.locator(`[data-p5-entry="SUPPLY:${siblingB.study.studyId}"]`).waitFor();assert.equal(await page.locator('[data-p5-entry]').count(),beforeSiblings+2);await page.locator(`[data-p5-entry="SUPPLY:${siblingA.study.studyId}"] [data-p5-action="open"]`).click();await waitSupply(page,value=>value?.study?.studyId===siblingA.study.studyId);assert.equal((await supply(page)).study.inputHash,siblingA.study.inputHash);summary.siblings={parentStudyId:parentId,siblingA:siblingA.study.studyId,siblingB:siblingB.study.studyId,sameInputHash:siblingA.study.inputHash===siblingB.study.inputHash,doubleClickCreatedOne:true,parentInputHashUnchanged:originalC.study.inputHash===parentHash};summary.stages.push(stage);
    json('summary.json',summary);
    assert.equal(hash(original),originalHash);assert.deepEqual(summary.pageErrors,[]);summary.status='PASS';json('summary.json',summary);console.log(JSON.stringify({status:'PASS',stages:summary.stages,services:summary.services,ucGrowthChain:summary.ucGrowthChain}));
  }catch(error){summary.status='FAIL';summary.failedStage=stage;summary.error=String(error.stack||error);if(page)try{await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});}catch(_){}console.error(JSON.stringify({status:'FAIL',stage,error:summary.error}));process.exitCode=1;}finally{if(browser)await browser.close();if(server.listening)await new Promise(resolve=>server.close(resolve));if(optimizer.exitCode===null&&optimizer.signalCode===null){const stopped=new Promise(resolve=>optimizer.once('exit',resolve));optimizer.kill('SIGTERM');await Promise.race([stopped,pause(5000)]);if(optimizer.exitCode===null&&optimizer.signalCode===null){optimizer.kill('SIGKILL');await stopped;}}fs.writeFileSync(path.join(out,'optimizer-service.log'),serviceLog);summary.cleanup={optimizerPid:optimizer.pid,optimizerExitCode:optimizer.exitCode,optimizerSignalCode:optimizer.signalCode,staticClosed:!server.listening};json('summary.json',summary);}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
