#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),http=require('node:http'),net=require('node:net'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const output=process.env.STCT_V83_EVIDENCE||path.join(os.tmpdir(),'stct-v83-local-recovery.json');
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const freePort=()=>new Promise((resolve,reject)=>{const socket=net.createServer();socket.once('error',reject);socket.listen(0,'127.0.0.1',()=>{const port=socket.address().port;socket.close(()=>resolve(port));});});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
const server=http.createServer((request,response)=>{const name=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname),file=path.resolve(root,`.${name==='/'?'/index.html':name}`);if(!file.startsWith(root+path.sep))return response.writeHead(403).end();fs.readFile(file,(error,bytes)=>error?response.writeHead(404).end():response.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream','cache-control':'no-store'}).end(bytes));});
const fixture={studyId:'V83-SYNTHETIC-RECOVERY',name:'V8.3 Synthetic Recovery',coordinateSystem:'WGS84',dataClassification:'SYNTHETIC',sourceRefs:['V83_SYNTHETIC_ONLY'],demands:[{demandId:'D1',coordinate:[120,30],demand:{quantity:10,weight:0,volume:0}},{demandId:'D2',coordinate:[121,30],demand:{quantity:10,weight:0,volume:0}}],sites:[{siteId:'S1',name:'Site One',coordinate:[120,30],capacity:{quantity:30,weight:0,volume:0},fixedCost:20},{siteId:'S2',name:'Site Two',coordinate:[121,30],capacity:{quantity:30,weight:0,volume:0},fixedCost:20}],options:{facilityCounts:[1,2],costPeriod:'P1',currency:'CNY',transportCostPerUnitKm:1}};
const evidence={status:'RUNNING',injection:'Chromium DevTools Storage.overrideQuotaForOrigin in isolated browser context',stages:[],pageErrors:[]};
async function ready(port,child){for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error('isolated optimizer exited');try{const response=await fetch(`http://127.0.0.1:${port}/health`);if(response.ok&&(await response.json()).dependencies.supplyChainReady)return;}catch(_){}await pause(100);}throw Error('isolated optimizer unavailable');}
async function login(page,url){await page.goto(url);const button=page.locator('#loginForm .login-btn');if(await button.isVisible())await button.click();await page.locator('.platform-home').waitFor();}
async function route(page,value){await page.locator(`button[data-platform-route="${value}"]:visible`).first().click();await page.waitForFunction(route=>location.hash.split('?')[0]===`#${route}`,value);}
async function pointerCount(page){return page.evaluate(async()=>{const request=indexedDB.open('stct-platform-v19-p5',4),db=await new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise((resolve,reject)=>{const rows=db.transaction('pointers').objectStore('pointers').getAll();rows.onsuccess=()=>resolve(rows.result.filter(row=>row.type==='FACILITY_STUDY').length);rows.onerror=()=>reject(rows.error);});}finally{db.close();}});}
async function main(){const port=await freePort(),optimizer=spawn(process.env.STCT_PYTHON||'python3',['optimizer/ortools_service.py'],{cwd:root,env:{...process.env,OPT_PORT:String(port)},stdio:['ignore','pipe','pipe']});let log='',browser,page,stage='START';optimizer.stdout.on('data',chunk=>log+=chunk);optimizer.stderr.on('data',chunk=>log+=chunk);try{await ready(port,optimizer);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`,url=`${origin}/index.html?optPort=${port}&noWebGL=1#/`;browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--disable-webgl']});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:800}});await context.route('**/*',handler=>{const address=new URL(handler.request().url());return ['127.0.0.1','localhost'].includes(address.hostname)||['data:','blob:'].includes(address.protocol)?handler.continue():handler.abort();});page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>evidence.pageErrors.push(error.message));
    stage='VISIBLE_FACILITY_ANALYSIS';await login(page,url);await page.locator('.platform-home button[data-platform-workspace="DESIGN"]').click();await route(page,'/platform/data');await page.locator('select[data-v8-kind]').selectOption('FACILITY');await page.locator('input[data-p5-upload]').setInputFiles({name:'v83-synthetic-facility.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.locator('[data-design-route="/design/facility-location"]').waitFor();await page.locator('[data-design-action="p7-step"][data-design-id="2"]').first().click();await page.locator('[data-p7-option="facilityCounts"]').fill('1,2');await page.locator('[data-p7-option="facilityCounts"]').press('Tab');await page.locator('[data-design-action="p7-step"][data-design-id="3"]').first().click();await page.locator('[data-design-action="facility-run"]').click();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot()?.status==='RESULT_READY',null,{timeout:120000});const solved=await page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot());assert.equal(solved.verification.status,'PASS');assert.equal(await pointerCount(page),0);evidence.stages.push(stage);
    stage='QUOTA_FAILURE_AND_RETRY';const cdp=await context.newCDPSession(page);await cdp.send('Storage.overrideQuotaForOrigin',{origin,quotaSize:1});try{await page.locator('[data-design-action="p7-step"][data-design-id="5"]').first().click();await page.locator('[data-design-action="facility-save"]').click();await page.waitForTimeout(300);const message=await page.locator('.design-notice').allTextContents();evidence.quotaMessage=message.join(' ');assert.match(evidence.quotaMessage,/本机存储空间不足，研究未保存/);assert.equal(await pointerCount(page),0,'failed save must leave no Facility pointer');assert.equal((await page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot())).status,'RESULT_READY');await route(page,'/platform/scenarios');const rescueDownload=page.waitForEvent('download');await page.locator('[data-p5-action="rescue"]').click();const draft=JSON.parse(fs.readFileSync(await(await rescueDownload).path(),'utf8'));assert.equal(draft.status,'NOT_SAVED');assert.equal(draft.study.studyId,fixture.studyId);}finally{await cdp.send('Storage.overrideQuotaForOrigin',{origin});await cdp.detach();}await route(page,'/design/facility-location');await page.locator('[data-design-action="facility-save"]').click();await page.getByText('方案已保存').first().waitFor();assert.equal(await page.locator('.design-notice.is-error').count(),0);assert.equal(await pointerCount(page),1);evidence.stages.push(stage);
    stage='PACKAGE_MIGRATION_AND_INVALID_JSON';await route(page,'/platform/scenarios');const row=page.locator('[data-p5-entry]').filter({hasText:'V8.3 Synthetic Recovery'});await row.waitFor();const download=page.waitForEvent('download');await row.locator('[data-p5-action="export"]').click();const file=await download,packageBytes=fs.readFileSync(await file.path());assert.ok(packageBytes.length>1000);await page.locator('[data-p5-package]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{')});await page.locator('[data-p5-message]').getByText(/Unexpected|JSON|INVALID/).waitFor();assert.equal(await row.count(),1);const second=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:800}});const migrated=await second.newPage();await login(migrated,url);await migrated.locator('.platform-home button[data-platform-route="/platform/scenarios"]').click();await migrated.locator('[data-p5-package]').setInputFiles({name:'v83-synthetic.package.json',mimeType:'application/json',buffer:packageBytes});await migrated.locator('[data-p5-action="import-package"]').click();await migrated.locator('[data-design-route="/design/facility-location"]').waitFor();assert.equal((await migrated.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot())).study.studyId,fixture.studyId);await migrated.reload();const loginAgain=migrated.locator('#loginForm .login-btn');if(await loginAgain.isVisible())await loginAgain.click();await migrated.locator('[data-design-route="/design/facility-location"]').waitFor();assert.equal((await migrated.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot())).verification.status,'PASS');await second.close();evidence.stages.push(stage);
    assert.deepEqual(evidence.pageErrors,[]);evidence.status='PASS';console.log(JSON.stringify({status:evidence.status,stages:evidence.stages,quotaMessage:evidence.quotaMessage}));
  }catch(error){evidence.status='FAIL';evidence.failedStage=stage;evidence.error=String(error.stack||error);console.error(evidence.error);process.exitCode=1;}finally{if(browser)await browser.close();if(server.listening)await new Promise(resolve=>server.close(resolve));if(optimizer.exitCode===null&&optimizer.signalCode===null){const exited=new Promise(resolve=>optimizer.once('exit',resolve));optimizer.kill('SIGTERM');await Promise.race([exited,pause(5000)]);if(optimizer.exitCode===null&&optimizer.signalCode===null){optimizer.kill('SIGKILL');await exited;}}evidence.optimizerExitCode=optimizer.exitCode;evidence.optimizerSignalCode=optimizer.signalCode;evidence.optimizerLogTail=log.slice(-1000);fs.writeFileSync(output,JSON.stringify(evidence,null,2)+'\n');}}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
