'use strict';
// Finite UX vectors via upload inputs and visible business controls. No study-state injection.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('playwright'),X=require('../vendor/xlsx/xlsx.full.min.js');
const out=process.env.STCT_ENTERPRISE_EVIDENCE,base=process.env.STCT_ENTERPRISE_URL;assert.ok(out&&base);fs.mkdirSync(out,{recursive:true});
const report={status:'RUNNING',tier:'BROWSER_BUSINESS_CONTROLS_SYNTHETIC_VECTORS',cases:[],pageErrors:[],requestFailures:[]};
const file=(name,bytes)=>{const p=path.join(out,name);fs.writeFileSync(p,bytes);return p;};
const excel=(name,sheets)=>{const b=X.utils.book_new();for(const [n,rows] of sheets)X.utils.book_append_sheet(b,Array.isArray(rows)?X.utils.aoa_to_sheet(rows):rows,n);return file(name,X.write(b,{type:'buffer',bookType:'xlsx'}));};
const csv=(name,rows,sep=',')=>file(name,rows.map(row=>row.map(v=>String(v).includes(sep)||String(v).includes('"')?'"'+String(v).replaceAll('"','""')+'"':v).join(sep)).join('\n'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
let browser,page,ctx;
const a=n=>page.locator('[data-supply-action="'+n+'"]'),f=n=>page.locator('[data-supply-field="'+n+'"]'),pa=n=>page.locator('[data-p5-action="'+n+'"]');
const state=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function start(route='/design/supply-chain-study'){ctx=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:950},reducedMotion:'reduce'});await ctx.route('**/*',r=>{const u=new URL(r.request().url());return ['127.0.0.1','localhost'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?r.continue():r.abort();});page=await ctx.newPage();page.setDefaultTimeout(10000);page.on('requestfailed',r=>report.requestFailures.push({url:r.url(),error:r.failure()?.errorText}));page.on('pageerror',e=>report.pageErrors.push(e.message));await page.goto(base);await page.locator('#loginForm .login-btn').click();if(route==='/command/overview')await page.locator('.platform-home button[data-platform-workspace="COMMAND"]').click();else await page.locator('.platform-home-action[data-platform-route="'+route+'"]').click();}
async function upload(p){await page.locator('[data-supply-file="workbook"]').setInputFiles(p);await page.locator('[data-supply-mapping-overview]').waitFor();}
async function mapping(index=0){await page.locator('[data-supply-action="mapping-select"][data-supply-id="'+index+'"]').click();}
async function apply(){await a('profile-confirm').click();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.study);return state();}
async function download(button,name){if(!await button.isVisible()){await button.locator('xpath=ancestor::details[1]').locator('summary').click();}const [d]=await Promise.all([page.waitForEvent('download'),button.click()]);const p=path.join(out,name);await d.saveAs(p);await page.waitForTimeout(60);assert.ok(fs.statSync(p).size>0);return {file:p,suggestedFilename:d.suggestedFilename(),sha256:sha(p)};}
async function run(name,fn){if(process.env.STCT_CASE&& !name.includes(process.env.STCT_CASE))return;const row={name,status:'RUNNING'};try{await fn(row);row.status='PASS';}catch(e){row.status='FAIL';row.error=e.stack;if(page)row.visibleText=await page.locator('body').innerText().catch(()=>null);if(page)await page.screenshot({path:path.join(out,name.replace(/[^a-zA-Z0-9-]/g,'_')+'.png'),fullPage:true}).catch(()=>{});}finally{if(ctx)await ctx.close();ctx=null;page=null;report.cases.push(row);fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(row));}}
const head=['编号','客户编号','客户名称','经度','纬度'];
(async()=>{browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--disable-webgl']});try{
 for(const [unit,expected] of [['箱','boxes'],['kg','kg'],['m3','m3'],['','']])await run('units-'+(unit||'unknown'),async row=>{await start();const p=excel('unit-'+(unit||'unknown')+'.xlsx',[['Demand',[[...head,'2026-01 '+unit],['R1','001','Alpha',120,30,1.25]]]]);await upload(p);await mapping();assert.equal(await page.locator('[data-supply-map-period="0"][data-map-key="unit"]').inputValue(),expected);assert.equal(await page.locator('[data-supply-map-field="customerNodeId"]').inputValue(),'2');if(!unit){await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/单位|期间/);await f('blockUnit').selectOption('m3');}const s=await apply();assert.equal(s.study.periodDemand[0].quantity,1.25);assert.equal(s.study.periodDemand[0].unit,expected||'m3');assert.equal(s.study.periodDemand[0].customerNodeId,'001');row.unit=s.study.periodDemand[0].unit;});
 await run('mixed-measures',async()=>{await start();await upload(excel('mixed.xlsx',[['Demand',[[...head,'2026-01 箱数','2026-01 m3'],['R1','001','Alpha',120,30,10,1.25]]]]));await mapping();const units=await page.locator('[data-supply-map-period][data-map-key="unit"]').evaluateAll(es=>es.map(e=>e.value));assert.deepEqual(units,['boxes','m3']);const s=await apply();assert.equal(s.study.periodDemand.length,1);assert.equal(s.study.periodDemand[0].quantity,1.25);assert.equal(s.study.periodDemand[0].unit,'m3');});
 for(const [name,headers,values] of [['zh-reversed',['客户名称','客户编号','编号','纬度','经度','202601 m3'],['Alpha','001','R1',30,120,1.25]],['en-reversed',['customerName','customerNumber','demandId','latitude','longitude','Jan2026 m3'],['Alpha','001','R1',30,120,1.25]]])await run(name,async row=>{await start();await upload(excel(name+'.xlsx',[['Data',[headers,values]]]));const s=await apply();const d=s.study.periodDemand[0];assert.equal(d.customerNodeId,'001');assert.equal(s.study.nodes.find(n=>n.nodeId==='001').name,'Alpha');assert.equal(d.period,'2026-01');assert.equal(d.quantity,1.25);row.canonical={period:d.period,quantity:d.quantity,unit:d.unit};});
 await run('ambiguous-name',async()=>{await start();await upload(csv('ambiguous.csv',[['编号','客户编号','客户名称','customerName','2026-01m3'],['R','001','Alpha','Beta',5]]));await mapping();assert.equal(await page.locator('[data-supply-map-field="customerName"]').inputValue(),'0');await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/必要字段尚未映射/);await a('import-review').click();await page.waitForFunction(()=>document.activeElement.dataset.supplyMapField==='customerName');await page.locator('[data-supply-map-field="customerName"]').selectOption('3');const s=await apply();assert.equal(s.study.nodes[0].name,'Alpha');});
 await run('missing-record-id-recovery',async()=>{await start();await upload(csv('record-id.csv',[['customerNumber','customer','2026-01m3'],['001','Alpha',5]]));await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/必要字段尚未映射/);await a('import-review').click();await page.waitForFunction(()=>document.activeElement.dataset.supplyMapField==='demandId');await page.locator('[data-supply-map-field="demandId"]').selectOption('1');assert.equal((await apply()).study.periodDemand[0].quantity,5);});
 for(const [name,coords,valid] of [['empty',['',''],true],['range',[181,30],false],['swapped',[30,120],false],['zero',[0,0],true]])await run('coordinates-'+name,async()=>{await start();await upload(excel('coordinate-'+name+'.xlsx',[['Data',[[...head,'2026-01 m3'],['R1','001','Alpha',...coords,1.25]]]]));if(valid){const s=await apply();assert.deepEqual(s.study.nodes[0].coordinate,name==='empty'?null:coords);}else{await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/坐标格式或范围无效/);await a('import-review').click();assert.ok(await page.locator('.sc-import-issue').innerText());}});
 for(const sep of [',',';','\t'])await run('csv-'+({',':'comma',';':'semicolon','\t':'tab'}[sep]),async row=>{await start();const p=csv('csv-'+sep.charCodeAt(0)+'.csv',[['编号','客户编号','客户名称','月份','物量','单位'],['R1','001','Alpha, quoted','2026/01',1.25,'m3'],['R1','001','Alpha, quoted','2026-02',2.5,'m3']],sep);if(sep===',')fs.writeFileSync(p,Buffer.concat([Buffer.from([239,187,191]),fs.readFileSync(p)]));await upload(p);const s=await apply();assert.equal(s.study.periodDemand.length,2);assert.equal(s.study.nodes[0].nodeId,'001');assert.equal(s.study.nodes[0].name,'Alpha, quoted');assert.deepEqual(s.study.periodDemand.map(d=>[d.period,d.quantity]),[['2026-01',1.25],['2026-02',2.5]]);row.sourceSha256=sha(p);});
 await run('title-repeated-header-and-error',async()=>{await start();const rows=[['Monthly volume m3 export'],[...head,'2026-01 m3'],['R1','001','Alpha',120,30,1.25],[...head,'2026-01 m3'],['R2','002','Beta',121,30,'oops']];const sh=X.utils.aoa_to_sheet(rows);sh['!merges']=[{s:{r:0,c:0},e:{r:0,c:5}}];await upload(excel('repeated.xlsx',[['Rows',sh]]));await mapping();assert.equal(await f('blockStart').inputValue(),'3');await a('profile-confirm').click();assert.match(await page.locator('.sc-import-issue').innerText(),/oops/);assert.match(await page.locator('.sc-message.is-error').innerText(),/物量不是/);});
 await run('formula-provenance-download',async row=>{await start();const sh=X.utils.aoa_to_sheet([[...head,'2026-01m3'],['R1','001','Manual',120,30,5],['R2','002','Cached',121,30,5],['R3','003','Uncached',122,30,null]]);sh.F3={t:'n',f:'2+3',v:5};sh.F4={t:'n',f:'2+3'};await upload(excel('formula.xlsx',[['Formula',sh]]));await mapping();assert.match(await page.locator('[data-formula-provenance]').innerText(),/不重新计算公式/);const s=await apply();assert.equal(s.study.periodDemand.length,2);await a('step').filter({hasText:'上传数据'}).click();assert.ok(await page.locator('[data-supply-ledger-kind="PERIOD_DEMAND"]').count());await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();row.download=await download(a('package-export'),'formula-draft.package.json');const pkg=JSON.parse(fs.readFileSync(row.download.file));const text=JSON.stringify(pkg);assert.match(text,/2\+3/);assert.match(text,/PERIOD_VALUE_MISSING/);});
 for(const route of ['/design/supply-chain-study','/platform/data'])await run('invalid-utf8-'+route.split('/').pop(),async()=>{await start(route);const p=file('bad.csv',Buffer.from([0xff,0xfe,0x80,0x81]));if(route.includes('supply')){await page.locator('[data-supply-file="workbook"]').setInputFiles(p);await page.locator('.sc-message.is-error').waitFor();assert.match(await page.locator('.sc-message.is-error').innerText(),/UTF-8/);}else{await page.locator('[data-v8-kind]').selectOption('NETWORK_ORDERS');await page.locator('[data-p5-upload]').setInputFiles(p);await page.waitForFunction(()=>document.body.innerText.includes('UTF-8'));}});
 for(const [name,headers,label] of [['wide',['编号','客户名称','2026-01m3'],'供应链网络设计'],['csv-period',['编号','客户名称','月份','物量','单位'],'供应链网络设计']])await run('public-suggestion-'+name,async()=>{await start('/platform/data');const p=csv(name+'.csv',[headers,name==='wide'?['R1','Alpha',1.25]:['R1','Alpha','2026-01',1.25,'m3']]);await page.locator('[data-p5-upload]').setInputFiles(p);await pa('confirm-import-kind').waitFor();assert.match(await page.locator('.p5-import-kind').innerText(),new RegExp(label));await page.locator('[data-v8-kind]').selectOption('SUPPLY_CHAIN_PERIOD');await pa('confirm-import-kind').click();await page.locator('[data-supply-mapping-overview]').waitFor();});
 await run('facility-template-native-journey',async row=>{await start('/platform/data');await page.locator('[data-v8-kind]').selectOption('FACILITY');row.download=await download(pa('facility-excel-template'),'facility-template.xlsx');await page.locator('[data-p5-upload]').setInputFiles(row.download.file);await pa('preview-facility').waitFor();await page.locator('[data-p5-field="observationPeriod"]').selectOption('MONTH');await page.locator('[data-p5-field="costPeriod"]').selectOption('MONTH');await page.locator('[data-p5-facility="transportRate"]').fill('1');await page.locator('[data-p5-confirm]').check();await pa('preview-facility').click();await pa('adopt-facility').click();await page.locator('[data-design-route="/design/facility-location"]').waitFor();await page.locator('[data-design-action="p7-step"][data-design-id="3"]').first().click();await page.locator('[data-design-action="facility-run"]').click();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot()?.status==='RESULT_READY',null,{timeout:90000});const s=await page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.facilitySnapshot());assert.equal(s.verification.status,'PASS');row.studyHash=s.study.studyHash;await page.locator('[data-design-action="p7-step"][data-design-id="5"]').first().click();row.report=await download(page.locator('[data-design-action="facility-export-html"]'),'facility-template.html');await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'facility-mobile.png'),fullPage:true});const reportPage=await ctx.newPage();await reportPage.setContent(fs.readFileSync(row.report.file,'utf8'));await reportPage.emulateMedia({media:'print'});await reportPage.pdf({path:path.join(out,'facility-print.pdf'),format:'A4'});assert.ok((await reportPage.locator('body').innerText()).length>300);await reportPage.close();});
 await run('profile-month-roll-and-schema-change',async row=>{await start();await upload(excel('roll.xlsx',[['Plan',[[...head,'2026-01m3'],['R1','001','Alpha',120,30,1.25]]]]));const original=await apply();row.original=original.study.inputHash;for(const [sheet,period,unit]of [['Plan','2026-02','m3'],['Renamed','2026-03','m3'],['Renamed','2026-04','kg']]){await page.locator('[data-supply-action="step"][data-supply-id="0"]').click();await upload(excel('roll.xlsx',[[sheet,[[...head,period+unit],['R1','001','Alpha',120,30,1.25]]]]));await mapping();assert.equal(await page.locator('[data-supply-map-field="customerNodeId"]').inputValue(),'2');assert.equal(await page.locator('[data-supply-map-period="0"][data-map-key="period"]').inputValue(),period);assert.equal(await page.locator('[data-supply-map-period="0"][data-map-key="unit"]').inputValue(),unit);if(unit==='kg'){await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/物量类型已不在/);await a('import-review').click();await f('primaryMeasure').selectOption('weight');}const current=await apply();assert.equal(current.study.periodDemand[0].period,period);assert.equal(current.study.periodDemand[0].unit,unit);}await page.locator('[data-supply-action="step"][data-supply-id="0"]').click();await upload(excel('roll.xlsx',[['Renamed',[['客户编号','客户名称','2026-05m3'],['001','Alpha',1.25]]]]));await a('profile-confirm').click();assert.match(await page.locator('.sc-message.is-error').innerText(),/必要字段尚未映射/);});
 for(const [quality,expected] of [['估算道路','ESTIMATED_ROAD'],['已核验道路','VERIFIED_ROAD'],['地理距离','GEOGRAPHIC']])await run('matrix-'+expected,async row=>{await start();await upload(excel('matrix-nodes.xlsx',[['Nodes',[['nodeId','name','role','coordinate'],['W','Shared','DC','120,30'],['F','Shared','FACTORY','121,30']]],['Demand',[['demandId','customerNodeId','customerName','currentSiteId','coordinate','2026-01m3'],['D','C','Alpha','W','120.5,30',.25]]]]));await apply();const input=page.locator('[data-supply-file="matrix"]');await input.locator('xpath=ancestor::details[1]').locator('summary').click();await input.setInputFiles(csv('matrix-'+expected+'.csv',[['起点','终点','距离km','质量','来源','单位'],['Shared','Alpha',1500,quality,'SYNTHETIC_BROWSER','m']]));if(expected==='GEOGRAPHIC'){await page.locator('.sc-message.is-error').waitFor();assert.equal((await state()).study.distanceRows.length,0);assert.equal(await f('distanceBasis').inputValue(),'GEOGRAPHIC_SCREENING');row.rejectedAsRoad=true;return;}await f('matrixChoice').waitFor();assert.match(await f('matrixChoice').innerText(),/Shared.*W/);assert.match(await f('matrixChoice').innerText(),/Shared.*F/);await f('matrixChoice').selectOption('W');await a('matrix-resolve').click();await a('matrix-confirm').click();const s=await state();assert.equal(s.study.distanceRows[0].distanceKm,1.5);assert.equal(s.study.distanceRows[0].fromNodeId,'W');assert.equal(s.study.distanceRows[0].toNodeId,'C');assert.equal(s.study.distanceRows[0].quality,expected);const hash=s.study.inputHash;await input.setInputFiles(csv('matrix-invalid.csv',[['起点','终点','距离km','质量','来源','单位'],['W','C','',quality,'SYNTHETIC_BROWSER','km']]));await page.locator('.sc-message.is-error').waitFor();assert.equal((await state()).study.inputHash,hash);row.distance=1.5;row.source='Synthetic imported evidence label only; no routing service verified';});
 for(const locale of ['zh','en','ja'])await run('command-keyboard-'+locale,async row=>{await start('/command/overview');await page.locator('.platform-locale-control select').selectOption(locale);const finder=page.locator('[data-command-action="open-finder"]');await finder.click();await page.locator('[data-command-finder-input]').waitFor();await page.waitForFunction(()=>document.activeElement.matches('[data-command-finder-input]'));await page.keyboard.press('ArrowDown');await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>!!document.activeElement.closest('[data-command-overlay="finder"]')));await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement.matches('[data-command-action="open-finder"]'));await page.setViewportSize({width:390,height:844});await finder.click();await page.locator('[data-command-finder-input]').fill('does-not-exist');await page.locator('.command-finder-results .command-empty').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>document.activeElement.matches('[data-command-action="open-finder"]'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await finder.press('Enter');await page.locator('[data-command-result-index="0"]').waitFor();row.firstResult=await page.locator('[data-command-result-index="0"]').innerText();await page.locator('[data-command-finder-input]').press('Enter');await page.locator('[data-command-overlay="finder"]').waitFor({state:'hidden'});await page.screenshot({path:path.join(out,'command-'+locale+'-390.png'),fullPage:true});assert.match(await page.locator('.command-workspace').innerText(),{zh:/模拟|合成/,en:/Simulat|synthetic/i,ja:/シミュレーション|合成/}[locale]);});
 await run('native-three-language-repeated-downloads',async row=>{await start();const source=process.env.STCT_NON_UC_PACKAGE;assert.ok(source,'Native non-UC package path required');const input=page.locator('[data-supply-file="study"]');await input.locator('xpath=ancestor::details[1]').locator('summary').click();await input.setInputFiles(source);await page.locator('[data-supply-map-panel]').waitFor();const initial=await state(),focus=initial.snapshot.decision.focusScenarioId,rank=initial.snapshot.decision.rankedScenarioIds;row.downloads=[];for(const locale of ['zh','en','ja']){await page.locator('.platform-locale-control select').selectOption(locale);assert.equal((await state()).snapshot.decision.focusScenarioId,focus);for(const [type,ext]of [['export-html','html'],['export-md','md'],['export-comparison-csv','csv']]){const d=await download(a(type),'native-'+locale+'.'+ext);row.downloads.push(d);const text=fs.readFileSync(d.file,'utf8');for(const id of rank)assert.ok(text.includes(id));}const first=await download(a('package-export'),'native-'+locale+'-first.package.json'),second=await download(a('package-export'),'native-'+locale+'-second.package.json');assert.equal(first.sha256,second.sha256);row.downloads.push(first,second);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:950});}
 const copy=row.downloads.find(d=>d.file.endsWith('zh-first.package.json'));await ctx.close();ctx=null;await start('/platform/data');await page.locator('[data-p5-upload]').setInputFiles(copy.file);await pa('confirm-import-kind').waitFor();assert.match(await page.locator('.p5-import-kind').innerText(),/未能确定|研究包|供应链/);await pa('cancel').click();await page.locator('button[data-platform-route="/platform/scenarios"]:visible').first().click();await page.locator('[data-p5-package]').setInputFiles(copy.file);await pa('import-package').click();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.snapshot);assert.equal((await state()).snapshot.snapshotHash,initial.snapshot.snapshotHash);await page.locator('[data-supply-action="step"][data-supply-id="1"]').click();await f('planName').fill('Changed after export');await f('planName').press('Tab');await page.waitForFunction(()=>!window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.snapshot);assert.equal(await a('export-html').count(),0);row.focus=focus;row.snapshotHash=initial.snapshot.snapshotHash;
 });
 for(const locale of ['zh','en'])await run('public-orders-business-mapping-'+locale,async row=>{
  await start('/platform/data');
  const headers=locale==='zh'?['客户名称','物量','纬度','订单编号','经度']:['volume','customerName','longitude','orderId','latitude'];
  const values=locale==='zh'?['Synthetic public',.25,30,'001',120]:[.25,'Synthetic public',120,'001',30];
  const p=excel('public-orders-'+locale+'.xlsx',[[locale==='zh'?'订单':'Orders',[headers,values]],[locale==='zh'?'仓库':'Depots',[[locale==='zh'?'仓库编号':'depotId',locale==='zh'?'仓库名称':'name',locale==='zh'?'经度':'longitude',locale==='zh'?'纬度':'latitude'],['W','Synthetic harbor',120,30]]]]);
  await page.locator('[data-p5-upload]').setInputFiles(p);await pa('confirm-import-kind').waitFor();assert.match(await page.locator('.p5-import-kind').innerText(),/订单型仓网研究/);await page.locator('[data-v8-kind]').selectOption('NETWORK_ORDERS');await pa('confirm-import-kind').click();await page.locator('[data-p5-mapping] summary').click();
  await page.locator('[data-p5-map="0"][data-p5-header="'+(locale==='zh'?'物量':'volume')+'"]').selectOption({label:'需求体积 · 必填'});
  await page.locator('[data-p5-field="observationPeriod"]').fill('MONTH');await page.locator('[data-p5-field="costPeriod"]').selectOption('MONTH');await page.locator('[data-p5-confirm]').check();await pa('validate').click();await page.locator('[data-p5-validation-status]').waitFor();assert.equal(await page.locator('[data-p5-validation-status]').getAttribute('data-state'),'DATA_ONLY_SAVED');assert.equal(await page.locator('[data-p5-validation-status]').innerText(),'可保存为数据草稿');
  assert.match(await page.locator('body').innerText(),/001/);await pa('save-data').click();await pa('export-data').first().waitFor();assert.match(await pa('export-data').first().locator('xpath=ancestor::tr').innerText(),/1 订单/);const d=await download(pa('export-data').first(),'public-orders-'+locale+'.json');const pkg=JSON.parse(fs.readFileSync(d.file));assert.equal(pkg.scenario.orders[0].orderId,'001');assert.equal(pkg.scenario.orders[0].demand.volume,.25);assert.deepEqual(pkg.scenario.orders[0].coordinate,[120,30]);row.download=d;row.scope='Valid partial network dataset; no vehicles added and no dispatch solve claimed';
  await page.reload();if(await page.locator('#loginForm .login-btn').isVisible())await page.locator('#loginForm .login-btn').click();await pa('export-data').first().waitFor();const reread=await download(pa('export-data').first(),'public-orders-'+locale+'-reopened.json');assert.equal(reread.sha256,d.sha256);
  await page.locator('[data-v8-kind]').selectOption('NETWORK_ORDERS');await page.locator('[data-p5-upload]').setInputFiles(csv('public-invalid-'+locale+'.csv',[[...headers],values,locale==='zh'?['Broken','oops',30,'002',120]:['oops','Broken',120,'002',30]]));await pa('validate').waitFor();await page.locator('[data-p5-field="observationPeriod"]').fill('MONTH');await page.locator('[data-p5-confirm]').check();await pa('validate').click();await pa('issue-map').first().click();await page.waitForFunction(h=>document.activeElement.dataset.p5Header===h,locale==='zh'?'物量':'volume');await page.locator('[data-p5-exclude-confirm]').check();await pa('exclude').click();await page.waitForFunction(()=>document.querySelector('.p5-counts')?.innerText.includes('1 已排除'));assert.match(await page.locator('.p5-counts').innerText(),/2 记录[\s\S]*1 有效[\s\S]*1 已排除/);row.excluded=await download(pa('issues'),'public-orders-'+locale+'-issues.json');assert.equal(JSON.parse(fs.readFileSync(row.excluded.file)).records.length,1);await pa('cancel').click();const afterCancel=await download(pa('export-data').first(),'public-orders-'+locale+'-after-cancel.json');assert.equal(afterCancel.sha256,d.sha256);
 });
 }finally{await browser.close();report.status=report.cases.some(c=>c.status==='FAIL')||report.pageErrors.length?'FAIL':'PASS';fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(report,null,2));if(report.status!=='PASS')process.exitCode=1;console.log(JSON.stringify({status:report.status,cases:report.cases.length,failed:report.cases.filter(c=>c.status==='FAIL').map(c=>c.name),pageErrors:report.pageErrors}));}})();
