'use strict';
// The browser plugin is unavailable here; use the existing Playwright runtime.
// Real business controls and local CP-SAT; no injected study or result state.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_ENTERPRISE_EVIDENCE;assert.ok(out);fs.mkdirSync(out,{recursive:true});
const X=require(path.join(root,'vendor/xlsx/xlsx.full.min.js'));
const book=X.utils.book_new();
for(const [name,rows] of [
 ['Locations',[['name','code','role','coordinate'],['Origin A','S-A','FACTORY','120,30'],['Origin B','S-B','FACTORY','121,30'],['Hub East','W-E','DC','120.1,30'],['Hub West','W-W','DC','121.1,30']]],
 ['Demand',[['customerNumber','customer','assignedDepot','coordinate','2026-01'],['D-A','Shop Alpha','W-E','120.2,30',10],['D-B','Shop Beta','W-W','121.2,30',10]]],
 ['Inbound',[['flowId','fromNodeId','toNodeId','2026-01'],['F-A','S-A','W-E',10],['F-B','S-B','W-W',10]]]
])X.utils.book_append_sheet(book,X.utils.aoa_to_sheet(rows),name);
const workbook=X.write(book,{type:'buffer',bookType:'xlsx'});fs.writeFileSync(path.join(out,'synthetic-input.xlsx'),workbook);
const log={status:'RUNNING',classification:'SYNTHETIC_TEST',method:'HOME_PUBLIC_DATA_IMPORT_BUSINESS_CONTROLS_NATIVE_CP_SAT',checks:[],pageErrors:[]};
const save=()=>fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(log,null,2));
(async()=>{const browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--disable-webgl']});const ctx=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:950},reducedMotion:'reduce'});await ctx.route('**/*',r=>{const u=new URL(r.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?r.continue():r.abort()});const page=await ctx.newPage();page.setDefaultTimeout(25000);page.on('pageerror',e=>log.pageErrors.push(e.message));const field=n=>page.locator('[data-supply-field="'+n+'"]'),action=n=>page.locator('[data-supply-action="'+n+'"]'),state=()=>page.evaluate(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot());
async function download(n,name){const b=action(n);if(!await b.isVisible()){const d=b.locator('xpath=ancestor::details[1]');await d.locator('summary').click();}const got=page.waitForEvent('download');await b.click();await(await got).saveAs(path.join(out,name));}
try{await page.goto(process.env.STCT_ENTERPRISE_URL||'http://127.0.0.1:9865/index.html?optPort=9887&noWebGL=1#/');await page.locator('#loginForm .login-btn').click();await page.locator('.platform-home-action[data-platform-route="/platform/data"]').click();await page.locator('[data-v8-kind]').selectOption('SUPPLY_CHAIN_PERIOD');await page.locator('[data-p5-upload]').setInputFiles(path.join(out,'synthetic-input.xlsx'));await action('profile-confirm').waitFor();for(const index of ['1','2']){await page.locator('[data-supply-action="mapping-select"][data-supply-id="'+index+'"]').click();await field('blockUnit').selectOption('m3');if(index==='1'){await page.locator('[data-supply-map-field="demandId"]').selectOption('1');await page.locator('[data-supply-map-field="currentSiteId"]').selectOption('3');}}await field('studyName').fill('Synthetic generic full-cost acceptance');await action('profile-confirm').click();await field('analysisScope').waitFor();
let current=await state();assert.equal(current.study.periodDemand.length,2);assert.equal(current.study.observedInbound.length,2);assert.equal(current.study.nodes.filter(n=>n.role==='DC').length,2);
await field('geoConfirmed').check();await field('analysisScope').selectOption('FULL_CHAIN');await field('homogeneousDemandConfirmed').check();await field('allowAllSupplierSiteEdgesConfirmed').check();await field('sourceMode').selectOption('FREE');await field('supplierTotalMode').selectOption('ADJUSTABLE');await field('networkMode').selectOption('MULTI');for(const row of await page.locator('.sc-sites tbody tr:has(input[data-supply-site])').all())await row.locator('input[value="adjust"]').check();await field('minSites').fill('1');await field('maxSites').fill('2');
await page.locator('.sc-supplements summary:has-text("费率与费用范围")').click();for(const kind of ['INBOUND_TRANSPORT','OUTBOUND_TRANSPORT']){await page.locator('[data-supply-rate="'+kind+'"][data-rate-key="amount"]').fill('1');await page.locator('[data-supply-rate="'+kind+'"][data-rate-key="status"]').selectOption('KNOWN');}for(const kind of ['FIXED_OPERATING','HANDLING'])await page.locator('[data-supply-rate="'+kind+'"][data-rate-key="status"]').selectOption('CONFIRMED_ZERO');await page.locator('[data-supply-scope="inventoryHolding"]').check();await page.locator('[data-supply-scope="transferTransport"]').check();
await page.locator('.sc-supplements summary:has-text("各仓逐期容量")').click();for(const f of await page.locator('[data-supply-capacity]').all()){await f.fill('100');await f.press('Tab');}await field('capacityPolicy').selectOption('PROVIDED');for(const f of await page.locator('[data-supply-supplier-capacity]').all())await f.fill('100');await field('objective').selectOption('COST');await field('costMode').selectOption('ACTUAL');await field('conversionCost').fill('0');assert.equal(await page.locator('.sc-advanced textarea:visible').count(),0);
await action('analyze').click();await page.waitForFunction(()=>window.STCTPlatformV19.instance.designAdapter.supplySnapshot()?.snapshot?.scenario.objective==='COST',null,{timeout:90000});current=await state();fs.writeFileSync(path.join(out,'state.private.json'),JSON.stringify(current));assert.equal(current.snapshot.analysisScope,'FULL_CHAIN');assert.ok(current.snapshot.rows.length>=2);
const toRad=d=>d*Math.PI/180,km=(a,b)=>{const [x,y]=a.map(toRad),[xx,yy]=b.map(toRad),h=Math.sin((yy-y)/2)**2+Math.cos(y)*Math.cos(yy)*Math.sin((xx-x)/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));};const nodes=new Map(current.study.nodes.map(n=>[n.nodeId,n]));const checks=[];
for(const r of [current.snapshot.planningReference,...current.snapshot.rows]){const independent=[...r.inbound,...r.outbound].reduce((v,leg)=>v+leg.quantity*km(nodes.get(leg.fromNodeId).coordinate,nodes.get(leg.toNodeId).coordinate),0);assert.ok(Math.abs(independent-r.metrics.operatingCost)<1e-7,JSON.stringify({independent,actual:r.metrics.operatingCost}));assert.equal(r.capacityStatus,'PASS');assert.equal(r.metrics.outbound.volume,20);checks.push({id:r.scenarioId,independent,operatingCost:r.metrics.operatingCost,status:r.status});}
log.checks.push({name:'Generic import + native cost solve + independent geometry ledger',rows:checks});save();
const expected=current.snapshot.decision.rankedScenarioIds;assert.deepEqual(await page.locator('.sc-compare tr[data-scenario-id]').evaluateAll(es=>es.map(e=>e.dataset.scenarioId)),[...expected,...current.snapshot.rows.map(r=>r.scenarioId).filter(id=>!expected.includes(id))]);
await download('export-html','synthetic-full-cost.html');await download('export-csv','synthetic-full-cost.csv');await download('export-md','synthetic-full-cost.md');await download('package-export','synthetic-full-cost.package.json');await action('report-open').click();await page.locator('.scro-overlay .sc-advanced-toggle').click();await page.locator('.scro-overlay .rp-stage [data-advanced-feature="tco"]').click();const body=page.locator('.scro-overlay .rp-stage #sc-advanced-body');assert.equal(await body.locator('[data-tool-candidate]').getAttribute('data-tool-candidate'),current.snapshot.decision.focusScenarioId);assert.ok(!await body.locator('input').count());await page.screenshot({path:path.join(out,'synthetic-tco.png'),fullPage:true});
assert.deepEqual(log.pageErrors,[]);log.status='PASS';log.focus=current.snapshot.decision.focusScenarioId;log.snapshotHash=current.snapshot.snapshotHash;log.rankingBasis=current.snapshot.rankingBasis;
}catch(e){log.status='FAIL';log.error=e.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}finally{save();await browser.close();console.log(JSON.stringify(log));}})();
