'use strict';
const assert=require('node:assert/strict');
const Contract=require('../network-contract-v18.js');
const Controller=require('../supply-chain-controller-v19.js');
const Design=require('../supply-chain-design-v19.js');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
function memoryRepository(){const rows=new Map(),key=(store,id)=>`${store}:${id}`;return{record:(id,payload,refs=[])=>({id,payload:structuredClone(payload),refs,contentHash:Contract.hashArtifact(payload)}),async read(store,id){return id===undefined?[...rows.entries()].filter(([name])=>name.startsWith(`${store}:`)).map(([,row])=>structuredClone(row)):structuredClone(rows.get(key(store,id))||null);},async commit({records,pointer,expectedRevision}){const current=rows.get(key('pointers',pointer.id));assert.equal(current?.revision||0,expectedRevision);for(const [store,list]of Object.entries(records))for(const row of list)rows.set(key(store,row.id),structuredClone(row));const saved={...pointer,revision:expectedRevision+1};rows.set(key('pointers',pointer.id),structuredClone(saved));return{status:'SAVED',pointer:saved};}};}
const road=(fromNodeId,toNodeId,distanceKm)=>({fromNodeId,toNodeId,distanceKm,unit:'km',source:'TEST',quality:'VERIFIED_ROAD'});
const rates=['OUTBOUND_TRANSPORT','INBOUND_TRANSPORT'].map(kind=>({kind,status:'KNOWN',basis:'PER_UNIT_KM',amount:1})).concat([{kind:'FIXED_OPERATING',status:'KNOWN',basis:'PER_PERIOD',amount:0},{kind:'HANDLING',status:'KNOWN',basis:'PER_UNIT',amount:0}]);
const study=Design.createStudy({studyId:'CONTROLLER-SYNTHETIC',classification:'SYNTHETIC_TEST',costApplicability:{inventoryHolding:'NOT_APPLICABLE',transferTransport:'NOT_APPLICABLE'},nodes:[{nodeId:'F',role:'FACTORY'},{nodeId:'A',role:'DC',capacityByPeriod:{P1:10}},{nodeId:'B',role:'DC',capacityByPeriod:{P1:10}},{nodeId:'C',role:'CUSTOMER'}],periodDemand:[{demandId:'D',customerNodeId:'C',period:'P1',quantity:5,unit:'m3',currentSiteId:'A'}],observedInbound:[{flowId:'I',fromNodeId:'F',toNodeId:'A',period:'P1',quantity:5,unit:'m3'}],distanceRows:[road('A','C',10),road('B','C',4),road('F','A',2),road('F','B',20)],rates});
const repo=memoryRepository(),script=`import json,sys,ortools\nfrom ortools.sat.python import cp_model\nfrom facility_mvp1 import solve_facility\nprint(json.dumps(solve_facility(json.load(sys.stdin),cp_model,ortools.__version__)))`;
const fetch=async(_url,{body})=>{const run=spawnSync('python3',['-c',script],{cwd:path.resolve(__dirname,'../optimizer'),input:body,encoding:'utf8'});assert.equal(run.status,0,run.stderr);return{ok:true,json:async()=>JSON.parse(run.stdout)};};
(async()=>{
  const controller=Controller.createController({repository:repo,fetch});controller.loadStudy(study);controller.calculateBaseline();controller.configureScenario({scenarioId:'COMPARE',type:'NETWORK_CANDIDATE',objective:'COST',distanceBasis:'VERIFIED_ROAD',facilityCounts:[1,2],sourcePlan:[{sourceNodeId:'F',siteNodeId:'A',share:1},{sourceNodeId:'F',siteNodeId:'B',share:1}],oneTimeConversionCost:10});await controller.run();assert.ok(controller.snapshot().candidates.length>=2);controller.compare();const original=controller.snapshot().snapshot;assert.ok(original.snapshotHash);const saved=await controller.save();assert.equal(saved.status,'SAVED');assert.equal((await controller.listStudies()).length,1);const json=controller.exportReport('json'),csv=controller.exportReport('csv'),md=controller.exportReport('md'),html=controller.exportReport('html'),pack=controller.exportPackage();assert.ok(json.includes(original.snapshotHash));assert.ok(csv.includes('VERIFIED_ROAD'));assert.ok(md.includes('真实现状'));assert.ok(html.includes('供应链网络设计')&&!html.includes('计算附件 · 公式'));const copy=Controller.createController({repository:repo,fetch});await copy.reopen(saved.pointer.id);assert.equal(copy.snapshot().snapshot.snapshotHash,original.snapshotHash);const fresh=Controller.createController({repository:repo,fetch});fresh.importPackage(pack);assert.equal(fresh.snapshot().snapshot.snapshotHash,original.snapshotHash);const tampered=JSON.parse(pack);tampered.study.name='altered';assert.throws(()=>fresh.importPackage(tampered),{code:'SUPPLY_PACKAGE_INVALID'});controller.updateStudy({rates:[...study.rates,{kind:'INVENTORY_HOLDING',status:'KNOWN',basis:'PER_UNIT',amount:2}]});assert.equal(controller.snapshot().staleResult.snapshotHash,original.snapshotHash);assert.equal(controller.snapshot().staleResult.reason,'STUDY_INPUT_CHANGED');assert.throws(()=>controller.exportReport('json'),{code:'SUPPLY_SNAPSHOT_NOT_READY'});console.log(JSON.stringify({suite:'SUPPLY_CHAIN_CONTROLLER_V19',status:'PASS',candidateCount:copy.snapshot().candidates.length,savedReadback:true,formats:['json','csv','md','html'],staleBlocked:true}));
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
