#!/usr/bin/env node
"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");

function option(name, fallback) { const index = process.argv.indexOf(name); return index >= 0 ? process.argv[index + 1] : fallback; }
const baseUrl = option("--base-url", "http://127.0.0.1:19231/index.html?v=v17-browser-gate");
const evidenceDir = path.resolve(option("--evidence-dir", "/tmp/stct-v17-browser-evidence"));
const evidencePath = path.resolve(option("--evidence", path.join(evidenceDir, "browser-report.json")));
const chromePath = process.env.STCT_CHROME_PATH || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const assertions = []; const consoleRows = []; const screenshots = []; const workflows = [];
function check(requirementId, condition, observed, expected, evidence = evidencePath) { const row = { assertionId: `${requirementId}-A1`, requirementId, status: condition ? "PASS" : "FAIL", observed, expected, evidence }; assertions.push(row); assert(condition, `${requirementId}: ${JSON.stringify({ observed, expected })}`); }
async function shot(page, name, group) { const target = path.join(evidenceDir, `${group}-${name}.png`); await page.screenshot({ path: target, fullPage: false }); screenshots.push({ group, name, path: target, bytes: fs.statSync(target).size }); return target; }
function urlWith(query) { const url = new URL(baseUrl); Object.entries(query || {}).forEach(([key, value]) => url.searchParams.set(key, value)); return url.toString(); }
async function openExperience(browser, options = {}) {
  const context = await browser.newContext({ viewport: options.viewport || { width: 1440, height: 900 }, locale: options.browserLocale || "en-US", reducedMotion: options.reducedMotion ? "reduce" : "no-preference", acceptDownloads: true });
  const page = await context.newPage();
  page.on("pageerror", (error) => consoleRows.push({ type: "pageerror", text: error.message, surface: options.name }));
  page.on("console", (message) => { if (["error", "warning"].includes(message.type())) consoleRows.push({ type: message.type(), text: message.text(), surface: options.name, location: message.location() }); });
  await page.goto(urlWith(options.query), { waitUntil: "domcontentloaded", timeout: 120000 });
  await page.selectOption("#loginLang", options.locale || "en");
  await page.fill("#loginUser", "demo"); await page.fill("#loginPass", "demo123"); await page.click(".login-btn");
  await page.waitForFunction(() => getComputedStyle(document.getElementById("loginScreen")).display === "none");
  await page.click("[data-v17-open]"); await page.waitForSelector("#v17Experience");
  return { context, page };
}

async function main() {
  fs.mkdirSync(evidenceDir, { recursive: true });
  const browser = await chromium.launch({ executablePath: chromePath, headless: true, args: ["--disable-background-timer-throttling", "--disable-renderer-backgrounding"] });
  try {
    const desktop = await openExperience(browser, { name: "desktop", locale: "en", viewport: { width: 1440, height: 900 } }); const page = desktop.page;
    const desktopFleet = await page.evaluate(() => ({ tracks: document.querySelectorAll("[data-v17-track]").length, rows: document.querySelectorAll('[data-v17-table="fleet"] tbody tr').length, vehicles: STCTV17.experienceUI.state.model.scenario.routes.length, stops: STCTV17.experienceUI.state.model.scenario.stops.length }));
    await shot(page, "fleet", "desktop"); check("T551", desktopFleet.tracks === 20 && desktopFleet.rows === 20 && desktopFleet.vehicles === 20 && desktopFleet.stops === 240, desktopFleet, { tracks: 20, rows: 20, vehicles: 20, stops: 240 });
    await page.click('[data-v17-tab="telemetry"]'); const telemetryView = await page.evaluate(() => ({ panel: Boolean(document.querySelector('[data-v17-panel="telemetry"]')), reported: document.body.innerText.includes("Reported by device"), derived: document.body.innerText.includes("Derived by STCT"), confidence: document.body.innerText.includes("Match confidence") })); await shot(page, "telemetry", "desktop"); check("T552", Object.values(telemetryView).every(Boolean), telemetryView, "Verified Telemetry Inspector visible");
    await page.click('[data-v17-tab="review"]'); const reviewView = await page.evaluate(() => ({ panel: Boolean(document.querySelector('[data-v17-panel="review"]')), routes: document.querySelectorAll('[data-v17-table="review"] tbody tr').length, recorder: document.querySelectorAll("[data-v17-recorder-index]").length, description: document.getElementById("v17ReviewDescription")?.textContent.length || 0 })); await shot(page, "review", "desktop"); check("T553", reviewView.panel && reviewView.routes === 20 && reviewView.recorder > 0 && reviewView.description > 80, reviewView, "Desktop Shift Review");
    await page.click('[data-v17-tab="conflicts"]'); const conflictView = await page.evaluate(() => ({ panel: Boolean(document.querySelector('[data-v17-panel="conflicts"]')), pending: document.querySelectorAll("[data-conflict-id]").length, actions: document.querySelectorAll("[data-v17-conflict]").length })); await shot(page, "conflicts", "desktop"); check("T554", conflictView.panel && conflictView.pending === 6 && conflictView.actions === 18, conflictView, "Desktop Offline Conflict");
    for (const action of ["ack", "handling", "resolve"]) { await page.focus(`[data-v17-alert="${action}"]`); await page.keyboard.press("Enter"); }
    const alertState = await page.evaluate(() => STCTV17.experienceUI.snapshot().workspace.alerts.alerts.find((row) => row.alertId === "V17-ALERT-01").state); workflows.push({ id: "desktop-alert", result: alertState });
    await page.focus('[data-v17-conflict="keep"]'); await page.keyboard.press("Enter"); const conflictStatus = await page.evaluate(() => STCTV17.experienceUI.snapshot().conflictStatuses.find((row) => row.id === "LOCAL-001")); workflows.push({ id: "desktop-conflict", result: conflictStatus });
    await page.click('[data-v17-tab="recovery"]'); await page.click('[data-v17-action="recovery-preview"]'); await page.click('[data-v17-action="recovery-apply"]'); const recoveryState = await page.evaluate(() => ({ revision: STCTV17.experienceUI.snapshot().workspace.planRevision, effect: STCTV17.experienceUI.state.lastRecoveryEffect, events: STCTV17.experienceUI.state.model.workspace.events().filter((row) => row.eventType === "RECOVERY_APPLIED").length })); await shot(page, "recovery", "desktop"); check("T555", recoveryState.revision === 2 && recoveryState.events === 1 && recoveryState.effect.startsWith("APPLIED"), recoveryState, "Desktop Domain-Wired Recovery"); workflows.push({ id: "desktop-recovery", result: recoveryState });
    await page.click('[data-v17-action="export-capsule"]'); await page.waitForFunction(() => STCTV17.experienceUI.snapshot().downloads.length > 0, null, { timeout: 30000 }); const capsuleDownload = await page.evaluate(() => STCTV17.experienceUI.snapshot().downloads.at(-1)); workflows.push({ id: "capsule-export", result: capsuleDownload });

    await page.click('[data-v17-tab="fleet"]'); await page.focus('[data-v17-action="vehicle-next"]'); await page.keyboard.press("Enter"); const fleetKeyboard = await page.evaluate(() => ({ selected: STCTV17.experienceUI.state.selectedVehicle, focused: document.activeElement?.dataset?.v17Action || "" })); check("T575", fleetKeyboard.selected === 1 && fleetKeyboard.focused === "vehicle-next", fleetKeyboard, "Keyboard Fleet step-through");
    const driverBefore = await page.evaluate(() => STCTV17.experienceUI.state.driverStage); for (let index = 0; index < 3; index += 1) { await page.focus('[data-v17-action="driver-next"]'); await page.keyboard.press("Enter"); } const driverAfter = await page.evaluate(() => STCTV17.experienceUI.state.driverStage); check("T576", driverBefore === 0 && driverAfter === 3, { driverBefore, driverAfter }, { driverBefore: 0, driverAfter: 3 });
    check("T577", alertState === "RESOLVED", alertState, "Keyboard Alert workflow reaches RESOLVED");
    check("T578", conflictStatus.status === "KEPT_LOCAL" && conflictStatus.action === "KEEP", conflictStatus, "Keyboard conflict resolution");
    await page.click('[data-v17-tab="review"]'); await page.focus('[data-v17-recorder-index="0"]'); await page.keyboard.press("ArrowDown"); const recorderFocus = await page.evaluate(() => document.activeElement?.dataset?.v17RecorderIndex); await page.keyboard.press("Enter"); const recorderSelection = await page.evaluate(() => STCTV17.experienceUI.snapshot().workspace.selection.eventId); check("T579", recorderFocus === "1" && recorderSelection, { recorderFocus, recorderSelection }, "Keyboard Shift Review");
    const visibleFocus = await page.evaluate(() => { const node = document.activeElement; const style = getComputedStyle(node); return { tag: node?.tagName, outlineStyle: style.outlineStyle, outlineWidth: style.outlineWidth }; }); check("T580", visibleFocus.tag === "BUTTON" && visibleFocus.outlineStyle !== "none" && parseFloat(visibleFocus.outlineWidth) >= 3, visibleFocus, "visible focus");
    await page.click('[data-v17-tab="fleet"]'); await page.focus('[data-v17-action="vehicle-next"]'); await page.keyboard.press("Enter"); const focusAfterRefresh = await page.evaluate(() => document.activeElement?.dataset?.v17Action); check("T581", focusAfterRefresh === "vehicle-next", focusAfterRefresh, "focus preserved across render");
    const encoding = await page.evaluate(() => ({ badges: [...document.querySelectorAll(".v17-status")].every((node) => node.textContent.trim().length > 1 && node.querySelector("b")), patterns: new Set([...document.querySelectorAll("[data-v17-track]")].map((node) => node.getAttribute("stroke-dasharray"))).size, icon: Boolean(document.querySelector(".v17-vehicle-icon")) })); check("T582", encoding.badges, encoding, "Color has text/icon duplicate"); check("T583", encoding.patterns >= 3 && encoding.icon, encoding, "Track pattern and vehicle icon");
    await page.click('[data-v17-tab="telemetry"]'); const confidenceText = await page.locator(".v17-confidence").innerText(); check("T584", /HIGH/.test(confidenceText) && /Snap/.test(confidenceText), confidenceText, "confidence direct text");
    const focusAlternatives = await page.evaluate(() => ({ tracksFocusable: [...document.querySelectorAll("[data-v17-track]")].every((node) => node.tabIndex === 0), buttons: document.querySelectorAll("button").length })); check("T585", focusAlternatives.tracksFocusable && focusAlternatives.buttons > 5, focusAlternatives, "Hover has focus/tap alternative");
    await page.click('[data-v17-tab="fleet"]'); const dragAlternative = await page.evaluate(() => ({ draggable: document.querySelectorAll('[draggable="true"]').length, stepButtons: document.querySelectorAll('[data-v17-action="vehicle-prev"],[data-v17-action="vehicle-next"]').length })); check("T586", dragAlternative.draggable === 0 && dragAlternative.stepButtons === 2, dragAlternative, "Drag has previous/next button alternative");
    await page.click('[data-v17-action="driver-next"]'); await page.click('[data-v17-action="driver-next"]'); await page.waitForTimeout(220); const liveState = await page.evaluate(() => ({ live: document.getElementById("v17Live").textContent, diagnostics: STCTV17.experienceUI.diagnostics() })); check("T587", /stage/.test(liveState.live) && liveState.diagnostics.positionAnnouncements === 0, liveState, "ARIA live critical updates throttled"); check("T588", liveState.diagnostics.positionAnnouncements === 0 && !/POSITION_RECORDED/.test(liveState.live), liveState, "positions not announced");
    check("T589", desktopFleet.rows === desktopFleet.tracks && desktopFleet.rows === 20, desktopFleet, "fleet table equivalent"); await page.click('[data-v17-tab="telemetry"]'); const telemetryRows = await page.locator('[data-v17-table="telemetry"] tbody tr').count(); check("T590", telemetryRows === 1, telemetryRows, "telemetry table equivalent"); await page.click('[data-v17-tab="review"]'); check("T591", reviewView.description > 80, reviewView.description, ">80 character Shift Review long description");
    await desktop.context.close();

    const mobile = await openExperience(browser, { name: "mobile", locale: "en", viewport: { width: 390, height: 844 } }); const mp = mobile.page; await shot(mp, "fleet", "mobile");
    const initialPrevDisabled = await mp.locator('[data-v17-action="driver-prev"]').isDisabled(); for (let index = 0; index < 3; index += 1) await mp.click('[data-v17-action="driver-next"]'); const mobileDriver = await mp.evaluate(() => ({ stage: STCTV17.experienceUI.state.driverStage, offline: STCTV17.experienceUI.state.driverOffline, width: document.querySelector("#v17Experience").scrollWidth, viewport: innerWidth })); check("T556", mobileDriver.stage === 3 && mobileDriver.offline === true && mobileDriver.width <= mobileDriver.viewport, mobileDriver, "Mobile driver offline multi-step");
    await mp.click('[data-v17-tab="conflicts"]'); await shot(mp, "conflicts", "mobile"); await mp.click('[data-v17-conflict="retry"]'); const mobileConflict = await mp.evaluate(() => STCTV17.experienceUI.snapshot().conflictStatuses.find((row) => row.id === "LOCAL-001")); check("T557", mobileConflict.status === "RETRY_PENDING", mobileConflict, "Mobile conflict resolution");
    await mp.click('[data-v17-tab="fleet"]'); await mp.click('[data-v17-action="vehicle-next"]'); const mobileFleet = await mp.evaluate(() => ({ selected: STCTV17.experienceUI.state.selectedVehicle, tracks: document.querySelectorAll("[data-v17-track]").length })); check("T558", mobileFleet.selected === 1 && mobileFleet.tracks === 20, mobileFleet, "Mobile Fleet Replay");
    await mp.click('[data-v17-tab="review"]'); await shot(mp, "review", "mobile"); const mobileReview = await mp.evaluate(() => ({ panel: Boolean(document.querySelector('[data-v17-panel="review"]')), table: document.querySelectorAll('[data-v17-table="review"] tbody tr').length, overflow: document.querySelector("#v17Experience").scrollWidth - innerWidth })); check("T559", mobileReview.panel && mobileReview.table === 20 && mobileReview.overflow <= 0, mobileReview, "Mobile Shift Review");
    const mobileCss = fs.readFileSync(path.resolve(__dirname, "../experience-v17.css"), "utf8"); check("T592", mobileCss.includes("env(safe-area-inset-bottom)"), "safe-area-inset-bottom", "mobile safe area CSS"); await mp.click('[data-v17-tab="fleet"]'); const touchAction = await mp.locator(".v17-fleet-svg").evaluate((node) => getComputedStyle(node).touchAction); check("T593", touchAction === "manipulation" || (/pan-x/.test(touchAction) && /pinch-zoom/.test(touchAction)), touchAction, "pinch and scroll policy"); const obstruction = await mp.evaluate(() => ({ fixedPanels: [...document.querySelectorAll(".v17-panel,.v17-driver")].filter((node) => getComputedStyle(node).position === "fixed").length, driverHeight: document.querySelector(".v17-driver").getBoundingClientRect().height })); check("T594", obstruction.fixedPanels === 0 && obstruction.driverHeight > 0, obstruction, "no fixed bottom sheet obscures critical state");
    const readableStates = await mp.locator("#v17Experience").innerText(); check("T595", readableStates.includes("Offline"), readableStates.slice(0, 300), "offline state readable"); check("T596", readableStates.includes("PARTIAL_EVENTS"), readableStates.slice(0, 300), "stale state readable"); check("T597", readableStates.includes("Partial data"), readableStates.slice(0, 300), "partial state readable"); await mp.click('[data-v17-tab="conflicts"]'); const conflictText = await mp.locator("#v17PanelHost").innerText(); check("T598", conflictText.includes("PENDING") && conflictText.includes("SEQUENCE_CONFLICT"), conflictText.slice(0, 300), "conflict state readable"); await mp.click('[data-v17-tab="fleet"]'); await mp.click('[data-v17-action="driver-next"]'); const disabledAfter = await mp.locator('[data-v17-action="driver-prev"]').isDisabled(); check("T599", initialPrevDisabled === true && disabledAfter === false, { initialPrevDisabled, disabledAfter }, "disabled state reflects real driver stage");
    const mobileDiagnostics = await mp.evaluate(() => STCTV17.experienceUI.diagnostics()); check("T600", mobileDiagnostics.inertPrimaryControls.length === 0 && Object.keys(mobileDiagnostics.actionCounts).length > 0, mobileDiagnostics, "primary controls are not inert"); await mobile.context.close();

    const landscape = await openExperience(browser, { name: "landscape", locale: "en", viewport: { width: 844, height: 390 } }); const landscapeInfo = await landscape.page.evaluate(() => ({ timeline: document.querySelector(".v17-timeline")?.getBoundingClientRect(), viewport: { width: innerWidth, height: innerHeight }, buttons: document.querySelectorAll(".v17-timeline button").length })); await shot(landscape.page, "timeline", "mobile-landscape"); check("T560", landscapeInfo.buttons === 10 && landscapeInfo.timeline.width > 200 && landscapeInfo.timeline.height > 100, landscapeInfo, "Mobile landscape Timeline"); await landscape.context.close();

    const noWebGL = await openExperience(browser, { name: "no-webgl", locale: "en", query: { "no-webgl": "1" }, viewport: { width: 1280, height: 800 } }); const np = noWebGL.page; const noWebglOps = await np.evaluate(() => ({ mode: STCTV17.experienceUI.snapshot().noWebGL, fallback: Boolean(document.querySelector(".v17-no-map")), tableRows: document.querySelectorAll('[data-v17-table="fleet"] tbody tr').length })); check("T561", noWebglOps.mode && noWebglOps.fallback && noWebglOps.tableRows === 20, noWebglOps, "No-WebGL Operations"); await np.click('[data-v17-tab="telemetry"]'); const noWebglTelemetry = await np.evaluate(() => ({ table: document.querySelectorAll('[data-v17-table="telemetry"] tbody tr').length, mode: STCTV17.experienceUI.snapshot().noWebGL })); check("T562", noWebglTelemetry.mode && noWebglTelemetry.table === 1, noWebglTelemetry, "No-WebGL Telemetry"); await np.click('[data-v17-tab="review"]'); const noWebglReview = await np.evaluate(() => ({ table: document.querySelectorAll('[data-v17-table="review"] tbody tr').length, description: document.getElementById("v17ReviewDescription").textContent.length })); await shot(np, "review", "no-webgl"); check("T563", noWebglReview.table === 20 && noWebglReview.description > 80, noWebglReview, "No-WebGL Shift Review"); await noWebGL.context.close();

    const reduced = await openExperience(browser, { name: "reduced", locale: "en", query: { "reduced-motion": "1" }, reducedMotion: true, viewport: { width: 1280, height: 800 } }); const rp = reduced.page; const reducedFleet = await rp.evaluate(() => ({ mode: STCTV17.experienceUI.snapshot().reducedMotion, className: document.getElementById("v17Experience").className, animation: getComputedStyle(document.querySelector(".v17-track")).animationDuration })); await shot(rp, "fleet", "reduced-motion"); check("T564", reducedFleet.mode && reducedFleet.className.includes("is-reduced-motion") && ["0s", "auto"].includes(reducedFleet.animation), reducedFleet, "Reduced Motion Fleet"); await rp.click('[data-v17-tab="recovery"]'); await rp.click('[data-v17-action="recovery-preview"]'); const reducedRecovery = await rp.evaluate(() => ({ selected: STCTV17.experienceUI.snapshot().workspace.selectedCandidateHash, mode: STCTV17.experienceUI.snapshot().reducedMotion })); check("T565", reducedRecovery.mode && reducedRecovery.selected, reducedRecovery, "Reduced Motion Recovery keeps domain action"); await reduced.context.close();

    const localeResults = {};
    for (const locale of ["zh", "en", "ja"]) { const app = await openExperience(browser, { name: `locale-${locale}`, locale, viewport: { width: 1024, height: 768 } }); localeResults[locale] = await app.page.evaluate(() => ({ lang: document.documentElement.lang, title: document.querySelector(".v17-header h2").textContent, tabs: [...document.querySelectorAll("[data-v17-tab]")].map((node) => node.textContent), pageIdentity: document.getElementById("v17Experience").dataset.pageIdentity, textLength: document.getElementById("v17Experience").innerText.length, overlays: document.querySelectorAll('[class*="error-overlay"],iframe[title*="error" i]').length })); await app.context.close(); }
    check("T566", localeResults.zh.title === "多车辆执行控制台" && localeResults.zh.tabs.includes("可信遥测"), localeResults.zh, "Chinese complete"); check("T567", localeResults.en.title === "Multi-Vehicle Execution Control" && localeResults.en.tabs.includes("Verified Telemetry"), localeResults.en, "English complete"); check("T568", localeResults.ja.title === "複数車両実行コントロール" && localeResults.ja.tabs.includes("検証済みテレメトリ"), localeResults.ja, "Japanese complete");
    check("T569", Object.values(localeResults).every((row) => row.pageIdentity === "STCT_OPERATIONAL_TRUTH"), localeResults, "page identity"); check("T570", Object.values(localeResults).every((row) => row.textLength > 500), localeResults, "non-empty pages"); check("T571", Object.values(localeResults).every((row) => row.overlays === 0), localeResults, "no framework overlay");
    const appErrors = consoleRows.filter((row) => row.type === "pageerror" || row.type === "error"); const warnings = consoleRows.filter((row) => row.type === "warning"); const warningClassification = warnings.map((row) => ({ ...row, classification: /map|tile|webgl/i.test(row.text) ? "EXTERNAL_MAP_WARNING" : "UNEXPLAINED" })); check("T572", appErrors.length === 0, appErrors, 0); check("T573", warningClassification.filter((row) => row.classification === "UNEXPLAINED").length === 0, warningClassification, "0 unexplained warnings"); check("T574", warningClassification.every((row) => row.classification === "EXTERNAL_MAP_WARNING"), warningClassification, "external map warnings classified");
    check("T601", recoveryState.revision === 2 && recoveryState.events === 1, recoveryState, "Recovery button has domain side effect"); check("T602", capsuleDownload.status === "DOWNLOADED" && capsuleDownload.bytes > 1000 && capsuleDownload.filename.endsWith(".json"), capsuleDownload, "Capsule button creates real file");
    const designContract = path.resolve(__dirname, "../V17_VISUAL_DESIGN_CONTRACT.md"); const mismatchLedger = path.resolve(__dirname, "../V17_VISUAL_MISMATCH_LEDGER.md"); check("T603", fs.existsSync(designContract) && fs.readFileSync(designContract, "utf8").includes("Required Scenarios"), designContract, "Visual Design Contract"); check("T604", fs.existsSync(mismatchLedger) && fs.readFileSync(mismatchLedger, "utf8").includes("Runtime status"), mismatchLedger, "Mismatch Ledger");
    const desktopShots = screenshots.filter((row) => row.group === "desktop"); const mobileShots = screenshots.filter((row) => row.group.startsWith("mobile")); check("T605", desktopShots.length >= 5 && desktopShots.every((row) => row.bytes > 10000), desktopShots, ">=5 desktop screenshots"); check("T606", mobileShots.length >= 3 && mobileShots.every((row) => row.bytes > 5000), mobileShots, ">=3 mobile screenshots"); const noWebglShot = screenshots.find((row) => row.group === "no-webgl"); const reducedShot = screenshots.find((row) => row.group === "reduced-motion"); check("T607", noWebglShot?.bytes > 5000, noWebglShot, "No-WebGL screenshot"); check("T608", reducedShot?.bytes > 5000, reducedShot, "Reduced Motion screenshot");
    const browserApi = { runner: "Playwright chromium", chromePath, baseUrl, command: "node tests/test_browser_accessibility_v17.js --base-url <local-url> --evidence-dir <dir>", viewports: ["1440x900", "390x844", "844x390", "1280x800"], apiCalls: ["page.goto", "page.click", "page.keyboard.press", "page.screenshot", "page.evaluate"] }; check("T609", browserApi.runner && browserApi.apiCalls.length >= 5, browserApi, "Browser command/API recorded"); const ledgerText = fs.readFileSync(mismatchLedger, "utf8"); check("T610", ledgerText.includes("BLOCKED_MEASUREMENT") && ledgerText.includes("Physical iPhone"), ledgerText.match(/Physical iPhone[^\n]*/), "unmeasured physical device marked BLOCKED_MEASUREMENT"); check("T611", workflows.length >= 4 && workflows.some((row) => row.id === "desktop-recovery") && workflows.some((row) => row.id === "capsule-export"), workflows, "actual core workflow evidence");
    const report = { schemaVersion: "stct-browser-accessibility-report-v1.7", status: "PASS", assertions, screenshots, workflows, console: consoleRows, warningClassification, localeResults, browserApi, boundaries: ["LOCAL_SYNTHETIC_NOT_LIVE_FLEET", "NO_LIVE_GPS", "PHYSICAL_IPHONE_BLOCKED_MEASUREMENT"] };
    fs.writeFileSync(evidencePath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
    process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, evidencePath, screenshots: screenshots.length, appErrors: appErrors.length, warnings: warnings.length }, null, 2)}\n`);
  } finally { await browser.close(); }
}
main().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exit(1); });
