#!/usr/bin/env node
'use strict';
// Explicit synthetic runtime vectors, separate from native-study business acceptance.
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=process.env.STCT_MAP_COMPONENT_EVIDENCE||path.join(require('node:os').tmpdir(),'stct-map-ux-component');fs.mkdirSync(out,{recursive:true});
const result={status:'RUNNING',kind:'Synthetic map component only; not a native solve or a UC business result',checks:[],errors:[]};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,body)=>error?res.writeHead(404).end():res.writeHead(200,{'content-type':({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json'})[path.extname(file)]||'application/octet-stream'}).end(body));});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.STCT_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(15000);page.on('pageerror',e=>result.errors.push(e.message));let styles=0;
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='tiles.openfreemap.org'&&u.pathname.startsWith('/styles/')){styles++;if(styles===1)return route.abort();return route.fulfill({contentType:'application/json',body:JSON.stringify({version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#e9eef7'}}]})});}return ['127.0.0.1','localhost'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?route.continue():route.abort();});
 await page.goto(`http://127.0.0.1:${server.address().port}/index.html#/`);await page.locator('#loginForm .login-btn').click();await page.locator('.platform-home').waitFor();
 await page.evaluate(()=>{
  const slot=document.createElement('div');slot.id='map-ux-fixture';slot.style.cssText='width:min(96vw,1100px);margin:30px auto';document.body.append(slot);
  const study={studyId:'MAP-UX-SYNTHETIC',inputHash:'SYNTHETIC-HASH',unit:'m3',coordinateUse:'CONFIRMED_WGS84',periods:['P1'],nodes:[
   {nodeId:'S',role:'FACTORY',name:'共享园区',coordinateSystem:'WGS84',coordinate:[119,31]},
   {nodeId:'A',role:'DC',name:'共享园区',coordinateSystem:'WGS84',coordinate:[119,31]},
   {nodeId:'B',role:'DC',name:'候选仓',coordinateSystem:'WGS84',coordinate:[120,31]},
   {nodeId:'C',role:'CUSTOMER',name:'<img src=x onerror=window.mapUnsafe=1>送货地',coordinateSystem:'WGS84',coordinate:[121,31]},
   {nodeId:'M',role:'CUSTOMER',name:'缺坐标对象',coordinateSystem:'UNKNOWN'}]};
  const leg=(fromNodeId,toNodeId)=>({fromNodeId,toNodeId,period:'P1',quantity:0.000001});
  const snapshot={schemaVersion:'stct-supply-chain-v5-snapshot-v1',studyHash:study.inputHash,snapshotHash:'SYNTHETIC-SNAPSHOT',analysisScope:'FULL_CHAIN',distanceBasis:'GEOGRAPHIC_SCREENING',planningReference:{inbound:[leg('S','A')],outbound:[leg('A','C')]},rows:[{scenarioId:'TEST-CANDIDATE',selectedSiteIds:['B'],inbound:[leg('S','B')],outbound:[leg('B','C')]}],decision:{focusScenarioId:'TEST-CANDIDATE'}};
  const model=window.STCTPlatformV19.supplyMap.projectComparison(study,snapshot,{mode:'BOTH'},'zh');window.mapUxFixture={slot,model};window.STCTPlatformV19.mapRuntime.mount(slot,model,{locale:'zh',route:'/design/supply-chain-study'});
 });
 const host=page.locator('#map-ux-fixture'),diag=()=>page.evaluate(()=>window.STCTPlatformV19.mapRuntime.diagnostics());
 await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-relations-candidate'));await host.locator('.p7-map-viewport').scrollIntoViewIfNeeded();await page.waitForTimeout(300);
 const initial=await page.evaluate(()=>JSON.stringify(window.mapUxFixture.model));
 const pos=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.project('S')),box=await host.locator('.p7-map-canvas').boundingBox();await page.mouse.click(box.x+pos.x,box.y+pos.y);await host.locator('.p7-map-picker').waitFor();
 assert.deepEqual((await host.locator('[data-p7-pick]').evaluateAll(es=>es.map(e=>e.dataset.p7Pick))).sort(),['A','S']);assert.match(await host.locator('[data-p7-pick="A"]').innerText(),/仓库/);assert.match(await host.locator('[data-p7-pick="S"]').innerText(),/供应商/);
 await host.locator('[data-p7-pick="S"]').press('Enter');assert.equal((await diag()).viewStates.SUPPLY.selectedEntityId,'S');await host.locator('[data-p7-related]').click();assert.equal((await diag()).mapInstances,1);assert.equal(await page.evaluate(()=>JSON.stringify(window.mapUxFixture.model)),initial);
 const camera=(await diag()).viewStates.SUPPLY;await host.locator('[data-p7-basemap-retry]').click();await page.waitForFunction(()=>window.STCTPlatformV19.mapRuntime.diagnostics().layers.includes('p7-supply-relations-reference')&&window.STCTPlatformV19.mapRuntime.diagnostics().basemap.status==='LOADED');assert.equal((await diag()).viewStates.SUPPLY.selectedEntityId,'S');assert.ok(Math.abs((await diag()).viewStates.SUPPLY.zoom-camera.zoom)<.01);assert.ok((await diag()).renderedEntityIds.every(id=>['S','A','B'].includes(id)));
 result.checks.push({name:'Exact same coordinate and same name factory/DC remain separate; keyboard pick; immutable model; connected focus; visible retry keeps camera and focus',status:'PASS'});
 await host.locator('[data-p7-clear-focus]').click();await page.waitForTimeout(300);const c=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.project('C')),b=await host.locator('.p7-map-canvas').boundingBox();await page.mouse.move(b.x+c.x,b.y+c.y);await host.locator('.p7-map-tooltip').waitFor();assert.match(await host.locator('.p7-map-tooltip').innerText(),/<img src=x/);assert.equal(await host.locator('.p7-map-tooltip img').count(),0);assert.equal(await page.evaluate(()=>window.mapUnsafe),undefined);
 const bb=await host.locator('.p7-map-canvas').boundingBox();
 const a=await page.evaluate(()=>window.STCTPlatformV19.mapRuntime.project('A'));await page.mouse.move(bb.x+a.x*.67+c.x*.33,bb.y+a.y*.67+c.y*.33);await host.locator('.p7-map-tooltip').waitFor();assert.match(await host.locator('.p7-map-tooltip').innerText(),/<0\.1/);assert.equal(await page.evaluate(()=>window.mapUxFixture.model.relations.find(r=>r.fromNodeId==='S'&&r.toNodeId==='B').after),0.000001);
 result.checks.push({name:'Imported HTML names escaped; small positive volume in the tooltip is not displayed as zero',status:'PASS'});
 await page.evaluate(()=>{const f=window.mapUxFixture;window.STCTPlatformV19.mapRuntime.mount(f.slot,f.model,{locale:'zh',route:'/design/supply-chain-study',noWebGL:true});});assert.equal((await diag()).mode,'SCHEMATIC');const marker=host.locator('.p7-map-schematic [role="button"][data-p7-entity="S"]');await marker.focus();await marker.press('Enter');assert.equal((await diag()).viewStates.SUPPLY.selectedEntityId,'S');await host.locator('[data-p7-clear-focus]').click();if(!await host.locator('.p7-entity-details').evaluate(e=>e.open))await host.locator('.p7-entity-details summary').click();await host.locator('[data-p7-kind="customer"]').click();await host.locator('.p7-map-list [data-p7-entity="M"]').click();assert.match(await host.locator('.p7-map-focusbar').innerText(),/没有可定位/);assert.equal(await page.evaluate(()=>JSON.stringify(window.mapUxFixture.model)),initial);
 await page.emulateMedia({media:'print'});assert.equal(await host.locator('.p7-map-focusbar [role=status]').isVisible(),true);assert.equal(await host.locator('[data-p7-related]').isVisible(),false);await page.emulateMedia({media:'screen'});result.checks.push({name:'No-WebGL SVG keyboard; coordinate-missing object remains selectable and explicitly non-locatable',status:'PASS'});
 assert.deepEqual(result.errors,[]);result.status='PASS';
 }catch(e){result.status='FAIL';result.error=e.stack;process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}})();
