#!/usr/bin/env node
"use strict";

const assert = require("assert");
const Contract = require("../network-contract-v18.js");
const Network = require("../network-solver-v18.js");
const Custody = require("../pickup-custody-v18.js");
const Accounting = require("../network-accounting-v18.js");
const { makeNetwork } = require("./fixtures/network-v18-fixture.js");

const assertions = [];
function check(requirementId, condition, observed, expected, negative = false) {
  const row = { assertionId: `${requirementId}-A1`, requirementId, status: condition ? "PASS" : "FAIL", observed, expected, negative, evidence: "tests/test_network_accounting_v18.js" };
  assertions.push(row); assert(condition, `${requirementId}: ${JSON.stringify({ observed, expected })}`);
}
const clone = (value) => structuredClone(value); const sum = (values) => Math.round(values.reduce((total, value) => total + value, 0) * 1000) / 1000;
function sourceFixture(orderCount = 20, depotCount = 2, vehicleCount = 4) { const source = makeNetwork({ depotCount, vehicleCount, orderCount }); source.depots.forEach((depot) => { depot.capacity.volume = 100000; depot.capacity.weight = 100000; depot.capacity.handlingMinutes = 100000; }); return source; }

const source = sourceFixture(); const plan = Network.solveNetwork(source, { maxStopsPerTrip: 4 }); const started = performance.now(); const ledger = Accounting.computeAccounting(source, plan); const accountingElapsed = performance.now() - started; const verification = Accounting.verifyAccounting(source, plan, ledger);
check("T0480", ledger.conservation.orders.status === "PASS" && ledger.conservation.orders.assigned + ledger.conservation.orders.unassigned + ledger.conservation.orders.blocked === ledger.conservation.orders.expected, ledger.conservation.orders, "exact order conservation");
const pairSource = makeNetwork({ depotCount: 1, vehicleCount: 2, orderCount: 2, pickupDelivery: true }); const pairPlan = Network.solveNetwork(pairSource, { maxStopsPerTrip: 2 }); const pairLedger = Accounting.computeAccounting(pairSource, pairPlan);
check("T0481", pairLedger.conservation.shipments.expected === 1 && pairLedger.conservation.shipments.status === "PASS" && pairLedger.conservation.shipments.rows[0].custodyEvents > 0, pairLedger.conservation.shipments, "exact shipment conservation");
check("T0482", ledger.conservation.vehicleTime.status === "PASS" && ledger.conservation.vehicleTime.overlaps.length === 0, ledger.conservation.vehicleTime, "vehicle time conservation");
check("T0483", ledger.conservation.driverTime.status === "PASS" && ledger.conservation.driverTime.overlaps.length === 0, ledger.conservation.driverTime, "driver time conservation");
check("T0484", ledger.conservation.dockIntervals.status === "PASS" && ledger.conservation.dockIntervals.violations.length === 0, ledger.conservation.dockIntervals, "dock interval conservation");
check("T0485", ledger.conservation.waveOrders.status === "PASS" && ledger.conservation.waveOrders.missing.length === 0, ledger.conservation.waveOrders, "wave order conservation");
check("T0486", ledger.conservation.tripLoads.status === "PASS" && ledger.conservation.tripLoads.rows.every((row) => row.volume <= row.capacityVolume && row.weight <= row.capacityWeight), ledger.conservation.tripLoads, "trip load conservation");
const crossSource = makeNetwork({ depotCount: 2, vehicleCount: 2, orderCount: 2, pickupDelivery: true, crossDock: true }); crossSource.pickupDeliveryPairs[0].sameVehicleRequired = false; crossSource.pickupDeliveryPairs[0].sameTripRequired = false; const crossPlan = Network.solveNetwork(crossSource, { crossDock: true, maxStopsPerTrip: 2 }); const crossLedger = Accounting.computeAccounting(crossSource, crossPlan);
check("T0487", crossLedger.conservation.transfers.status === "PASS" && crossLedger.conservation.transfers.rows.length === 1, crossLedger.conservation.transfers, "transfer load conservation");
check("T0488", ledger.conservation.depotThroughput.status === "PASS" && sum(ledger.conservation.depotThroughput.rows.map((row) => row.orders)) === ledger.metrics.assignedCount, ledger.conservation.depotThroughput, "depot throughput conservation");
const dailySource = sourceFixture(2, 1, 1); dailySource.depots[0].capacity.dailyOrders = 1; dailySource.orders[0].serviceDay = "2026-09-04"; dailySource.orders[1].serviceDay = "2026-09-05"; const dailyPlan = Network.solveNetwork(dailySource, { maxStopsPerTrip: 2 }); const dailyRows = Accounting.depotDailyThroughput(Contract.normalizeScenario(dailySource), dailyPlan);
check("T0489", dailyRows.length === 2 && dailyRows.every((row) => row.orders === 1), dailyRows, "daily capacity resets");
const overnightSource = sourceFixture(1, 1, 1); overnightSource.planningHorizon.businessDayStart = "18:00"; overnightSource.planningHorizon.businessDayEnd = "02:00";
check("T0490", Accounting.businessDayAttribution(1450, Contract.normalizeScenario(overnightSource)) === "DAY-1", Accounting.businessDayAttribution(1450, Contract.normalizeScenario(overnightSource)), "cross-midnight business day attribution");
check("T0491", ledger.cost.components.vehicleFixed > 0, ledger.cost.components.vehicleFixed, "vehicle fixed cost");
check("T0492", ledger.cost.components.tripFixed > 0, ledger.cost.components.tripFixed, "trip fixed cost");
check("T0493", ledger.cost.components.distance > 0, ledger.cost.components.distance, "distance cost");
check("T0494", ledger.cost.components.time > 0, ledger.cost.components.time, "time cost");
check("T0495", ledger.cost.components.toll > 0, ledger.cost.components.toll, "toll cost");
const repositionSource = sourceFixture(4, 2, 2); repositionSource.vehicles[0].allowedStartDepotIds = ["D1", "D2"]; repositionSource.vehicles[0].maxTrips = 4; repositionSource.constraints.maxTripsPerVehicle = 4; const repositionPlan = Network.solveNetwork(repositionSource, { maxStopsPerTrip: 1, tripOptions: { vehicleIds: ["V1"] } }); const repositionLedger = Accounting.computeAccounting(repositionSource, repositionPlan);
check("T0496", repositionLedger.cost.components.emptyReposition > 0, repositionLedger.cost.components.emptyReposition, "empty reposition cost");
check("T0497", ledger.cost.components.dockHandling > 0, ledger.cost.components.dockHandling, "dock handling cost");
check("T0498", ledger.cost.components.dockWaiting > 0, ledger.cost.components.dockWaiting, "dock waiting cost");
check("T0499", ledger.cost.components.reload > 0, ledger.cost.components.reload, "reload cost");
check("T0500", crossLedger.cost.components.transfer > 0, crossLedger.cost.components.transfer, "transfer cost");
check("T0501", ledger.cost.components.depotHandling > 0, ledger.cost.components.depotHandling, "depot handling cost");
const overtimeLedger = Accounting.computeAccounting(source, plan, { regularDutyMinutes: 1, overtimeCostPerMinute: 1 });
check("T0502", overtimeLedger.cost.components.overtime > 0, overtimeLedger.cost.components.overtime, "overtime cost");
const penaltySource = sourceFixture(6, 1, 1); penaltySource.vehicles[0].maxTrips = 1; penaltySource.constraints.maxTripsPerVehicle = 1; const penaltyPlan = Network.solveNetwork(penaltySource, { maxStopsPerTrip: 1 }); const penaltyLedger = Accounting.computeAccounting(penaltySource, penaltyPlan, { unassignedPenalty: 1234 });
check("T0503", penaltyLedger.cost.components.unassigned === penaltyPlan.trip.unassigned.length * 1234 && penaltyLedger.cost.components.unassigned > 0, penaltyLedger.cost.components.unassigned, "unassigned penalty");
const missedPlan = clone(crossPlan); missedPlan.custody = Custody.planPickupDelivery(crossSource, { crossDock: true, latestHandoverMinute: 1 }); const missedLedger = Accounting.computeAccounting(crossSource, missedPlan, { failedConnectionPenalty: 4321 });
check("T0504", missedLedger.cost.components.failedConnection === 4321, missedLedger.cost.components.failedConnection, "failed transfer penalty");
check("T0505", ledger.cost.total === sum(Object.values(ledger.cost.components)), { total: ledger.cost.total, components: ledger.cost.components }, "cost total equals components");
check("T0506", ledger.cost.allocationMethod === "COMPONENT_LEDGER_THEN_EQUAL_ORDER_ALLOCATION_WITH_FINAL_REMAINDER" && ledger.cost.currency === "CNY", ledger.cost, "allocation method disclosed");
check("T0507", ledger.allocations.order.length === source.orders.length && sum(ledger.allocations.order.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.order.slice(0, 3), "order cost-to-serve");
check("T0508", ledger.allocations.zone.length === source.zones.length && sum(ledger.allocations.zone.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.zone, "zone cost-to-serve");
check("T0509", ledger.allocations.depot.length === source.depots.length && sum(ledger.allocations.depot.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.depot, "depot cost-to-serve");
check("T0510", ledger.allocations.trip.length === plan.trip.trips.length && sum(ledger.allocations.trip.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.trip, "trip cost-to-serve");
check("T0511", ledger.allocations.wave.length === plan.waves.waves.length && sum(ledger.allocations.wave.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.wave, "wave cost-to-serve");
check("T0512", ledger.allocations.vehicleType.length >= 1 && sum(ledger.allocations.vehicleType.map((row) => row.amount)) === ledger.cost.total, ledger.allocations.vehicleType, "vehicle-type cost-to-serve");
check("T0513", ledger.carbon.components.loadedTravel > 0, ledger.carbon.components.loadedTravel, "loaded distance carbon");
check("T0514", repositionLedger.carbon.components.emptyTravel > 0, repositionLedger.carbon.components.emptyTravel, "empty distance carbon");
check("T0515", ledger.carbon.components.handling > 0, ledger.carbon.components.handling, "handling carbon");
check("T0516", crossLedger.carbon.components.transfer > 0, crossLedger.carbon.components.transfer, "transfer carbon");
check("T0517", ledger.carbon.totalKg === sum(Object.values(ledger.carbon.components)), ledger.carbon, "carbon total equals components");
check("T0518", ledger.carbon.factorSource === "SYNTHETIC_VEHICLE_AND_DEPOT_FACTORS_V1.8", ledger.carbon.factorSource, "carbon factor source");
check("T0519", ledger.carbon.disclaimer.includes("not certified ESG accounting"), ledger.carbon.disclaimer, "not certified ESG");
check("T0520", ledger.metrics.serviceLevel === ledger.metrics.assignedCount / source.orders.length, ledger.metrics.serviceLevel, "exact service level");
check("T0521", ledger.metrics.priorityScore === 1, ledger.metrics.priorityScore, "exact priority score");
check("T0522", ledger.metrics.assignedCount === plan.trip.trips.flatMap((row) => row.orderIds).length, ledger.metrics.assignedCount, "exact assigned count");
check("T0523", ledger.metrics.blockedCount === plan.assignment.blocked.length, ledger.metrics.blockedCount, "exact blocked count");
check("T0524", penaltyLedger.metrics.unassignedReasons.MAX_TRIPS_EXCEEDED === penaltyPlan.trip.unassigned.length, penaltyLedger.metrics.unassignedReasons, "exact unassigned reasons");
check("T0525", ledger.metrics.depotImbalance === 0, ledger.metrics.depotImbalance, "depot imbalance metric");
check("T0526", ledger.metrics.dockCongestion === plan.dock.metrics.congestionReservations, ledger.metrics.dockCongestion, "dock congestion metric");
check("T0527", repositionLedger.metrics.emptyDistanceKm === repositionPlan.trip.metrics.repositionDistanceKm && repositionLedger.metrics.emptyDistanceKm > 0, repositionLedger.metrics.emptyDistanceKm, "empty distance metric");
check("T0528", crossLedger.metrics.transferCount === 1, crossLedger.metrics.transferCount, "transfer count metric");
check("T0529", ledger.metrics.latestCompletionMinute === Math.max(...plan.trip.trips.map((row) => row.endMinute)), ledger.metrics.latestCompletionMinute, "latest completion metric");
check("T0530", ledger.metrics.vehicleUtilization.length === source.vehicles.length && ledger.metrics.vehicleUtilization.every((row) => row.utilization >= 0 && row.utilization <= 1), ledger.metrics.vehicleUtilization, "vehicle utilization");
check("T0531", ledger.metrics.tripUtilization.length === plan.trip.trips.length && ledger.metrics.tripUtilization.every((row) => row.volumeUtilization >= 0 && row.volumeUtilization <= 1), ledger.metrics.tripUtilization, "trip utilization");
check("T0532", ledger.metrics.depotUtilization.length === source.depots.length && ledger.metrics.depotUtilization.every((row) => row.orderUtilization >= 0 && row.orderUtilization <= 1), ledger.metrics.depotUtilization, "depot utilization");
check("T0533", ledger.metrics.driverUtilization.length === plan.trip.driverDutyAudit.length && ledger.metrics.driverUtilization.every((row) => row.dutyUtilization >= 0 && row.dutyUtilization <= 1), ledger.metrics.driverUtilization, "driver utilization");
const costTamper = clone(ledger); costTamper.cost.total += 1;
check("T0534", Accounting.verifyAccounting(source, plan, costTamper).issues.includes("COST_LEDGER_MISMATCH"), Accounting.verifyAccounting(source, plan, costTamper).issues, "cost tamper rejected", true);
const carbonTamper = clone(ledger); carbonTamper.carbon.totalKg += 1;
check("T0535", Accounting.verifyAccounting(source, plan, carbonTamper).issues.includes("CARBON_LEDGER_MISMATCH"), Accounting.verifyAccounting(source, plan, carbonTamper).issues, "carbon tamper rejected", true);
const conservationTamper = clone(ledger); conservationTamper.conservation.orders.assigned -= 1; conservationTamper.conservation.status = "FAIL";
check("T0536", Accounting.verifyAccounting(source, plan, conservationTamper).issues.includes("CONSERVATION_MISMATCH"), Accounting.verifyAccounting(source, plan, conservationTamper).issues, "conservation tamper rejected", true);
const missingComponent = clone(ledger); delete missingComponent.cost.components.toll;
check("T0537", Accounting.candidateEligibility(missingComponent).status === "EXCLUDED" && Accounting.candidateEligibility(missingComponent).reasons.includes("MISSING_COST:toll"), Accounting.candidateEligibility(missingComponent), "missing component excludes candidate", true);
const nonFinite = clone(ledger); nonFinite.cost.components.toll = NaN;
check("T0538", Accounting.candidateEligibility(nonFinite).status === "EXCLUDED" && Accounting.candidateEligibility(nonFinite).reasons.includes("NON_FINITE_METRIC"), Accounting.candidateEligibility(nonFinite), "NaN excluded", true);
check("T0539", Accounting.candidateEligibility(ledger).status === "VERIFIED_METRICS" && verification.status === "PASS", Accounting.candidateEligibility(ledger), "Pareto metrics verified");
const csvProbe = clone(ledger); csvProbe.audit[0].component = "=2+2";
check("T0540", Accounting.toCsv(csvProbe).includes("\"'=2+2\""), Accounting.toCsv(csvProbe).split("\r\n")[1], "CSV formula safety");
const jsonExport = JSON.parse(Accounting.toJson(ledger));
check("T0541", jsonExport.accountingHash === ledger.accountingHash && jsonExport.ledger.networkPlanHash === plan.networkPlanHash, { accountingHash: jsonExport.accountingHash, networkPlanHash: jsonExport.ledger.networkPlanHash }, "JSON export identity");
const capsule = Accounting.createCapsule(source, plan, ledger);
check("T0542", Accounting.replay(source, plan, capsule).status === "EQUIVALENT", Accounting.replay(source, plan, capsule), "capsule recompute");
const repositionCostTamper = clone(repositionLedger); repositionCostTamper.cost.components.emptyReposition = 0;
check("T0543", Accounting.verifyAccounting(repositionSource, repositionPlan, repositionCostTamper).issues.includes("COST_LEDGER_MISMATCH"), Accounting.verifyAccounting(repositionSource, repositionPlan, repositionCostTamper).issues, "empty reposition cost mutation killed", true);
const transferCostTamper = clone(crossLedger); transferCostTamper.cost.components.transfer = 0;
check("T0544", Accounting.verifyAccounting(crossSource, crossPlan, transferCostTamper).issues.includes("COST_LEDGER_MISMATCH"), Accounting.verifyAccounting(crossSource, crossPlan, transferCostTamper).issues, "missing transfer cost mutation killed", true);
check("T0545", Number.isFinite(accountingElapsed) && accountingElapsed >= 0, accountingElapsed, "cost performance measured");
const carbonStarted = performance.now(); Accounting.computeCarbon(Contract.normalizeScenario(source), plan, ledger.assumptions); const carbonElapsed = performance.now() - carbonStarted;
check("T0546", Number.isFinite(carbonElapsed) && carbonElapsed >= 0, carbonElapsed, "carbon performance measured");
check("T0547", ["zh", "en", "ja"].every((locale) => ["COST", "CARBON", "CONSERVATION", "UTILIZATION", "EXCLUDED"].every((code) => Accounting.term(code, locale) !== code)), ["zh", "en", "ja"].map((locale) => Accounting.term("CARBON", locale)), "Chinese English Japanese labels");
check("T0548", ledger.trustLab.costFormula.includes("sum") && ledger.trustLab.carbonFormula.includes("loadedTravel") && ledger.trustLab.serviceFormula.includes("assigned unique orders") && ledger.trustLab.priorityFormula.includes("priority weight"), ledger.trustLab, "Trust Lab formulas");
check("T0549", ledger.audit.length === Accounting.COST_COMPONENTS.length + Accounting.CARBON_COMPONENTS.length && ledger.audit.every((row) => row.component && Number.isFinite(row.value) && row.source === "CANONICAL_FACT_RECOMPUTE"), ledger.audit, "component audit ledger");
check("T0550", [ledger.cost.total, ledger.carbon.totalKg, ...Object.values(ledger.cost.components), ...Object.values(ledger.carbon.components)].every((value) => Number((value * 1000).toFixed(6)) === Math.round(value * 1000)), { cost: ledger.cost, carbon: ledger.carbon }, "consistent three-decimal rounding");

assert.strictEqual(assertions.length, 71, "Gate 7 must contain exactly T0480-T0550");
process.stdout.write(`${JSON.stringify({ status: "PASS", checks: assertions.length, accountingPerformanceMs: accountingElapsed, carbonPerformanceMs: carbonElapsed, cost: ledger.cost, carbon: ledger.carbon, metrics: ledger.metrics, assertions }, null, 2)}\n`);
